-- SDA module: deposit return system for beverage packaging (Moldova).
-- Legal basis: Law 209/2016 art. 54^1-54^4, DRS implementing regulation.
-- Prefix: SDA_. Target database: platform cloud ADB.

CREATE TABLE SDA_PARTIC (
  PARTIC_ID      NUMBER(12)      NOT NULL,
  IDNO           VARCHAR2(20)    NOT NULL,
  DENUMIRE       VARCHAR2(200)   NOT NULL,
  DATA_INREG     DATE,
  NR_CONTRACT    VARCHAR2(60),
  DATA_CONTRACT  DATE,
  CONTACT_NUME   VARCHAR2(120),
  CONTACT_TEL    VARCHAR2(40),
  CONTACT_EMAIL  VARCHAR2(120),
  STARE          VARCHAR2(20)    DEFAULT 'ACTIV' NOT NULL,
  -- Blocks 6 and 7 of the registration notification (pct. 78): units of
  -- SD packaging sold last year and forecast for the current year.
  VANDUT_AN_ANT  NUMBER(14),
  ESTIMARE_AN    NUMBER(14),
  CREATED_AT     DATE            DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SDA_PARTIC PRIMARY KEY (PARTIC_ID),
  CONSTRAINT CK_SDA_PARTIC_STARE CHECK (STARE IN ('ACTIV','SUSPENDAT','INCHIS'))
);
CREATE SEQUENCE SEQ_SDA_PARTIC START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_PARTIC_BI BEFORE INSERT ON SDA_PARTIC FOR EACH ROW
BEGIN IF :NEW.PARTIC_ID IS NULL THEN SELECT SEQ_SDA_PARTIC.NEXTVAL INTO :NEW.PARTIC_ID FROM DUAL; END IF; END;
/
CREATE UNIQUE INDEX UX_SDA_PARTIC_IDNO ON SDA_PARTIC (IDNO);

-- One economic operator may hold several roles at once (regulation pct. 83).
CREATE TABLE SDA_PARTIC_ROL (
  ROL_ID     NUMBER(12)   NOT NULL,
  PARTIC_ID  NUMBER(12)   NOT NULL,
  ROL        VARCHAR2(10) NOT NULL,
  ACTIV_DIN  DATE         DEFAULT SYSDATE NOT NULL,
  ACTIV_PANA DATE,
  CONSTRAINT PK_SDA_PARTIC_ROL PRIMARY KEY (ROL_ID),
  CONSTRAINT FK_SDA_PARTIC_ROL_P FOREIGN KEY (PARTIC_ID) REFERENCES SDA_PARTIC (PARTIC_ID),
  CONSTRAINT CK_SDA_PARTIC_ROL CHECK (ROL IN ('PROD','COM','HORECA','DISTR','APL','ADMIN'))
);
CREATE SEQUENCE SEQ_SDA_PARTIC_ROL START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_PARTIC_ROL_BI BEFORE INSERT ON SDA_PARTIC_ROL FOR EACH ROW
BEGIN IF :NEW.ROL_ID IS NULL THEN SELECT SEQ_SDA_PARTIC_ROL.NEXTVAL INTO :NEW.ROL_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_PARTIC_ROL_P ON SDA_PARTIC_ROL (PARTIC_ID);

-- Retail units. SUPRAFATA_MP and TIP_AMPLASAMENT decide REGIM (pct. 93, 97).
CREATE TABLE SDA_UNIT (
  UNIT_ID          NUMBER(12)     NOT NULL,
  PARTIC_ID        NUMBER(12)     NOT NULL,
  COD_ERP          VARCHAR2(40),
  DENUMIRE         VARCHAR2(200)  NOT NULL,
  ADRESA           VARCHAR2(300),
  LOCALITATE       VARCHAR2(120),
  RAION            VARCHAR2(120),
  SUPRAFATA_MP     NUMBER(10,2),
  TIP_AMPLASAMENT  VARCHAR2(24)   DEFAULT 'MAGAZIN' NOT NULL,
  REGIM            VARCHAR2(20),
  REGIM_MOTIV      VARCHAR2(300),
  DATA_EVALUARE    DATE,
  CREATED_AT       DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SDA_UNIT PRIMARY KEY (UNIT_ID),
  CONSTRAINT FK_SDA_UNIT_P FOREIGN KEY (PARTIC_ID) REFERENCES SDA_PARTIC (PARTIC_ID),
  CONSTRAINT CK_SDA_UNIT_TIP CHECK (TIP_AMPLASAMENT IN
    ('MAGAZIN','TARABA','CHIOSC','BENZINARIE','ALIMENTATIE_PUBLICA')),
  CONSTRAINT CK_SDA_UNIT_REGIM CHECK (REGIM IN
    ('A_PUNCT_PROPRIU','B_EXCEPTIE_APL','C_HORECA')),
  CONSTRAINT CK_SDA_UNIT_SUPRAF CHECK (SUPRAFATA_MP IS NULL OR SUPRAFATA_MP > 0)
);
CREATE SEQUENCE SEQ_SDA_UNIT START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_UNIT_BI BEFORE INSERT ON SDA_UNIT FOR EACH ROW
BEGIN IF :NEW.UNIT_ID IS NULL THEN SELECT SEQ_SDA_UNIT.NEXTVAL INTO :NEW.UNIT_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_UNIT_P ON SDA_UNIT (PARTIC_ID);
CREATE INDEX IX_SDA_UNIT_REGIM ON SDA_UNIT (REGIM);

-- Return points. The 150 m limit and the opening hours come from pct. 85.
CREATE TABLE SDA_RETURN_POINT (
  POINT_ID            NUMBER(12)    NOT NULL,
  UNIT_ID             NUMBER(12)    NOT NULL,
  TIP                 VARCHAR2(10)  DEFAULT 'MANUAL' NOT NULL,
  ADRESA              VARCHAR2(300),
  DISTANTA_M          NUMBER(6)     DEFAULT 0 NOT NULL,
  ORAR                VARCHAR2(200),
  PARTENER_APL        VARCHAR2(200),
  RESPONSABIL_NUME    VARCHAR2(120),
  RESPONSABIL_CONTACT VARCHAR2(120),
  ACTIV_DIN           DATE,
  ACTIV_PANA          DATE,
  CONSTRAINT PK_SDA_RETURN_POINT PRIMARY KEY (POINT_ID),
  CONSTRAINT FK_SDA_RETURN_POINT_U FOREIGN KEY (UNIT_ID) REFERENCES SDA_UNIT (UNIT_ID),
  CONSTRAINT CK_SDA_RP_TIP CHECK (TIP IN ('MANUAL','AUTOMAT','MIXT')),
  CONSTRAINT CK_SDA_RP_DIST CHECK (DISTANTA_M BETWEEN 0 AND 150)
);
CREATE SEQUENCE SEQ_SDA_RETURN_POINT START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_RETURN_POINT_BI BEFORE INSERT ON SDA_RETURN_POINT FOR EACH ROW
BEGIN IF :NEW.POINT_ID IS NULL THEN SELECT SEQ_SDA_RETURN_POINT.NEXTVAL INTO :NEW.POINT_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_RETURN_POINT_U ON SDA_RETURN_POINT (UNIT_ID);

-- Reverse vending machines. PROPRIETAR affects the management tariff (pct. 14.14 j).
CREATE TABLE SDA_RVM (
  RVM_ID          NUMBER(12)    NOT NULL,
  POINT_ID        NUMBER(12)    NOT NULL,
  MODEL           VARCHAR2(120),
  SERIA           VARCHAR2(60),
  PROPRIETAR      VARCHAR2(20)  DEFAULT 'COMERCIANT' NOT NULL,
  DATA_INSTALARE  DATE,
  STARE           VARCHAR2(20)  DEFAULT 'ACTIV' NOT NULL,
  ULTIM_HEARTBEAT DATE,
  CONSTRAINT PK_SDA_RVM PRIMARY KEY (RVM_ID),
  CONSTRAINT FK_SDA_RVM_PT FOREIGN KEY (POINT_ID) REFERENCES SDA_RETURN_POINT (POINT_ID),
  CONSTRAINT CK_SDA_RVM_PROP CHECK (PROPRIETAR IN ('COMERCIANT','ADMINISTRATOR')),
  CONSTRAINT CK_SDA_RVM_STARE CHECK (STARE IN ('ACTIV','DEFECT','DEMONTAT'))
);
CREATE SEQUENCE SEQ_SDA_RVM START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_RVM_BI BEFORE INSERT ON SDA_RVM FOR EACH ROW
BEGIN IF :NEW.RVM_ID IS NULL THEN SELECT SEQ_SDA_RVM.NEXTVAL INTO :NEW.RVM_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_RVM_PT ON SDA_RVM (POINT_ID);

-- Registry of SD packaging (pct. 14.12). EAN is the key of the whole module.
CREATE TABLE SDA_PACK (
  PACK_ID       NUMBER(12)    NOT NULL,
  EAN           VARCHAR2(20)  NOT NULL,
  DENUMIRE      VARCHAR2(200),
  PRODUCATOR    VARCHAR2(200),
  MATERIAL      VARCHAR2(10)  NOT NULL,
  CULOARE       VARCHAR2(20),
  BARIERA_O2    CHAR(1)       DEFAULT 'N' NOT NULL,
  REUTILIZABIL  CHAR(1)       DEFAULT 'N' NOT NULL,
  VOLUM_L       NUMBER(6,3)   NOT NULL,
  GREUTATE_G    NUMBER(8,2)   NOT NULL,
  CAT_ADMIN     CHAR(1),
  CAT_GEST      CHAR(1),
  SURSA         VARCHAR2(20)  DEFAULT 'MANUAL' NOT NULL,
  ACTIV_DIN     DATE,
  ACTIV_PANA    DATE,
  CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SDA_PACK PRIMARY KEY (PACK_ID),
  CONSTRAINT CK_SDA_PACK_MAT CHECK (MATERIAL IN ('PLASTIC','STICLA','METAL')),
  CONSTRAINT CK_SDA_PACK_REUT CHECK (REUTILIZABIL IN ('D','N')),
  CONSTRAINT CK_SDA_PACK_BAR CHECK (BARIERA_O2 IN ('D','N')),
  CONSTRAINT CK_SDA_PACK_SURSA CHECK (SURSA IN ('MANUAL','ADMIN_REGISTRU','IMPORT')),
  CONSTRAINT CK_SDA_PACK_VOL CHECK (VOLUM_L >= 0.1 AND VOLUM_L <= 3),
  CONSTRAINT CK_SDA_PACK_GREU CHECK (GREUTATE_G > 0),
  -- Administration tariff categories, regulation pct. 14.13: closed set a-g.
  CONSTRAINT CK_SDA_PACK_CATADM CHECK (CAT_ADMIN IS NULL OR CAT_ADMIN IN ('a','b','c','d','e','f','g')),
  -- Management tariff categories, regulation pct. 14.14: closed set a-e.
  CONSTRAINT CK_SDA_PACK_CATGES CHECK (CAT_GEST IS NULL OR CAT_GEST IN ('a','b','c','d','e'))
);
CREATE SEQUENCE SEQ_SDA_PACK START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_PACK_BI BEFORE INSERT ON SDA_PACK FOR EACH ROW
BEGIN IF :NEW.PACK_ID IS NULL THEN SELECT SEQ_SDA_PACK.NEXTVAL INTO :NEW.PACK_ID FROM DUAL; END IF; END;
/
CREATE UNIQUE INDEX UX_SDA_PACK_EAN ON SDA_PACK (EAN);

-- Bridge to the ERP nomenclature. COD_MPT is the OfficePlus item code.
CREATE TABLE SDA_PACK_SKU (
  SKU_ID     NUMBER(12)    NOT NULL,
  PACK_ID    NUMBER(12)    NOT NULL,
  COD_MPT    VARCHAR2(40)  NOT NULL,
  EAN_SURSA  VARCHAR2(20),
  CREATED_AT DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SDA_PACK_SKU PRIMARY KEY (SKU_ID),
  CONSTRAINT FK_SDA_PACK_SKU_P FOREIGN KEY (PACK_ID) REFERENCES SDA_PACK (PACK_ID)
);
CREATE SEQUENCE SEQ_SDA_PACK_SKU START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_PACK_SKU_BI BEFORE INSERT ON SDA_PACK_SKU FOR EACH ROW
BEGIN IF :NEW.SKU_ID IS NULL THEN SELECT SEQ_SDA_PACK_SKU.NEXTVAL INTO :NEW.SKU_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_PACK_SKU_P ON SDA_PACK_SKU (PACK_ID);
CREATE INDEX IX_SDA_PACK_SKU_COD ON SDA_PACK_SKU (COD_MPT);

-- Tariff periods. The law fixes none of these values: they arrive by
-- ministerial order and by the Administrator financing scheme.
CREATE TABLE SDA_TARIFF (
  TARIFF_ID     NUMBER(12)    NOT NULL,
  TIP           VARCHAR2(10)  NOT NULL,
  DATA_START    DATE          NOT NULL,
  DATA_END      DATE,
  ACT_NORMATIV  VARCHAR2(200),
  OBS           VARCHAR2(400),
  CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SDA_TARIFF PRIMARY KEY (TARIFF_ID),
  CONSTRAINT CK_SDA_TARIFF_TIP CHECK (TIP IN ('DEPOZIT','ADMIN','GESTIUNE')),
  CONSTRAINT CK_SDA_TARIFF_PER CHECK (DATA_END IS NULL OR DATA_END >= DATA_START)
);
CREATE SEQUENCE SEQ_SDA_TARIFF START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_TARIFF_BI BEFORE INSERT ON SDA_TARIFF FOR EACH ROW
BEGIN IF :NEW.TARIFF_ID IS NULL THEN SELECT SEQ_SDA_TARIFF.NEXTVAL INTO :NEW.TARIFF_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_TARIFF_TIP ON SDA_TARIFF (TIP, DATA_START);

CREATE TABLE SDA_TARIFF_LINE (
  LINE_ID      NUMBER(12)   NOT NULL,
  TARIFF_ID    NUMBER(12)   NOT NULL,
  CATEGORIE    VARCHAR2(2)  DEFAULT '*' NOT NULL,
  METODA       VARCHAR2(10),
  REUTILIZABIL CHAR(1),
  VALOARE_LEI  NUMBER(10,4) NOT NULL,
  CONSTRAINT PK_SDA_TARIFF_LINE PRIMARY KEY (LINE_ID),
  CONSTRAINT FK_SDA_TARIFF_LINE_T FOREIGN KEY (TARIFF_ID) REFERENCES SDA_TARIFF (TARIFF_ID),
  CONSTRAINT CK_SDA_TL_METODA CHECK (METODA IS NULL OR METODA IN ('MANUAL','AUTOMAT')),
  CONSTRAINT CK_SDA_TL_VAL CHECK (VALOARE_LEI >= 0),
  -- NULL applies to both reusable and single-use packaging.
  CONSTRAINT CK_SDA_TL_REUT CHECK (REUTILIZABIL IS NULL OR REUTILIZABIL IN ('D','N')),
  -- Tariff categories: a-g domain plus '*' wildcard used by the deposit tariff.
  CONSTRAINT CK_SDA_TL_CAT CHECK (CATEGORIE IN ('a','b','c','d','e','f','g','*'))
);
CREATE SEQUENCE SEQ_SDA_TARIFF_LINE START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_TARIFF_LINE_BI BEFORE INSERT ON SDA_TARIFF_LINE FOR EACH ROW
BEGIN IF :NEW.LINE_ID IS NULL THEN SELECT SEQ_SDA_TARIFF_LINE.NEXTVAL INTO :NEW.LINE_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_TARIFF_LINE_T ON SDA_TARIFF_LINE (TARIFF_ID);

-- Append-only journal of the module. Never a shared container.
CREATE TABLE SDA_EVENT_LOG (
  EVENT_ID    NUMBER(12)     NOT NULL,
  EVENT_DATE  DATE           DEFAULT SYSDATE NOT NULL,
  TIP         VARCHAR2(40)   NOT NULL,
  ENTITATE    VARCHAR2(40),
  ENTITATE_ID NUMBER(12),
  UTILIZATOR  VARCHAR2(120),
  DETALII     VARCHAR2(1000),
  CONSTRAINT PK_SDA_EVENT_LOG PRIMARY KEY (EVENT_ID)
);
CREATE SEQUENCE SEQ_SDA_EVENT_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_EVENT_LOG_BI BEFORE INSERT ON SDA_EVENT_LOG FOR EACH ROW
BEGIN IF :NEW.EVENT_ID IS NULL THEN SELECT SEQ_SDA_EVENT_LOG.NEXTVAL INTO :NEW.EVENT_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_EVENT_LOG_D ON SDA_EVENT_LOG (EVENT_DATE);
