-- SDA module: return and settlement contour (evidence of packaging taken
-- back, and the management tariff the retail chain claims from the
-- Administrator). Legal basis: Law 209/2016 art. 54^1 alin. (9)-(10),
-- regulation pct. 14.14-14.15, pct. 202 (settlement within 14 days).
-- Prefix: SDA_. Target database: platform cloud ADB. Depends on
-- 117_sda_tables.sql (SDA_RETURN_POINT, SDA_RVM, SDA_PACK, SDA_TARIFF,
-- SDA_PARTIC).

-- Take-back session at one return point. METODA is captured here, on the
-- session, because SDA_RETURN_POINT.TIP can be MIXT: the point itself does
-- not decide by what method a given session took packaging back.
CREATE TABLE SDA_RETURN (
  RETURN_ID      NUMBER(12)     NOT NULL,
  POINT_ID       NUMBER(12)     NOT NULL,
  RVM_ID         NUMBER(12),
  DATA_RETUR     DATE           DEFAULT SYSDATE NOT NULL,
  METODA         VARCHAR2(10)   NOT NULL,
  OPERATOR_NUME  VARCHAR2(120),
  TOTAL_BUC      NUMBER(10)     DEFAULT 0 NOT NULL,
  TOTAL_KG       NUMBER(10,3)   DEFAULT 0 NOT NULL,
  TOTAL_LEI      NUMBER(12,2)   DEFAULT 0 NOT NULL,
  MOD_RAMBURS    VARCHAR2(10)   NOT NULL,
  VOUCHER_ID     NUMBER(12),
  CREATED_AT     DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SDA_RETURN PRIMARY KEY (RETURN_ID),
  CONSTRAINT FK_SDA_RETURN_PT FOREIGN KEY (POINT_ID) REFERENCES SDA_RETURN_POINT (POINT_ID),
  CONSTRAINT FK_SDA_RETURN_RVM FOREIGN KEY (RVM_ID) REFERENCES SDA_RVM (RVM_ID),
  CONSTRAINT CK_SDA_RETURN_METODA CHECK (METODA IN ('MANUAL','AUTOMAT')),
  -- Regulation pct. 150: manual take-back allows cash or ticket; automatic
  -- take-back (RVM) issues only a ticket. The FK to SDA_VOUCHER is added
  -- below, once that table exists.
  CONSTRAINT CK_SDA_RETURN_MODRAMB CHECK (MOD_RAMBURS IN ('NUMERAR','TICHET')),
  CONSTRAINT CK_SDA_RETURN_MODRAMB_AUT CHECK (
    METODA != 'AUTOMAT' OR MOD_RAMBURS = 'TICHET')
);
CREATE SEQUENCE SEQ_SDA_RETURN START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_RETURN_BI BEFORE INSERT ON SDA_RETURN FOR EACH ROW
BEGIN IF :NEW.RETURN_ID IS NULL THEN SELECT SEQ_SDA_RETURN.NEXTVAL INTO :NEW.RETURN_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_RETURN_PT ON SDA_RETURN (POINT_ID);
CREATE INDEX IX_SDA_RETURN_RVM ON SDA_RETURN (RVM_ID);
CREATE INDEX IX_SDA_RETURN_D ON SDA_RETURN (DATA_RETUR);

-- One line per packaging kind inside a take-back session. Every dimension
-- that decides the management tariff (pct. 14.14) is snapshotted here as
-- it was at the moment of the return, not derived later from SDA_PACK or
-- SDA_RETURN_POINT: a point is converted from manual to automatic over
-- time, and re-deriving the method retroactively would rewrite amounts
-- already claimed. Same reasoning as SDA_TARIFF snapshots the deposit
-- value on SDA_SALE lines rather than only a foreign key.
CREATE TABLE SDA_RETURN_LINE (
  LINE_ID         NUMBER(12)    NOT NULL,
  RETURN_ID       NUMBER(12)    NOT NULL,
  PACK_ID         NUMBER(12)    NOT NULL,
  CANT_BUC        NUMBER(10)    DEFAULT 0 NOT NULL,
  CANT_KG         NUMBER(10,3)  DEFAULT 0 NOT NULL,
  DEPOZIT_LEI     NUMBER(12,2)  DEFAULT 0 NOT NULL,
  -- Snapshot dimensions (regulation pct. 14.14): method, reusable, material
  -- category and RVM ownership at the moment of this return.
  METODA          VARCHAR2(10)  NOT NULL,
  REUTILIZABIL    CHAR(1)       NOT NULL,
  CAT_GEST        CHAR(1)       NOT NULL,
  RVM_PROPRIETAR  VARCHAR2(20),
  -- Management tariff resolved at the return date, snapshotted alongside
  -- the tariff row that produced it.
  TARIFF_ID       NUMBER(12)    NOT NULL,
  GESTIUNE_UNITAR NUMBER(10,4)  NOT NULL,
  GESTIUNE_LEI    NUMBER(12,2)  NOT NULL,
  REZULTAT        VARCHAR2(10)  DEFAULT 'ACCEPTAT' NOT NULL,
  MOTIV_REFUZ     VARCHAR2(300),
  CONSTRAINT PK_SDA_RETURN_LINE PRIMARY KEY (LINE_ID),
  CONSTRAINT FK_SDA_RETURN_LINE_R FOREIGN KEY (RETURN_ID) REFERENCES SDA_RETURN (RETURN_ID),
  CONSTRAINT FK_SDA_RETURN_LINE_P FOREIGN KEY (PACK_ID) REFERENCES SDA_PACK (PACK_ID),
  CONSTRAINT FK_SDA_RETURN_LINE_T FOREIGN KEY (TARIFF_ID) REFERENCES SDA_TARIFF (TARIFF_ID),
  CONSTRAINT CK_SDA_RL_METODA CHECK (METODA IN ('MANUAL','AUTOMAT')),
  CONSTRAINT CK_SDA_RL_REUT CHECK (REUTILIZABIL IN ('D','N')),
  CONSTRAINT CK_SDA_RL_CATGES CHECK (CAT_GEST IN ('a','b','c','d','e')),
  CONSTRAINT CK_SDA_RL_RVMPROP CHECK (RVM_PROPRIETAR IS NULL OR RVM_PROPRIETAR IN ('COMERCIANT','ADMINISTRATOR')),
  CONSTRAINT CK_SDA_RL_REZULTAT CHECK (REZULTAT IN ('ACCEPTAT','REFUZAT')),
  -- Art. 54^1 alin. (9)-(10): a refusal must carry its reason.
  CONSTRAINT CK_SDA_RL_MOTIV CHECK (REZULTAT = 'ACCEPTAT' OR MOTIV_REFUZ IS NOT NULL)
);
CREATE SEQUENCE SEQ_SDA_RETURN_LINE START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_RETURN_LINE_BI BEFORE INSERT ON SDA_RETURN_LINE FOR EACH ROW
BEGIN IF :NEW.LINE_ID IS NULL THEN SELECT SEQ_SDA_RETURN_LINE.NEXTVAL INTO :NEW.LINE_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_RETURN_LINE_R ON SDA_RETURN_LINE (RETURN_ID);
CREATE INDEX IX_SDA_RETURN_LINE_P ON SDA_RETURN_LINE (PACK_ID);
CREATE INDEX IX_SDA_RETURN_LINE_T ON SDA_RETURN_LINE (TARIFF_ID);

-- Ticket registry (pct. 14.15). Issued by manual choice or forced by an
-- RVM (see CK_SDA_RETURN_MODRAMB_AUT above); valid 12 months from issue.
CREATE TABLE SDA_VOUCHER (
  VOUCHER_ID    NUMBER(12)     NOT NULL,
  COD           VARCHAR2(40)   NOT NULL,
  PARTIC_ID     NUMBER(12)     NOT NULL,
  POINT_ID      NUMBER(12)     NOT NULL,
  VALOARE_LEI   NUMBER(12,2)   NOT NULL,
  DATA_EMITERE  DATE           DEFAULT SYSDATE NOT NULL,
  DATA_EXPIRARE DATE           NOT NULL,
  STARE         VARCHAR2(24)   DEFAULT 'EMIS' NOT NULL,
  DATA_CONSUM   DATE,
  DOC_CONSUM    VARCHAR2(60),
  CREATED_AT    DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SDA_VOUCHER PRIMARY KEY (VOUCHER_ID),
  CONSTRAINT FK_SDA_VOUCHER_P FOREIGN KEY (PARTIC_ID) REFERENCES SDA_PARTIC (PARTIC_ID),
  CONSTRAINT FK_SDA_VOUCHER_PT FOREIGN KEY (POINT_ID) REFERENCES SDA_RETURN_POINT (POINT_ID),
  CONSTRAINT CK_SDA_VOUCHER_STARE CHECK (STARE IN
    ('EMIS','PRESCHIMBAT_NUMERAR','FOLOSIT_CUMPARATURI','EXPIRAT','ANULAT')),
  CONSTRAINT CK_SDA_VOUCHER_VAL CHECK (VALOARE_LEI >= 0),
  CONSTRAINT CK_SDA_VOUCHER_EXP CHECK (DATA_EXPIRARE >= DATA_EMITERE)
);
CREATE SEQUENCE SEQ_SDA_VOUCHER START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_VOUCHER_BI BEFORE INSERT ON SDA_VOUCHER FOR EACH ROW
BEGIN IF :NEW.VOUCHER_ID IS NULL THEN SELECT SEQ_SDA_VOUCHER.NEXTVAL INTO :NEW.VOUCHER_ID FROM DUAL; END IF; END;
/
CREATE UNIQUE INDEX UX_SDA_VOUCHER_COD ON SDA_VOUCHER (COD);
CREATE INDEX IX_SDA_VOUCHER_P ON SDA_VOUCHER (PARTIC_ID);
CREATE INDEX IX_SDA_VOUCHER_PT ON SDA_VOUCHER (POINT_ID);

-- SDA_RETURN.VOUCHER_ID references the ticket issued for that session,
-- added only now that SDA_VOUCHER exists.
ALTER TABLE SDA_RETURN ADD CONSTRAINT FK_SDA_RETURN_VOUCHER
  FOREIGN KEY (VOUCHER_ID) REFERENCES SDA_VOUCHER (VOUCHER_ID);
CREATE INDEX IX_SDA_RETURN_VOUCHER ON SDA_RETURN (VOUCHER_ID);

-- The management-tariff claim toward the Administrator for one period.
-- Settlement frequency is at most 14 days (pct. 202): DATA_SCADENTA
-- applies that rule and ZILE_INTARZIERE records the actual outcome.
CREATE TABLE SDA_SETTLEMENT (
  SETTLEMENT_ID    NUMBER(12)    NOT NULL,
  PARTIC_ID        NUMBER(12)    NOT NULL,
  PERIOADA_START   DATE          NOT NULL,
  PERIOADA_END     DATE          NOT NULL,
  DATA_SCADENTA    DATE          NOT NULL,
  TOTAL_LEI        NUMBER(14,2)  DEFAULT 0 NOT NULL,
  PRIMIT_LEI       NUMBER(14,2)  DEFAULT 0 NOT NULL,
  DATA_INCASARE    DATE,
  ZILE_INTARZIERE  NUMBER(6),
  STARE            VARCHAR2(20)  DEFAULT 'DESCHISA' NOT NULL,
  CREATED_AT       DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_SDA_SETTLEMENT PRIMARY KEY (SETTLEMENT_ID),
  CONSTRAINT FK_SDA_SETTLEMENT_P FOREIGN KEY (PARTIC_ID) REFERENCES SDA_PARTIC (PARTIC_ID),
  CONSTRAINT CK_SDA_SETTLEMENT_PER CHECK (PERIOADA_END >= PERIOADA_START),
  CONSTRAINT CK_SDA_SETTLEMENT_STARE CHECK (STARE IN ('DESCHISA','ACHITATA','INTARZIATA'))
);
CREATE SEQUENCE SEQ_SDA_SETTLEMENT START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_SETTLEMENT_BI BEFORE INSERT ON SDA_SETTLEMENT FOR EACH ROW
BEGIN IF :NEW.SETTLEMENT_ID IS NULL THEN SELECT SEQ_SDA_SETTLEMENT.NEXTVAL INTO :NEW.SETTLEMENT_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_SETTLEMENT_P ON SDA_SETTLEMENT (PARTIC_ID);

-- Analytical breakdown of a settlement, one row per (METODA x REUTILIZABIL
-- x CAT_GEST) combination — the exact shape of the claim the merchant puts
-- to the Administrator (pct. 14.14).
CREATE TABLE SDA_SETTLEMENT_LINE (
  LINE_ID       NUMBER(12)    NOT NULL,
  SETTLEMENT_ID NUMBER(12)    NOT NULL,
  METODA        VARCHAR2(10)  NOT NULL,
  REUTILIZABIL  CHAR(1)       NOT NULL,
  CAT_GEST      CHAR(1)       NOT NULL,
  CANT_BUC      NUMBER(12)    DEFAULT 0 NOT NULL,
  CANT_KG       NUMBER(12,3)  DEFAULT 0 NOT NULL,
  TARIFF_UNITAR NUMBER(10,4)  NOT NULL,
  SUMA_LEI      NUMBER(14,2)  DEFAULT 0 NOT NULL,
  CONSTRAINT PK_SDA_SETTLEMENT_LINE PRIMARY KEY (LINE_ID),
  CONSTRAINT FK_SDA_SETTLEMENT_LINE_S FOREIGN KEY (SETTLEMENT_ID) REFERENCES SDA_SETTLEMENT (SETTLEMENT_ID),
  CONSTRAINT CK_SDA_SL_METODA CHECK (METODA IN ('MANUAL','AUTOMAT')),
  CONSTRAINT CK_SDA_SL_REUT CHECK (REUTILIZABIL IN ('D','N')),
  CONSTRAINT CK_SDA_SL_CATGES CHECK (CAT_GEST IN ('a','b','c','d','e'))
);
CREATE SEQUENCE SEQ_SDA_SETTLEMENT_LINE START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER TRG_SDA_SETTLEMENT_LINE_BI BEFORE INSERT ON SDA_SETTLEMENT_LINE FOR EACH ROW
BEGIN IF :NEW.LINE_ID IS NULL THEN SELECT SEQ_SDA_SETTLEMENT_LINE.NEXTVAL INTO :NEW.LINE_ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_SDA_SETTLEMENT_LINE_S ON SDA_SETTLEMENT_LINE (SETTLEMENT_ID);
