-- NMON_: Oracle-объекты модуля netmon (мониторинг офисной сети и Telegram-каналов).
-- Нормализованная схема: устройства, прогоны сканирования, каналы, лента алертов.
-- Ставится ТОЛЬКО своим установщиком modules/netmon/scripts/netmon_deploy.py.
-- '/' обязателен и ПЕРЕД, и ПОСЛЕ каждого PL/SQL-блока (CLAUDE.md, §2 п.5).

-- Прогон сканирования сети: когда, сколько нашли, сколько новых
CREATE TABLE NMON_SCANS (
  ID           NUMBER        NOT NULL,
  SUBNET       VARCHAR2(32)  NOT NULL,
  STARTED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  FINISHED_AT  TIMESTAMP,
  HOSTS_FOUND  NUMBER        DEFAULT 0 NOT NULL,
  HOSTS_NEW    NUMBER        DEFAULT 0 NOT NULL,
  HOSTS_GONE   NUMBER        DEFAULT 0 NOT NULL,
  RUN_BY       VARCHAR2(100),
  NOTE         VARCHAR2(400),
  CONSTRAINT PK_NMON_SCANS PRIMARY KEY (ID)
);

-- Устройство офисной сети: одна строка на IP, история — в LAST_SEEN/FIRST_SEEN
CREATE TABLE NMON_DEVICES (
  ID           NUMBER        NOT NULL,
  IP           VARCHAR2(45)  NOT NULL,
  DNS_NAME     VARCHAR2(150),
  TTL          NUMBER,
  PORTS        VARCHAR2(300),
  KIND         VARCHAR2(80),
  CRITICALITY  VARCHAR2(10)  DEFAULT 'low' NOT NULL,
  TITLE        VARCHAR2(200),
  SERVER_BANNER VARCHAR2(120),
  SSH_BANNER   VARCHAR2(120),
  IN_ZABBIX    CHAR(1)       DEFAULT 'N' NOT NULL,
  ZABBIX_HOST  VARCHAR2(128),
  ZABBIX_HOSTID NUMBER,
  STATUS       VARCHAR2(10)  DEFAULT 'up' NOT NULL,
  FIRST_SEEN   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  LAST_SEEN    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  LAST_SCAN_ID NUMBER,
  CONSTRAINT PK_NMON_DEVICES PRIMARY KEY (ID),
  CONSTRAINT UK_NMON_DEVICES_IP UNIQUE (IP),
  CONSTRAINT CK_NMON_DEV_ZBX CHECK (IN_ZABBIX IN ('Y','N')),
  CONSTRAINT CK_NMON_DEV_CRIT CHECK (CRITICALITY IN ('high','medium','low')),
  CONSTRAINT CK_NMON_DEV_STATUS CHECK (STATUS IN ('up','down')),
  CONSTRAINT FK_NMON_DEV_SCAN FOREIGN KEY (LAST_SCAN_ID) REFERENCES NMON_SCANS (ID)
);

CREATE INDEX IX_NMON_DEVICES_SCAN ON NMON_DEVICES (LAST_SCAN_ID);
CREATE INDEX IX_NMON_DEVICES_KIND ON NMON_DEVICES (KIND);

-- Telegram-канал, в который Zabbix пишет уведомления
CREATE TABLE NMON_TG_CHANNELS (
  ID            NUMBER        NOT NULL,
  CHAT_ID       VARCHAR2(40)  NOT NULL,
  TITLE         VARCHAR2(200),
  CHAT_TYPE     VARCHAR2(20),
  MEMBERS_CNT   NUMBER,
  BOT_USERNAME  VARCHAR2(100),
  MEDIATYPE     VARCHAR2(100),
  ZBX_USER      VARCHAR2(100),
  IS_ENABLED    CHAR(1)       DEFAULT 'Y' NOT NULL,
  LAST_SYNC_AT  TIMESTAMP,
  LAST_ALERT_AT TIMESTAMP,
  NOTE          VARCHAR2(400),
  CONSTRAINT PK_NMON_TG_CHANNELS PRIMARY KEY (ID),
  CONSTRAINT UK_NMON_TG_CHAT UNIQUE (CHAT_ID),
  CONSTRAINT CK_NMON_TG_ENABLED CHECK (IS_ENABLED IN ('Y','N'))
);

-- Лента сообщений, отправленных Zabbix в каналы (источник — alert.get)
CREATE TABLE NMON_TG_ALERTS (
  ID           NUMBER        NOT NULL,
  ZBX_ALERTID  NUMBER        NOT NULL,
  CHANNEL_ID   NUMBER        NOT NULL,
  SENT_AT      TIMESTAMP     NOT NULL,
  SUBJECT      VARCHAR2(500),
  SEVERITY     VARCHAR2(20),
  HOST_NAME    VARCHAR2(128),
  SEND_STATUS  VARCHAR2(20),
  RETRIES      NUMBER        DEFAULT 0,
  ERROR_TEXT   VARCHAR2(500),
  CONSTRAINT PK_NMON_TG_ALERTS PRIMARY KEY (ID),
  CONSTRAINT UK_NMON_TG_ALERT UNIQUE (ZBX_ALERTID),
  CONSTRAINT FK_NMON_ALERT_CH FOREIGN KEY (CHANNEL_ID) REFERENCES NMON_TG_CHANNELS (ID)
);

CREATE INDEX IX_NMON_ALERTS_CH ON NMON_TG_ALERTS (CHANNEL_ID);
CREATE INDEX IX_NMON_ALERTS_TIME ON NMON_TG_ALERTS (SENT_AT);

CREATE SEQUENCE NMON_SCANS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NMON_DEVICES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NMON_TG_CHANNELS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NMON_TG_ALERTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER NMON_SCANS_BI
BEFORE INSERT ON NMON_SCANS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_SCANS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER NMON_DEVICES_BI
BEFORE INSERT ON NMON_DEVICES FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_DEVICES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER NMON_TG_CHANNELS_BI
BEFORE INSERT ON NMON_TG_CHANNELS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_TG_CHANNELS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER NMON_TG_ALERTS_BI
BEFORE INSERT ON NMON_TG_ALERTS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_TG_ALERTS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
