-- NMON_: Oracle-объекты модуля netmon. Нормализованная схема, свой префикс.
-- Ставится ТОЛЬКО своим установщиком modules/netmon/scripts/netmon_deploy.py.
-- '/' обязателен и ПЕРЕД, и ПОСЛЕ каждого PL/SQL-блока (CLAUDE.md, §2 п.5).

CREATE TABLE NMON_SETTINGS (
  ID          NUMBER        NOT NULL,
  CODE        VARCHAR2(50)  NOT NULL,
  VALUE       VARCHAR2(500),
  UPDATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_NMON_SETTINGS PRIMARY KEY (ID),
  CONSTRAINT UK_NMON_SETTINGS_CODE UNIQUE (CODE)
);

CREATE SEQUENCE NMON_SETTINGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER NMON_SETTINGS_BI
BEFORE INSERT ON NMON_SETTINGS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_SETTINGS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
