-- NMON_FAC_*: инженерное оборудование офиса — кондиционеры, котёл, СКУД,
-- лифт, умные розетки. То, что нельзя опросить по сети, ведётся журналом
-- обслуживания с фотофиксацией от сотрудников.
--
-- Текстовые колонки в СИМВОЛЬНОЙ семантике (N CHAR): Oracle считает
-- VARCHAR2 в байтах, а здесь всё на русском.
-- Ставится своим установщиком modules/netmon/scripts/netmon_deploy.py.
-- '/' обязателен и ПЕРЕД, и ПОСЛЕ каждого PL/SQL-блока (CLAUDE.md, §2 п.5).

CREATE TABLE NMON_FACILITIES (
  ID            NUMBER              NOT NULL,
  CODE          VARCHAR2(40 CHAR)   NOT NULL,
  KIND          VARCHAR2(24)        NOT NULL,
  NAME          VARCHAR2(150 CHAR)  NOT NULL,
  ROOM          VARCHAR2(100 CHAR),
  MODEL         VARCHAR2(150 CHAR),
  SERIAL_NO     VARCHAR2(80 CHAR),
  VENDOR        VARCHAR2(100 CHAR),
  IP            VARCHAR2(45),
  PROTOCOL      VARCHAR2(40 CHAR),
  INSTALLED_ON  DATE,
  RESPONSIBLE   VARCHAR2(120 CHAR),
  SERVICE_DAYS  NUMBER              DEFAULT 180 NOT NULL,
  STATUS        VARCHAR2(20)        DEFAULT 'ok' NOT NULL,
  IS_MONITORED  CHAR(1)             DEFAULT 'N' NOT NULL,
  NOTE          VARCHAR2(1000 CHAR),
  CREATED_AT    TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_NMON_FACILITIES PRIMARY KEY (ID),
  CONSTRAINT UK_NMON_FAC_CODE UNIQUE (CODE),
  CONSTRAINT CK_NMON_FAC_KIND CHECK (KIND IN
    ('aircon','boiler','access','elevator','smartplug','other')),
  CONSTRAINT CK_NMON_FAC_STATUS CHECK (STATUS IN ('ok','attention','fault','off')),
  CONSTRAINT CK_NMON_FAC_MON CHECK (IS_MONITORED IN ('Y','N'))
);

CREATE INDEX IX_NMON_FAC_KIND ON NMON_FACILITIES (KIND);
CREATE INDEX IX_NMON_FAC_ROOM ON NMON_FACILITIES (ROOM);

-- Журнал работ: замена фреона, чистка фильтров, осмотр, ремонт
CREATE TABLE NMON_FAC_LOG (
  ID            NUMBER              NOT NULL,
  FACILITY_ID   NUMBER              NOT NULL,
  WORK_KIND     VARCHAR2(30)        NOT NULL,
  DONE_AT       DATE                DEFAULT SYSDATE NOT NULL,
  PERFORMER     VARCHAR2(120 CHAR),
  DESCRIPTION   VARCHAR2(2000 CHAR),
  NEXT_DUE      DATE,
  COST_MDL      NUMBER(12,2),
  CREATED_BY    VARCHAR2(100 CHAR),
  CREATED_AT    TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_NMON_FAC_LOG PRIMARY KEY (ID),
  CONSTRAINT FK_NMON_LOG_FAC FOREIGN KEY (FACILITY_ID)
    REFERENCES NMON_FACILITIES (ID),
  CONSTRAINT CK_NMON_LOG_KIND CHECK (WORK_KIND IN
    ('freon','filter','inspect','repair','install','other'))
);

CREATE INDEX IX_NMON_LOG_FAC ON NMON_FAC_LOG (FACILITY_ID);
CREATE INDEX IX_NMON_LOG_DATE ON NMON_FAC_LOG (DONE_AT);

-- Фотофиксация состояния: снимок делает сотрудник, файл лежит на диске,
-- в базе — только путь и кто снял.
CREATE TABLE NMON_FAC_PHOTO (
  ID            NUMBER              NOT NULL,
  FACILITY_ID   NUMBER              NOT NULL,
  LOG_ID        NUMBER,
  FILE_PATH     VARCHAR2(400 CHAR)  NOT NULL,
  FILE_NAME     VARCHAR2(200 CHAR),
  CAPTION       VARCHAR2(500 CHAR),
  TAKEN_BY      VARCHAR2(120 CHAR),
  TAKEN_AT      TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
  SIZE_KB       NUMBER,
  CONSTRAINT PK_NMON_FAC_PHOTO PRIMARY KEY (ID),
  CONSTRAINT FK_NMON_PHOTO_FAC FOREIGN KEY (FACILITY_ID)
    REFERENCES NMON_FACILITIES (ID),
  CONSTRAINT FK_NMON_PHOTO_LOG FOREIGN KEY (LOG_ID)
    REFERENCES NMON_FAC_LOG (ID)
);

CREATE INDEX IX_NMON_PHOTO_FAC ON NMON_FAC_PHOTO (FACILITY_ID);

CREATE SEQUENCE NMON_FACILITIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NMON_FAC_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NMON_FAC_PHOTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER NMON_FACILITIES_BI
BEFORE INSERT ON NMON_FACILITIES FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_FACILITIES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER NMON_FAC_LOG_BI
BEFORE INSERT ON NMON_FAC_LOG FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_FAC_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER NMON_FAC_PHOTO_BI
BEFORE INSERT ON NMON_FAC_PHOTO FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_FAC_PHOTO_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
