-- NMON_FS_: файловые ресурсы офиса на 192.168.0.21 (Samba) и выдача прав.
-- Ставится своим установщиком modules/netmon/scripts/netmon_deploy.py.
-- Без точки с запятой в комментариях: общий разборщик режет по ней.
--
-- Политика доступа хранится здесь, а не в коде: роли, ресурсы и какая роль
-- куда входит. Люди учитываются по почте @unisim-soft.com, а на сервере у
-- каждого локальная учётка Samba с именем, выведенным из почты.

-- Роль = локальная группа Unix на файловом сервере
CREATE TABLE NMON_FS_ROLES (
  CODE        VARCHAR2(20)   NOT NULL,
  TITLE       VARCHAR2(100 CHAR) NOT NULL,
  UNIX_GROUP  VARCHAR2(32)   NOT NULL,
  SORT_ORDER  NUMBER(3)      DEFAULT 0 NOT NULL,
  CONSTRAINT PK_NMON_FS_ROLES PRIMARY KEY (CODE),
  CONSTRAINT UK_NMON_FS_ROLES_GRP UNIQUE (UNIX_GROUP)
);

-- Ресурс Samba и буква диска, под которой он стоит у сотрудников
CREATE TABLE NMON_FS_SHARES (
  NAME        VARCHAR2(40)   NOT NULL,
  DRIVE       CHAR(1)        NOT NULL,
  TITLE       VARCHAR2(200 CHAR),
  SORT_ORDER  NUMBER(3)      DEFAULT 0 NOT NULL,
  CONSTRAINT PK_NMON_FS_SHARES PRIMARY KEY (NAME),
  CONSTRAINT UK_NMON_FS_SHARES_DRIVE UNIQUE (DRIVE)
);

-- Политика: какая роль входит в какой ресурс
CREATE TABLE NMON_FS_POLICY (
  SHARE_NAME  VARCHAR2(40)   NOT NULL,
  ROLE_CODE   VARCHAR2(20)   NOT NULL,
  CONSTRAINT PK_NMON_FS_POLICY PRIMARY KEY (SHARE_NAME, ROLE_CODE),
  CONSTRAINT FK_NMON_FS_POL_SHARE FOREIGN KEY (SHARE_NAME) REFERENCES NMON_FS_SHARES (NAME),
  CONSTRAINT FK_NMON_FS_POL_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES NMON_FS_ROLES (CODE)
);

CREATE INDEX IX_NMON_FS_POLICY_ROLE ON NMON_FS_POLICY (ROLE_CODE);

-- Сотрудник: почта — ключ учёта, LOGIN — учётка на файловом сервере
CREATE TABLE NMON_FS_PEOPLE (
  ID          NUMBER         NOT NULL,
  EMAIL       VARCHAR2(100)  NOT NULL,
  LOGIN       VARCHAR2(32)   NOT NULL,
  FULL_NAME   VARCHAR2(200 CHAR),
  ROLE_CODE   VARCHAR2(20)   NOT NULL,
  STATUS      VARCHAR2(10)   DEFAULT 'active' NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(100),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE,
  NOTE        VARCHAR2(400 CHAR),
  CONSTRAINT PK_NMON_FS_PEOPLE PRIMARY KEY (ID),
  CONSTRAINT UK_NMON_FS_PEOPLE_EMAIL UNIQUE (EMAIL),
  CONSTRAINT UK_NMON_FS_PEOPLE_LOGIN UNIQUE (LOGIN),
  CONSTRAINT FK_NMON_FS_PEOPLE_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES NMON_FS_ROLES (CODE),
  CONSTRAINT CK_NMON_FS_PEOPLE_STATUS CHECK (STATUS IN ('active','disabled'))
);

CREATE INDEX IX_NMON_FS_PEOPLE_ROLE ON NMON_FS_PEOPLE (ROLE_CODE);

-- Журнал изменений, только добавление: кто, когда, что сделал с доступом
CREATE TABLE NMON_FS_LOG (
  ID          NUMBER         NOT NULL,
  AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ACTOR       VARCHAR2(100),
  ACTION      VARCHAR2(30)   NOT NULL,
  TARGET      VARCHAR2(100),
  DETAILS     VARCHAR2(2000 CHAR),
  CONSTRAINT PK_NMON_FS_LOG PRIMARY KEY (ID)
);

CREATE INDEX IX_NMON_FS_LOG_TARGET ON NMON_FS_LOG (TARGET);

CREATE SEQUENCE NMON_FS_PEOPLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NMON_FS_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE OR REPLACE TRIGGER NMON_FS_PEOPLE_BI
BEFORE INSERT ON NMON_FS_PEOPLE FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_FS_PEOPLE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER NMON_FS_LOG_BI
BEFORE INSERT ON NMON_FS_LOG FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NMON_FS_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
-- Начальная политика владельца (06.10.2026). U, K, T только администрация,
-- I, X, M все три группы.
INSERT INTO NMON_FS_ROLES (CODE, TITLE, UNIX_GROUP, SORT_ORDER) VALUES ('admin', 'Администрация', 'fs_administratia', 1);
INSERT INTO NMON_FS_ROLES (CODE, TITLE, UNIX_GROUP, SORT_ORDER) VALUES ('consult', 'Консультанты и программисты', 'fs_consult_prog', 2);
INSERT INTO NMON_FS_ROLES (CODE, TITLE, UNIX_GROUP, SORT_ORDER) VALUES ('support', 'Инженеры техподдержки', 'fs_support', 3);
INSERT INTO NMON_FS_SHARES (NAME, DRIVE, TITLE, SORT_ORDER) VALUES ('unisim', 'U', 'Unisim', 1);
INSERT INTO NMON_FS_SHARES (NAME, DRIVE, TITLE, SORT_ORDER) VALUES ('uni_bank', 'K', 'Uni_bank', 2);
INSERT INTO NMON_FS_SHARES (NAME, DRIVE, TITLE, SORT_ORDER) VALUES ('st8', 'T', 'st8 — хранилище Proxmox', 3);
INSERT INTO NMON_FS_SHARES (NAME, DRIVE, TITLE, SORT_ORDER) VALUES ('docs', 'I', 'Документы', 4);
INSERT INTO NMON_FS_SHARES (NAME, DRIVE, TITLE, SORT_ORDER) VALUES ('shares', 'X', 'Общие папки', 5);
INSERT INTO NMON_FS_SHARES (NAME, DRIVE, TITLE, SORT_ORDER) VALUES ('db', 'M', 'Базы', 6);
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('unisim', 'admin');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('uni_bank', 'admin');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('st8', 'admin');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('docs', 'admin');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('docs', 'consult');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('docs', 'support');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('shares', 'admin');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('shares', 'consult');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('shares', 'support');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('db', 'admin');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('db', 'consult');
INSERT INTO NMON_FS_POLICY (SHARE_NAME, ROLE_CODE) VALUES ('db', 'support');
