-- RO: Conturul CRM_* (05.09.2026) - baza proprie de clienti a CRM-ului (beta),
--     replica web a Demo CRM din repo-ul Contragenti (clients.db pe SQLite):
--       CRM_SETTING    setarile (adresa Contragenti, limba)
--       CRM_CLIENT     clientul = cardul contrapartii, IDNO unic = deduplicare
--       CRM_FOUNDER    fondatorii (founders/founder@name,@share)
--       CRM_DEBT       datoriile la buget (debts/debt@nr,@type,@sum)
--       CRM_EVENT_LOG  jurnal append-only (adaugat / duplicat / sters / import)
--     Text ASCII: baza OfficePlus e CL8MSWIN1251.
-- EN: CRM_ schema for the web CRM (beta) integrated with Contragenti.

CREATE TABLE CRM_SETTING (
    SKEY      VARCHAR2(60)   NOT NULL,
    SVALUE    VARCHAR2(2000),
    UPDATED   DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CRM_SETTING PRIMARY KEY (SKEY)
)
/

CREATE TABLE CRM_CLIENT (
    ID             NUMBER          NOT NULL,
    IDNO           VARCHAR2(20)    NOT NULL,
    NAME           VARCHAR2(400),
    REG_DATE       VARCHAR2(20),               -- DD.MM.YYYY, asa cum vine din registru
    LEGAL_FORM     VARCHAR2(200),
    IS_LIQUIDATED  NUMBER(1)       DEFAULT 0 NOT NULL,
    ADDRESS        VARCHAR2(1000),
    MANAGERS       VARCHAR2(1000),
    DETAILS_TEXT   CLOB,
    SOURCE         VARCHAR2(60),
    SOURCE_UPDATED VARCHAR2(40),
    NOTE           VARCHAR2(2000),
    CREATED        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED        DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CRM_CLIENT PRIMARY KEY (ID),
    CONSTRAINT UQ_CRM_CLIENT_IDNO UNIQUE (IDNO)
)
/

CREATE SEQUENCE CRM_CLIENT_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_CLIENT_BI
BEFORE INSERT ON CRM_CLIENT FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_CLIENT_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_FOUNDER (
    ID         NUMBER        NOT NULL,
    CLIENT_ID  NUMBER        NOT NULL,
    NAME       VARCHAR2(400) NOT NULL,
    SHARE_PCT  NUMBER(9,4),
    CONSTRAINT PK_CRM_FOUNDER PRIMARY KEY (ID),
    CONSTRAINT FK_CRM_FOUNDER_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES CRM_CLIENT (ID) ON DELETE CASCADE
)
/

CREATE INDEX IX_CRM_FOUNDER_CLIENT ON CRM_FOUNDER (CLIENT_ID)
/

CREATE SEQUENCE CRM_FOUNDER_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_FOUNDER_BI
BEFORE INSERT ON CRM_FOUNDER FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_FOUNDER_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_DEBT (
    ID         NUMBER        NOT NULL,
    CLIENT_ID  NUMBER        NOT NULL,
    NR         NUMBER,
    DEBT_TYPE  VARCHAR2(200),
    AMOUNT     NUMBER(14,2),
    CURRENCY   VARCHAR2(3)   DEFAULT 'MDL',
    CONSTRAINT PK_CRM_DEBT PRIMARY KEY (ID),
    CONSTRAINT FK_CRM_DEBT_CLIENT FOREIGN KEY (CLIENT_ID)
        REFERENCES CRM_CLIENT (ID) ON DELETE CASCADE
)
/

CREATE INDEX IX_CRM_DEBT_CLIENT ON CRM_DEBT (CLIENT_ID)
/

CREATE SEQUENCE CRM_DEBT_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_DEBT_BI
BEFORE INSERT ON CRM_DEBT FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_DEBT_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_EVENT_LOG (
    ID         NUMBER         NOT NULL,
    TS         DATE           DEFAULT SYSDATE NOT NULL,
    CLIENT_ID  NUMBER,
    IDNO       VARCHAR2(20),
    EVENT      VARCHAR2(40)   NOT NULL,       -- added | dup | updated | deleted | import_error
    SRC        VARCHAR2(20),                  -- contragenti | return_to | xml | ui
    DETAIL     VARCHAR2(2000),
    CONSTRAINT PK_CRM_EVENT_LOG PRIMARY KEY (ID)
)
/

CREATE INDEX IX_CRM_EVENT_LOG_TS ON CRM_EVENT_LOG (TS)
/

CREATE SEQUENCE CRM_EVENT_LOG_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_EVENT_LOG_BI
BEFORE INSERT ON CRM_EVENT_LOG FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_EVENT_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/
