-- RO: Conturul CRM_* partea a doua (08.09.2026) - procesul "de la contract la bani"
--     dupa schema prototipului Demo CRM (crm_delphi/uCrmData.pas, TZ_CRM_ZAVOD §9.1):
--       contacts, leads, deals, items, orders + order_lines, tasks, projects.
--     Numele coloanelor = cele din prototip (compatibilitate cu clientii Delphi/Swift
--     si cu datele demo), cu trei exceptii impuse de Oracle: number -> DOC_NO,
--     sum -> LINE_SUM, position -> JOB_TITLE, unit_ ramine UNIT_.
--     Multi-chirias (cerinta 08.09.2026: instrument al OfficePlus SI al fiecarui
--     client din cabinet): fiecare rind are OWNER_KIND ('office' | 'client') si
--     OWNER_ID (0 pentru office, YBIRO_CLIENT.ID pentru client). Rindurile vechi
--     din CRM_CLIENT devin 'office'.
--     Valorile enumerarilor se scriu canonic (ca in prototip), traducerile sint in
--     lang.json - de aceea DDL-ul nu are DEFAULT-uri pe ele (text ASCII in DDL).
--     Datele sint DATE (nu TEXT ca in SQLite); API-ul le da/primeste yyyy-mm-dd.
-- EN: CRM process schema mirroring the Demo CRM prototype, multi-tenant.

ALTER TABLE CRM_CLIENT ADD (
    OWNER_KIND      VARCHAR2(10)  DEFAULT 'office' NOT NULL,
    OWNER_ID        NUMBER        DEFAULT 0 NOT NULL,
    CLIENT_TYPE     VARCHAR2(40),
    PHONE           VARCHAR2(60),
    EMAIL           VARCHAR2(120),
    CONTACT_PERSON  VARCHAR2(200)
)
/

CREATE INDEX IX_CRM_CLIENT_OWNER ON CRM_CLIENT (OWNER_KIND, OWNER_ID)
/

ALTER TABLE CRM_EVENT_LOG ADD (
    OWNER_KIND      VARCHAR2(10)  DEFAULT 'office' NOT NULL,
    OWNER_ID        NUMBER        DEFAULT 0 NOT NULL
)
/

CREATE TABLE CRM_CONTACT (
    ID          NUMBER         NOT NULL,
    OWNER_KIND  VARCHAR2(10)   DEFAULT 'office' NOT NULL,
    OWNER_ID    NUMBER         DEFAULT 0 NOT NULL,
    NAME        VARCHAR2(200)  NOT NULL,
    CLIENT_ID   NUMBER,
    JOB_TITLE   VARCHAR2(120),
    PHONE       VARCHAR2(60),
    EMAIL       VARCHAR2(120),
    NOTES       VARCHAR2(2000),
    CONSTRAINT PK_CRM_CONTACT PRIMARY KEY (ID)
)
/

CREATE INDEX IX_CRM_CONTACT_OWNER ON CRM_CONTACT (OWNER_KIND, OWNER_ID)
/

CREATE SEQUENCE CRM_CONTACT_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_CONTACT_BI
BEFORE INSERT ON CRM_CONTACT FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_CONTACT_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_LEAD (
    ID          NUMBER         NOT NULL,
    OWNER_KIND  VARCHAR2(10)   DEFAULT 'office' NOT NULL,
    OWNER_ID    NUMBER         DEFAULT 0 NOT NULL,
    NAME        VARCHAR2(200)  NOT NULL,
    COMPANY     VARCHAR2(200),
    STATUS      VARCHAR2(40),
    SOURCE      VARCHAR2(40),
    PHONE       VARCHAR2(60),
    EMAIL       VARCHAR2(120),
    NOTES       VARCHAR2(2000),
    CLIENT_ID   NUMBER,
    CREATED_AT  DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CRM_LEAD PRIMARY KEY (ID)
)
/

CREATE INDEX IX_CRM_LEAD_OWNER ON CRM_LEAD (OWNER_KIND, OWNER_ID)
/

CREATE SEQUENCE CRM_LEAD_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_LEAD_BI
BEFORE INSERT ON CRM_LEAD FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_LEAD_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_DEAL (
    ID          NUMBER         NOT NULL,
    OWNER_KIND  VARCHAR2(10)   DEFAULT 'office' NOT NULL,
    OWNER_ID    NUMBER         DEFAULT 0 NOT NULL,
    TITLE       VARCHAR2(300)  NOT NULL,
    CLIENT_ID   NUMBER,
    STAGE       VARCHAR2(40),
    AMOUNT      NUMBER(14,2)   DEFAULT 0,
    CLOSE_DATE  DATE,
    NOTES       VARCHAR2(2000),
    CREATED_AT  DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CRM_DEAL PRIMARY KEY (ID)
)
/

CREATE INDEX IX_CRM_DEAL_OWNER ON CRM_DEAL (OWNER_KIND, OWNER_ID)
/

CREATE SEQUENCE CRM_DEAL_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_DEAL_BI
BEFORE INSERT ON CRM_DEAL FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_DEAL_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_ITEM (
    ID          NUMBER         NOT NULL,
    OWNER_KIND  VARCHAR2(10)   DEFAULT 'office' NOT NULL,
    OWNER_ID    NUMBER         DEFAULT 0 NOT NULL,
    CODE        VARCHAR2(40),
    NAME        VARCHAR2(300)  NOT NULL,
    KIND        VARCHAR2(40),
    UNIT_       VARCHAR2(20),
    PRICE       NUMBER(14,2)   DEFAULT 0,
    VAT         NUMBER(5,2)    DEFAULT 20,
    STOCK       NUMBER(14,3)   DEFAULT 0,
    NOTES       VARCHAR2(2000),
    CONSTRAINT PK_CRM_ITEM PRIMARY KEY (ID)
)
/

CREATE INDEX IX_CRM_ITEM_OWNER ON CRM_ITEM (OWNER_KIND, OWNER_ID)
/

CREATE SEQUENCE CRM_ITEM_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_ITEM_BI
BEFORE INSERT ON CRM_ITEM FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_ITEM_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_PROJECT (
    ID              NUMBER         NOT NULL,
    OWNER_KIND      VARCHAR2(10)   DEFAULT 'office' NOT NULL,
    OWNER_ID        NUMBER         DEFAULT 0 NOT NULL,
    NAME            VARCHAR2(300)  NOT NULL,
    CLIENT_ID       NUMBER,
    KIND            VARCHAR2(40),
    STATUS          VARCHAR2(40),
    TENDER_NO       VARCHAR2(60),
    TENDER_DEADLINE DATE,
    BUDGET          NUMBER(14,2)   DEFAULT 0,
    PREPAY_PCT      NUMBER(5,2)    DEFAULT 0,
    PREPAID         NUMBER(14,2)   DEFAULT 0,
    PAID            NUMBER(14,2)   DEFAULT 0,
    START_DATE      DATE,
    DUE_DATE        DATE,
    MANAGER         VARCHAR2(120),
    NOTES           VARCHAR2(2000),
    CREATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CRM_PROJECT PRIMARY KEY (ID)
)
/

CREATE INDEX IX_CRM_PROJECT_OWNER ON CRM_PROJECT (OWNER_KIND, OWNER_ID)
/

CREATE SEQUENCE CRM_PROJECT_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_PROJECT_BI
BEFORE INSERT ON CRM_PROJECT FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_PROJECT_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_ORDER (
    ID          NUMBER         NOT NULL,
    OWNER_KIND  VARCHAR2(10)   DEFAULT 'office' NOT NULL,
    OWNER_ID    NUMBER         DEFAULT 0 NOT NULL,
    DOC_NO      VARCHAR2(40)   NOT NULL,
    ORDER_DATE  DATE,
    CLIENT_ID   NUMBER,
    PROJECT_ID  NUMBER,
    KIND        VARCHAR2(40),
    STATUS      VARCHAR2(40),
    TOTAL       NUMBER(14,2)   DEFAULT 0,
    ADVANCE     NUMBER(14,2)   DEFAULT 0,
    PAID        NUMBER(14,2)   DEFAULT 0,
    DUE_DATE    DATE,
    SHIP_DATE   DATE,
    NOTES       VARCHAR2(2000),
    POSTED      NUMBER(1)      DEFAULT 0 NOT NULL,
    ERP_BATCH   VARCHAR2(60),
    ERP_SENT_AT DATE,
    CREATED_AT  DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CRM_ORDER PRIMARY KEY (ID)
)
/

CREATE INDEX IX_CRM_ORDER_OWNER ON CRM_ORDER (OWNER_KIND, OWNER_ID)
/

CREATE SEQUENCE CRM_ORDER_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_ORDER_BI
BEFORE INSERT ON CRM_ORDER FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_ORDER_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_ORDER_LINE (
    ID          NUMBER         NOT NULL,
    ORDER_ID    NUMBER         NOT NULL,
    ITEM_ID     NUMBER         NOT NULL,
    QTY         NUMBER(14,3)   DEFAULT 1,
    PRICE       NUMBER(14,2)   DEFAULT 0,
    LINE_SUM    NUMBER(14,2)   DEFAULT 0,
    CONSTRAINT PK_CRM_ORDER_LINE PRIMARY KEY (ID),
    CONSTRAINT FK_CRM_ORDER_LINE_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES CRM_ORDER (ID) ON DELETE CASCADE
)
/

CREATE INDEX IX_CRM_ORDER_LINE_ORDER ON CRM_ORDER_LINE (ORDER_ID)
/

CREATE SEQUENCE CRM_ORDER_LINE_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_ORDER_LINE_BI
BEFORE INSERT ON CRM_ORDER_LINE FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_ORDER_LINE_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE TABLE CRM_TASK (
    ID          NUMBER         NOT NULL,
    OWNER_KIND  VARCHAR2(10)   DEFAULT 'office' NOT NULL,
    OWNER_ID    NUMBER         DEFAULT 0 NOT NULL,
    SUBJECT     VARCHAR2(300)  NOT NULL,
    KIND        VARCHAR2(40),
    DUE_AT      DATE,
    CLIENT_ID   NUMBER,
    DEAL_ID     NUMBER,
    PROJECT_ID  NUMBER,
    DONE        NUMBER(1)      DEFAULT 0 NOT NULL,
    STAGE       VARCHAR2(40),
    PRIORITY    VARCHAR2(40),
    ASSIGNEE    VARCHAR2(120),
    PLAN_START  DATE,
    HOURS_PLAN  NUMBER(9,2),
    HOURS_FACT  NUMBER(9,2),
    DEPENDS_ON  NUMBER,
    SEQ         NUMBER,
    NOTES       VARCHAR2(2000),
    CREATED_AT  DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CRM_TASK PRIMARY KEY (ID)
)
/

CREATE INDEX IX_CRM_TASK_OWNER ON CRM_TASK (OWNER_KIND, OWNER_ID)
/

CREATE INDEX IX_CRM_TASK_PROJECT ON CRM_TASK (PROJECT_ID)
/

CREATE SEQUENCE CRM_TASK_SEQ START WITH 1 INCREMENT BY 1
/

CREATE OR REPLACE TRIGGER CRM_TASK_BI
BEFORE INSERT ON CRM_TASK FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  SELECT CRM_TASK_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/
