-- Copie a sql/50_credite_tables.sql pentru OfficePlus (Oracle 11g).
-- =====================================================================
-- RO/RU: TMS_CREDITE_* — creditare: provideri API (EasyCredit, Iute),
--        organizatii, pachete, cereri si jurnalul apelurilor API.
-- Acelasi DDL se aplica in AMBELE baze: Oracle ADB (proiectul principal)
-- si Oracle 11g (OfficePlus/Biro26). Fara identity — secventa + trigger.
-- Migrare din YBIRO_CREDIT_* — vezi deploy_credite_oracle.py.
-- =====================================================================

CREATE TABLE TMS_CREDITE_PROVIDER (
  ID        NUMBER NOT NULL,
  CODE      VARCHAR2(30)  NOT NULL,
  NAME      VARCHAR2(100) NOT NULL,
  ENABLED   VARCHAR2(1)   DEFAULT '0',
  ENV       VARCHAR2(20)  DEFAULT 'sandbox',
  BASE_URL  VARCHAR2(400),
  ICON      VARCHAR2(20),
  COLOR     VARCHAR2(20),
  INFO      VARCHAR2(2000),
  ORD       NUMBER DEFAULT 0,
  UPDATED   DATE DEFAULT SYSDATE,
  CONSTRAINT PK_TMS_CREDITE_PROVIDER PRIMARY KEY (ID),
  CONSTRAINT UQ_TMS_CREDITE_PROV_CODE UNIQUE (CODE)
);
CREATE SEQUENCE TMS_CREDITE_PROVIDER_SEQ START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER TMS_CREDITE_PROVIDER_BI
  BEFORE INSERT ON TMS_CREDITE_PROVIDER FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN SELECT TMS_CREDITE_PROVIDER_SEQ.NEXTVAL INTO :NEW.ID FROM dual; END;
/

CREATE TABLE TMS_CREDITE_PROVIDER_PARAM (
  PROVIDER_ID NUMBER       NOT NULL,
  PARAM_NAME  VARCHAR2(40) NOT NULL,
  PARAM_VALUE VARCHAR2(400),
  IS_SECRET   VARCHAR2(1) DEFAULT '0',
  CONSTRAINT PK_TMS_CREDITE_PRV_PARAM PRIMARY KEY (PROVIDER_ID, PARAM_NAME),
  CONSTRAINT FK_TMS_CREDITE_PRV_PARAM FOREIGN KEY (PROVIDER_ID)
    REFERENCES TMS_CREDITE_PROVIDER (ID)
);

CREATE TABLE TMS_CREDITE_ORG (
  ID          NUMBER NOT NULL,
  NAME        VARCHAR2(100) NOT NULL,
  ENABLED     VARCHAR2(1) DEFAULT '1',
  ORG_MODE    VARCHAR2(10) DEFAULT 'manual',
  PROVIDER_ID NUMBER,
  API_URL     VARCHAR2(400),
  LOGO_URL    VARCHAR2(400),
  INFO        VARCHAR2(2000),
  ORD         NUMBER DEFAULT 0,
  CONSTRAINT PK_TMS_CREDITE_ORG PRIMARY KEY (ID),
  CONSTRAINT FK_TMS_CREDITE_ORG_PRV FOREIGN KEY (PROVIDER_ID)
    REFERENCES TMS_CREDITE_PROVIDER (ID)
);
CREATE SEQUENCE TMS_CREDITE_ORG_SEQ START WITH 1 NOCACHE;
CREATE OR REPLACE TRIGGER TMS_CREDITE_ORG_BI
  BEFORE INSERT ON TMS_CREDITE_ORG FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN SELECT TMS_CREDITE_ORG_SEQ.NEXTVAL INTO :NEW.ID FROM dual; END;
/

CREATE TABLE TMS_CREDITE_PLAN (
  ID              NUMBER NOT NULL,
  ORG_ID          NUMBER NOT NULL,
  NAME            VARCHAR2(120) NOT NULL,
  MONTHS_MIN      NUMBER NOT NULL,
  MONTHS_MAX      NUMBER NOT NULL,
  AMOUNT_MIN      NUMBER DEFAULT 1000,
  AMOUNT_MAX      NUMBER DEFAULT 100000,
  MARKUP_PCT      NUMBER DEFAULT 0,
  ANNUAL_PCT      NUMBER DEFAULT 0,
  MONTHLY_FEE_PCT NUMBER DEFAULT 0,
  ISSUE_FEE       NUMBER DEFAULT 0,
  AVANS_MIN_PCT   NUMBER DEFAULT 0,
  ENABLED         VARCHAR2(1) DEFAULT '1',
  INFO            VARCHAR2(2000),
  CONSTRAINT PK_TMS_CREDITE_PLAN PRIMARY KEY (ID),
  CONSTRAINT FK_TMS_CREDITE_PLAN_ORG FOREIGN KEY (ORG_ID)
    REFERENCES TMS_CREDITE_ORG (ID)
);
CREATE SEQUENCE TMS_CREDITE_PLAN_SEQ START WITH 1 NOCACHE;
CREATE INDEX IX_TMS_CREDITE_PLAN_ORG ON TMS_CREDITE_PLAN (ORG_ID);
CREATE OR REPLACE TRIGGER TMS_CREDITE_PLAN_BI
  BEFORE INSERT ON TMS_CREDITE_PLAN FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN SELECT TMS_CREDITE_PLAN_SEQ.NEXTVAL INTO :NEW.ID FROM dual; END;
/

CREATE TABLE TMS_CREDITE_REQ (
  ID                 NUMBER NOT NULL,
  ORG_ID             NUMBER,
  PLAN_ID            NUMBER,
  MONTHS             NUMBER,
  PRODUCT_COD        NUMBER,
  PRODUCT_NAME       VARCHAR2(300),
  QTY                NUMBER DEFAULT 1,
  AMOUNT             NUMBER,
  CREDIT_PRICE       NUMBER,
  MONTHLY            NUMBER,
  CLIENT_NAME        VARCHAR2(200),
  PHONE              VARCHAR2(40),
  STATUS             VARCHAR2(20) DEFAULT 'NEW',
  PROVIDER_CODE      VARCHAR2(30),
  EXT_REF            VARCHAR2(120),
  API_STATUS         VARCHAR2(60),
  PREAPPROVED_AMOUNT NUMBER,
  IDNP_MASKED        VARCHAR2(20),
  LAST_CHECK         DATE,
  CREATED            DATE DEFAULT SYSDATE,
  CONSTRAINT PK_TMS_CREDITE_REQ PRIMARY KEY (ID)
);
CREATE SEQUENCE TMS_CREDITE_REQ_SEQ START WITH 1 NOCACHE;
CREATE INDEX IX_TMS_CREDITE_REQ_EXT ON TMS_CREDITE_REQ (EXT_REF);
CREATE OR REPLACE TRIGGER TMS_CREDITE_REQ_BI
  BEFORE INSERT ON TMS_CREDITE_REQ FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN SELECT TMS_CREDITE_REQ_SEQ.NEXTVAL INTO :NEW.ID FROM dual; END;
/

CREATE TABLE TMS_CREDITE_REQ_EVENT (
  ID            NUMBER NOT NULL,
  REQ_ID        NUMBER,
  PROVIDER_CODE VARCHAR2(30),
  OP            VARCHAR2(30),
  HTTP_CODE     NUMBER,
  DURATION_MS   NUMBER,
  PAYLOAD       CLOB,
  RESULT        CLOB,
  IS_ERROR      VARCHAR2(1) DEFAULT '0',
  CREATED       DATE DEFAULT SYSDATE,
  CONSTRAINT PK_TMS_CREDITE_REQ_EVENT PRIMARY KEY (ID)
);
CREATE SEQUENCE TMS_CREDITE_REQ_EVENT_SEQ START WITH 1 NOCACHE;
CREATE INDEX IX_TMS_CREDITE_EVT_REQ ON TMS_CREDITE_REQ_EVENT (REQ_ID);
CREATE OR REPLACE TRIGGER TMS_CREDITE_REQ_EVENT_BI
  BEFORE INSERT ON TMS_CREDITE_REQ_EVENT FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN SELECT TMS_CREDITE_REQ_EVENT_SEQ.NEXTVAL INTO :NEW.ID FROM dual; END;
/
