#!/usr/bin/env python3
"""RO: trece denumirile RUSESTI ale categoriilor de catalog pe ROMANA.

De ce: numele de baza (`BIRO26_GOODS.CATEGORIE`) e si cheia dupa care vitrina
afiseaza categoria si dupa care se leaga dictionarul `YBIRO_GRP_I18N`. Cind el e
scris in rusa, clientul cu limba ROMANA vede tot rusa — nu exista de unde lua
altceva. Deci: numele romanesc devine numele de baza, iar rusescul se pastreaza
in dictionar ca NAME_RU (nu se pierde nimic, iar la RU vitrina arata la fel ca inainte).

Rulare:
    python scripts/biro26_cat_ro_migrate.py            # doar arata ce ar face
    python scripts/biro26_cat_ro_migrate.py --apply    # scrie in baza

Totul e jurnalizat in YBIRO_CAT_RENAME (vechi -> nou, cine si cind), deci se
poate si intoarce inapoi.
EN: move Russian catalog category names to Romanian; Russian kept as NAME_RU.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models.biro26_cat_ro import ramine_rus, tradu  # noqa: E402
from models.biro26_db import Biro26DB  # noqa: E402
from models.biro26_oracle_store import _rows  # noqa: E402

DDL_LOG = """CREATE TABLE YBIRO_CAT_RENAME (
  ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  KIND      VARCHAR2(16)  NOT NULL,
  NAME_OLD  VARCHAR2(400) NOT NULL,
  NAME_NEW  VARCHAR2(400) NOT NULL,
  PRODUSE   NUMBER,
  CREATED   DATE DEFAULT SYSDATE,
  CREATED_BY VARCHAR2(64)
)"""


def _db():
    db = Biro26DB()

    def q(sql, p=None, tries=3):
        last = None
        for _ in range(tries):
            r = db.execute_query(sql, p or {})
            if r.get("success"):
                return _rows(r)
            last = str(r.get("message"))[:250]
        raise RuntimeError("interogare esuata: %s" % last)

    def dml(sql, p=None, ok_daca=()):
        r = db.execute_dml(sql, p or {})
        if r.get("success"):
            return r.get("rowcount") or 0
        msg = str(r.get("message"))
        if any(code in msg for code in ok_daca):
            return 0
        raise RuntimeError(msg[:300])

    return q, dml


def categorii_rusesti(q):
    """RO: categoriile din catalog al caror nume de baza contine litere chirilice."""
    return q("SELECT g.CATEGORIE, COUNT(DISTINCT g.COD_UNIVERS) N FROM BIRO26_GOODS g "
             "JOIN TMS_UNIVERS u ON u.COD=g.COD_UNIVERS AND u.TIP='P' "
             "  AND NVL(u.ISARHIV,'0') <> '2' "
             "WHERE g.CATEGORIE IS NOT NULL AND REGEXP_LIKE(g.CATEGORIE,'[А-Яа-яЁё]') "
             "GROUP BY g.CATEGORIE ORDER BY g.CATEGORIE")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="scrie in baza")
    ap.add_argument("--user", default=os.environ.get("USER", "agent"))
    args = ap.parse_args()
    q, dml = _db()

    randuri = categorii_rusesti(q)
    plan, sarite = [], []
    for r in randuri:
        vechi = r["categorie"]
        nou = tradu(vechi)
        if not nou or ramine_rus(nou) or nou == vechi:
            sarite.append((vechi, nou))
            continue
        plan.append((vechi, nou, int(r["n"] or 0)))

    print("categorii rusesti: %d | de tradus: %d | sarite: %d"
          % (len(randuri), len(plan), len(sarite)))
    for v, n in sarite:
        print("   SARIT  %-52s -> %s" % (v[:52], n[:52]))
    if not args.apply:
        for v, n, cnt in plan[:20]:
            print("   %-52s -> %-52s (%d produse)" % (v[:52], n[:52], cnt))
        print("... (fara --apply nu se scrie nimic)")
        return 0

    dml(DDL_LOG, ok_daca=("ORA-00955",))
    schimbate = dictionar = 0
    for vechi, nou, cnt in plan:
        # 1) rusescul ramine ca traducere RU pe noul nume romanesc
        dictionar += dml(
            "MERGE INTO YBIRO_GRP_I18N t USING (SELECT 'categorie' KIND, :ro NAME_RO FROM dual) s "
            "ON (t.KIND=s.KIND AND t.NAME_RO=s.NAME_RO) "
            "WHEN MATCHED THEN UPDATE SET t.NAME_RU = NVL(t.NAME_RU, :ru) "
            "WHEN NOT MATCHED THEN INSERT (KIND, NAME_RO, NAME_RU) VALUES ('categorie', :ro, :ru)",
            {"ro": nou, "ru": vechi})
        # 2) numele de baza devine romanesc
        schimbate += dml("UPDATE BIRO26_GOODS SET CATEGORIE=:nou WHERE CATEGORIE=:vechi",
                         {"nou": nou, "vechi": vechi})
        dml("INSERT INTO YBIRO_CAT_RENAME (KIND, NAME_OLD, NAME_NEW, PRODUSE, CREATED_BY) "
            "VALUES ('categorie', :o, :n, :c, :u)",
            {"o": vechi, "n": nou, "c": cnt, "u": args.user})
    print("rinduri BIRO26_GOODS actualizate: %d | intrari de dictionar: %d" % (schimbate, dictionar))
    ramase = categorii_rusesti(q)
    print("categorii inca in rusa: %d" % len(ramase))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
