-- Autopark module: fuel-tanker fleet automation for client Bemol.
-- Driver payroll by normative mileage, route/fuel control, supply planning.
-- Prefix: FLT_. Target database: platform cloud ADB (same as SDA).
--
-- All sequences use CACHE 20 -- a NOCACHE sequence under parallel
-- INSERT...SELECT produced ORA-12860 deadlocks on this ADB for the PECO
-- module (26.08.2026). Every PL/SQL block (trigger) is fenced by '/'
-- BEFORE and AFTER it -- without the leading '/' the shared splitter
-- glues the preceding CREATE TABLE/INDEX statements into the same PL/SQL
-- block, which cursor.execute() then rejects (SDA incident 25.08.2026).

-- Reference: petroleum products (A92/A95/A98/DIESEL). Natural key, no ID.
CREATE TABLE FLT_PRODUCTS (
  CODE      VARCHAR2(20)   NOT NULL,
  NAME_RU   VARCHAR2(120)  NOT NULL,
  ACTIVE    NUMBER(1)      DEFAULT 1 NOT NULL,
  CONSTRAINT PK_FLT_PRODUCTS PRIMARY KEY (CODE),
  CONSTRAINT CK_FLT_PRODUCTS_ACT CHECK (ACTIVE IN (0,1))
);

-- Fuel stations (AZS).
CREATE TABLE FLT_STATIONS (
  ID       NUMBER(12)     NOT NULL,
  CODE     VARCHAR2(20)   NOT NULL,
  NAME     VARCHAR2(200)  NOT NULL,
  ADDRESS  VARCHAR2(300),
  ACTIVE   NUMBER(1)      DEFAULT 1 NOT NULL,
  CONSTRAINT PK_FLT_STATIONS PRIMARY KEY (ID),
  CONSTRAINT CK_FLT_STATIONS_ACT CHECK (ACTIVE IN (0,1))
);
CREATE SEQUENCE SEQ_FLT_STATIONS START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_STATIONS_BI BEFORE INSERT ON FLT_STATIONS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_STATIONS.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE UNIQUE INDEX UX_FLT_STATIONS_CODE ON FLT_STATIONS (CODE);

-- Tank capacity per station and product.
CREATE TABLE FLT_STATION_TANKS (
  ID            NUMBER(12)    NOT NULL,
  STATION_ID    NUMBER(12)    NOT NULL,
  PRODUCT_CODE  VARCHAR2(20)  NOT NULL,
  CAPACITY_L    NUMBER(10,2)  NOT NULL,
  CONSTRAINT PK_FLT_STATION_TANKS PRIMARY KEY (ID),
  CONSTRAINT FK_FLT_STATION_TANKS_ST FOREIGN KEY (STATION_ID) REFERENCES FLT_STATIONS (ID),
  CONSTRAINT FK_FLT_STATION_TANKS_PR FOREIGN KEY (PRODUCT_CODE) REFERENCES FLT_PRODUCTS (CODE),
  CONSTRAINT UQ_FLT_STATION_TANKS UNIQUE (STATION_ID, PRODUCT_CODE),
  CONSTRAINT CK_FLT_STATION_TANKS_CAP CHECK (CAPACITY_L > 0)
);
CREATE SEQUENCE SEQ_FLT_STATION_TANKS START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_STATION_TANKS_BI BEFORE INSERT ON FLT_STATION_TANKS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_STATION_TANKS.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_FLT_STATION_TANKS_ST ON FLT_STATION_TANKS (STATION_ID);
CREATE INDEX IX_FLT_STATION_TANKS_PR ON FLT_STATION_TANKS (PRODUCT_CODE);

-- Loading points (Chisinau, MSPD, Constanta, ...). IS_FOREIGN drives
-- DOMESTIC/IMPORT classification (see modules/autopark/rules.py::classify_trip).
CREATE TABLE FLT_LOAD_POINTS (
  ID          NUMBER(12)    NOT NULL,
  CODE        VARCHAR2(20)  NOT NULL,
  NAME        VARCHAR2(200) NOT NULL,
  IS_FOREIGN  NUMBER(1)     DEFAULT 0 NOT NULL,
  CONSTRAINT PK_FLT_LOAD_POINTS PRIMARY KEY (ID),
  CONSTRAINT CK_FLT_LOAD_POINTS_FRN CHECK (IS_FOREIGN IN (0,1))
);
CREATE SEQUENCE SEQ_FLT_LOAD_POINTS START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_LOAD_POINTS_BI BEFORE INSERT ON FLT_LOAD_POINTS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_LOAD_POINTS.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE UNIQUE INDEX UX_FLT_LOAD_POINTS_CODE ON FLT_LOAD_POINTS (CODE);

-- End points of a route (garage/base). The final leg of a route targets a
-- row here. NOTE: FLT_DISTANCES.TO_KIND='END' cannot carry a real FOREIGN KEY
-- to this table (the same column also points at FLT_STATIONS when
-- TO_KIND='STATION') -- the kind/id pair is a polymorphic reference,
-- enforced only in application code (modules/autopark/rules.py).
CREATE TABLE FLT_END_POINTS (
  ID    NUMBER(12)    NOT NULL,
  CODE  VARCHAR2(20)  NOT NULL,
  NAME  VARCHAR2(200) NOT NULL,
  CONSTRAINT PK_FLT_END_POINTS PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_FLT_END_POINTS START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_END_POINTS_BI BEFORE INSERT ON FLT_END_POINTS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_END_POINTS.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE UNIQUE INDEX UX_FLT_END_POINTS_CODE ON FLT_END_POINTS (CODE);

-- Fuel tankers.
CREATE TABLE FLT_TRUCKS (
  ID                NUMBER(12)    NOT NULL,
  PLATE             VARCHAR2(20)  NOT NULL,
  BRAND             VARCHAR2(80),
  CAPACITY_L        NUMBER(10,2)  NOT NULL,
  SECTIONS_CNT      NUMBER(3)     DEFAULT 1 NOT NULL,
  NORM_L_PER_100KM  NUMBER(6,2)   NOT NULL,
  ACTIVE            NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT PK_FLT_TRUCKS PRIMARY KEY (ID),
  CONSTRAINT CK_FLT_TRUCKS_CAP CHECK (CAPACITY_L > 0),
  CONSTRAINT CK_FLT_TRUCKS_SECT CHECK (SECTIONS_CNT > 0),
  CONSTRAINT CK_FLT_TRUCKS_NORM CHECK (NORM_L_PER_100KM > 0),
  CONSTRAINT CK_FLT_TRUCKS_ACT CHECK (ACTIVE IN (0,1))
);
CREATE SEQUENCE SEQ_FLT_TRUCKS START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_TRUCKS_BI BEFORE INSERT ON FLT_TRUCKS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_TRUCKS.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE UNIQUE INDEX UX_FLT_TRUCKS_PLATE ON FLT_TRUCKS (PLATE);

-- Products a given tanker is allowed to carry. Pure junction table --
-- natural composite key, no surrogate ID needed.
CREATE TABLE FLT_TRUCK_PRODUCTS (
  TRUCK_ID      NUMBER(12)    NOT NULL,
  PRODUCT_CODE  VARCHAR2(20)  NOT NULL,
  CONSTRAINT PK_FLT_TRUCK_PRODUCTS PRIMARY KEY (TRUCK_ID, PRODUCT_CODE),
  CONSTRAINT FK_FLT_TRUCK_PRODUCTS_TR FOREIGN KEY (TRUCK_ID) REFERENCES FLT_TRUCKS (ID),
  CONSTRAINT FK_FLT_TRUCK_PRODUCTS_PR FOREIGN KEY (PRODUCT_CODE) REFERENCES FLT_PRODUCTS (CODE)
);
CREATE INDEX IX_FLT_TRUCK_PRODUCTS_TR ON FLT_TRUCK_PRODUCTS (TRUCK_ID);
CREATE INDEX IX_FLT_TRUCK_PRODUCTS_PR ON FLT_TRUCK_PRODUCTS (PRODUCT_CODE);

-- Drivers.
CREATE TABLE FLT_DRIVERS (
  ID          NUMBER(12)    NOT NULL,
  FULL_NAME   VARCHAR2(200) NOT NULL,
  TAB_NO      VARCHAR2(20)  NOT NULL,
  TRUCK_ID    NUMBER(12),
  ACTIVE      NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT PK_FLT_DRIVERS PRIMARY KEY (ID),
  CONSTRAINT FK_FLT_DRIVERS_TRUCK FOREIGN KEY (TRUCK_ID) REFERENCES FLT_TRUCKS (ID),
  CONSTRAINT CK_FLT_DRIVERS_ACT CHECK (ACTIVE IN (0,1))
);
CREATE SEQUENCE SEQ_FLT_DRIVERS START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_DRIVERS_BI BEFORE INSERT ON FLT_DRIVERS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_DRIVERS.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE UNIQUE INDEX UX_FLT_DRIVERS_TABNO ON FLT_DRIVERS (TAB_NO);
CREATE INDEX IX_FLT_DRIVERS_TRUCK ON FLT_DRIVERS (TRUCK_ID);

-- Distance matrix between load points, stations and end points.
-- FROM_ID/TO_ID are polymorphic (their meaning depends on FROM_KIND/
-- TO_KIND), so no single FOREIGN KEY can target them -- application code
-- (modules/autopark/rules.py::route_legs) resolves FROM_KIND/TO_KIND to
-- the right table before doing a lookup.
CREATE TABLE FLT_DISTANCES (
  ID         NUMBER(12)    NOT NULL,
  FROM_KIND  VARCHAR2(10)  NOT NULL,
  FROM_ID    NUMBER(12)    NOT NULL,
  TO_KIND    VARCHAR2(10)  NOT NULL,
  TO_ID      NUMBER(12)    NOT NULL,
  KM         NUMBER(7,1)   NOT NULL,
  CONSTRAINT PK_FLT_DISTANCES PRIMARY KEY (ID),
  CONSTRAINT CK_FLT_DIST_FROM_KIND CHECK (FROM_KIND IN ('LOAD','STATION','END')),
  CONSTRAINT CK_FLT_DIST_TO_KIND CHECK (TO_KIND IN ('LOAD','STATION','END')),
  CONSTRAINT CK_FLT_DIST_KM CHECK (KM >= 0),
  CONSTRAINT UQ_FLT_DISTANCES UNIQUE (FROM_KIND, FROM_ID, TO_KIND, TO_ID)
);
CREATE SEQUENCE SEQ_FLT_DISTANCES START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_DISTANCES_BI BEFORE INSERT ON FLT_DISTANCES FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_DISTANCES.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/

-- Trip type reference: DOMESTIC pays the 600 lei trip bonus, IMPORT does
-- not (Bemol ToR pt. 10 -- Chisinau-Constanta-Chisinau is IMPORT).
CREATE TABLE FLT_REF_TRIP_TYPES (
  CODE         VARCHAR2(10)  NOT NULL,
  NAME_RU      VARCHAR2(120) NOT NULL,
  PAYS_BONUS   NUMBER(1)     DEFAULT 0 NOT NULL,
  CONSTRAINT PK_FLT_REF_TRIP_TYPES PRIMARY KEY (CODE),
  CONSTRAINT CK_FLT_TRIP_TYPES_BONUS CHECK (PAYS_BONUS IN (0,1))
);

-- Trip status reference: DRAFT / APPROVED / DONE.
CREATE TABLE FLT_REF_TRIP_STATUS (
  CODE     VARCHAR2(10)  NOT NULL,
  NAME_RU  VARCHAR2(120) NOT NULL,
  CONSTRAINT PK_FLT_REF_TRIP_STATUS PRIMARY KEY (CODE)
);

-- Trips. A DRAFT trip is not yet payroll basis (ToR pt. 6): only an
-- APPROVED/DONE trip counts (see rules.py::payroll).
CREATE TABLE FLT_TRIPS (
  ID             NUMBER(12)    NOT NULL,
  TRIP_DATE      DATE          NOT NULL,
  TRUCK_ID       NUMBER(12)    NOT NULL,
  DRIVER_ID      NUMBER(12)    NOT NULL,
  TYPE_CODE      VARCHAR2(10)  NOT NULL,
  STATUS_CODE    VARCHAR2(10)  DEFAULT 'DRAFT' NOT NULL,
  LOAD_POINT_ID  NUMBER(12)    NOT NULL,
  END_POINT_ID   NUMBER(12)    NOT NULL,
  SOURCE         VARCHAR2(10)  DEFAULT 'MANUAL' NOT NULL,
  NORM_KM        NUMBER(8,1),
  FACT_KM        NUMBER(8,1),
  FACT_MINUTES   NUMBER(8),
  APPROVED_BY    VARCHAR2(120),
  CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_FLT_TRIPS PRIMARY KEY (ID),
  CONSTRAINT FK_FLT_TRIPS_TRUCK FOREIGN KEY (TRUCK_ID) REFERENCES FLT_TRUCKS (ID),
  CONSTRAINT FK_FLT_TRIPS_DRIVER FOREIGN KEY (DRIVER_ID) REFERENCES FLT_DRIVERS (ID),
  CONSTRAINT FK_FLT_TRIPS_TYPE FOREIGN KEY (TYPE_CODE) REFERENCES FLT_REF_TRIP_TYPES (CODE),
  CONSTRAINT FK_FLT_TRIPS_STATUS FOREIGN KEY (STATUS_CODE) REFERENCES FLT_REF_TRIP_STATUS (CODE),
  CONSTRAINT FK_FLT_TRIPS_LOAD FOREIGN KEY (LOAD_POINT_ID) REFERENCES FLT_LOAD_POINTS (ID),
  CONSTRAINT FK_FLT_TRIPS_END FOREIGN KEY (END_POINT_ID) REFERENCES FLT_END_POINTS (ID),
  CONSTRAINT CK_FLT_TRIPS_SOURCE CHECK (SOURCE IN ('AUTO','MANUAL'))
);
CREATE SEQUENCE SEQ_FLT_TRIPS START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_TRIPS_BI BEFORE INSERT ON FLT_TRIPS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_TRIPS.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_FLT_TRIPS_TRUCK ON FLT_TRIPS (TRUCK_ID);
CREATE INDEX IX_FLT_TRIPS_DRIVER ON FLT_TRIPS (DRIVER_ID);
CREATE INDEX IX_FLT_TRIPS_TYPE ON FLT_TRIPS (TYPE_CODE);
CREATE INDEX IX_FLT_TRIPS_STATUS ON FLT_TRIPS (STATUS_CODE);
CREATE INDEX IX_FLT_TRIPS_LOAD ON FLT_TRIPS (LOAD_POINT_ID);
CREATE INDEX IX_FLT_TRIPS_END ON FLT_TRIPS (END_POINT_ID);

-- Stops of a trip, in the order the route is actually served.
CREATE TABLE FLT_TRIP_STOPS (
  ID          NUMBER(12)  NOT NULL,
  TRIP_ID     NUMBER(12)  NOT NULL,
  SEQ_NO      NUMBER(4)   NOT NULL,
  STATION_ID  NUMBER(12)  NOT NULL,
  CONSTRAINT PK_FLT_TRIP_STOPS PRIMARY KEY (ID),
  CONSTRAINT FK_FLT_TRIP_STOPS_TRIP FOREIGN KEY (TRIP_ID) REFERENCES FLT_TRIPS (ID),
  CONSTRAINT FK_FLT_TRIP_STOPS_ST FOREIGN KEY (STATION_ID) REFERENCES FLT_STATIONS (ID),
  CONSTRAINT UQ_FLT_TRIP_STOPS UNIQUE (TRIP_ID, SEQ_NO)
);
CREATE SEQUENCE SEQ_FLT_TRIP_STOPS START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_TRIP_STOPS_BI BEFORE INSERT ON FLT_TRIP_STOPS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_TRIP_STOPS.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_FLT_TRIP_STOPS_TRIP ON FLT_TRIP_STOPS (TRIP_ID);
CREATE INDEX IX_FLT_TRIP_STOPS_ST ON FLT_TRIP_STOPS (STATION_ID);

-- Products discharged at a stop.
CREATE TABLE FLT_TRIP_STOP_ITEMS (
  ID            NUMBER(12)    NOT NULL,
  STOP_ID       NUMBER(12)    NOT NULL,
  PRODUCT_CODE  VARCHAR2(20)  NOT NULL,
  VOLUME_L      NUMBER(10,2)  NOT NULL,
  CONSTRAINT PK_FLT_TRIP_STOP_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_FLT_TSI_STOP FOREIGN KEY (STOP_ID) REFERENCES FLT_TRIP_STOPS (ID),
  CONSTRAINT FK_FLT_TSI_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES FLT_PRODUCTS (CODE),
  CONSTRAINT CK_FLT_TSI_VOL CHECK (VOLUME_L > 0)
);
CREATE SEQUENCE SEQ_FLT_TRIP_STOP_ITEMS START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_TRIP_STOP_ITEMS_BI BEFORE INSERT ON FLT_TRIP_STOP_ITEMS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_TRIP_STOP_ITEMS.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_FLT_TSI_STOP ON FLT_TRIP_STOP_ITEMS (STOP_ID);
CREATE INDEX IX_FLT_TSI_PRODUCT ON FLT_TRIP_STOP_ITEMS (PRODUCT_CODE);

-- Supply invoices (deliveries). TRIP_ID is filled in once a trip is
-- formed around the delivery (ToR pt. 5).
CREATE TABLE FLT_DELIVERIES (
  ID             NUMBER(12)    NOT NULL,
  DELIV_DATE     DATE          NOT NULL,
  PRODUCT_CODE   VARCHAR2(20)  NOT NULL,
  VOLUME_L       NUMBER(10,2)  NOT NULL,
  LOAD_POINT_ID  NUMBER(12)    NOT NULL,
  STATION_ID     NUMBER(12)    NOT NULL,
  TRUCK_ID       NUMBER(12)    NOT NULL,
  DRIVER_ID      NUMBER(12)    NOT NULL,
  TRIP_ID        NUMBER(12),
  CONSTRAINT PK_FLT_DELIVERIES PRIMARY KEY (ID),
  CONSTRAINT FK_FLT_DELIV_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES FLT_PRODUCTS (CODE),
  CONSTRAINT FK_FLT_DELIV_LOAD FOREIGN KEY (LOAD_POINT_ID) REFERENCES FLT_LOAD_POINTS (ID),
  CONSTRAINT FK_FLT_DELIV_STATION FOREIGN KEY (STATION_ID) REFERENCES FLT_STATIONS (ID),
  CONSTRAINT FK_FLT_DELIV_TRUCK FOREIGN KEY (TRUCK_ID) REFERENCES FLT_TRUCKS (ID),
  CONSTRAINT FK_FLT_DELIV_DRIVER FOREIGN KEY (DRIVER_ID) REFERENCES FLT_DRIVERS (ID),
  CONSTRAINT FK_FLT_DELIV_TRIP FOREIGN KEY (TRIP_ID) REFERENCES FLT_TRIPS (ID),
  CONSTRAINT CK_FLT_DELIV_VOL CHECK (VOLUME_L > 0)
);
CREATE SEQUENCE SEQ_FLT_DELIVERIES START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_DELIVERIES_BI BEFORE INSERT ON FLT_DELIVERIES FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_DELIVERIES.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_FLT_DELIV_PRODUCT ON FLT_DELIVERIES (PRODUCT_CODE);
CREATE INDEX IX_FLT_DELIV_LOAD ON FLT_DELIVERIES (LOAD_POINT_ID);
CREATE INDEX IX_FLT_DELIV_STATION ON FLT_DELIVERIES (STATION_ID);
CREATE INDEX IX_FLT_DELIV_TRUCK ON FLT_DELIVERIES (TRUCK_ID);
CREATE INDEX IX_FLT_DELIV_DRIVER ON FLT_DELIVERIES (DRIVER_ID);
CREATE INDEX IX_FLT_DELIV_TRIP ON FLT_DELIVERIES (TRIP_ID);

-- Daily station/product stock accounting.
CREATE TABLE FLT_STATION_STOCK (
  ID            NUMBER(12)    NOT NULL,
  STATION_ID    NUMBER(12)    NOT NULL,
  PRODUCT_CODE  VARCHAR2(20)  NOT NULL,
  STOCK_DATE    DATE          NOT NULL,
  OPEN_L        NUMBER(10,2)  NOT NULL,
  CLOSE_L       NUMBER(10,2)  NOT NULL,
  SALES_L       NUMBER(10,2)  DEFAULT 0 NOT NULL,
  RECEIVED_L    NUMBER(10,2)  DEFAULT 0 NOT NULL,
  CONSTRAINT PK_FLT_STATION_STOCK PRIMARY KEY (ID),
  CONSTRAINT FK_FLT_STOCK_STATION FOREIGN KEY (STATION_ID) REFERENCES FLT_STATIONS (ID),
  CONSTRAINT FK_FLT_STOCK_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES FLT_PRODUCTS (CODE),
  CONSTRAINT UQ_FLT_STATION_STOCK UNIQUE (STATION_ID, PRODUCT_CODE, STOCK_DATE)
);
CREATE SEQUENCE SEQ_FLT_STATION_STOCK START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_STATION_STOCK_BI BEFORE INSERT ON FLT_STATION_STOCK FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_STATION_STOCK.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_FLT_STOCK_STATION ON FLT_STATION_STOCK (STATION_ID);
CREATE INDEX IX_FLT_STOCK_PRODUCT ON FLT_STATION_STOCK (PRODUCT_CODE);

-- Single-row settings table -- explicit named columns, not a KV blob
-- (CLAUDE.md forbids APP_RUNTIME_KV-style generic tables).
CREATE TABLE FLT_SETTINGS (
  ID                  NUMBER(1)     NOT NULL,
  RATE_PER_KM         NUMBER(6,2)   DEFAULT 2.75 NOT NULL,
  TRIP_BONUS          NUMBER(8,2)   DEFAULT 600 NOT NULL,
  SAFETY_DAYS         NUMBER(3)     DEFAULT 6 NOT NULL,
  KM_DEVIATION_LIMIT  NUMBER(6,1)   DEFAULT 15 NOT NULL,
  FUEL_DEVIATION_PCT  NUMBER(5,2)   DEFAULT 5 NOT NULL,
  CONSTRAINT PK_FLT_SETTINGS PRIMARY KEY (ID),
  CONSTRAINT CK_FLT_SETTINGS_ID CHECK (ID = 1)
);

-- Append-only event log. Never a shared/generic container.
CREATE TABLE FLT_EVENT_LOG (
  ID          NUMBER(12)     NOT NULL,
  EVENT_TIME  DATE           DEFAULT SYSDATE NOT NULL,
  EVENT_TYPE  VARCHAR2(40)   NOT NULL,
  REF_KIND    VARCHAR2(40),
  REF_ID      NUMBER(12),
  DETAILS     VARCHAR2(1000),
  USERNAME    VARCHAR2(120),
  CONSTRAINT PK_FLT_EVENT_LOG PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_FLT_EVENT_LOG START WITH 1 INCREMENT BY 1 CACHE 20;
/
CREATE OR REPLACE TRIGGER TRG_FLT_EVENT_LOG_BI BEFORE INSERT ON FLT_EVENT_LOG FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN SELECT SEQ_FLT_EVENT_LOG.NEXTVAL INTO :NEW.ID FROM DUAL; END IF; END;
/
CREATE INDEX IX_FLT_EVENT_LOG_TIME ON FLT_EVENT_LOG (EVENT_TIME);
