-- Autopark module: reference-data seed. Idempotent -- every statement is
-- a MERGE, safe to re-run against an already-seeded schema.

MERGE INTO FLT_PRODUCTS t
USING (SELECT 'A92' CODE, 'Benzina A92' NAME_RU FROM DUAL
       UNION ALL SELECT 'A95', 'Benzina A95' FROM DUAL
       UNION ALL SELECT 'A98', 'Benzina A98' FROM DUAL
       UNION ALL SELECT 'DIESEL', 'Motorina' FROM DUAL) s
ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (CODE, NAME_RU) VALUES (s.CODE, s.NAME_RU);

MERGE INTO FLT_REF_TRIP_TYPES t
USING (SELECT 'DOMESTIC' CODE, 'Rejs intern' NAME_RU, 1 PAYS_BONUS FROM DUAL
       UNION ALL SELECT 'IMPORT', 'Rejs de import', 0 FROM DUAL) s
ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (CODE, NAME_RU, PAYS_BONUS)
  VALUES (s.CODE, s.NAME_RU, s.PAYS_BONUS);

MERGE INTO FLT_REF_TRIP_STATUS t
USING (SELECT 'DRAFT' CODE, 'Ciorna' NAME_RU FROM DUAL
       UNION ALL SELECT 'APPROVED', 'Aprobat' FROM DUAL
       UNION ALL SELECT 'DONE', 'Finalizat' FROM DUAL) s
ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (CODE, NAME_RU) VALUES (s.CODE, s.NAME_RU);

MERGE INTO FLT_SETTINGS t
USING (SELECT 1 ID FROM DUAL) s
ON (t.ID = s.ID)
WHEN NOT MATCHED THEN INSERT (ID) VALUES (s.ID);

MERGE INTO FLT_LOAD_POINTS t
USING (SELECT 'KIS' CODE, 'Chisinau' NAME, 0 IS_FOREIGN FROM DUAL
       UNION ALL SELECT 'MSPD', 'MSPD', 0 FROM DUAL
       UNION ALL SELECT 'CONST', 'Constanta', 1 FROM DUAL) s
ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_FOREIGN)
  VALUES (s.CODE, s.NAME, s.IS_FOREIGN);

MERGE INTO FLT_END_POINTS t
USING (SELECT 'BAZA' CODE, 'Baza Chisinau' NAME FROM DUAL) s
ON (t.CODE = s.CODE)
WHEN NOT MATCHED THEN INSERT (CODE, NAME) VALUES (s.CODE, s.NAME);
