-- ============================================================
-- Табло отправлений автовокзала: таблицы
-- ============================================================

-- Маршруты
CREATE TABLE BUS_ROUTES (
  ROUTE_CODE   VARCHAR2(20)  NOT NULL,
  DESTINATION  VARCHAR2(200) NOT NULL,
  DESCRIPTION  VARCHAR2(500),
  CREATED_AT   TIMESTAMP,
  CONSTRAINT PK_BUS_ROUTES PRIMARY KEY (ROUTE_CODE)
);

-- Рейсы (отправления)
CREATE SEQUENCE BUS_DEPARTURES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE BUS_DEPARTURES (
  ID            NUMBER        NOT NULL,
  ROUTE_CODE    VARCHAR2(20)  NOT NULL,
  DEPARTURE_DT  DATE          NOT NULL,
  PLATFORM      VARCHAR2(10)  NOT NULL,
  GATE          VARCHAR2(10),
  STATUS        VARCHAR2(30)  NOT NULL,
  CREATED_AT    TIMESTAMP,
  UPDATED_AT    TIMESTAMP,
  CONSTRAINT PK_BUS_DEPARTURES PRIMARY KEY (ID),
  CONSTRAINT FK_BUS_DEP_Route FOREIGN KEY (ROUTE_CODE) REFERENCES BUS_ROUTES(ROUTE_CODE),
  CONSTRAINT CHK_BUS_DEP_STATUS CHECK (STATUS IN ('Ожидание','Посадка','Отправлен','Отменен'))
);
/

CREATE OR REPLACE TRIGGER BUS_DEPARTURES_BI
BEFORE INSERT ON BUS_DEPARTURES FOR EACH ROW
WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := BUS_DEPARTURES_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_BUS_DEPARTURES_DT ON BUS_DEPARTURES (DEPARTURE_DT);
CREATE INDEX IX_BUS_DEPARTURES_ROUTE ON BUS_DEPARTURES (ROUTE_CODE);

/
