-- ============================================================
-- Кредиты (админка + оператор): таблицы
-- ============================================================

CREATE SEQUENCE CRED_BANKS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CRED_CATEGORIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CRED_BRANDS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CRED_PROGRAMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CRED_PRODUCTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CRED_APPLICATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRED_BANKS (
  ID         NUMBER NOT NULL,
  CODE       VARCHAR2(50)  NOT NULL,
  NAME       VARCHAR2(200) NOT NULL,
  CREATED_AT TIMESTAMP,
  CONSTRAINT PK_CRED_BANKS PRIMARY KEY (ID),
  CONSTRAINT UQ_CRED_BANKS_CODE UNIQUE (CODE)
);
/
CREATE OR REPLACE TRIGGER CRED_BANKS_BI BEFORE INSERT ON CRED_BANKS FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := CRED_BANKS_SEQ.NEXTVAL; END;
/

CREATE TABLE CRED_CATEGORIES (
  ID         NUMBER NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  CREATED_AT TIMESTAMP,
  CONSTRAINT PK_CRED_CATEGORIES PRIMARY KEY (ID),
  CONSTRAINT UQ_CRED_CATEGORIES_NAME UNIQUE (NAME)
);
/
CREATE OR REPLACE TRIGGER CRED_CATEGORIES_BI BEFORE INSERT ON CRED_CATEGORIES FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := CRED_CATEGORIES_SEQ.NEXTVAL; END;
/

CREATE TABLE CRED_BRANDS (
  ID         NUMBER NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  CREATED_AT TIMESTAMP,
  CONSTRAINT PK_CRED_BRANDS PRIMARY KEY (ID),
  CONSTRAINT UQ_CRED_BRANDS_NAME UNIQUE (NAME)
);
/
CREATE OR REPLACE TRIGGER CRED_BRANDS_BI BEFORE INSERT ON CRED_BRANDS FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := CRED_BRANDS_SEQ.NEXTVAL; END;
/

CREATE TABLE CRED_PROGRAMS (
  ID                NUMBER NOT NULL,
  NAME              VARCHAR2(200) NOT NULL,
  BANK_ID           NUMBER        NOT NULL,
  TERM_MONTHS       NUMBER        NOT NULL,
  RATE_PCT          NUMBER,
  FIRST_PAYMENT_PCT NUMBER,
  MIN_SUM           NUMBER        NOT NULL,
  MAX_SUM           NUMBER        NOT NULL,
  COMMISSION_PCT    NUMBER,
  ACTIVE            CHAR(1),
  NOTES             VARCHAR2(4000),
  CREATED_AT        TIMESTAMP,
  UPDATED_AT        TIMESTAMP,
  CONSTRAINT PK_CRED_PROGRAMS PRIMARY KEY (ID),
  CONSTRAINT FK_CRED_PROG_BANK FOREIGN KEY (BANK_ID) REFERENCES CRED_BANKS(ID),
  CONSTRAINT CHK_CRED_PROG_ACTIVE CHECK (ACTIVE IN ('Y','N')),
  CONSTRAINT CHK_CRED_PROG_SUM CHECK (MIN_SUM <= MAX_SUM)
);
/
CREATE OR REPLACE TRIGGER CRED_PROGRAMS_BI BEFORE INSERT ON CRED_PROGRAMS FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := CRED_PROGRAMS_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_CRED_PROGRAMS_BANK ON CRED_PROGRAMS (BANK_ID);
CREATE INDEX IX_CRED_PROGRAMS_ACTIVE ON CRED_PROGRAMS (ACTIVE);

CREATE TABLE CRED_PROGRAM_CATEGORIES (
  PROGRAM_ID  NUMBER NOT NULL,
  CATEGORY_ID NUMBER NOT NULL,
  CREATED_AT  TIMESTAMP,
  CONSTRAINT PK_CRED_PRG_CAT PRIMARY KEY (PROGRAM_ID, CATEGORY_ID),
  CONSTRAINT FK_CRED_PRG_CAT_PRG FOREIGN KEY (PROGRAM_ID) REFERENCES CRED_PROGRAMS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CRED_PRG_CAT_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CRED_CATEGORIES(ID)
);

CREATE TABLE CRED_PROGRAM_EXCLUDED_BRANDS (
  PROGRAM_ID NUMBER NOT NULL,
  BRAND_ID   NUMBER NOT NULL,
  CREATED_AT TIMESTAMP,
  CONSTRAINT PK_CRED_PRG_BRAND PRIMARY KEY (PROGRAM_ID, BRAND_ID),
  CONSTRAINT FK_CRED_PRG_BRAND_PRG FOREIGN KEY (PROGRAM_ID) REFERENCES CRED_PROGRAMS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CRED_PRG_BRAND_BRAND FOREIGN KEY (BRAND_ID) REFERENCES CRED_BRANDS(ID)
);

CREATE TABLE CRED_PRODUCTS (
  ID          NUMBER NOT NULL,
  NAME        VARCHAR2(300) NOT NULL,
  ARTICLE     VARCHAR2(100),
  BARCODE     VARCHAR2(50),
  PRICE       NUMBER        NOT NULL,
  CATEGORY_ID NUMBER        NOT NULL,
  BRAND_ID    NUMBER,
  IMG_URL     VARCHAR2(500),
  CREATED_AT  TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT PK_CRED_PRODUCTS PRIMARY KEY (ID),
  CONSTRAINT FK_CRED_PROD_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CRED_CATEGORIES(ID),
  CONSTRAINT FK_CRED_PROD_BRAND FOREIGN KEY (BRAND_ID) REFERENCES CRED_BRANDS(ID)
);
/
CREATE OR REPLACE TRIGGER CRED_PRODUCTS_BI BEFORE INSERT ON CRED_PRODUCTS FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := CRED_PRODUCTS_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_CRED_PRODUCTS_CAT ON CRED_PRODUCTS (CATEGORY_ID);
CREATE INDEX IX_CRED_PRODUCTS_BARCODE ON CRED_PRODUCTS (BARCODE);

CREATE TABLE CRED_APPLICATIONS (
  ID               NUMBER NOT NULL,
  PRODUCT_ID       NUMBER        NOT NULL,
  PROGRAM_ID       NUMBER        NOT NULL,
  CLIENT_FIO       VARCHAR2(300) NOT NULL,
  CLIENT_PHONE     VARCHAR2(50)  NOT NULL,
  CLIENT_IDN       VARCHAR2(50),
  STATUS           VARCHAR2(30)  NOT NULL,
  APPROVED_AMOUNT  NUMBER,
  REJECTION_REASON VARCHAR2(500),
  CREATED_AT       TIMESTAMP,
  UPDATED_AT       TIMESTAMP,
  CONSTRAINT PK_CRED_APPLICATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_CRED_APP_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES CRED_PRODUCTS(ID),
  CONSTRAINT FK_CRED_APP_PROGRAM FOREIGN KEY (PROGRAM_ID) REFERENCES CRED_PROGRAMS(ID),
  CONSTRAINT CHK_CRED_APP_STATUS CHECK (STATUS IN ('pending','approved','rejected','on_review'))
);
/
CREATE OR REPLACE TRIGGER CRED_APPLICATIONS_BI BEFORE INSERT ON CRED_APPLICATIONS FOR EACH ROW WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := CRED_APPLICATIONS_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_CRED_APPLICATIONS_CREATED ON CRED_APPLICATIONS (CREATED_AT DESC);

/
