-- ============================================================
-- Кредиты: пакет CRED_OPERATOR_PKG (интерфейс оператора)
-- ============================================================

CREATE OR REPLACE PACKAGE CRED_OPERATOR_PKG AS
  PROCEDURE GET_PRODUCTS (
    P_SEARCH   IN  VARCHAR2 DEFAULT NULL,
    P_LIMIT    IN  NUMBER   DEFAULT 10,
    P_CUR      OUT SYS_REFCURSOR
  );
  PROCEDURE GET_PRODUCT_BY_ID (
    P_ID   IN  NUMBER,
    P_CUR  OUT SYS_REFCURSOR
  );
  PROCEDURE GET_PROGRAMS_FOR_PRODUCT (
    P_PRODUCT_ID IN  NUMBER,
    P_CUR        OUT SYS_REFCURSOR
  );
  PROCEDURE CREATE_APPLICATION (
    P_PRODUCT_ID   IN  NUMBER,
    P_PROGRAM_ID   IN  NUMBER,
    P_CLIENT_FIO   IN  VARCHAR2,
    P_CLIENT_PHONE IN  VARCHAR2,
    P_CLIENT_IDN   IN  VARCHAR2 DEFAULT NULL,
    P_APP_ID       OUT NUMBER,
    P_STATUS       OUT VARCHAR2,
    P_APPROVED_AMT OUT NUMBER,
    P_REJECT_REASON OUT VARCHAR2
  );
  PROCEDURE GET_RECENT_APPLICATIONS (
    P_LIMIT IN  NUMBER DEFAULT 5,
    P_CUR   OUT SYS_REFCURSOR
  );
END CRED_OPERATOR_PKG;
/

CREATE OR REPLACE PACKAGE BODY CRED_OPERATOR_PKG AS
  PROCEDURE GET_PRODUCTS (
    P_SEARCH   IN  VARCHAR2 DEFAULT NULL,
    P_LIMIT    IN  NUMBER   DEFAULT 10,
    P_CUR      OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT ID, NAME, ARTICLE, BARCODE, PRICE, CATEGORY_ID, CATEGORY_NAME,
             BRAND_ID, BRAND_NAME, IMG_URL
      FROM (
        SELECT * FROM V_CRED_PRODUCTS
        WHERE P_SEARCH IS NULL
           OR UPPER(NAME) LIKE '%' || UPPER(P_SEARCH) || '%'
           OR UPPER(NVL(ARTICLE,'')) LIKE '%' || UPPER(P_SEARCH) || '%'
           OR NVL(BARCODE,'') = P_SEARCH
        ORDER BY PRICE DESC
      ) WHERE ROWNUM <= P_LIMIT;
  END GET_PRODUCTS;

  PROCEDURE GET_PRODUCT_BY_ID (
    P_ID   IN  NUMBER,
    P_CUR  OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT * FROM V_CRED_PRODUCTS WHERE ID = P_ID;
  END GET_PRODUCT_BY_ID;

  PROCEDURE GET_PROGRAMS_FOR_PRODUCT (
    P_PRODUCT_ID IN  NUMBER,
    P_CUR        OUT SYS_REFCURSOR
  ) IS
    v_price      NUMBER;
    v_category_id NUMBER;
    v_brand_id   NUMBER;
  BEGIN
    SELECT PRICE, CATEGORY_ID, BRAND_ID
      INTO v_price, v_category_id, v_brand_id
      FROM CRED_PRODUCTS WHERE ID = P_PRODUCT_ID;

    OPEN P_CUR FOR
      SELECT
        p.ID, p.NAME, p.TERM_MONTHS, p.RATE_PCT, p.FIRST_PAYMENT_PCT,
        p.MIN_SUM, p.MAX_SUM, b.NAME AS BANK_NAME
      FROM CRED_PROGRAMS p
      JOIN CRED_BANKS b ON b.ID = p.BANK_ID
      JOIN CRED_PROGRAM_CATEGORIES pc ON pc.PROGRAM_ID = p.ID AND pc.CATEGORY_ID = v_category_id
      WHERE p.ACTIVE = 'Y'
        AND v_price BETWEEN p.MIN_SUM AND p.MAX_SUM
        AND (v_brand_id IS NULL OR NOT EXISTS (
          SELECT 1 FROM CRED_PROGRAM_EXCLUDED_BRANDS eb
          WHERE eb.PROGRAM_ID = p.ID AND eb.BRAND_ID = v_brand_id
        ))
      ORDER BY p.TERM_MONTHS DESC;
  END GET_PROGRAMS_FOR_PRODUCT;

  PROCEDURE CREATE_APPLICATION (
    P_PRODUCT_ID    IN  NUMBER,
    P_PROGRAM_ID    IN  NUMBER,
    P_CLIENT_FIO    IN  VARCHAR2,
    P_CLIENT_PHONE  IN  VARCHAR2,
    P_CLIENT_IDN    IN  VARCHAR2 DEFAULT NULL,
    P_APP_ID        OUT NUMBER,
    P_STATUS        OUT VARCHAR2,
    P_APPROVED_AMT  OUT NUMBER,
    P_REJECT_REASON OUT VARCHAR2
  ) IS
    v_price NUMBER;
    v_out_status VARCHAR2(30);
    v_approved   NUMBER;
    v_reason     VARCHAR2(500);
    rnd NUMBER;
  BEGIN
    SELECT PRICE INTO v_price FROM CRED_PRODUCTS WHERE ID = P_PRODUCT_ID;

    INSERT INTO CRED_APPLICATIONS (
      PRODUCT_ID, PROGRAM_ID, CLIENT_FIO, CLIENT_PHONE, CLIENT_IDN, STATUS
    ) VALUES (
      P_PRODUCT_ID, P_PROGRAM_ID, P_CLIENT_FIO, P_CLIENT_PHONE, P_CLIENT_IDN, 'pending'
    )
    RETURNING ID INTO P_APP_ID;

    SELECT DBMS_RANDOM.VALUE(1,100) INTO rnd FROM DUAL;
    IF rnd <= 80 THEN
      v_out_status := 'approved';
      v_approved   := v_price;
      v_reason     := NULL;
    ELSIF rnd <= 95 THEN
      v_out_status := 'rejected';
      v_approved   := NULL;
      v_reason     := 'Низкий скоринг';
    ELSE
      v_out_status := 'on_review';
      v_approved   := NULL;
      v_reason     := NULL;
    END IF;

    UPDATE CRED_APPLICATIONS SET
      STATUS = v_out_status,
      APPROVED_AMOUNT = v_approved,
      REJECTION_REASON = v_reason
    WHERE ID = P_APP_ID;

    P_STATUS        := v_out_status;
    P_APPROVED_AMT  := v_approved;
    P_REJECT_REASON := v_reason;
    COMMIT;
  END CREATE_APPLICATION;

  PROCEDURE GET_RECENT_APPLICATIONS (
    P_LIMIT IN  NUMBER DEFAULT 5,
    P_CUR   OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT PRODUCT_NAME, CLIENT_FIO, STATUS, CREATED_TIME, ID
      FROM (
        SELECT a.*, ROWNUM rn
        FROM (SELECT * FROM V_CRED_APPLICATIONS_RECENT ORDER BY CREATED_AT DESC) a
      )
      WHERE rn <= P_LIMIT;
  END GET_RECENT_APPLICATIONS;
END CRED_OPERATOR_PKG;
/
