-- ============================================================
-- PECO: розничная продажа топлива в сети АЗС.
-- Справочники, мастер-данные, цены.
-- Спецификация: docs/superpowers/specs/2026-08-19-peco-fuel-retail-design.md
-- Префикс объектов: PECO_
-- ============================================================

CREATE SEQUENCE PECO_STATIONS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PECO_TANKS_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PECO_PUMPS_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PECO_NOZZLES_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PECO_EMPLOYEES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PECO_PRICES_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;

-- ==================== Справочники ====================

-- Виды топлива: A92, A95, A98, DIESEL
CREATE TABLE PECO_REF_FUEL_GRADES (
  CODE       VARCHAR2(10)  NOT NULL,
  NAME       VARCHAR2(60)  NOT NULL,
  COLOR      VARCHAR2(20),
  DENSITY    NUMBER(6,4),
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_PECO_REF_FUEL_GRADES PRIMARY KEY (CODE)
);

-- Способы оплаты: CASH, MIA_QR
CREATE TABLE PECO_REF_PAY_METHODS (
  CODE          VARCHAR2(10)  NOT NULL,
  NAME          VARCHAR2(60)  NOT NULL,
  -- 1 = попадает в кассовую сверку, 0 = безналичный поток
  IS_CASH       NUMBER(1) DEFAULT 0 NOT NULL,
  SORT_ORDER    NUMBER DEFAULT 0,
  CONSTRAINT PK_PECO_REF_PAY_METHODS PRIMARY KEY (CODE),
  CONSTRAINT CK_PECO_PAY_IS_CASH CHECK (IS_CASH IN (0,1))
);

-- Статусы смены: OPEN, CLOSING, CLOSED, DISPUTED
CREATE TABLE PECO_REF_SHIFT_STATUS (
  CODE       VARCHAR2(15)  NOT NULL,
  NAME       VARCHAR2(60)  NOT NULL,
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_PECO_REF_SHIFT_STATUS PRIMARY KEY (CODE)
);

-- Статусы транзакции: AUTHORIZED, DISPENSING, AWAITING_PAY, PAID, VOIDED
CREATE TABLE PECO_REF_TXN_STATUS (
  CODE       VARCHAR2(15)  NOT NULL,
  NAME       VARCHAR2(60)  NOT NULL,
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_PECO_REF_TXN_STATUS PRIMARY KEY (CODE)
);

-- ==================== Мастер-данные ====================

CREATE TABLE PECO_STATIONS (
  ID       NUMBER        NOT NULL,
  CODE     VARCHAR2(20)  NOT NULL,
  NAME     VARCHAR2(150) NOT NULL,
  ADDRESS  VARCHAR2(300),
  REGION   VARCHAR2(100),
  TZ_NAME  VARCHAR2(60)  DEFAULT 'Europe/Chisinau',
  ACTIVE   NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PECO_STATIONS PRIMARY KEY (ID),
  CONSTRAINT UQ_PECO_STATIONS_CODE UNIQUE (CODE),
  CONSTRAINT CK_PECO_STATIONS_ACT CHECK (ACTIVE IN (0,1))
);

-- Резервуар: один на вид топлива на станции
CREATE TABLE PECO_TANKS (
  ID          NUMBER        NOT NULL,
  STATION_ID  NUMBER        NOT NULL,
  GRADE_CODE  VARCHAR2(10)  NOT NULL,
  CODE        VARCHAR2(20)  NOT NULL,
  CAPACITY_L  NUMBER(14,3)  NOT NULL,
  CURRENT_L   NUMBER(14,3)  DEFAULT 0 NOT NULL,
  MIN_ALARM_L NUMBER(14,3)  DEFAULT 0 NOT NULL,
  ACTIVE      NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PECO_TANKS PRIMARY KEY (ID),
  CONSTRAINT UQ_PECO_TANKS UNIQUE (STATION_ID, CODE),
  -- Один резервуар на вид топлива на станции (комментарий выше становится инвариантом)
  CONSTRAINT UQ_PECO_TANKS_ST_GR UNIQUE (STATION_ID, GRADE_CODE),
  -- Опорные UNIQUE для составных FK: PECO_NOZZLES проверяет по ним станцию и вид топлива резервуара
  CONSTRAINT UQ_PECO_TANKS_ID_ST UNIQUE (ID, STATION_ID),
  CONSTRAINT UQ_PECO_TANKS_ID_GR UNIQUE (ID, GRADE_CODE),
  CONSTRAINT FK_PECO_TANKS_ST FOREIGN KEY (STATION_ID) REFERENCES PECO_STATIONS (ID),
  CONSTRAINT FK_PECO_TANKS_GR FOREIGN KEY (GRADE_CODE) REFERENCES PECO_REF_FUEL_GRADES (CODE),
  CONSTRAINT CK_PECO_TANKS_ACT CHECK (ACTIVE IN (0,1))
);

CREATE TABLE PECO_PUMPS (
  ID           NUMBER       NOT NULL,
  STATION_ID   NUMBER       NOT NULL,
  CODE         VARCHAR2(20) NOT NULL,
  SELF_SERVICE NUMBER(1)    DEFAULT 1 NOT NULL,
  ACTIVE       NUMBER(1)    DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PECO_PUMPS PRIMARY KEY (ID),
  CONSTRAINT UQ_PECO_PUMPS UNIQUE (STATION_ID, CODE),
  -- Опорный UNIQUE для составного FK PECO_NOZZLES: пистолет проверяется на ту же станцию, что и колонка
  CONSTRAINT UQ_PECO_PUMPS_ID_ST UNIQUE (ID, STATION_ID),
  CONSTRAINT FK_PECO_PUMPS_ST FOREIGN KEY (STATION_ID) REFERENCES PECO_STATIONS (ID),
  CONSTRAINT CK_PECO_PUMPS_ACT CHECK (ACTIVE IN (0,1)),
  CONSTRAINT CK_PECO_PUMPS_SS  CHECK (SELF_SERVICE IN (0,1))
);

-- Пистолет. Счётчик (тотализатор) живёт ЗДЕСЬ, не на колонке:
-- колонка с несколькими пистолетами иначе теряет разбивку по видам топлива.
CREATE TABLE PECO_NOZZLES (
  ID           NUMBER       NOT NULL,
  STATION_ID   NUMBER       NOT NULL,
  PUMP_ID      NUMBER       NOT NULL,
  TANK_ID      NUMBER       NOT NULL,
  GRADE_CODE   VARCHAR2(10) NOT NULL,
  CODE         VARCHAR2(20) NOT NULL,
  METER_TOTAL  NUMBER(14,3) DEFAULT 0 NOT NULL,
  ACTIVE       NUMBER(1)    DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PECO_NOZZLES PRIMARY KEY (ID),
  CONSTRAINT UQ_PECO_NOZZLES UNIQUE (PUMP_ID, CODE),
  CONSTRAINT FK_PECO_NOZZLES_ST FOREIGN KEY (STATION_ID) REFERENCES PECO_STATIONS (ID),
  -- Составной FK: колонка пистолета обязана принадлежать той же станции, что и сам пистолет
  -- (иначе пистолет может "смотреть" на колонку соседней АЗС)
  CONSTRAINT FK_PECO_NOZZLES_PU FOREIGN KEY (PUMP_ID, STATION_ID) REFERENCES PECO_PUMPS (ID, STATION_ID),
  -- Составной FK: резервуар пистолета обязан принадлежать той же станции, что и пистолет
  CONSTRAINT FK_PECO_NOZZLES_TA FOREIGN KEY (TANK_ID, STATION_ID) REFERENCES PECO_TANKS (ID, STATION_ID),
  -- Составной FK: вид топлива пистолета обязан совпадать с видом топлива его резервуара
  -- (иначе счётчик пистолета сверяется не с тем баком при реконсиляции)
  CONSTRAINT FK_PECO_NOZZLES_TA_GR FOREIGN KEY (TANK_ID, GRADE_CODE) REFERENCES PECO_TANKS (ID, GRADE_CODE),
  CONSTRAINT FK_PECO_NOZZLES_GR FOREIGN KEY (GRADE_CODE) REFERENCES PECO_REF_FUEL_GRADES (CODE),
  CONSTRAINT CK_PECO_NOZZLES_ACT CHECK (ACTIVE IN (0,1))
);

-- PIN хешируется PBKDF2-HMAC-SHA256 с солью на сотрудника. Голый SHA-256
-- от четырёхзначного PIN подбирается перебором мгновенно, а этот PIN
-- подтверждает расхождение по кассе — то есть закрывает недостачу денег.
CREATE TABLE PECO_EMPLOYEES (
  ID         NUMBER        NOT NULL,
  STATION_ID NUMBER,
  FULL_NAME  VARCHAR2(150) NOT NULL,
  ROLE_CODE  VARCHAR2(15)  DEFAULT 'ATTENDANT' NOT NULL,
  PIN_SALT   VARCHAR2(64)  NOT NULL,
  PIN_HASH   VARCHAR2(128) NOT NULL,
  ACTIVE     NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PECO_EMPLOYEES PRIMARY KEY (ID),
  CONSTRAINT CK_PECO_EMP_ROLE CHECK (ROLE_CODE IN ('ATTENDANT','MANAGER','ADMIN')),
  CONSTRAINT FK_PECO_EMP_ST FOREIGN KEY (STATION_ID) REFERENCES PECO_STATIONS (ID)
);

-- Цена никогда не обновляется на месте: изменение закрывает старую строку
-- (VALID_TO) и вставляет новую. Действующая цена = VALID_TO IS NULL.
CREATE TABLE PECO_PRICES (
  ID          NUMBER        NOT NULL,
  STATION_ID  NUMBER        NOT NULL,
  GRADE_CODE  VARCHAR2(10)  NOT NULL,
  PRICE       NUMBER(12,2)  NOT NULL,
  VALID_FROM  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  VALID_TO    TIMESTAMP,
  CONSTRAINT PK_PECO_PRICES PRIMARY KEY (ID),
  CONSTRAINT FK_PECO_PRICES_ST FOREIGN KEY (STATION_ID) REFERENCES PECO_STATIONS (ID),
  CONSTRAINT FK_PECO_PRICES_GR FOREIGN KEY (GRADE_CODE) REFERENCES PECO_REF_FUEL_GRADES (CODE)
);

CREATE INDEX IX_PECO_PRICES_CUR ON PECO_PRICES (STATION_ID, GRADE_CODE, VALID_TO);
CREATE INDEX IX_PECO_TANKS_ST   ON PECO_TANKS (STATION_ID);
CREATE INDEX IX_PECO_NOZ_TANK   ON PECO_NOZZLES (TANK_ID);
