-- ============================================================
-- PECO: операционные таблицы — смены, показания счётчиков, транзакции.
-- ============================================================

CREATE SEQUENCE PECO_SHIFTS_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PECO_SHIFT_METERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PECO_TXN_SEQ          START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE PECO_SHIFTS (
  ID              NUMBER       NOT NULL,
  STATION_ID      NUMBER       NOT NULL,
  STATUS_CODE     VARCHAR2(15) DEFAULT 'OPEN' NOT NULL,
  OPENED_AT       TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CLOSED_AT       TIMESTAMP,
  OPENED_BY       NUMBER       NOT NULL,
  CLOSED_BY       NUMBER,
  -- заполняются при закрытии
  CASH_DECLARED   NUMBER(12,2),
  CASH_EXPECTED   NUMBER(12,2),
  CASH_VARIANCE   NUMBER(12,2),
  LITER_VARIANCE  NUMBER(14,3),
  TANK_VARIANCE   NUMBER(14,3),
  -- PIN менеджера, подтвердившего расхождение выше допуска
  APPROVED_BY     NUMBER,
  NOTE            VARCHAR2(500),
  CONSTRAINT PK_PECO_SHIFTS PRIMARY KEY (ID),
  CONSTRAINT FK_PECO_SHIFTS_ST FOREIGN KEY (STATION_ID) REFERENCES PECO_STATIONS (ID),
  CONSTRAINT FK_PECO_SHIFTS_OB FOREIGN KEY (OPENED_BY)  REFERENCES PECO_EMPLOYEES (ID),
  CONSTRAINT FK_PECO_SHIFTS_CB FOREIGN KEY (CLOSED_BY)  REFERENCES PECO_EMPLOYEES (ID),
  CONSTRAINT FK_PECO_SHIFTS_AB FOREIGN KEY (APPROVED_BY) REFERENCES PECO_EMPLOYEES (ID),
  CONSTRAINT FK_PECO_SHIFTS_SS FOREIGN KEY (STATUS_CODE) REFERENCES PECO_REF_SHIFT_STATUS (CODE)
);

-- Опорная точка сверки: показания счётчика каждого пистолета за смену.
CREATE TABLE PECO_SHIFT_METERS (
  ID          NUMBER       NOT NULL,
  SHIFT_ID    NUMBER       NOT NULL,
  NOZZLE_ID   NUMBER       NOT NULL,
  METER_OPEN  NUMBER(14,3) NOT NULL,
  METER_CLOSE NUMBER(14,3),
  CONSTRAINT PK_PECO_SHIFT_METERS PRIMARY KEY (ID),
  CONSTRAINT UQ_PECO_SHIFT_METERS UNIQUE (SHIFT_ID, NOZZLE_ID),
  CONSTRAINT FK_PECO_SM_SH FOREIGN KEY (SHIFT_ID)  REFERENCES PECO_SHIFTS (ID),
  CONSTRAINT FK_PECO_SM_NO FOREIGN KEY (NOZZLE_ID) REFERENCES PECO_NOZZLES (ID)
);

CREATE TABLE PECO_TXN (
  ID              NUMBER       NOT NULL,
  SHIFT_ID        NUMBER       NOT NULL,
  NOZZLE_ID       NUMBER       NOT NULL,
  GRADE_CODE      VARCHAR2(10) NOT NULL,
  STATUS_CODE     VARCHAR2(15) DEFAULT 'AUTHORIZED' NOT NULL,
  LITERS          NUMBER(14,3) DEFAULT 0 NOT NULL,
  -- цена, по которой транзакция ФАКТИЧЕСКИ проведена; смена цены
  -- посреди смены не переписывает историю
  PRICE           NUMBER(12,2) NOT NULL,
  AMOUNT          NUMBER(12,2) DEFAULT 0 NOT NULL,
  PAY_METHOD      VARCHAR2(10),
  IS_SELF_SERVICE NUMBER(1)    DEFAULT 0 NOT NULL,
  AUTHORIZED_BY   NUMBER,
  MIA_REF         VARCHAR2(100),
  METER_START     NUMBER(14,3) NOT NULL,
  METER_END       NUMBER(14,3),
  STARTED_AT      TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  PAID_AT         TIMESTAMP,
  CONSTRAINT PK_PECO_TXN PRIMARY KEY (ID),
  CONSTRAINT FK_PECO_TXN_SH FOREIGN KEY (SHIFT_ID)    REFERENCES PECO_SHIFTS (ID),
  CONSTRAINT FK_PECO_TXN_NO FOREIGN KEY (NOZZLE_ID)   REFERENCES PECO_NOZZLES (ID),
  CONSTRAINT FK_PECO_TXN_GR FOREIGN KEY (GRADE_CODE)  REFERENCES PECO_REF_FUEL_GRADES (CODE),
  CONSTRAINT FK_PECO_TXN_TS FOREIGN KEY (STATUS_CODE) REFERENCES PECO_REF_TXN_STATUS (CODE),
  CONSTRAINT FK_PECO_TXN_PM FOREIGN KEY (PAY_METHOD)  REFERENCES PECO_REF_PAY_METHODS (CODE),
  CONSTRAINT FK_PECO_TXN_AB FOREIGN KEY (AUTHORIZED_BY) REFERENCES PECO_EMPLOYEES (ID)
);

CREATE INDEX IX_PECO_TXN_SHIFT  ON PECO_TXN (SHIFT_ID, STATUS_CODE);
CREATE INDEX IX_PECO_TXN_NOZZLE ON PECO_TXN (NOZZLE_ID);
CREATE INDEX IX_PECO_SHIFTS_ST  ON PECO_SHIFTS (STATION_ID, STATUS_CODE);
