-- ============================================================
-- PECO: справочные значения + одна демо-станция.
-- ============================================================

INSERT INTO PECO_REF_FUEL_GRADES (CODE, NAME, COLOR, DENSITY, SORT_ORDER) VALUES ('A92',    'Бензин А-92', '#16a34a', 0.7350, 1);
INSERT INTO PECO_REF_FUEL_GRADES (CODE, NAME, COLOR, DENSITY, SORT_ORDER) VALUES ('A95',    'Бензин А-95', '#2563eb', 0.7500, 2);
INSERT INTO PECO_REF_FUEL_GRADES (CODE, NAME, COLOR, DENSITY, SORT_ORDER) VALUES ('A98',    'Бензин А-98', '#9333ea', 0.7600, 3);
INSERT INTO PECO_REF_FUEL_GRADES (CODE, NAME, COLOR, DENSITY, SORT_ORDER) VALUES ('DIESEL', 'Дизель',      '#ca8a04', 0.8400, 4);

INSERT INTO PECO_REF_PAY_METHODS (CODE, NAME, IS_CASH, SORT_ORDER) VALUES ('CASH',   'Наличные на кассе', 1, 1);
INSERT INTO PECO_REF_PAY_METHODS (CODE, NAME, IS_CASH, SORT_ORDER) VALUES ('MIA_QR', 'MIA QR-код',        0, 2);

INSERT INTO PECO_REF_SHIFT_STATUS (CODE, NAME, SORT_ORDER) VALUES ('OPEN',     'Открыта',            1);
INSERT INTO PECO_REF_SHIFT_STATUS (CODE, NAME, SORT_ORDER) VALUES ('CLOSING',  'Закрывается',        2);
INSERT INTO PECO_REF_SHIFT_STATUS (CODE, NAME, SORT_ORDER) VALUES ('CLOSED',   'Закрыта',            3);
INSERT INTO PECO_REF_SHIFT_STATUS (CODE, NAME, SORT_ORDER) VALUES ('DISPUTED', 'Расхождение',        4);

INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER) VALUES ('AUTHORIZED',   'Авторизована',      1);
INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER) VALUES ('DISPENSING',   'Идёт налив',        2);
INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER) VALUES ('AWAITING_PAY', 'Ожидает оплаты',    3);
INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER) VALUES ('PAID',         'Оплачена',          4);
INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER) VALUES ('VOIDED',       'Аннулирована',      5);

-- Демо-станция
INSERT INTO PECO_STATIONS (ID, CODE, NAME, ADDRESS, REGION)
VALUES (PECO_STATIONS_SEQ.NEXTVAL, 'AZS-001', 'АЗС №1 Кишинёв-Центр', 'бул. Штефан чел Маре 1', 'Кишинёв');

INSERT INTO PECO_TANKS (ID, STATION_ID, GRADE_CODE, CODE, CAPACITY_L, CURRENT_L, MIN_ALARM_L)
SELECT PECO_TANKS_SEQ.NEXTVAL, s.ID, g.CODE, 'T-' || g.CODE, 20000, 12000, 2000
  FROM PECO_STATIONS s CROSS JOIN PECO_REF_FUEL_GRADES g
 WHERE s.CODE = 'AZS-001';

INSERT INTO PECO_PUMPS (ID, STATION_ID, CODE, SELF_SERVICE)
SELECT PECO_PUMPS_SEQ.NEXTVAL, ID, 'P-1', 1 FROM PECO_STATIONS WHERE CODE = 'AZS-001';
INSERT INTO PECO_PUMPS (ID, STATION_ID, CODE, SELF_SERVICE)
SELECT PECO_PUMPS_SEQ.NEXTVAL, ID, 'P-2', 0 FROM PECO_STATIONS WHERE CODE = 'AZS-001';

-- По одному пистолету каждого вида топлива на первой колонке.
-- STATION_ID заполняется явно: составные внешние ключи не дают привязать
-- пистолет к колонке одной станции и резервуару другой.
INSERT INTO PECO_NOZZLES (ID, PUMP_ID, TANK_ID, STATION_ID, GRADE_CODE, CODE, METER_TOTAL)
SELECT PECO_NOZZLES_SEQ.NEXTVAL, p.ID, t.ID, p.STATION_ID, t.GRADE_CODE,
       'N-' || t.GRADE_CODE, 0
  FROM PECO_PUMPS p
  JOIN PECO_TANKS t ON t.STATION_ID = p.STATION_ID
 WHERE p.CODE = 'P-1';

-- PIN_HASH заведомо невалиден: демо-сотрудники не должны иметь рабочий PIN.
-- Реальный PIN задаётся через бэк-офис, который считает PBKDF2 с новой солью.
INSERT INTO PECO_EMPLOYEES (ID, STATION_ID, FULL_NAME, ROLE_CODE, PIN_SALT, PIN_HASH)
SELECT PECO_EMPLOYEES_SEQ.NEXTVAL, ID, 'Оператор Демо', 'ATTENDANT',
       'NO_SALT_SET', 'NO_PIN_SET'
  FROM PECO_STATIONS WHERE CODE = 'AZS-001';
INSERT INTO PECO_EMPLOYEES (ID, STATION_ID, FULL_NAME, ROLE_CODE, PIN_SALT, PIN_HASH)
SELECT PECO_EMPLOYEES_SEQ.NEXTVAL, ID, 'Менеджер Демо', 'MANAGER',
       'NO_SALT_SET', 'NO_PIN_SET'
  FROM PECO_STATIONS WHERE CODE = 'AZS-001';

INSERT INTO PECO_PRICES (ID, STATION_ID, GRADE_CODE, PRICE)
SELECT PECO_PRICES_SEQ.NEXTVAL, s.ID, g.CODE,
       CASE g.CODE WHEN 'A92' THEN 22.50 WHEN 'A95' THEN 23.90
                   WHEN 'A98' THEN 26.40 ELSE 21.80 END
  FROM PECO_STATIONS s CROSS JOIN PECO_REF_FUEL_GRADES g
 WHERE s.CODE = 'AZS-001';

COMMIT;
