-- ============================================================
-- PECO: справочные значения (обязательны для работы модуля).
--
-- Это НЕ демо-данные: без этих строк не заведётся ни один сорт топлива,
-- способ оплаты, статус смены или статус транзакции — модуль не работает
-- вообще ни на одной станции. Поэтому файл остаётся в безусловном
-- порядке deploy_oracle_objects.py, а демо-станция вынесена отдельно в
-- 105_peco_demo_station.sql и НЕ должна запускаться на production.
--
-- Инсерты идемпотентны (WHERE NOT EXISTS по PK): повторный запуск этого
-- файла (например, повторный `--only peco` после частично прошедшего
-- деплоя) не падает на нарушении PRIMARY KEY и не дублирует справочники.
-- ============================================================

INSERT INTO PECO_REF_FUEL_GRADES (CODE, NAME, COLOR, DENSITY, SORT_ORDER)
SELECT 'A92', 'Бензин А-92', '#16a34a', 0.7350, 1 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_FUEL_GRADES WHERE CODE = 'A92');
INSERT INTO PECO_REF_FUEL_GRADES (CODE, NAME, COLOR, DENSITY, SORT_ORDER)
SELECT 'A95', 'Бензин А-95', '#2563eb', 0.7500, 2 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_FUEL_GRADES WHERE CODE = 'A95');
INSERT INTO PECO_REF_FUEL_GRADES (CODE, NAME, COLOR, DENSITY, SORT_ORDER)
SELECT 'A98', 'Бензин А-98', '#9333ea', 0.7600, 3 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_FUEL_GRADES WHERE CODE = 'A98');
INSERT INTO PECO_REF_FUEL_GRADES (CODE, NAME, COLOR, DENSITY, SORT_ORDER)
SELECT 'DIESEL', 'Дизель', '#ca8a04', 0.8400, 4 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_FUEL_GRADES WHERE CODE = 'DIESEL');

INSERT INTO PECO_REF_PAY_METHODS (CODE, NAME, IS_CASH, SORT_ORDER)
SELECT 'CASH', 'Наличные на кассе', 1, 1 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_PAY_METHODS WHERE CODE = 'CASH');
INSERT INTO PECO_REF_PAY_METHODS (CODE, NAME, IS_CASH, SORT_ORDER)
SELECT 'MIA_QR', 'MIA QR-код', 0, 2 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_PAY_METHODS WHERE CODE = 'MIA_QR');

INSERT INTO PECO_REF_SHIFT_STATUS (CODE, NAME, SORT_ORDER)
SELECT 'OPEN', 'Открыта', 1 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_SHIFT_STATUS WHERE CODE = 'OPEN');
INSERT INTO PECO_REF_SHIFT_STATUS (CODE, NAME, SORT_ORDER)
SELECT 'CLOSING', 'Закрывается', 2 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_SHIFT_STATUS WHERE CODE = 'CLOSING');
INSERT INTO PECO_REF_SHIFT_STATUS (CODE, NAME, SORT_ORDER)
SELECT 'CLOSED', 'Закрыта', 3 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_SHIFT_STATUS WHERE CODE = 'CLOSED');
INSERT INTO PECO_REF_SHIFT_STATUS (CODE, NAME, SORT_ORDER)
SELECT 'DISPUTED', 'Расхождение', 4 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_SHIFT_STATUS WHERE CODE = 'DISPUTED');

INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER)
SELECT 'AUTHORIZED', 'Авторизована', 1 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_TXN_STATUS WHERE CODE = 'AUTHORIZED');
INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER)
SELECT 'DISPENSING', 'Идёт налив', 2 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_TXN_STATUS WHERE CODE = 'DISPENSING');
INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER)
SELECT 'AWAITING_PAY', 'Ожидает оплаты', 3 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_TXN_STATUS WHERE CODE = 'AWAITING_PAY');
INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER)
SELECT 'PAID', 'Оплачена', 4 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_TXN_STATUS WHERE CODE = 'PAID');
INSERT INTO PECO_REF_TXN_STATUS (CODE, NAME, SORT_ORDER)
SELECT 'VOIDED', 'Аннулирована', 5 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM PECO_REF_TXN_STATUS WHERE CODE = 'VOIDED');

COMMIT;
