-- ============================================================
-- Демонстрационные и тестовые данные
-- ============================================================

-- ---------- Кредиты: банки ----------
INSERT INTO CRED_BANKS (CODE, NAME) VALUES ('Maib', 'Maib');
INSERT INTO CRED_BANKS (CODE, NAME) VALUES ('Victoriabank', 'Victoriabank');
INSERT INTO CRED_BANKS (CODE, NAME) VALUES ('Moldindconbank', 'Moldindconbank');
INSERT INTO CRED_BANKS (CODE, NAME) VALUES ('Express Credit', 'Express Credit');

-- ---------- Кредиты: категории ----------
INSERT INTO CRED_CATEGORIES (NAME) VALUES ('Холодильники');
INSERT INTO CRED_CATEGORIES (NAME) VALUES ('Стиральные машины');
INSERT INTO CRED_CATEGORIES (NAME) VALUES ('Телевизоры');
INSERT INTO CRED_CATEGORIES (NAME) VALUES ('Смартфоны');
INSERT INTO CRED_CATEGORIES (NAME) VALUES ('Ноутбуки');

-- ---------- Кредиты: бренды ----------
INSERT INTO CRED_BRANDS (NAME) VALUES ('Samsung');
INSERT INTO CRED_BRANDS (NAME) VALUES ('Apple');
INSERT INTO CRED_BRANDS (NAME) VALUES ('LG');
INSERT INTO CRED_BRANDS (NAME) VALUES ('Beko');
INSERT INTO CRED_BRANDS (NAME) VALUES ('ASUS');

COMMIT;

-- ---------- Кредиты: программы (bank_id 1=Maib, 2=Victoriabank, 3=Moldindconbank, 4=Express) ----------
INSERT INTO CRED_PROGRAMS (NAME, BANK_ID, TERM_MONTHS, RATE_PCT, FIRST_PAYMENT_PCT, MIN_SUM, MAX_SUM, COMMISSION_PCT, ACTIVE)
VALUES ('Maib 0-0-24', 1, 24, 0, 0, 1000, 50000, 0, 'Y');
INSERT INTO CRED_PROGRAMS (NAME, BANK_ID, TERM_MONTHS, RATE_PCT, FIRST_PAYMENT_PCT, MIN_SUM, MAX_SUM, COMMISSION_PCT, ACTIVE)
VALUES ('Victoriabank 0-0-12', 2, 12, 0, 0, 500, 30000, 0, 'Y');
INSERT INTO CRED_PROGRAMS (NAME, BANK_ID, TERM_MONTHS, RATE_PCT, FIRST_PAYMENT_PCT, MIN_SUM, MAX_SUM, COMMISSION_PCT, ACTIVE)
VALUES ('Moldindconbank 0-0-36', 3, 36, 0, 0, 2000, 100000, 1, 'Y');
INSERT INTO CRED_PROGRAMS (NAME, BANK_ID, TERM_MONTHS, RATE_PCT, FIRST_PAYMENT_PCT, MIN_SUM, MAX_SUM, COMMISSION_PCT, ACTIVE)
VALUES ('Express 0-10-12', 4, 12, 0, 10, 1000, 25000, 0, 'N');
INSERT INTO CRED_PROGRAMS (NAME, BANK_ID, TERM_MONTHS, RATE_PCT, FIRST_PAYMENT_PCT, MIN_SUM, MAX_SUM, COMMISSION_PCT, ACTIVE)
VALUES ('Maib 0-0-6', 1, 6, 0, 0, 500, 15000, 0, 'Y');
INSERT INTO CRED_PROGRAMS (NAME, BANK_ID, TERM_MONTHS, RATE_PCT, FIRST_PAYMENT_PCT, MIN_SUM, MAX_SUM, COMMISSION_PCT, ACTIVE)
VALUES ('Victoriabank 0-20-24', 2, 24, 0, 20, 3000, 80000, 0.5, 'Y');

COMMIT;

-- ---------- Матрица: все категории для программ 1,2,3,5,6 (активные) ----------
INSERT INTO CRED_PROGRAM_CATEGORIES (PROGRAM_ID, CATEGORY_ID)
SELECT p.ID, c.ID FROM CRED_PROGRAMS p, CRED_CATEGORIES c
WHERE p.ACTIVE = 'Y' AND p.ID IN (1,2,3,5,6);

-- Исключённые бренды: программа 1 (Maib 0-0-24) — без Apple
INSERT INTO CRED_PROGRAM_EXCLUDED_BRANDS (PROGRAM_ID, BRAND_ID)
SELECT 1, ID FROM CRED_BRANDS WHERE NAME = 'Apple';

COMMIT;

-- ---------- Товары (category 1–5, brand 1–5) ----------
INSERT INTO CRED_PRODUCTS (NAME, ARTICLE, BARCODE, PRICE, CATEGORY_ID, BRAND_ID, IMG_URL)
VALUES ('Холодильник Samsung RB37', 'S-RB37', '4601234567890', 25000, 1, 1, 'https://via.placeholder.com/200/f0f0f0/666?text=Samsung');
INSERT INTO CRED_PRODUCTS (NAME, ARTICLE, BARCODE, PRICE, CATEGORY_ID, BRAND_ID, IMG_URL)
VALUES ('Смартфон iPhone 15', 'AP-15', '4601234567891', 15000, 4, 2, 'https://via.placeholder.com/200/f0f0f0/666?text=iPhone');
INSERT INTO CRED_PRODUCTS (NAME, ARTICLE, BARCODE, PRICE, CATEGORY_ID, BRAND_ID, IMG_URL)
VALUES ('Стиральная машина Beko', 'BEKO-WM', '4601234567892', 12000, 2, 4, 'https://via.placeholder.com/200/f0f0f0/666?text=Beko');
INSERT INTO CRED_PRODUCTS (NAME, ARTICLE, BARCODE, PRICE, CATEGORY_ID, BRAND_ID, IMG_URL)
VALUES ('Телевизор LG 55"', 'LG-55', '4601234567893', 18000, 3, 3, 'https://via.placeholder.com/200/f0f0f0/666?text=LG');
INSERT INTO CRED_PRODUCTS (NAME, ARTICLE, BARCODE, PRICE, CATEGORY_ID, BRAND_ID, IMG_URL)
VALUES ('Ноутбук ASUS', 'ASUS-NB', '4601234567894', 22000, 5, 5, 'https://via.placeholder.com/200/f0f0f0/666?text=ASUS');
INSERT INTO CRED_PRODUCTS (NAME, ARTICLE, BARCODE, PRICE, CATEGORY_ID, BRAND_ID, IMG_URL)
VALUES ('Холодильник Beko', 'BEKO-F', '4601234567895', 9500, 1, 4, 'https://via.placeholder.com/200/f0f0f0/666?text=Beko');
INSERT INTO CRED_PRODUCTS (NAME, ARTICLE, BARCODE, PRICE, CATEGORY_ID, BRAND_ID, IMG_URL)
VALUES ('Смартфон Samsung A54', 'S-A54', '4601234567896', 8500, 4, 1, 'https://via.placeholder.com/200/f0f0f0/666?text=Samsung');
INSERT INTO CRED_PRODUCTS (NAME, ARTICLE, BARCODE, PRICE, CATEGORY_ID, BRAND_ID, IMG_URL)
VALUES ('Телевизор Samsung 43"', 'S-TV43', '4601234567897', 11000, 3, 1, 'https://via.placeholder.com/200/f0f0f0/666?text=Samsung');

COMMIT;

-- ---------- Табло: маршруты ----------
INSERT INTO BUS_ROUTES (ROUTE_CODE, DESTINATION) VALUES ('101', 'Кишинэу');
INSERT INTO BUS_ROUTES (ROUTE_CODE, DESTINATION) VALUES ('205', 'Бэлць');
INSERT INTO BUS_ROUTES (ROUTE_CODE, DESTINATION) VALUES ('302', 'Унгень');
INSERT INTO BUS_ROUTES (ROUTE_CODE, DESTINATION) VALUES ('418', 'Орхей');
INSERT INTO BUS_ROUTES (ROUTE_CODE, DESTINATION) VALUES ('501', 'Кагул');
INSERT INTO BUS_ROUTES (ROUTE_CODE, DESTINATION) VALUES ('112', 'Сорока');
INSERT INTO BUS_ROUTES (ROUTE_CODE, DESTINATION) VALUES ('207', 'Бендеры');

COMMIT;

-- ---------- Табло: рейсы на сегодня (SYSDATE + N минут) ----------
INSERT INTO BUS_DEPARTURES (ROUTE_CODE, DEPARTURE_DT, PLATFORM, GATE, STATUS) VALUES ('101', SYSDATE + 12/1440, '3', 'A', 'Посадка');
INSERT INTO BUS_DEPARTURES (ROUTE_CODE, DEPARTURE_DT, PLATFORM, GATE, STATUS) VALUES ('205', SYSDATE + 25/1440, '1', 'B', 'Ожидание');
INSERT INTO BUS_DEPARTURES (ROUTE_CODE, DEPARTURE_DT, PLATFORM, GATE, STATUS) VALUES ('302', SYSDATE + 38/1440, '2', 'A', 'Ожидание');
INSERT INTO BUS_DEPARTURES (ROUTE_CODE, DEPARTURE_DT, PLATFORM, GATE, STATUS) VALUES ('418', SYSDATE + 55/1440, '4', 'C', 'Ожидание');
INSERT INTO BUS_DEPARTURES (ROUTE_CODE, DEPARTURE_DT, PLATFORM, GATE, STATUS) VALUES ('501', SYSDATE + 78/1440, '1', 'B', 'Ожидание');
INSERT INTO BUS_DEPARTURES (ROUTE_CODE, DEPARTURE_DT, PLATFORM, GATE, STATUS) VALUES ('112', SYSDATE + 95/1440, '2', 'A', 'Ожидание');
INSERT INTO BUS_DEPARTURES (ROUTE_CODE, DEPARTURE_DT, PLATFORM, GATE, STATUS) VALUES ('207', SYSDATE + 120/1440, '3', 'C', 'Ожидание');

COMMIT;

-- ---------- Заявки (демо для истории оператора) ----------
-- Используем product_id 1,2,3 и program_id 1,2,3
INSERT INTO CRED_APPLICATIONS (PRODUCT_ID, PROGRAM_ID, CLIENT_FIO, CLIENT_PHONE, CLIENT_IDN, STATUS, APPROVED_AMOUNT, REJECTION_REASON)
VALUES (1, 1, 'Иванов Иван Иванович', '+37369123456', '1234567890123', 'approved', 25000, NULL);
INSERT INTO CRED_APPLICATIONS (PRODUCT_ID, PROGRAM_ID, CLIENT_FIO, CLIENT_PHONE, CLIENT_IDN, STATUS, APPROVED_AMOUNT, REJECTION_REASON)
VALUES (2, 2, 'Петров Пётр Петрович', '+37369234567', '2345678901234', 'rejected', NULL, 'Низкий скоринг');
INSERT INTO CRED_APPLICATIONS (PRODUCT_ID, PROGRAM_ID, CLIENT_FIO, CLIENT_PHONE, CLIENT_IDN, STATUS, APPROVED_AMOUNT, REJECTION_REASON)
VALUES (3, 1, 'Сидорова Анна Сергеевна', '+37369345678', '3456789012345', 'on_review', NULL, NULL);

COMMIT;

/
