-- ============================================================
-- Связь программа × конкретные товары (для ограничения по товарам в матрице)
-- ============================================================

CREATE TABLE CRED_PROGRAM_PRODUCTS (
  PROGRAM_ID  NUMBER NOT NULL,
  PRODUCT_ID  NUMBER NOT NULL,
  CREATED_AT  TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT PK_CRED_PRG_PROD PRIMARY KEY (PROGRAM_ID, PRODUCT_ID),
  CONSTRAINT FK_CRED_PRG_PROD_PRG FOREIGN KEY (PROGRAM_ID) REFERENCES CRED_PROGRAMS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_CRED_PRG_PROD_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES CRED_PRODUCTS(ID) ON DELETE CASCADE
);

CREATE INDEX IX_CRED_PROGRAM_PRODUCTS_PROG ON CRED_PROGRAM_PRODUCTS (PROGRAM_ID);
CREATE INDEX IX_CRED_PROGRAM_PRODUCTS_PROD ON CRED_PROGRAM_PRODUCTS (PRODUCT_ID);

/