-- ============================================================
-- Кредиты: настраиваемые отчёты (таблицы + пакет)
-- ============================================================

CREATE SEQUENCE CRED_REPORTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CRED_REPORT_PARAMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Справочник отчётов (название, пакет, процедура, шаблон)
CREATE TABLE CRED_REPORTS (
  ID             NUMBER        NOT NULL,
  CODE           VARCHAR2(50)  NOT NULL,
  NAME           VARCHAR2(200) NOT NULL,
  DESCRIPTION    VARCHAR2(500),
  PACKAGE_NAME   VARCHAR2(100) NOT NULL,
  PROCEDURE_NAME VARCHAR2(100) NOT NULL,
  TEMPLATE_TYPE  VARCHAR2(20)  DEFAULT 'table',
  TEMPLATE_HTML  CLOB,
  ENABLED        CHAR(1)       DEFAULT 'Y',
  DISPLAY_ORDER  NUMBER        DEFAULT 0,
  CREATED_AT     TIMESTAMP,
  UPDATED_AT     TIMESTAMP,
  CONSTRAINT PK_CRED_REPORTS PRIMARY KEY (ID),
  CONSTRAINT UQ_CRED_REPORTS_CODE UNIQUE (CODE),
  CONSTRAINT CHK_CRED_REPORTS_ENABLED CHECK (ENABLED IN ('Y','N')),
  CONSTRAINT CHK_CRED_REPORTS_TEMPLATE CHECK (TEMPLATE_TYPE IN ('table','json','custom'))
);
/
CREATE OR REPLACE TRIGGER CRED_REPORTS_BI BEFORE INSERT ON CRED_REPORTS FOR EACH ROW
WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := CRED_REPORTS_SEQ.NEXTVAL; END;
/

-- Параметры отчётов (название, тип, значение по умолчанию)
CREATE TABLE CRED_REPORT_PARAMS (
  ID            NUMBER        NOT NULL,
  REPORT_ID     NUMBER        NOT NULL,
  PARAM_CODE    VARCHAR2(50)  NOT NULL,
  PARAM_NAME    VARCHAR2(200) NOT NULL,
  PARAM_TYPE    VARCHAR2(20)  DEFAULT 'string',
  DEFAULT_VALUE VARCHAR2(500),
  REQUIRED      CHAR(1)       DEFAULT 'N',
  OPTIONS_JSON  VARCHAR2(2000),
  DISPLAY_ORDER NUMBER        DEFAULT 0,
  CREATED_AT    TIMESTAMP,
  CONSTRAINT PK_CRED_REPORT_PARAMS PRIMARY KEY (ID),
  CONSTRAINT FK_CRED_RP_REPORT FOREIGN KEY (REPORT_ID) REFERENCES CRED_REPORTS(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_CRED_RP_REQUIRED CHECK (REQUIRED IN ('Y','N')),
  CONSTRAINT CHK_CRED_RP_TYPE CHECK (PARAM_TYPE IN ('string','number','date','select'))
);
/
CREATE OR REPLACE TRIGGER CRED_REPORT_PARAMS_BI BEFORE INSERT ON CRED_REPORT_PARAMS FOR EACH ROW
WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := CRED_REPORT_PARAMS_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_CRED_REPORT_PARAMS_RID ON CRED_REPORT_PARAMS (REPORT_ID);

/
-- ============================================================
-- Пакет логики отчётов (алгоритмы в процедурах)
-- ============================================================

CREATE OR REPLACE PACKAGE CRED_REPORT_LOGIC_PKG AS
  PROCEDURE REPORT_APPLICATIONS_BY_STATUS (
    P_STATUS   IN  VARCHAR2 DEFAULT NULL,
    P_DATE_FROM IN DATE DEFAULT NULL,
    P_DATE_TO   IN DATE DEFAULT NULL,
    P_CUR       OUT SYS_REFCURSOR
  );
  PROCEDURE REPORT_PROGRAMS_BY_BANK (
    P_BANK_ID IN NUMBER DEFAULT NULL,
    P_CUR     OUT SYS_REFCURSOR
  );
END CRED_REPORT_LOGIC_PKG;
/

CREATE OR REPLACE PACKAGE BODY CRED_REPORT_LOGIC_PKG AS
  PROCEDURE REPORT_APPLICATIONS_BY_STATUS (
    P_STATUS    IN  VARCHAR2 DEFAULT NULL,
    P_DATE_FROM IN  DATE DEFAULT NULL,
    P_DATE_TO   IN  DATE DEFAULT NULL,
    P_CUR       OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT a.ID, a.CLIENT_FIO, a.CLIENT_PHONE, a.STATUS, a.APPROVED_AMOUNT, a.CREATED_AT,
             p.NAME AS PRODUCT_NAME, pr.NAME AS PROGRAM_NAME, b.NAME AS BANK_NAME
      FROM CRED_APPLICATIONS a
      JOIN CRED_PRODUCTS p ON a.PRODUCT_ID = p.ID
      JOIN CRED_PROGRAMS pr ON a.PROGRAM_ID = pr.ID
      JOIN CRED_BANKS b ON pr.BANK_ID = b.ID
      WHERE (P_STATUS IS NULL OR a.STATUS = P_STATUS)
        AND (P_DATE_FROM IS NULL OR TRUNC(a.CREATED_AT) >= TRUNC(P_DATE_FROM))
        AND (P_DATE_TO IS NULL OR TRUNC(a.CREATED_AT) <= TRUNC(P_DATE_TO))
      ORDER BY a.CREATED_AT DESC;
  END REPORT_APPLICATIONS_BY_STATUS;

  PROCEDURE REPORT_PROGRAMS_BY_BANK (
    P_BANK_ID IN NUMBER DEFAULT NULL,
    P_CUR     OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT pr.ID, pr.NAME, b.NAME AS BANK_NAME, pr.TERM_MONTHS, pr.RATE_PCT,
             pr.MIN_SUM, pr.MAX_SUM, pr.ACTIVE,
             (SELECT COUNT(*) FROM CRED_APPLICATIONS a WHERE a.PROGRAM_ID = pr.ID) AS APP_COUNT
      FROM CRED_PROGRAMS pr
      JOIN CRED_BANKS b ON pr.BANK_ID = b.ID
      WHERE (P_BANK_ID IS NULL OR pr.BANK_ID = P_BANK_ID)
      ORDER BY b.NAME, pr.TERM_MONTHS, pr.ID;
  END REPORT_PROGRAMS_BY_BANK;
END CRED_REPORT_LOGIC_PKG;
/

-- ============================================================
-- Пакет CRED_REPORTS_PKG (управление и выполнение отчётов)
-- ============================================================

CREATE OR REPLACE PACKAGE CRED_REPORTS_PKG AS
  PROCEDURE GET_REPORTS (P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_REPORT_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_REPORT_PARAMS (P_REPORT_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE EXECUTE_REPORT (
    P_REPORT_ID  IN  NUMBER,
    P_PARAMS_JSON IN VARCHAR2,
    P_CUR        OUT SYS_REFCURSOR
  );
  PROCEDURE UPSERT_REPORT (
    P_ID             IN OUT NUMBER,
    P_CODE           IN     VARCHAR2,
    P_NAME           IN     VARCHAR2,
    P_DESCRIPTION    IN     VARCHAR2 DEFAULT NULL,
    P_PACKAGE_NAME   IN     VARCHAR2,
    P_PROCEDURE_NAME IN     VARCHAR2,
    P_TEMPLATE_TYPE  IN     VARCHAR2 DEFAULT 'table',
    P_ENABLED        IN     VARCHAR2 DEFAULT 'Y',
    P_DISPLAY_ORDER  IN     NUMBER DEFAULT 0
  );
  PROCEDURE UPSERT_REPORT_PARAM (
    P_ID            IN OUT NUMBER,
    P_REPORT_ID     IN     NUMBER,
    P_PARAM_CODE    IN     VARCHAR2,
    P_PARAM_NAME    IN     VARCHAR2,
    P_PARAM_TYPE    IN     VARCHAR2 DEFAULT 'string',
    P_DEFAULT_VALUE IN     VARCHAR2 DEFAULT NULL,
    P_REQUIRED      IN     VARCHAR2 DEFAULT 'N',
    P_OPTIONS_JSON  IN     VARCHAR2 DEFAULT NULL,
    P_DISPLAY_ORDER IN     NUMBER DEFAULT 0
  );
END CRED_REPORTS_PKG;
/

CREATE OR REPLACE PACKAGE BODY CRED_REPORTS_PKG AS
  PROCEDURE GET_REPORTS (P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT ID, CODE, NAME, DESCRIPTION, PACKAGE_NAME, PROCEDURE_NAME,
             TEMPLATE_TYPE, ENABLED, DISPLAY_ORDER
      FROM CRED_REPORTS
      WHERE ENABLED = 'Y'
      ORDER BY DISPLAY_ORDER, ID;
  END GET_REPORTS;

  PROCEDURE GET_REPORT_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT ID, CODE, NAME, DESCRIPTION, PACKAGE_NAME, PROCEDURE_NAME,
             TEMPLATE_TYPE, TEMPLATE_HTML, ENABLED, DISPLAY_ORDER
      FROM CRED_REPORTS WHERE ID = P_ID;
  END GET_REPORT_BY_ID;

  PROCEDURE GET_REPORT_PARAMS (P_REPORT_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT ID, REPORT_ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, DEFAULT_VALUE,
             REQUIRED, OPTIONS_JSON, DISPLAY_ORDER
      FROM CRED_REPORT_PARAMS
      WHERE REPORT_ID = P_REPORT_ID
      ORDER BY DISPLAY_ORDER, ID;
  END GET_REPORT_PARAMS;

  PROCEDURE EXECUTE_REPORT (
    P_REPORT_ID   IN  NUMBER,
    P_PARAMS_JSON IN  VARCHAR2,
    P_CUR         OUT SYS_REFCURSOR
  ) IS
    v_pkg    VARCHAR2(100);
    v_proc   VARCHAR2(100);
    v_status VARCHAR2(50);
    v_date_from DATE;
    v_date_to   DATE;
    v_bank_id   NUMBER;
    v_sql       VARCHAR2(4000);
  BEGIN
    SELECT PACKAGE_NAME, PROCEDURE_NAME INTO v_pkg, v_proc
    FROM CRED_REPORTS WHERE ID = P_REPORT_ID AND ENABLED = 'Y';

    IF v_pkg = 'CRED_REPORT_LOGIC_PKG' AND v_proc = 'REPORT_APPLICATIONS_BY_STATUS' THEN
      BEGIN
        SELECT TRIM(JSON_VALUE(P_PARAMS_JSON, '$.status')),
               TO_DATE(JSON_VALUE(P_PARAMS_JSON, '$.date_from'), 'YYYY-MM-DD'),
               TO_DATE(JSON_VALUE(P_PARAMS_JSON, '$.date_to'), 'YYYY-MM-DD')
        INTO v_status, v_date_from, v_date_to
        FROM DUAL;
      EXCEPTION WHEN OTHERS THEN
        v_status := NULL; v_date_from := NULL; v_date_to := NULL;
      END;
      CRED_REPORT_LOGIC_PKG.REPORT_APPLICATIONS_BY_STATUS(v_status, v_date_from, v_date_to, P_CUR);

    ELSIF v_pkg = 'CRED_REPORT_LOGIC_PKG' AND v_proc = 'REPORT_PROGRAMS_BY_BANK' THEN
      BEGIN
        v_bank_id := TO_NUMBER(JSON_VALUE(P_PARAMS_JSON, '$.bank_id'));
      EXCEPTION WHEN OTHERS THEN
        v_bank_id := NULL;
      END;
      CRED_REPORT_LOGIC_PKG.REPORT_PROGRAMS_BY_BANK(v_bank_id, P_CUR);

    ELSE
      RAISE_APPLICATION_ERROR(-20001, 'Unknown report: ' || v_pkg || '.' || v_proc);
    END IF;
  END EXECUTE_REPORT;

  PROCEDURE UPSERT_REPORT (
    P_ID             IN OUT NUMBER,
    P_CODE           IN     VARCHAR2,
    P_NAME           IN     VARCHAR2,
    P_DESCRIPTION    IN     VARCHAR2 DEFAULT NULL,
    P_PACKAGE_NAME   IN     VARCHAR2,
    P_PROCEDURE_NAME IN     VARCHAR2,
    P_TEMPLATE_TYPE  IN     VARCHAR2 DEFAULT 'table',
    P_ENABLED        IN     VARCHAR2 DEFAULT 'Y',
    P_DISPLAY_ORDER  IN     NUMBER DEFAULT 0
  ) IS
  BEGIN
    IF P_ID IS NULL OR P_ID = 0 THEN
      INSERT INTO CRED_REPORTS (CODE, NAME, DESCRIPTION, PACKAGE_NAME, PROCEDURE_NAME,
        TEMPLATE_TYPE, ENABLED, DISPLAY_ORDER, CREATED_AT, UPDATED_AT)
      VALUES (P_CODE, P_NAME, P_DESCRIPTION, P_PACKAGE_NAME, P_PROCEDURE_NAME,
        P_TEMPLATE_TYPE, P_ENABLED, P_DISPLAY_ORDER, SYSTIMESTAMP, SYSTIMESTAMP)
      RETURNING ID INTO P_ID;
    ELSE
      UPDATE CRED_REPORTS SET
        CODE = P_CODE, NAME = P_NAME, DESCRIPTION = P_DESCRIPTION,
        PACKAGE_NAME = P_PACKAGE_NAME, PROCEDURE_NAME = P_PROCEDURE_NAME,
        TEMPLATE_TYPE = P_TEMPLATE_TYPE, ENABLED = P_ENABLED, DISPLAY_ORDER = P_DISPLAY_ORDER,
        UPDATED_AT = SYSTIMESTAMP
      WHERE ID = P_ID;
    END IF;
  END UPSERT_REPORT;

  PROCEDURE UPSERT_REPORT_PARAM (
    P_ID            IN OUT NUMBER,
    P_REPORT_ID     IN     NUMBER,
    P_PARAM_CODE    IN     VARCHAR2,
    P_PARAM_NAME    IN     VARCHAR2,
    P_PARAM_TYPE    IN     VARCHAR2 DEFAULT 'string',
    P_DEFAULT_VALUE IN     VARCHAR2 DEFAULT NULL,
    P_REQUIRED      IN     VARCHAR2 DEFAULT 'N',
    P_OPTIONS_JSON  IN     VARCHAR2 DEFAULT NULL,
    P_DISPLAY_ORDER IN     NUMBER DEFAULT 0
  ) IS
  BEGIN
    IF P_ID IS NULL OR P_ID = 0 THEN
      INSERT INTO CRED_REPORT_PARAMS (REPORT_ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE,
        DEFAULT_VALUE, REQUIRED, OPTIONS_JSON, DISPLAY_ORDER, CREATED_AT)
      VALUES (P_REPORT_ID, P_PARAM_CODE, P_PARAM_NAME, P_PARAM_TYPE,
        P_DEFAULT_VALUE, P_REQUIRED, P_OPTIONS_JSON, P_DISPLAY_ORDER, SYSTIMESTAMP)
      RETURNING ID INTO P_ID;
    ELSE
      UPDATE CRED_REPORT_PARAMS SET
        PARAM_CODE = P_PARAM_CODE, PARAM_NAME = P_PARAM_NAME, PARAM_TYPE = P_PARAM_TYPE,
        DEFAULT_VALUE = P_DEFAULT_VALUE, REQUIRED = P_REQUIRED, OPTIONS_JSON = P_OPTIONS_JSON,
        DISPLAY_ORDER = P_DISPLAY_ORDER
      WHERE ID = P_ID;
    END IF;
  END UPSERT_REPORT_PARAM;
END CRED_REPORTS_PKG;
/

-- ============================================================
-- Демо-данные: 2 отчёта с параметрами
-- ============================================================

INSERT INTO CRED_REPORTS (CODE, NAME, DESCRIPTION, PACKAGE_NAME, PROCEDURE_NAME, TEMPLATE_TYPE, ENABLED, DISPLAY_ORDER)
VALUES ('APP_BY_STATUS', 'Заявки по статусу', 'Отчёт по заявкам с фильтром по статусу и периоду',
        'CRED_REPORT_LOGIC_PKG', 'REPORT_APPLICATIONS_BY_STATUS', 'table', 'Y', 1);

INSERT INTO CRED_REPORTS (CODE, NAME, DESCRIPTION, PACKAGE_NAME, PROCEDURE_NAME, TEMPLATE_TYPE, ENABLED, DISPLAY_ORDER)
VALUES ('PROGS_BY_BANK', 'Программы по банку', 'Отчёт по кредитным программам с количеством заявок',
        'CRED_REPORT_LOGIC_PKG', 'REPORT_PROGRAMS_BY_BANK', 'table', 'Y', 2);

-- Параметры для отчёта "Заявки по статусу"
INSERT INTO CRED_REPORT_PARAMS (REPORT_ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, DEFAULT_VALUE, REQUIRED, OPTIONS_JSON, DISPLAY_ORDER)
SELECT ID, 'status', 'Статус заявки', 'select', 'pending', 'N',
       '["pending","approved","rejected","on_review"]', 1
FROM CRED_REPORTS WHERE CODE = 'APP_BY_STATUS';

INSERT INTO CRED_REPORT_PARAMS (REPORT_ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, DEFAULT_VALUE, REQUIRED, DISPLAY_ORDER)
SELECT ID, 'date_from', 'Дата с', 'date', NULL, 'N', 2
FROM CRED_REPORTS WHERE CODE = 'APP_BY_STATUS';

INSERT INTO CRED_REPORT_PARAMS (REPORT_ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, DEFAULT_VALUE, REQUIRED, DISPLAY_ORDER)
SELECT ID, 'date_to', 'Дата по', 'date', NULL, 'N', 3
FROM CRED_REPORTS WHERE CODE = 'APP_BY_STATUS';

-- Параметры для отчёта "Программы по банку" (options: source=banks — подставляется из API)
INSERT INTO CRED_REPORT_PARAMS (REPORT_ID, PARAM_CODE, PARAM_NAME, PARAM_TYPE, DEFAULT_VALUE, REQUIRED, OPTIONS_JSON, DISPLAY_ORDER)
SELECT ID, 'bank_id', 'Банк', 'select', NULL, 'N', '{"source":"banks"}', 1
FROM CRED_REPORTS WHERE CODE = 'PROGS_BY_BANK';

COMMIT;
/
