-- ============================================================
-- Shell: основной список проектов (каждый проект — свой префикс и набор дашбордов)
-- ============================================================

CREATE SEQUENCE UNA_SHELL_PROJECTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE UNA_SHELL_PROJECTS (
  ID              NUMBER        NOT NULL,
  SLUG            VARCHAR2(64)   NOT NULL,
  NAME            VARCHAR2(256)  NOT NULL,
  DESCRIPTION     VARCHAR2(1000),
  DASHBOARD_IDS   VARCHAR2(4000),
  SORT_ORDER      NUMBER        DEFAULT 0,
  IS_ACTIVE       CHAR(1)       DEFAULT 'Y',
  CREATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_UNA_SHELL_PROJECTS PRIMARY KEY (ID),
  CONSTRAINT UK_UNA_SHELL_PROJECTS_SLUG UNIQUE (SLUG),
  CONSTRAINT CHK_UNA_SHELL_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE OR REPLACE TRIGGER UNA_SHELL_PROJECTS_BI
BEFORE INSERT ON UNA_SHELL_PROJECTS FOR EACH ROW
WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := UNA_SHELL_PROJECTS_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_UNA_SHELL_PROJECTS_ACTIVE ON UNA_SHELL_PROJECTS (IS_ACTIVE);
CREATE INDEX IX_UNA_SHELL_PROJECTS_SORT ON UNA_SHELL_PROJECTS (SORT_ORDER);
/

-- Демо-данные: проекты shell (gara, credit, nufarul и т.д.)
INSERT INTO UNA_SHELL_PROJECTS (SLUG, NAME, DESCRIPTION, DASHBOARD_IDS, SORT_ORDER, IS_ACTIVE)
VALUES ('shell', 'Shell (главная)', 'Главная оболочка приложения', '00,01', 0, 'Y');
INSERT INTO UNA_SHELL_PROJECTS (SLUG, NAME, DESCRIPTION, DASHBOARD_IDS, SORT_ORDER, IS_ACTIVE)
VALUES ('gara', 'Автовокзал', 'Табло отправлений и маршруты', '00,01,02,03', 10, 'Y');
INSERT INTO UNA_SHELL_PROJECTS (SLUG, NAME, DESCRIPTION, DASHBOARD_IDS, SORT_ORDER, IS_ACTIVE)
VALUES ('credit', 'Кредиты', 'Кредитные программы и оформление', '00,01,04,05', 20, 'Y');
INSERT INTO UNA_SHELL_PROJECTS (SLUG, NAME, DESCRIPTION, DASHBOARD_IDS, SORT_ORDER, IS_ACTIVE)
VALUES ('nufarul', 'Нуфарул', 'Проект Нуфарул', '00,01', 30, 'Y');
COMMIT;
/
