-- ============================================================
-- Nufarul: химчистка — таблицы (заказы, услуги, статусы)
-- ============================================================

CREATE SEQUENCE NUF_SERVICES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NUF_ORDER_STATUSES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NUF_ORDERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NUF_ORDER_ITEMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Справочник статусов заказа
CREATE TABLE NUF_ORDER_STATUSES (
  ID         NUMBER NOT NULL,
  CODE       VARCHAR2(30)  NOT NULL,
  NAME_RO    VARCHAR2(100) NOT NULL,
  NAME_RU    VARCHAR2(100),
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_NUF_ORDER_STATUSES PRIMARY KEY (ID),
  CONSTRAINT UQ_NUF_ORDER_STATUSES_CODE UNIQUE (CODE)
);
/
CREATE OR REPLACE TRIGGER NUF_ORDER_STATUSES_BI
  BEFORE INSERT ON NUF_ORDER_STATUSES FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := NUF_ORDER_STATUSES_SEQ.NEXTVAL; END;
/

-- Справочник услуг (химчистка одежды, ковров и т.д.)
-- SERVICE_GROUP: delivery, dry_cleaning, carpets, pillows_cleaning, laundry, leather_dyeing, conditions, silicone_pillows
CREATE TABLE NUF_SERVICES (
  ID             NUMBER NOT NULL,
  NAME           VARCHAR2(200) NOT NULL,
  NAME_RO        VARCHAR2(200),
  NAME_EN        VARCHAR2(200),
  PRICE          NUMBER NOT NULL,
  UNIT           VARCHAR2(50) DEFAULT 'buc',
  ACTIVE         CHAR(1) DEFAULT 'Y',
  NOTES          VARCHAR2(4000),
  SERVICE_GROUP  VARCHAR2(80),
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT     TIMESTAMP,
  CONSTRAINT PK_NUF_SERVICES PRIMARY KEY (ID),
  CONSTRAINT CHK_NUF_SERVICES_ACTIVE CHECK (ACTIVE IN ('Y','N'))
);
/
CREATE OR REPLACE TRIGGER NUF_SERVICES_BI
  BEFORE INSERT ON NUF_SERVICES FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := NUF_SERVICES_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_NUF_SERVICES_ACTIVE ON NUF_SERVICES (ACTIVE);
CREATE INDEX IX_NUF_SERVICES_GROUP ON NUF_SERVICES (SERVICE_GROUP);

-- Заказы
CREATE TABLE NUF_ORDERS (
  ID           NUMBER NOT NULL,
  ORDER_NUMBER  VARCHAR2(50) NOT NULL,
  BARCODE      VARCHAR2(100),
  CLIENT_NAME  VARCHAR2(200) NOT NULL,
  CLIENT_PHONE VARCHAR2(50),
  STATUS_ID    NUMBER NOT NULL,
  TOTAL_AMOUNT NUMBER DEFAULT 0,
  NOTES        VARCHAR2(4000),
  CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP,
  CREATED_BY   VARCHAR2(100),
  CONSTRAINT PK_NUF_ORDERS PRIMARY KEY (ID),
  CONSTRAINT FK_NUF_ORDERS_STATUS FOREIGN KEY (STATUS_ID) REFERENCES NUF_ORDER_STATUSES(ID),
  CONSTRAINT UQ_NUF_ORDERS_NUMBER UNIQUE (ORDER_NUMBER)
);
/
CREATE OR REPLACE TRIGGER NUF_ORDERS_BI
  BEFORE INSERT ON NUF_ORDERS FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := NUF_ORDERS_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_NUF_ORDERS_STATUS ON NUF_ORDERS (STATUS_ID);
CREATE INDEX IX_NUF_ORDERS_BARCODE ON NUF_ORDERS (BARCODE);
CREATE INDEX IX_NUF_ORDERS_CREATED ON NUF_ORDERS (CREATED_AT);

-- Позиции заказа
CREATE TABLE NUF_ORDER_ITEMS (
  ID         NUMBER NOT NULL,
  ORDER_ID   NUMBER NOT NULL,
  SERVICE_ID NUMBER NOT NULL,
  QTY        NUMBER NOT NULL,
  PRICE      NUMBER NOT NULL,
  AMOUNT     NUMBER NOT NULL,
  NOTES      VARCHAR2(500),
  CONSTRAINT PK_NUF_ORDER_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_NUF_ORDER_ITEMS_ORDER   FOREIGN KEY (ORDER_ID)   REFERENCES NUF_ORDERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_NUF_ORDER_ITEMS_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES NUF_SERVICES(ID)
);
/
CREATE OR REPLACE TRIGGER NUF_ORDER_ITEMS_BI
  BEFORE INSERT ON NUF_ORDER_ITEMS FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := NUF_ORDER_ITEMS_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_NUF_ORDER_ITEMS_ORDER ON NUF_ORDER_ITEMS (ORDER_ID);

-- Последовательность для номера заказа (год + номер)
CREATE SEQUENCE NUF_ORDER_NUM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Данные по умолчанию: статусы
INSERT INTO NUF_ORDER_STATUSES (CODE, NAME_RO, NAME_RU, SORT_ORDER) VALUES ('received', 'Primit', 'Принят', 1);
INSERT INTO NUF_ORDER_STATUSES (CODE, NAME_RO, NAME_RU, SORT_ORDER) VALUES ('in_work', 'În lucru', 'В работе', 2);
INSERT INTO NUF_ORDER_STATUSES (CODE, NAME_RO, NAME_RU, SORT_ORDER) VALUES ('ready', 'Gata', 'Готов', 3);
INSERT INTO NUF_ORDER_STATUSES (CODE, NAME_RO, NAME_RU, SORT_ORDER) VALUES ('issued', 'Emit', 'Выдан', 4);
INSERT INTO NUF_ORDER_STATUSES (CODE, NAME_RO, NAME_RU, SORT_ORDER) VALUES ('cancelled', 'Anulat', 'Отменён', 5);
COMMIT;

-- Демо-услуги
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT) VALUES ('Spălare cravată', 'Spălare cravată', 25, 'buc');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT) VALUES ('Curățare covor', 'Curățare covor', 80, 'mp');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT) VALUES ('Curățare perne', 'Curățare perne', 50, 'buc');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT) VALUES ('Înălțăminte', 'Înălțăminte', 45, 'perechi');
COMMIT;
