-- Импорт услуг Nufarul из https://nufarul.com/ru/order-online.html
-- Запуск в SQL*Plus/SQL Developer или: python import_nufarul_services.py --sql | sqlplus user/pass@db
DELETE FROM NUF_SERVICES;
COMMIT;
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Доставка по всем секторам города (Botanica, Buiucani, Centru, Râșcani, Ciocana)', 'Доставка по всем секторам города (Botanica, Buiucani, Centru, Râșcani, Ciocana)', 90, 'com', 'Y', 'de la 90 lei/com');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Доставка другие населённые пункты (Durlești, Dumbrava, Stăuceni, Codru, Aeroport и др.)', 'Доставка другие населённые пункты (Durlești, Dumbrava, Stăuceni, Codru, Aeroport и др.)', 150, 'com', 'Y', 'de la 150 lei/com');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Доставка по республике', 'Доставка по республике', 6, 'km', 'Y', 'de la 6 lei/km');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Блуза с аппликациями из кожи', 'Блуза с аппликациями из кожи', 190, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Блуза с длинным рукавом', 'Блуза с длинным рукавом', 140, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Блуза с коротким рукавом', 'Блуза с коротким рукавом', 110, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Брюки на утепленной подкладке (вкл. для лыжников)', 'Брюки на утепленной подкладке (вкл. для лыжников)', 185, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Брюки с кожаными аппликациями', 'Брюки с кожаными аппликациями', 275, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Брюки, джинсы', 'Брюки, джинсы', 135, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Вуаль', 'Вуаль', 105, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Галстук', 'Галстук', 55, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Демисезонное пальто с капюшоном', 'Демисезонное пальто с капюшоном', 330, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Демисезонное пальто без капюшона', 'Демисезонное пальто без капюшона', 300, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Жилет с капюшоном', 'Жилет с капюшоном', 120, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Жилет без капюшона', 'Жилет без капюшона', 100, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Жилет на пуху, синтепоне (демисезонное) с капюшоном', 'Жилет на пуху, синтепоне (демисезонное) с капюшоном', 235, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Жилет на пуху, синтепоне (демисезонное) без капюшона', 'Жилет на пуху, синтепоне (демисезонное) без капюшона', 195, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Жилет на пуху, синтепоне с капюшоном', 'Жилет на пуху, синтепоне с капюшоном', 270, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Жилет на пуху, синтепоне без капюшона', 'Жилет на пуху, синтепоне без капюшона', 230, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Комбинезон', 'Комбинезон', 220, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Комбинезон с подкладкой', 'Комбинезон с подкладкой', 300, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка Vindiac (ветровка), джинсовая с капюшоном', 'Куртка Vindiac (ветровка), джинсовая с капюшоном', 205, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка Vindiac (ветровка), джинсовая без капюшона', 'Куртка Vindiac (ветровка), джинсовая без капюшона', 185, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на пуху (демисезонное) с капюшоном', 'Куртка на пуху (демисезонное) с капюшоном', 295, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на пуху (демисезонное) без капюшона', 'Куртка на пуху (демисезонное) без капюшона', 265, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на пуху с капюшоном', 'Куртка на пуху с капюшоном', 340, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на пуху без капюшона', 'Куртка на пуху без капюшона', 300, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на синтепоне (демисезонное) с капюшоном', 'Куртка на синтепоне (демисезонное) с капюшоном', 260, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на синтепоне (демисезонное) без капюшона', 'Куртка на синтепоне (демисезонное) без капюшона', 230, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на утеплённой подкладке из натурального меха с капюшоном', 'Куртка на утеплённой подкладке из натурального меха с капюшоном', 330, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на утеплённой подкладке из натурального меха без капюшона', 'Куртка на утеплённой подкладке из натурального меха без капюшона', 290, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на утеплённой подкладке из синтепона с капюшоном', 'Куртка на утеплённой подкладке из синтепона с капюшоном', 325, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка на утеплённой подкладке из синтепона без капюшона', 'Куртка на утеплённой подкладке из синтепона без капюшона', 285, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка от спортивного костюма с капюшоном', 'Куртка от спортивного костюма с капюшоном', 135, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка от спортивного костюма без капюшона', 'Куртка от спортивного костюма без капюшона', 115, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Майка трикотажная', 'Майка трикотажная', 55, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Носки', 'Носки', 40, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пальто зимнее, кашемировое с капюшоном', 'Пальто зимнее, кашемировое с капюшоном', 365, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пальто зимнее, кашемировое без капюшона', 'Пальто зимнее, кашемировое без капюшона', 325, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пальто короткое зимнее, кашемировое с капюшоном', 'Пальто короткое зимнее, кашемировое с капюшоном', 340, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пальто короткое зимнее, кашемировое без капюшона', 'Пальто короткое зимнее, кашемировое без капюшона', 300, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пальто короткое на пуху, синтепоне с капюшоном', 'Пальто короткое на пуху, синтепоне с капюшоном', 340, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пальто короткое на пуху, синтепоне без капюшона', 'Пальто короткое на пуху, синтепоне без капюшона', 300, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пальто на пуху, синтепоне с капюшоном', 'Пальто на пуху, синтепоне с капюшоном', 370, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пальто на пуху, синтепоне без капюшона', 'Пальто на пуху, синтепоне без капюшона', 330, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Перчатки', 'Перчатки', 45, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пиджак', 'Пиджак', 165, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пиджак (свыше 85 см), кардиган', 'Пиджак (свыше 85 см), кардиган', 190, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пиджак из пальтовой ткани', 'Пиджак из пальтовой ткани', 205, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пижама толстая', 'Пижама толстая', 115, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пижама тонкая', 'Пижама тонкая', 100, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье простое', 'Платье простое', 170, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье сложное', 'Платье сложное', 210, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье вечернее простое', 'Платье вечернее простое', 230, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье вечернее сложное', 'Платье вечернее сложное', 250, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье длинное простое', 'Платье длинное простое', 290, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье длинное сложное', 'Платье длинное сложное', 390, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье свадебное (макс. 2 юбки)', 'Платье свадебное (макс. 2 юбки)', 480, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье свадебное (сложное, 3 юбки)', 'Платье свадебное (сложное, 3 юбки)', 600, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье свадебное (сложное, мин. 4 юбки или шлейф)', 'Платье свадебное (сложное, мин. 4 юбки или шлейф)', 885, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плащ', 'Плащ', 260, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плащ на подкладке из натурального меха', 'Плащ на подкладке из натурального меха', 315, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плащ на подкладке из синтетического меха', 'Плащ на подкладке из синтетического меха', 260, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подкладка из искусственного меха с капюшоном', 'Подкладка из искусственного меха с капюшоном', 200, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подкладка из искусственного меха без капюшона', 'Подкладка из искусственного меха без капюшона', 160, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подкладка из натурального меха с капюшоном', 'Подкладка из натурального меха с капюшоном', 305, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подкладка из натурального меха без капюшона', 'Подкладка из натурального меха без капюшона', 265, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Поло, футболка, раглан с рукавами', 'Поло, футболка, раглан с рукавами', 75, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Поло, футболка, раглан без рукавов', 'Поло, футболка, раглан без рукавов', 65, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Рубашка', 'Рубашка', 85, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Рубашка из шелка', 'Рубашка из шелка', 115, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Рубашка сложного покроя', 'Рубашка сложного покроя', 100, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Свитер, жакет, джемпер с длинным рукавом', 'Свитер, жакет, джемпер с длинным рукавом', 130, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Свитер, жакет, джемпер с коротким рукавом', 'Свитер, жакет, джемпер с коротким рукавом', 105, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Спортивный костюм', 'Спортивный костюм', 200, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Тонкая шапка, кепка, берет', 'Тонкая шапка, кепка, берет', 75, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Халат длинный с капюшоном', 'Халат длинный с капюшоном', 135, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Халат длинный без капюшона', 'Халат длинный без капюшона', 115, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Халат короткий с капюшоном', 'Халат короткий с капюшоном', 125, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Халат короткий без капюшона', 'Халат короткий без капюшона', 105, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шапка зимняя', 'Шапка зимняя', 100, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шарф, платок <1м²', 'Шарф, платок <1м²', 60, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шарф, платок >1м²', 'Шарф, платок >1м²', 90, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Юбка <70 см', 'Юбка <70 см', 120, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Юбка >70 см', 'Юбка >70 см', 130, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Юбка (плиссе, гофре, складки)', 'Юбка (плиссе, гофре, складки)', 150, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Юбка вязанная <70 см', 'Юбка вязанная <70 см', 130, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Юбка вязанная >70 см', 'Юбка вязанная >70 см', 140, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Гардино, тюлевые изделия, шторы', 'Гардино, тюлевые изделия, шторы', 27, 'mp', 'Y', 'lei/m²');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Драпировочные изделия, скатерти, дорожка, чехлы, накидка на диван', 'Драпировочные изделия, скатерти, дорожка, чехлы, накидка на диван', 50, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Изделия для спальни из длинно-петлевого полотна 2-х спальные', 'Изделия для спальни из длинно-петлевого полотна 2-х спальные', 345, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Изделия для спальни из длинно-петлевого полотна', 'Изделия для спальни из длинно-петлевого полотна', 275, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Мягкие игрушки 3-4 кг', 'Мягкие игрушки 3-4 кг', 150, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Мягкие игрушки 4-5 кг', 'Мягкие игрушки 4-5 кг', 180, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Мягкие игрушки 1.0–2.0 кг', 'Мягкие игрушки 1.0–2.0 кг', 85, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Мягкие игрушки 2-3 кг', 'Мягкие игрушки 2-3 кг', 120, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Мягкие игрушки до 1 кг', 'Мягкие игрушки до 1 кг', 40, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло 2-х спальное шерстяное, полушерстяное, синтепоновое', 'Одеяло 2-х спальное шерстяное, полушерстяное, синтепоновое', 365, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло 2-х спальное двойное', 'Одеяло 2-х спальное двойное', 320, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло 2-х спальное шерстяное, полушерстяное', 'Одеяло 2-х спальное шерстяное, полушерстяное', 300, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло 2-х спальное синтепоновое', 'Одеяло 2-х спальное синтепоновое', 260, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло пуховое', 'Одеяло пуховое', 285, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло пуховое 2-х спальное', 'Одеяло пуховое 2-х спальное', 315, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло пуховое двойное', 'Одеяло пуховое двойное', 365, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло стёганое шерстяное, полушерстяное односпальное', 'Одеяло стёганое шерстяное, полушерстяное односпальное', 245, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло стёганое синтепоновое односпальное', 'Одеяло стёганое синтепоновое односпальное', 215, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяло шерстяное, полушерстяное', 'Одеяло шерстяное, полушерстяное', 190, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плед', 'Плед', 190, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плед 2-х спальный', 'Плед 2-х спальный', 205, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плед двойной', 'Плед двойной', 310, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плед дублированный 2-х спальный', 'Плед дублированный 2-х спальный', 310, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подушка на синтепоне 50x50', 'Подушка на синтепоне 50x50', 70, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подушка на синтепоне 50x70', 'Подушка на синтепоне 50x70', 80, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Покрывало более 3 кв.м', 'Покрывало более 3 кв.м', 245, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Покрывало до 3 кв.м', 'Покрывало до 3 кв.м', 145, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Спальный мешок на пуху', 'Спальный мешок на пуху', 360, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Спальный мешок на синтепоне', 'Спальный мешок на синтепоне', 300, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Сумка, ранец', 'Сумка, ранец', 195, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Чехол для матраса из тонкой ткани', 'Чехол для матраса из тонкой ткани', 65, 'mp', 'Y', 'lei/m²');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шторы на подкладке', 'Шторы на подкладке', 37, 'mp', 'Y', 'lei/m²');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Брюки рабочая одежда', 'Брюки рабочая одежда', 110, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Бонетка, берет, бейсболка рабочая', 'Бонетка, берет, бейсболка рабочая', 45, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Комбинезон рабочая одежда', 'Комбинезон рабочая одежда', 125, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка рабочая с капюшоном', 'Куртка рабочая с капюшоном', 160, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка рабочая без капюшона', 'Куртка рабочая без капюшона', 140, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одежда священнослужителей', 'Одежда священнослужителей', 350, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плащ, плащ-накидка с капюшоном', 'Плащ, плащ-накидка с капюшоном', 200, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плащ, плащ-накидка без капюшона', 'Плащ, плащ-накидка без капюшона', 170, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Полукомбинезон', 'Полукомбинезон', 120, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Рубашка рабочая', 'Рубашка рабочая', 70, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Фартук', 'Фартук', 70, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Футболка с длинным рукавом рабочая', 'Футболка с длинным рукавом рабочая', 70, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Футболка с коротким рукавом рабочая', 'Футболка с коротким рукавом рабочая', 55, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Халат рабочий', 'Халат рабочий', 95, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Брюки рабочие утеплённые', 'Брюки рабочие утеплённые', 120, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Комбинезон рабочий утепленный', 'Комбинезон рабочий утепленный', 215, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка длинная рабочая с капюшоном', 'Куртка длинная рабочая с капюшоном', 250, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка длинная рабочая без капюшона', 'Куртка длинная рабочая без капюшона', 220, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Брюки кожа', 'Брюки кожа', 400, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Воротник (волк, норка)', 'Воротник (волк, норка)', 145, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Дублёнка 60-90 см', 'Дублёнка 60-90 см', 565, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Дублёнка <60 см', 'Дублёнка <60 см', 530, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Дублёнка свыше 90 см', 'Дублёнка свыше 90 см', 615, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Жилет кожа', 'Жилет кожа', 265, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Кепи кожа', 'Кепи кожа', 120, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка кожа', 'Куртка кожа', 555, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пальто кожа', 'Пальто кожа', 615, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Перчатки кожа', 'Перчатки кожа', 110, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пиджак кожа', 'Пиджак кожа', 470, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Платье кожа', 'Платье кожа', 460, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Полушубок (волк, норка)', 'Полушубок (волк, норка)', 525, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Рубашка кожа', 'Рубашка кожа', 435, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шапка кожа', 'Шапка кожа', 110, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шуба (волк, норка)', 'Шуба (волк, норка)', 675, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шуба (кролик, собака, нутрия, каракуль)', 'Шуба (кролик, собака, нутрия, каракуль)', 525, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шуба (кролик, собака, нутрия, каракуль) 2', 'Шуба (кролик, собака, нутрия, каракуль) 2', 445, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Юбка кожа', 'Юбка кожа', 300, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Дублёнка искусственная до 90 см', 'Дублёнка искусственная до 90 см', 295, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Дублёнка искусственная свыше 90 см', 'Дублёнка искусственная свыше 90 см', 350, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шапка искусственная кожа', 'Шапка искусственная кожа', 90, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Шуба искусственная', 'Шуба искусственная', 315, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Ботики кожа', 'Ботики кожа', 170, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Ботики текстиль', 'Ботики текстиль', 110, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Полусапожки кожа', 'Полусапожки кожа', 210, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Полусапожки текстиль', 'Полусапожки текстиль', 150, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Сапожки кожа', 'Сапожки кожа', 290, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Сапожки текстиль', 'Сапожки текстиль', 210, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Туфли, мокасины, кроссовки кожаные', 'Туфли, мокасины, кроссовки кожаные', 170, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Туфли, мокасины, кроссовки текстиль', 'Туфли, мокасины, кроссовки текстиль', 110, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Антимолевая обработка ковров', 'Антимолевая обработка ковров', 20, 'mp', 'Y', 'lei/m²');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Ковры грязезащитные', 'Ковры грязезащитные', 60, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Ковры ручной работы или сильно загрязненные', 'Ковры ручной работы или сильно загрязненные', 50, 'mp', 'Y', 'lei/m²');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Ковры, паласы >6м и площадь >24 кв.м', 'Ковры, паласы >6м и площадь >24 кв.м', 55, 'mp', 'Y', 'lei/m²');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Ковры, паласы толщина <10 мм', 'Ковры, паласы толщина <10 мм', 40, 'mp', 'Y', 'lei/m²');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Ковры, паласы толщина >10 мм', 'Ковры, паласы толщина >10 мм', 45, 'mp', 'Y', 'lei/m²');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Упаковка ковров', 'Упаковка ковров', 20, 'buc', 'Y', 'lei/ковер');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Изменение размеров наперника или изготовление из ткани клиента', 'Изменение размеров наперника или изготовление из ткани клиента', 12, 'buc', 'Y', 'lei/шт');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Наперник 40x40', 'Наперник 40x40', 45, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Наперник 40x60', 'Наперник 40x60', 55, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Наперник 50x50', 'Наперник 50x50', 60, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Наперник 50x70', 'Наперник 50x70', 80, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Наперник 60x60', 'Наперник 60x60', 80, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Наперник 70x70', 'Наперник 70x70', 85, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Наперник 80x80', 'Наперник 80x80', 100, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Чистка пера', 'Чистка пера', 14, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Гардино, тюлевые изделия, шторы стирка без глажения', 'Гардино, тюлевые изделия, шторы стирка без глажения', 45, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Глажение белья после стирки', 'Глажение белья после стирки', 30, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Крахмаление', 'Крахмаление', 5, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Одеяла, толстые покрывала стирка', 'Одеяла, толстые покрывала стирка', 45, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Плед стирка', 'Плед стирка', 100, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Постельное и фасонное белье', 'Постельное и фасонное белье', 33, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Рабочая одежда стирка без глажения', 'Рабочая одежда стирка без глажения', 45, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Стирка комбинированная с химчисткой', 'Стирка комбинированная с химчисткой', 100, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Столовое белье салфетки', 'Столовое белье салфетки', 40, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Столовое белье скатерти', 'Столовое белье скатерти', 38, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Тонкие ковры стирка', 'Тонкие ковры стирка', 45, 'kg', 'Y', 'lei/kg');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Брюки крашение кожа', 'Брюки крашение кожа', 525, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Дублёнка крашение до 60 см', 'Дублёнка крашение до 60 см', 735, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Жилет крашение кожа', 'Жилет крашение кожа', 340, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Кепи крашение', 'Кепи крашение', 140, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Куртка крашение кожа', 'Куртка крашение кожа', 735, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Перчатки крашение', 'Перчатки крашение', 150, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Пиджак крашение кожа', 'Пиджак крашение кожа', 595, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Ремень крашение', 'Ремень крашение', 110, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Рубашка крашение кожа', 'Рубашка крашение кожа', 525, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Сандали, шлепанцы крашение', 'Сандали, шлепанцы крашение', 130, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Сапоги высокие крашение', 'Сапоги высокие крашение', 270, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Сумка, клач крашение', 'Сумка, клач крашение', 220, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Туфли, кеды, мокасины, кроссовки крашение', 'Туфли, кеды, мокасины, кроссовки крашение', 205, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Юбка крашение кожа', 'Юбка крашение кожа', 430, 'buc', 'Y', NULL);
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подушка силикон 40x40 см', 'Подушка силикон 40x40 см', 105, 'buc', 'Y', 'по предв. заказу');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подушка силикон 40x60 см', 'Подушка силикон 40x60 см', 116, 'buc', 'Y', 'по предв. заказу');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подушка силикон 50x50 см', 'Подушка силикон 50x50 см', 126, 'buc', 'Y', 'по предв. заказу');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подушка силикон 50x70 см', 'Подушка силикон 50x70 см', 180, 'buc', 'Y', 'по предв. заказу');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подушка силикон 60x60 см', 'Подушка силикон 60x60 см', 171, 'buc', 'Y', 'по предв. заказу');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подушка силикон 70x70 см', 'Подушка силикон 70x70 см', 219, 'buc', 'Y', 'по предв. заказу');
INSERT INTO NUF_SERVICES (NAME, NAME_RO, PRICE, UNIT, ACTIVE, NOTES) VALUES ('Подушка силикон 80x80 см', 'Подушка силикон 80x80 см', 251, 'buc', 'Y', 'по предв. заказу');
COMMIT;
