-- ============================================================
-- Nufarul: фотографии к заказам и позициям (BLOB)
-- ============================================================

CREATE SEQUENCE NUF_ORDER_PHOTOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE NUF_ORDER_PHOTOS (
  ID           NUMBER        NOT NULL,
  ORDER_ID     NUMBER        NOT NULL,
  ITEM_ID      NUMBER,                            -- NULL = фото заказа, NOT NULL = фото позиции
  PHOTO_BLOB   BLOB          NOT NULL,
  PHOTO_MIME   VARCHAR2(50)  DEFAULT 'image/jpeg',
  PHOTO_SIZE   NUMBER,                            -- размер в байтах
  PHOTO_NAME   VARCHAR2(200),                     -- имя файла
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_NUF_ORDER_PHOTOS PRIMARY KEY (ID),
  CONSTRAINT FK_NUF_OP_ORDER FOREIGN KEY (ORDER_ID) REFERENCES NUF_ORDERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_NUF_OP_ITEM  FOREIGN KEY (ITEM_ID)  REFERENCES NUF_ORDER_ITEMS(ID) ON DELETE CASCADE
);
/
CREATE OR REPLACE TRIGGER NUF_ORDER_PHOTOS_BI
  BEFORE INSERT ON NUF_ORDER_PHOTOS FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN :NEW.ID := NUF_ORDER_PHOTOS_SEQ.NEXTVAL; END;
/

CREATE INDEX IX_NUF_ORDER_PHOTOS_ORDER ON NUF_ORDER_PHOTOS (ORDER_ID);
CREATE INDEX IX_NUF_ORDER_PHOTOS_ITEM  ON NUF_ORDER_PHOTOS (ITEM_ID);
