-- ============================================================
-- DIGI Marketing: таблицы, последовательности, индексы, триггеры
-- Централизованное управление мультимедийным контентом для весов
-- DIGI SM5300/SM6000 и касс WEB3110
-- ============================================================

-- Последовательности
CREATE SEQUENCE DIGI_STORES_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_DEPARTMENTS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_DEVICES_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_MEDIA_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_PLAYLISTS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_PL_ITEMS_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_CAMPAIGNS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_CAMP_TARGETS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_SYNC_LOG_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_EVENT_LOG_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_MEDIA_TAGS_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIGI_MEDIA_RES_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;

-- ==================== Справочники ====================

-- Типы отделов
CREATE TABLE DIGI_REF_DEPT_TYPES (
  CODE       VARCHAR2(30)  NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_DIGI_REF_DEPT_TYPES PRIMARY KEY (CODE)
);

-- Типы устройств
CREATE TABLE DIGI_REF_DEVICE_TYPES (
  CODE       VARCHAR2(30)  NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_DIGI_REF_DEVICE_TYPES PRIMARY KEY (CODE)
);

-- Допустимые разрешения экрана
CREATE TABLE DIGI_REF_RESOLUTIONS (
  CODE       VARCHAR2(20)  NOT NULL,
  WIDTH      NUMBER        NOT NULL,
  HEIGHT     NUMBER        NOT NULL,
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_DIGI_REF_RESOLUTIONS PRIMARY KEY (CODE)
);

-- Какие разрешения поддерживает какой тип устройства
CREATE TABLE DIGI_REF_DEVICE_RESOLUTIONS (
  DEVICE_TYPE_CODE VARCHAR2(30) NOT NULL,
  RESOLUTION_CODE  VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_DIGI_DEV_RES PRIMARY KEY (DEVICE_TYPE_CODE, RESOLUTION_CODE),
  CONSTRAINT FK_DIGI_DR_DTYPE FOREIGN KEY (DEVICE_TYPE_CODE) REFERENCES DIGI_REF_DEVICE_TYPES(CODE),
  CONSTRAINT FK_DIGI_DR_RES   FOREIGN KEY (RESOLUTION_CODE) REFERENCES DIGI_REF_RESOLUTIONS(CODE)
);

-- Роли RBAC
CREATE TABLE DIGI_REF_ROLES (
  CODE        VARCHAR2(30)   NOT NULL,
  NAME        VARCHAR2(100)  NOT NULL,
  PERMISSIONS VARCHAR2(1000),
  CONSTRAINT PK_DIGI_REF_ROLES PRIMARY KEY (CODE)
);

-- ==================== Основные таблицы ====================

-- Магазины
CREATE TABLE DIGI_STORES (
  ID         NUMBER        NOT NULL,
  NAME       VARCHAR2(200) NOT NULL,
  ADDRESS    VARCHAR2(500),
  REGION     VARCHAR2(100),
  TIMEZONE   VARCHAR2(50)  DEFAULT 'Europe/Chisinau',
  STATUS     VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_DIGI_STORES PRIMARY KEY (ID),
  CONSTRAINT CHK_DIGI_STORE_STATUS CHECK (STATUS IN ('active','inactive'))
);
/
CREATE OR REPLACE TRIGGER DIGI_STORES_BI
  BEFORE INSERT ON DIGI_STORES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_STORES_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER DIGI_STORES_BU
  BEFORE UPDATE ON DIGI_STORES FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Отделы магазинов
CREATE TABLE DIGI_DEPARTMENTS (
  ID         NUMBER        NOT NULL,
  STORE_ID   NUMBER        NOT NULL,
  DEPT_TYPE  VARCHAR2(30)  NOT NULL,
  NAME       VARCHAR2(200) NOT NULL,
  STATUS     VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_DIGI_DEPARTMENTS PRIMARY KEY (ID),
  CONSTRAINT FK_DIGI_DEPT_STORE FOREIGN KEY (STORE_ID) REFERENCES DIGI_STORES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_DIGI_DEPT_TYPE  FOREIGN KEY (DEPT_TYPE) REFERENCES DIGI_REF_DEPT_TYPES(CODE),
  CONSTRAINT CHK_DIGI_DEPT_STATUS CHECK (STATUS IN ('active','inactive'))
);
/
CREATE OR REPLACE TRIGGER DIGI_DEPARTMENTS_BI
  BEFORE INSERT ON DIGI_DEPARTMENTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_DEPARTMENTS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_DIGI_DEPT_STORE ON DIGI_DEPARTMENTS (STORE_ID);
CREATE INDEX IX_DIGI_DEPT_TYPE  ON DIGI_DEPARTMENTS (DEPT_TYPE);

-- Устройства (весы, кассы)
CREATE TABLE DIGI_DEVICES (
  ID               NUMBER        NOT NULL,
  SERIAL_NUMBER    VARCHAR2(50)  NOT NULL,
  NAME             VARCHAR2(200) NOT NULL,
  DEVICE_TYPE      VARCHAR2(30)  NOT NULL,
  RESOLUTION       VARCHAR2(20)  NOT NULL,
  STORE_ID         NUMBER        NOT NULL,
  DEPARTMENT_ID    NUMBER,
  IP_ADDRESS       VARCHAR2(45),
  STATUS           VARCHAR2(20)  DEFAULT 'online',
  LAST_SYNC        TIMESTAMP,
  FIRMWARE_VERSION VARCHAR2(30),
  MEMORY_TOTAL_MB  NUMBER        DEFAULT 512,
  MEMORY_USED_MB   NUMBER        DEFAULT 0,
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_DIGI_DEVICES PRIMARY KEY (ID),
  CONSTRAINT FK_DIGI_DEV_STORE  FOREIGN KEY (STORE_ID) REFERENCES DIGI_STORES(ID),
  CONSTRAINT FK_DIGI_DEV_DEPT   FOREIGN KEY (DEPARTMENT_ID) REFERENCES DIGI_DEPARTMENTS(ID) ON DELETE SET NULL,
  CONSTRAINT FK_DIGI_DEV_DTYPE  FOREIGN KEY (DEVICE_TYPE) REFERENCES DIGI_REF_DEVICE_TYPES(CODE),
  CONSTRAINT FK_DIGI_DEV_RES    FOREIGN KEY (RESOLUTION) REFERENCES DIGI_REF_RESOLUTIONS(CODE),
  CONSTRAINT UQ_DIGI_DEV_SERIAL UNIQUE (SERIAL_NUMBER),
  CONSTRAINT CHK_DIGI_DEV_STATUS CHECK (STATUS IN ('online','offline','error','maintenance'))
);
/
CREATE OR REPLACE TRIGGER DIGI_DEVICES_BI
  BEFORE INSERT ON DIGI_DEVICES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_DEVICES_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER DIGI_DEVICES_BU
  BEFORE UPDATE ON DIGI_DEVICES FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE INDEX IX_DIGI_DEV_STORE  ON DIGI_DEVICES (STORE_ID);
CREATE INDEX IX_DIGI_DEV_DEPT   ON DIGI_DEVICES (DEPARTMENT_ID);
CREATE INDEX IX_DIGI_DEV_STATUS ON DIGI_DEVICES (STATUS);

-- Медиа-контент
CREATE TABLE DIGI_MEDIA (
  ID               NUMBER        NOT NULL,
  FILENAME         VARCHAR2(500) NOT NULL,
  ORIGINAL_NAME    VARCHAR2(500),
  MEDIA_TYPE       VARCHAR2(10)  NOT NULL,
  FORMAT           VARCHAR2(10)  NOT NULL,
  SIZE_BYTES       NUMBER        DEFAULT 0,
  DESCRIPTION      VARCHAR2(2000),
  DURATION_SECONDS NUMBER        DEFAULT 0,
  WIDTH            NUMBER        DEFAULT 0,
  HEIGHT           NUMBER        DEFAULT 0,
  STATUS           VARCHAR2(20)  DEFAULT 'ready',
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CREATED_BY       VARCHAR2(100),
  CONSTRAINT PK_DIGI_MEDIA PRIMARY KEY (ID),
  CONSTRAINT CHK_DIGI_MEDIA_TYPE CHECK (MEDIA_TYPE IN ('image','video')),
  CONSTRAINT CHK_DIGI_MEDIA_STATUS CHECK (STATUS IN ('ready','processing','error'))
);
/
CREATE OR REPLACE TRIGGER DIGI_MEDIA_BI
  BEFORE INSERT ON DIGI_MEDIA FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_MEDIA_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_DIGI_MEDIA_TYPE ON DIGI_MEDIA (MEDIA_TYPE);

-- Теги медиа-контента (many-to-many через строку TAG)
CREATE TABLE DIGI_MEDIA_TAGS (
  ID       NUMBER        NOT NULL,
  MEDIA_ID NUMBER        NOT NULL,
  TAG      VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_DIGI_MEDIA_TAGS PRIMARY KEY (ID),
  CONSTRAINT FK_DIGI_MTAG_MEDIA FOREIGN KEY (MEDIA_ID) REFERENCES DIGI_MEDIA(ID) ON DELETE CASCADE,
  CONSTRAINT UQ_DIGI_MTAG UNIQUE (MEDIA_ID, TAG)
);
/
CREATE OR REPLACE TRIGGER DIGI_MEDIA_TAGS_BI
  BEFORE INSERT ON DIGI_MEDIA_TAGS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_MEDIA_TAGS_SEQ.NEXTVAL;
END;
/

-- Разрешения, для которых адаптирован медиа-файл
CREATE TABLE DIGI_MEDIA_RESOLUTIONS (
  ID              NUMBER       NOT NULL,
  MEDIA_ID        NUMBER       NOT NULL,
  RESOLUTION_CODE VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_DIGI_MEDIA_RES PRIMARY KEY (ID),
  CONSTRAINT FK_DIGI_MRES_MEDIA FOREIGN KEY (MEDIA_ID) REFERENCES DIGI_MEDIA(ID) ON DELETE CASCADE,
  CONSTRAINT FK_DIGI_MRES_RES   FOREIGN KEY (RESOLUTION_CODE) REFERENCES DIGI_REF_RESOLUTIONS(CODE),
  CONSTRAINT UQ_DIGI_MRES UNIQUE (MEDIA_ID, RESOLUTION_CODE)
);
/
CREATE OR REPLACE TRIGGER DIGI_MEDIA_RES_BI
  BEFORE INSERT ON DIGI_MEDIA_RESOLUTIONS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_MEDIA_RES_SEQ.NEXTVAL;
END;
/

-- Плейлисты
CREATE TABLE DIGI_PLAYLISTS (
  ID             NUMBER        NOT NULL,
  NAME           VARCHAR2(200) NOT NULL,
  DESCRIPTION    VARCHAR2(2000),
  TOTAL_DURATION NUMBER        DEFAULT 0,
  STATUS         VARCHAR2(20)  DEFAULT 'draft',
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CREATED_BY     VARCHAR2(100),
  CONSTRAINT PK_DIGI_PLAYLISTS PRIMARY KEY (ID),
  CONSTRAINT CHK_DIGI_PL_STATUS CHECK (STATUS IN ('draft','active','archived'))
);
/
CREATE OR REPLACE TRIGGER DIGI_PLAYLISTS_BI
  BEFORE INSERT ON DIGI_PLAYLISTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_PLAYLISTS_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER DIGI_PLAYLISTS_BU
  BEFORE UPDATE ON DIGI_PLAYLISTS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Элементы плейлиста (порядок воспроизведения)
CREATE TABLE DIGI_PLAYLIST_ITEMS (
  ID          NUMBER NOT NULL,
  PLAYLIST_ID NUMBER NOT NULL,
  MEDIA_ID    NUMBER NOT NULL,
  DURATION    NUMBER DEFAULT 5,
  SORT_ORDER  NUMBER DEFAULT 0,
  CONSTRAINT PK_DIGI_PL_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_DIGI_PLI_PL    FOREIGN KEY (PLAYLIST_ID) REFERENCES DIGI_PLAYLISTS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_DIGI_PLI_MEDIA FOREIGN KEY (MEDIA_ID)    REFERENCES DIGI_MEDIA(ID)
);
/
CREATE OR REPLACE TRIGGER DIGI_PL_ITEMS_BI
  BEFORE INSERT ON DIGI_PLAYLIST_ITEMS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_PL_ITEMS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_DIGI_PLI_PL ON DIGI_PLAYLIST_ITEMS (PLAYLIST_ID);

-- Кампании
CREATE TABLE DIGI_CAMPAIGNS (
  ID              NUMBER        NOT NULL,
  NAME            VARCHAR2(200) NOT NULL,
  DESCRIPTION     VARCHAR2(2000),
  PLAYLIST_ID     NUMBER,
  PRIORITY        NUMBER        DEFAULT 5,
  STATUS          VARCHAR2(20)  DEFAULT 'draft',
  DELIVERY_STATUS VARCHAR2(20)  DEFAULT 'pending',
  DEVICES_TOTAL   NUMBER        DEFAULT 0,
  DEVICES_SYNCED  NUMBER        DEFAULT 0,
  -- Расписание (хранится в колонках)
  SCHEDULE_START  DATE,
  SCHEDULE_END    DATE,
  SCHEDULE_TIME_FROM VARCHAR2(5),
  SCHEDULE_TIME_TO   VARCHAR2(5),
  SCHEDULE_DAYS      VARCHAR2(20),
  PUBLISHED_AT    TIMESTAMP,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CREATED_BY      VARCHAR2(100),
  CONSTRAINT PK_DIGI_CAMPAIGNS PRIMARY KEY (ID),
  CONSTRAINT FK_DIGI_CAMP_PL FOREIGN KEY (PLAYLIST_ID) REFERENCES DIGI_PLAYLISTS(ID),
  CONSTRAINT CHK_DIGI_CAMP_STATUS CHECK (STATUS IN ('draft','active','paused','stopped')),
  CONSTRAINT CHK_DIGI_CAMP_DELIVERY CHECK (DELIVERY_STATUS IN ('pending','delivering','completed','stopped','error'))
);
/
CREATE OR REPLACE TRIGGER DIGI_CAMPAIGNS_BI
  BEFORE INSERT ON DIGI_CAMPAIGNS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_CAMPAIGNS_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER DIGI_CAMPAIGNS_BU
  BEFORE UPDATE ON DIGI_CAMPAIGNS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE INDEX IX_DIGI_CAMP_STATUS ON DIGI_CAMPAIGNS (STATUS);
CREATE INDEX IX_DIGI_CAMP_PL     ON DIGI_CAMPAIGNS (PLAYLIST_ID);

-- Таргетинг кампании (какие магазины/отделы/устройства)
CREATE TABLE DIGI_CAMPAIGN_TARGETS (
  ID          NUMBER       NOT NULL,
  CAMPAIGN_ID NUMBER       NOT NULL,
  TARGET_TYPE VARCHAR2(20) NOT NULL,
  TARGET_ID   NUMBER       NOT NULL,
  CONSTRAINT PK_DIGI_CAMP_TARGETS PRIMARY KEY (ID),
  CONSTRAINT FK_DIGI_CT_CAMP FOREIGN KEY (CAMPAIGN_ID) REFERENCES DIGI_CAMPAIGNS(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_DIGI_CT_TYPE CHECK (TARGET_TYPE IN ('store','department','device'))
);
/
CREATE OR REPLACE TRIGGER DIGI_CAMP_TARGETS_BI
  BEFORE INSERT ON DIGI_CAMPAIGN_TARGETS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_CAMP_TARGETS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_DIGI_CT_CAMP ON DIGI_CAMPAIGN_TARGETS (CAMPAIGN_ID);

-- Лог синхронизации (доставка контента на устройства)
CREATE TABLE DIGI_SYNC_LOG (
  ID          NUMBER       NOT NULL,
  CAMPAIGN_ID NUMBER       NOT NULL,
  DEVICE_ID   NUMBER       NOT NULL,
  STATUS      VARCHAR2(20) DEFAULT 'delivered',
  CREATED_AT  TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_DIGI_SYNC_LOG PRIMARY KEY (ID),
  CONSTRAINT FK_DIGI_SL_CAMP FOREIGN KEY (CAMPAIGN_ID) REFERENCES DIGI_CAMPAIGNS(ID),
  CONSTRAINT FK_DIGI_SL_DEV  FOREIGN KEY (DEVICE_ID)   REFERENCES DIGI_DEVICES(ID)
);
/
CREATE OR REPLACE TRIGGER DIGI_SYNC_LOG_BI
  BEFORE INSERT ON DIGI_SYNC_LOG FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_SYNC_LOG_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_DIGI_SL_CAMP ON DIGI_SYNC_LOG (CAMPAIGN_ID);
CREATE INDEX IX_DIGI_SL_DEV  ON DIGI_SYNC_LOG (DEVICE_ID);

-- Лог событий (аудит)
CREATE TABLE DIGI_EVENT_LOG (
  ID          NUMBER         NOT NULL,
  ACTION      VARCHAR2(30)   NOT NULL,
  ENTITY_TYPE VARCHAR2(30)   NOT NULL,
  ENTITY_ID   NUMBER,
  DETAILS     VARCHAR2(2000),
  USERNAME    VARCHAR2(100),
  CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_DIGI_EVENT_LOG PRIMARY KEY (ID)
);
/
CREATE OR REPLACE TRIGGER DIGI_EVENT_LOG_BI
  BEFORE INSERT ON DIGI_EVENT_LOG FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := DIGI_EVENT_LOG_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_DIGI_EL_ENTITY ON DIGI_EVENT_LOG (ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IX_DIGI_EL_DATE   ON DIGI_EVENT_LOG (CREATED_AT DESC);
