-- ============================================================
-- DIGI Marketing: представления (Views)
-- ============================================================

-- Устройства с названиями магазина и отдела
CREATE OR REPLACE VIEW V_DIGI_DEVICES AS
SELECT
  d.ID,
  d.SERIAL_NUMBER,
  d.NAME,
  d.DEVICE_TYPE,
  d.RESOLUTION,
  d.STORE_ID,
  s.NAME AS STORE_NAME,
  d.DEPARTMENT_ID,
  NVL(dp.NAME, '-') AS DEPARTMENT_NAME,
  d.IP_ADDRESS,
  d.STATUS,
  d.LAST_SYNC,
  d.FIRMWARE_VERSION,
  d.MEMORY_TOTAL_MB,
  d.MEMORY_USED_MB,
  d.CREATED_AT,
  d.UPDATED_AT
FROM DIGI_DEVICES d
JOIN DIGI_STORES s ON s.ID = d.STORE_ID
LEFT JOIN DIGI_DEPARTMENTS dp ON dp.ID = d.DEPARTMENT_ID;

-- Отделы с названием магазина
CREATE OR REPLACE VIEW V_DIGI_DEPARTMENTS AS
SELECT
  dp.ID,
  dp.STORE_ID,
  s.NAME AS STORE_NAME,
  dp.DEPT_TYPE,
  rt.NAME AS DEPT_TYPE_NAME,
  dp.NAME,
  dp.STATUS,
  dp.CREATED_AT
FROM DIGI_DEPARTMENTS dp
JOIN DIGI_STORES s ON s.ID = dp.STORE_ID
JOIN DIGI_REF_DEPT_TYPES rt ON rt.CODE = dp.DEPT_TYPE;

-- Медиа с тегами (агрегация через LISTAGG)
CREATE OR REPLACE VIEW V_DIGI_MEDIA AS
SELECT
  m.ID,
  m.FILENAME,
  m.ORIGINAL_NAME,
  m.MEDIA_TYPE,
  m.FORMAT,
  m.SIZE_BYTES,
  m.DESCRIPTION,
  m.DURATION_SECONDS,
  m.WIDTH,
  m.HEIGHT,
  m.STATUS,
  m.CREATED_AT,
  m.CREATED_BY,
  (SELECT LISTAGG(t.TAG, ',') WITHIN GROUP (ORDER BY t.TAG)
     FROM DIGI_MEDIA_TAGS t WHERE t.MEDIA_ID = m.ID) AS TAGS,
  (SELECT LISTAGG(r.RESOLUTION_CODE, ',') WITHIN GROUP (ORDER BY r.RESOLUTION_CODE)
     FROM DIGI_MEDIA_RESOLUTIONS r WHERE r.MEDIA_ID = m.ID) AS RESOLUTIONS
FROM DIGI_MEDIA m;

-- Плейлисты с количеством элементов
CREATE OR REPLACE VIEW V_DIGI_PLAYLISTS AS
SELECT
  p.ID,
  p.NAME,
  p.DESCRIPTION,
  p.TOTAL_DURATION,
  p.STATUS,
  p.CREATED_AT,
  p.UPDATED_AT,
  p.CREATED_BY,
  (SELECT COUNT(*) FROM DIGI_PLAYLIST_ITEMS pi WHERE pi.PLAYLIST_ID = p.ID) AS ITEM_COUNT
FROM DIGI_PLAYLISTS p;

-- Элементы плейлиста с данными о медиа
CREATE OR REPLACE VIEW V_DIGI_PLAYLIST_ITEMS AS
SELECT
  pi.ID,
  pi.PLAYLIST_ID,
  pi.MEDIA_ID,
  pi.DURATION,
  pi.SORT_ORDER,
  m.FILENAME,
  m.ORIGINAL_NAME,
  m.MEDIA_TYPE,
  m.FORMAT
FROM DIGI_PLAYLIST_ITEMS pi
JOIN DIGI_MEDIA m ON m.ID = pi.MEDIA_ID
ORDER BY pi.PLAYLIST_ID, pi.SORT_ORDER;

-- Кампании с названием плейлиста и таргетингом
CREATE OR REPLACE VIEW V_DIGI_CAMPAIGNS AS
SELECT
  c.ID,
  c.NAME,
  c.DESCRIPTION,
  c.PLAYLIST_ID,
  NVL(p.NAME, '-') AS PLAYLIST_NAME,
  c.PRIORITY,
  c.STATUS,
  c.DELIVERY_STATUS,
  c.DEVICES_TOTAL,
  c.DEVICES_SYNCED,
  c.SCHEDULE_START,
  c.SCHEDULE_END,
  c.SCHEDULE_TIME_FROM,
  c.SCHEDULE_TIME_TO,
  c.SCHEDULE_DAYS,
  c.PUBLISHED_AT,
  c.CREATED_AT,
  c.UPDATED_AT,
  c.CREATED_BY,
  -- Определяем тип таргетинга
  CASE
    WHEN NOT EXISTS (SELECT 1 FROM DIGI_CAMPAIGN_TARGETS t WHERE t.CAMPAIGN_ID = c.ID) THEN 'all'
    ELSE (SELECT MIN(t.TARGET_TYPE) FROM DIGI_CAMPAIGN_TARGETS t WHERE t.CAMPAIGN_ID = c.ID)
  END AS TARGET_TYPE,
  -- Сводка таргетинга
  CASE
    WHEN NOT EXISTS (SELECT 1 FROM DIGI_CAMPAIGN_TARGETS t WHERE t.CAMPAIGN_ID = c.ID) THEN 'Все магазины'
    ELSE (
      SELECT LISTAGG(
        CASE t.TARGET_TYPE
          WHEN 'store'      THEN (SELECT s.NAME FROM DIGI_STORES s WHERE s.ID = t.TARGET_ID)
          WHEN 'department'  THEN (SELECT dp.NAME FROM DIGI_DEPARTMENTS dp WHERE dp.ID = t.TARGET_ID)
          WHEN 'device'     THEN (SELECT dv.NAME FROM DIGI_DEVICES dv WHERE dv.ID = t.TARGET_ID)
        END, ', '
      ) WITHIN GROUP (ORDER BY t.TARGET_ID)
      FROM DIGI_CAMPAIGN_TARGETS t WHERE t.CAMPAIGN_ID = c.ID
    )
  END AS TARGET_SUMMARY
FROM DIGI_CAMPAIGNS c
LEFT JOIN DIGI_PLAYLISTS p ON p.ID = c.PLAYLIST_ID;

-- Лог синхронизации с именами
CREATE OR REPLACE VIEW V_DIGI_SYNC_LOG AS
SELECT
  sl.ID,
  sl.CAMPAIGN_ID,
  c.NAME AS CAMPAIGN_NAME,
  sl.DEVICE_ID,
  d.NAME AS DEVICE_NAME,
  sl.STATUS,
  sl.CREATED_AT
FROM DIGI_SYNC_LOG sl
JOIN DIGI_CAMPAIGNS c ON c.ID = sl.CAMPAIGN_ID
JOIN DIGI_DEVICES d   ON d.ID = sl.DEVICE_ID
ORDER BY sl.CREATED_AT DESC;

-- Сводная статистика дашборда
CREATE OR REPLACE VIEW V_DIGI_DASHBOARD_STATS AS
SELECT
  (SELECT COUNT(*) FROM DIGI_STORES)    AS TOTAL_STORES,
  (SELECT COUNT(*) FROM DIGI_DEVICES)   AS TOTAL_DEVICES,
  (SELECT COUNT(*) FROM DIGI_DEVICES WHERE STATUS = 'online')  AS ONLINE_DEVICES,
  (SELECT COUNT(*) FROM DIGI_DEVICES WHERE STATUS = 'offline') AS OFFLINE_DEVICES,
  (SELECT COUNT(*) FROM DIGI_DEVICES WHERE STATUS = 'error')   AS ERROR_DEVICES,
  (SELECT COUNT(*) FROM DIGI_CAMPAIGNS) AS TOTAL_CAMPAIGNS,
  (SELECT COUNT(*) FROM DIGI_CAMPAIGNS WHERE STATUS = 'active')  AS ACTIVE_CAMPAIGNS,
  (SELECT COUNT(*) FROM DIGI_CAMPAIGNS WHERE STATUS = 'draft')   AS DRAFT_CAMPAIGNS,
  (SELECT COUNT(*) FROM DIGI_CAMPAIGNS WHERE STATUS = 'paused')  AS PAUSED_CAMPAIGNS,
  (SELECT COUNT(*) FROM DIGI_CAMPAIGNS WHERE STATUS = 'stopped') AS STOPPED_CAMPAIGNS,
  (SELECT COUNT(*) FROM DIGI_MEDIA)     AS TOTAL_MEDIA,
  (SELECT COUNT(*) FROM DIGI_MEDIA WHERE MEDIA_TYPE = 'image') AS IMAGE_MEDIA,
  (SELECT COUNT(*) FROM DIGI_MEDIA WHERE MEDIA_TYPE = 'video') AS VIDEO_MEDIA,
  (SELECT COUNT(*) FROM DIGI_PLAYLISTS) AS TOTAL_PLAYLISTS
FROM DUAL;
