-- ============================================================
-- DIGI Marketing: пакет DIGI_MARKETING_PKG
-- ============================================================

CREATE OR REPLACE PACKAGE DIGI_MARKETING_PKG AS

  -- ===== Магазины =====
  PROCEDURE GET_STORES (P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_STORE_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE UPSERT_STORE (
    P_ID       IN OUT NUMBER,
    P_NAME     IN VARCHAR2,
    P_ADDRESS  IN VARCHAR2 DEFAULT NULL,
    P_REGION   IN VARCHAR2 DEFAULT NULL,
    P_TIMEZONE IN VARCHAR2 DEFAULT 'Europe/Chisinau',
    P_STATUS   IN VARCHAR2 DEFAULT 'active'
  );
  PROCEDURE DELETE_STORE (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2);

  -- ===== Отделы =====
  PROCEDURE GET_DEPARTMENTS (P_STORE_ID IN NUMBER DEFAULT NULL, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE CREATE_DEPARTMENT (
    P_ID        OUT NUMBER,
    P_STORE_ID  IN  NUMBER,
    P_DEPT_TYPE IN  VARCHAR2,
    P_NAME      IN  VARCHAR2
  );
  PROCEDURE DELETE_DEPARTMENT (P_ID IN NUMBER);

  -- ===== Устройства =====
  PROCEDURE GET_DEVICES (P_STORE_ID IN NUMBER DEFAULT NULL, P_DEPT_ID IN NUMBER DEFAULT NULL, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_DEVICE_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE UPSERT_DEVICE (
    P_ID              IN OUT NUMBER,
    P_SERIAL_NUMBER   IN VARCHAR2,
    P_NAME            IN VARCHAR2,
    P_DEVICE_TYPE     IN VARCHAR2,
    P_RESOLUTION      IN VARCHAR2,
    P_STORE_ID        IN NUMBER,
    P_DEPARTMENT_ID   IN NUMBER DEFAULT NULL,
    P_IP_ADDRESS      IN VARCHAR2 DEFAULT NULL,
    P_STATUS          IN VARCHAR2 DEFAULT 'online',
    P_FIRMWARE_VERSION IN VARCHAR2 DEFAULT NULL,
    P_MEMORY_TOTAL_MB IN NUMBER DEFAULT 512
  );
  PROCEDURE DELETE_DEVICE (P_ID IN NUMBER);

  -- ===== Медиа =====
  PROCEDURE GET_MEDIA_LIST (P_MEDIA_TYPE IN VARCHAR2 DEFAULT NULL, P_RESOLUTION IN VARCHAR2 DEFAULT NULL, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_MEDIA_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE CREATE_MEDIA (
    P_ID               OUT NUMBER,
    P_FILENAME         IN  VARCHAR2,
    P_ORIGINAL_NAME    IN  VARCHAR2,
    P_MEDIA_TYPE       IN  VARCHAR2,
    P_FORMAT           IN  VARCHAR2,
    P_SIZE_BYTES       IN  NUMBER DEFAULT 0,
    P_DESCRIPTION      IN  VARCHAR2 DEFAULT NULL,
    P_DURATION_SECONDS IN  NUMBER DEFAULT 0,
    P_WIDTH            IN  NUMBER DEFAULT 0,
    P_HEIGHT           IN  NUMBER DEFAULT 0,
    P_CREATED_BY       IN  VARCHAR2 DEFAULT NULL,
    P_TAGS             IN  VARCHAR2 DEFAULT NULL,
    P_RESOLUTIONS      IN  VARCHAR2 DEFAULT NULL
  );
  PROCEDURE UPDATE_MEDIA (
    P_ID          IN NUMBER,
    P_DESCRIPTION IN VARCHAR2 DEFAULT NULL,
    P_TAGS        IN VARCHAR2 DEFAULT NULL,
    P_RESOLUTIONS IN VARCHAR2 DEFAULT NULL
  );
  PROCEDURE DELETE_MEDIA (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2);

  -- ===== Плейлисты =====
  PROCEDURE GET_PLAYLISTS (P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_PLAYLIST_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_PLAYLIST_ITEMS (P_PLAYLIST_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE UPSERT_PLAYLIST (
    P_ID          IN OUT NUMBER,
    P_NAME        IN VARCHAR2,
    P_DESCRIPTION IN VARCHAR2 DEFAULT NULL,
    P_STATUS      IN VARCHAR2 DEFAULT 'draft',
    P_CREATED_BY  IN VARCHAR2 DEFAULT NULL
  );
  PROCEDURE SET_PLAYLIST_ITEM (
    P_PLAYLIST_ID IN NUMBER,
    P_MEDIA_ID    IN NUMBER,
    P_DURATION    IN NUMBER DEFAULT 5,
    P_SORT_ORDER  IN NUMBER DEFAULT 0
  );
  PROCEDURE CLEAR_PLAYLIST_ITEMS (P_PLAYLIST_ID IN NUMBER);
  PROCEDURE RECALC_PLAYLIST_DURATION (P_PLAYLIST_ID IN NUMBER);
  PROCEDURE DELETE_PLAYLIST (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2);

  -- ===== Кампании =====
  PROCEDURE GET_CAMPAIGNS (P_STATUS IN VARCHAR2 DEFAULT NULL, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_CAMPAIGN_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE UPSERT_CAMPAIGN (
    P_ID                IN OUT NUMBER,
    P_NAME              IN VARCHAR2,
    P_DESCRIPTION       IN VARCHAR2 DEFAULT NULL,
    P_PLAYLIST_ID       IN NUMBER DEFAULT NULL,
    P_PRIORITY          IN NUMBER DEFAULT 5,
    P_STATUS            IN VARCHAR2 DEFAULT 'draft',
    P_SCHEDULE_START    IN DATE DEFAULT NULL,
    P_SCHEDULE_END      IN DATE DEFAULT NULL,
    P_SCHEDULE_TIME_FROM IN VARCHAR2 DEFAULT NULL,
    P_SCHEDULE_TIME_TO  IN VARCHAR2 DEFAULT NULL,
    P_SCHEDULE_DAYS     IN VARCHAR2 DEFAULT NULL,
    P_CREATED_BY        IN VARCHAR2 DEFAULT NULL
  );
  PROCEDURE SET_CAMPAIGN_TARGETS (
    P_CAMPAIGN_ID IN NUMBER,
    P_TARGET_TYPE IN VARCHAR2,
    P_TARGET_IDS  IN VARCHAR2
  );
  PROCEDURE PUBLISH_CAMPAIGN (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2);
  PROCEDURE PAUSE_CAMPAIGN   (P_ID IN NUMBER);
  PROCEDURE STOP_CAMPAIGN    (P_ID IN NUMBER);
  PROCEDURE DELETE_CAMPAIGN  (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2);

  -- ===== Синхронизация =====
  PROCEDURE LOG_SYNC (P_CAMPAIGN_ID IN NUMBER, P_DEVICE_ID IN NUMBER, P_STATUS IN VARCHAR2 DEFAULT 'delivered');
  PROCEDURE SIMULATE_DELIVERY (P_CAMPAIGN_ID IN NUMBER);
  PROCEDURE GET_SYNC_LOG (P_CAMPAIGN_ID IN NUMBER DEFAULT NULL, P_DEVICE_ID IN NUMBER DEFAULT NULL, P_LIMIT IN NUMBER DEFAULT 50, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_DELIVERY_REPORT (P_CAMPAIGN_ID IN NUMBER DEFAULT NULL, P_CUR OUT SYS_REFCURSOR);

  -- ===== Статистика =====
  PROCEDURE GET_DASHBOARD_STATS (P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_EVENT_LOG (P_LIMIT IN NUMBER DEFAULT 100, P_ENTITY_TYPE IN VARCHAR2 DEFAULT NULL, P_CUR OUT SYS_REFCURSOR);
  PROCEDURE ADD_EVENT (P_ACTION IN VARCHAR2, P_ENTITY_TYPE IN VARCHAR2, P_ENTITY_ID IN NUMBER, P_DETAILS IN VARCHAR2 DEFAULT NULL, P_USERNAME IN VARCHAR2 DEFAULT NULL);

  -- ===== Справочники =====
  PROCEDURE GET_REF_DEPT_TYPES (P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_REF_DEVICE_TYPES (P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_REF_RESOLUTIONS (P_CUR OUT SYS_REFCURSOR);
  PROCEDURE GET_REF_ROLES (P_CUR OUT SYS_REFCURSOR);

  -- Утилита: разбор CSV-строки в таблицу чисел
  TYPE T_NUM_TAB IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  FUNCTION SPLIT_CSV_NUMS (P_CSV IN VARCHAR2) RETURN T_NUM_TAB;

END DIGI_MARKETING_PKG;
/

CREATE OR REPLACE PACKAGE BODY DIGI_MARKETING_PKG AS

  -- ===== Утилита =====
  FUNCTION SPLIT_CSV_NUMS (P_CSV IN VARCHAR2) RETURN T_NUM_TAB IS
    V_TAB T_NUM_TAB;
    V_STR VARCHAR2(4000) := P_CSV;
    V_POS NUMBER;
    V_IDX PLS_INTEGER := 1;
  BEGIN
    IF V_STR IS NULL THEN RETURN V_TAB; END IF;
    LOOP
      V_POS := INSTR(V_STR, ',');
      IF V_POS > 0 THEN
        V_TAB(V_IDX) := TO_NUMBER(TRIM(SUBSTR(V_STR, 1, V_POS - 1)));
        V_STR := SUBSTR(V_STR, V_POS + 1);
        V_IDX := V_IDX + 1;
      ELSE
        V_TAB(V_IDX) := TO_NUMBER(TRIM(V_STR));
        EXIT;
      END IF;
    END LOOP;
    RETURN V_TAB;
  END SPLIT_CSV_NUMS;

  -- ===== Магазины =====
  PROCEDURE GET_STORES (P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT ID, NAME, ADDRESS, REGION, TIMEZONE, STATUS, CREATED_AT, UPDATED_AT,
             (SELECT COUNT(*) FROM DIGI_DEVICES dv WHERE dv.STORE_ID = s.ID) AS DEVICE_COUNT,
             (SELECT COUNT(*) FROM DIGI_DEPARTMENTS dp WHERE dp.STORE_ID = s.ID) AS DEPARTMENT_COUNT
      FROM DIGI_STORES s ORDER BY NAME;
  END;

  PROCEDURE GET_STORE_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT ID, NAME, ADDRESS, REGION, TIMEZONE, STATUS, CREATED_AT, UPDATED_AT,
             (SELECT COUNT(*) FROM DIGI_DEVICES dv WHERE dv.STORE_ID = s.ID) AS DEVICE_COUNT,
             (SELECT COUNT(*) FROM DIGI_DEPARTMENTS dp WHERE dp.STORE_ID = s.ID) AS DEPARTMENT_COUNT
      FROM DIGI_STORES s WHERE ID = P_ID;
  END;

  PROCEDURE UPSERT_STORE (
    P_ID       IN OUT NUMBER,
    P_NAME     IN VARCHAR2,
    P_ADDRESS  IN VARCHAR2 DEFAULT NULL,
    P_REGION   IN VARCHAR2 DEFAULT NULL,
    P_TIMEZONE IN VARCHAR2 DEFAULT 'Europe/Chisinau',
    P_STATUS   IN VARCHAR2 DEFAULT 'active'
  ) IS
  BEGIN
    IF P_ID IS NULL OR P_ID = 0 THEN
      INSERT INTO DIGI_STORES (NAME, ADDRESS, REGION, TIMEZONE, STATUS)
      VALUES (P_NAME, P_ADDRESS, P_REGION, P_TIMEZONE, P_STATUS)
      RETURNING ID INTO P_ID;
    ELSE
      UPDATE DIGI_STORES SET
        NAME = P_NAME, ADDRESS = P_ADDRESS, REGION = P_REGION,
        TIMEZONE = P_TIMEZONE, STATUS = P_STATUS
      WHERE ID = P_ID;
    END IF;
    COMMIT;
  END;

  PROCEDURE DELETE_STORE (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2) IS
    V_CNT NUMBER;
  BEGIN
    SELECT COUNT(*) INTO V_CNT FROM DIGI_DEVICES WHERE STORE_ID = P_ID;
    IF V_CNT > 0 THEN
      P_OK := 0;
      P_MSG := 'Нельзя удалить: ' || V_CNT || ' устройств привязано к магазину';
      RETURN;
    END IF;
    DELETE FROM DIGI_STORES WHERE ID = P_ID;
    COMMIT;
    P_OK := 1;
    P_MSG := 'OK';
  END;

  -- ===== Отделы =====
  PROCEDURE GET_DEPARTMENTS (P_STORE_ID IN NUMBER DEFAULT NULL, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT * FROM V_DIGI_DEPARTMENTS
      WHERE (P_STORE_ID IS NULL OR STORE_ID = P_STORE_ID)
      ORDER BY STORE_NAME, NAME;
  END;

  PROCEDURE CREATE_DEPARTMENT (
    P_ID        OUT NUMBER,
    P_STORE_ID  IN  NUMBER,
    P_DEPT_TYPE IN  VARCHAR2,
    P_NAME      IN  VARCHAR2
  ) IS
  BEGIN
    INSERT INTO DIGI_DEPARTMENTS (STORE_ID, DEPT_TYPE, NAME)
    VALUES (P_STORE_ID, P_DEPT_TYPE, P_NAME)
    RETURNING ID INTO P_ID;
    COMMIT;
  END;

  PROCEDURE DELETE_DEPARTMENT (P_ID IN NUMBER) IS
  BEGIN
    DELETE FROM DIGI_DEPARTMENTS WHERE ID = P_ID;
    COMMIT;
  END;

  -- ===== Устройства =====
  PROCEDURE GET_DEVICES (P_STORE_ID IN NUMBER DEFAULT NULL, P_DEPT_ID IN NUMBER DEFAULT NULL, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT * FROM V_DIGI_DEVICES
      WHERE (P_STORE_ID IS NULL OR STORE_ID = P_STORE_ID)
        AND (P_DEPT_ID IS NULL OR DEPARTMENT_ID = P_DEPT_ID)
      ORDER BY STORE_NAME, NAME;
  END;

  PROCEDURE GET_DEVICE_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT * FROM V_DIGI_DEVICES WHERE ID = P_ID;
  END;

  PROCEDURE UPSERT_DEVICE (
    P_ID              IN OUT NUMBER,
    P_SERIAL_NUMBER   IN VARCHAR2,
    P_NAME            IN VARCHAR2,
    P_DEVICE_TYPE     IN VARCHAR2,
    P_RESOLUTION      IN VARCHAR2,
    P_STORE_ID        IN NUMBER,
    P_DEPARTMENT_ID   IN NUMBER DEFAULT NULL,
    P_IP_ADDRESS      IN VARCHAR2 DEFAULT NULL,
    P_STATUS          IN VARCHAR2 DEFAULT 'online',
    P_FIRMWARE_VERSION IN VARCHAR2 DEFAULT NULL,
    P_MEMORY_TOTAL_MB IN NUMBER DEFAULT 512
  ) IS
  BEGIN
    IF P_ID IS NULL OR P_ID = 0 THEN
      INSERT INTO DIGI_DEVICES (SERIAL_NUMBER, NAME, DEVICE_TYPE, RESOLUTION, STORE_ID,
                                DEPARTMENT_ID, IP_ADDRESS, STATUS, FIRMWARE_VERSION, MEMORY_TOTAL_MB)
      VALUES (P_SERIAL_NUMBER, P_NAME, P_DEVICE_TYPE, P_RESOLUTION, P_STORE_ID,
              P_DEPARTMENT_ID, P_IP_ADDRESS, P_STATUS, P_FIRMWARE_VERSION, P_MEMORY_TOTAL_MB)
      RETURNING ID INTO P_ID;
    ELSE
      UPDATE DIGI_DEVICES SET
        NAME = P_NAME, STORE_ID = P_STORE_ID, DEPARTMENT_ID = P_DEPARTMENT_ID,
        IP_ADDRESS = P_IP_ADDRESS, STATUS = P_STATUS, RESOLUTION = P_RESOLUTION,
        FIRMWARE_VERSION = P_FIRMWARE_VERSION
      WHERE ID = P_ID;
    END IF;
    COMMIT;
  END;

  PROCEDURE DELETE_DEVICE (P_ID IN NUMBER) IS
  BEGIN
    DELETE FROM DIGI_DEVICES WHERE ID = P_ID;
    COMMIT;
  END;

  -- ===== Медиа =====
  PROCEDURE GET_MEDIA_LIST (P_MEDIA_TYPE IN VARCHAR2 DEFAULT NULL, P_RESOLUTION IN VARCHAR2 DEFAULT NULL, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT * FROM V_DIGI_MEDIA
      WHERE (P_MEDIA_TYPE IS NULL OR MEDIA_TYPE = P_MEDIA_TYPE)
        AND (P_RESOLUTION IS NULL OR INSTR(RESOLUTIONS, P_RESOLUTION) > 0)
      ORDER BY CREATED_AT DESC;
  END;

  PROCEDURE GET_MEDIA_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT * FROM V_DIGI_MEDIA WHERE ID = P_ID;
  END;

  PROCEDURE CREATE_MEDIA (
    P_ID               OUT NUMBER,
    P_FILENAME         IN  VARCHAR2,
    P_ORIGINAL_NAME    IN  VARCHAR2,
    P_MEDIA_TYPE       IN  VARCHAR2,
    P_FORMAT           IN  VARCHAR2,
    P_SIZE_BYTES       IN  NUMBER DEFAULT 0,
    P_DESCRIPTION      IN  VARCHAR2 DEFAULT NULL,
    P_DURATION_SECONDS IN  NUMBER DEFAULT 0,
    P_WIDTH            IN  NUMBER DEFAULT 0,
    P_HEIGHT           IN  NUMBER DEFAULT 0,
    P_CREATED_BY       IN  VARCHAR2 DEFAULT NULL,
    P_TAGS             IN  VARCHAR2 DEFAULT NULL,
    P_RESOLUTIONS      IN  VARCHAR2 DEFAULT NULL
  ) IS
    V_TAG VARCHAR2(100);
    V_RES VARCHAR2(20);
    V_STR VARCHAR2(4000);
    V_POS NUMBER;
  BEGIN
    INSERT INTO DIGI_MEDIA (FILENAME, ORIGINAL_NAME, MEDIA_TYPE, FORMAT, SIZE_BYTES,
                            DESCRIPTION, DURATION_SECONDS, WIDTH, HEIGHT, CREATED_BY)
    VALUES (P_FILENAME, P_ORIGINAL_NAME, P_MEDIA_TYPE, P_FORMAT, P_SIZE_BYTES,
            P_DESCRIPTION, P_DURATION_SECONDS, P_WIDTH, P_HEIGHT, P_CREATED_BY)
    RETURNING ID INTO P_ID;

    -- Теги (CSV)
    IF P_TAGS IS NOT NULL THEN
      V_STR := P_TAGS;
      LOOP
        V_POS := INSTR(V_STR, ',');
        IF V_POS > 0 THEN
          V_TAG := TRIM(SUBSTR(V_STR, 1, V_POS - 1));
          V_STR := SUBSTR(V_STR, V_POS + 1);
        ELSE
          V_TAG := TRIM(V_STR);
        END IF;
        IF V_TAG IS NOT NULL THEN
          INSERT INTO DIGI_MEDIA_TAGS (MEDIA_ID, TAG) VALUES (P_ID, V_TAG);
        END IF;
        EXIT WHEN V_POS = 0;
      END LOOP;
    END IF;

    -- Разрешения (CSV)
    IF P_RESOLUTIONS IS NOT NULL THEN
      V_STR := P_RESOLUTIONS;
      LOOP
        V_POS := INSTR(V_STR, ',');
        IF V_POS > 0 THEN
          V_RES := TRIM(SUBSTR(V_STR, 1, V_POS - 1));
          V_STR := SUBSTR(V_STR, V_POS + 1);
        ELSE
          V_RES := TRIM(V_STR);
        END IF;
        IF V_RES IS NOT NULL THEN
          INSERT INTO DIGI_MEDIA_RESOLUTIONS (MEDIA_ID, RESOLUTION_CODE) VALUES (P_ID, V_RES);
        END IF;
        EXIT WHEN V_POS = 0;
      END LOOP;
    END IF;

    COMMIT;
  END;

  PROCEDURE UPDATE_MEDIA (
    P_ID          IN NUMBER,
    P_DESCRIPTION IN VARCHAR2 DEFAULT NULL,
    P_TAGS        IN VARCHAR2 DEFAULT NULL,
    P_RESOLUTIONS IN VARCHAR2 DEFAULT NULL
  ) IS
    V_TAG VARCHAR2(100);
    V_RES VARCHAR2(20);
    V_STR VARCHAR2(4000);
    V_POS NUMBER;
  BEGIN
    IF P_DESCRIPTION IS NOT NULL THEN
      UPDATE DIGI_MEDIA SET DESCRIPTION = P_DESCRIPTION WHERE ID = P_ID;
    END IF;

    IF P_TAGS IS NOT NULL THEN
      DELETE FROM DIGI_MEDIA_TAGS WHERE MEDIA_ID = P_ID;
      V_STR := P_TAGS;
      LOOP
        V_POS := INSTR(V_STR, ',');
        IF V_POS > 0 THEN
          V_TAG := TRIM(SUBSTR(V_STR, 1, V_POS - 1));
          V_STR := SUBSTR(V_STR, V_POS + 1);
        ELSE
          V_TAG := TRIM(V_STR);
        END IF;
        IF V_TAG IS NOT NULL THEN
          INSERT INTO DIGI_MEDIA_TAGS (MEDIA_ID, TAG) VALUES (P_ID, V_TAG);
        END IF;
        EXIT WHEN V_POS = 0;
      END LOOP;
    END IF;

    IF P_RESOLUTIONS IS NOT NULL THEN
      DELETE FROM DIGI_MEDIA_RESOLUTIONS WHERE MEDIA_ID = P_ID;
      V_STR := P_RESOLUTIONS;
      LOOP
        V_POS := INSTR(V_STR, ',');
        IF V_POS > 0 THEN
          V_RES := TRIM(SUBSTR(V_STR, 1, V_POS - 1));
          V_STR := SUBSTR(V_STR, V_POS + 1);
        ELSE
          V_RES := TRIM(V_STR);
        END IF;
        IF V_RES IS NOT NULL THEN
          INSERT INTO DIGI_MEDIA_RESOLUTIONS (MEDIA_ID, RESOLUTION_CODE) VALUES (P_ID, V_RES);
        END IF;
        EXIT WHEN V_POS = 0;
      END LOOP;
    END IF;

    COMMIT;
  END;

  PROCEDURE DELETE_MEDIA (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2) IS
    V_CNT NUMBER;
  BEGIN
    SELECT COUNT(*) INTO V_CNT FROM DIGI_PLAYLIST_ITEMS WHERE MEDIA_ID = P_ID;
    IF V_CNT > 0 THEN
      P_OK := 0;
      P_MSG := 'Используется в ' || V_CNT || ' плейлистах';
      RETURN;
    END IF;
    DELETE FROM DIGI_MEDIA WHERE ID = P_ID;
    COMMIT;
    P_OK := 1;
    P_MSG := 'OK';
  END;

  -- ===== Плейлисты =====
  PROCEDURE GET_PLAYLISTS (P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT * FROM V_DIGI_PLAYLISTS ORDER BY CREATED_AT DESC;
  END;

  PROCEDURE GET_PLAYLIST_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT * FROM V_DIGI_PLAYLISTS WHERE ID = P_ID;
  END;

  PROCEDURE GET_PLAYLIST_ITEMS (P_PLAYLIST_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT * FROM V_DIGI_PLAYLIST_ITEMS WHERE PLAYLIST_ID = P_PLAYLIST_ID ORDER BY SORT_ORDER;
  END;

  PROCEDURE UPSERT_PLAYLIST (
    P_ID          IN OUT NUMBER,
    P_NAME        IN VARCHAR2,
    P_DESCRIPTION IN VARCHAR2 DEFAULT NULL,
    P_STATUS      IN VARCHAR2 DEFAULT 'draft',
    P_CREATED_BY  IN VARCHAR2 DEFAULT NULL
  ) IS
  BEGIN
    IF P_ID IS NULL OR P_ID = 0 THEN
      INSERT INTO DIGI_PLAYLISTS (NAME, DESCRIPTION, STATUS, CREATED_BY)
      VALUES (P_NAME, P_DESCRIPTION, P_STATUS, P_CREATED_BY)
      RETURNING ID INTO P_ID;
    ELSE
      UPDATE DIGI_PLAYLISTS SET
        NAME = P_NAME, DESCRIPTION = P_DESCRIPTION, STATUS = P_STATUS
      WHERE ID = P_ID;
    END IF;
    COMMIT;
  END;

  PROCEDURE SET_PLAYLIST_ITEM (
    P_PLAYLIST_ID IN NUMBER,
    P_MEDIA_ID    IN NUMBER,
    P_DURATION    IN NUMBER DEFAULT 5,
    P_SORT_ORDER  IN NUMBER DEFAULT 0
  ) IS
  BEGIN
    INSERT INTO DIGI_PLAYLIST_ITEMS (PLAYLIST_ID, MEDIA_ID, DURATION, SORT_ORDER)
    VALUES (P_PLAYLIST_ID, P_MEDIA_ID, P_DURATION, P_SORT_ORDER);
    COMMIT;
  END;

  PROCEDURE CLEAR_PLAYLIST_ITEMS (P_PLAYLIST_ID IN NUMBER) IS
  BEGIN
    DELETE FROM DIGI_PLAYLIST_ITEMS WHERE PLAYLIST_ID = P_PLAYLIST_ID;
    COMMIT;
  END;

  PROCEDURE RECALC_PLAYLIST_DURATION (P_PLAYLIST_ID IN NUMBER) IS
    V_DUR NUMBER;
  BEGIN
    SELECT NVL(SUM(DURATION), 0) INTO V_DUR FROM DIGI_PLAYLIST_ITEMS WHERE PLAYLIST_ID = P_PLAYLIST_ID;
    UPDATE DIGI_PLAYLISTS SET TOTAL_DURATION = V_DUR WHERE ID = P_PLAYLIST_ID;
    COMMIT;
  END;

  PROCEDURE DELETE_PLAYLIST (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2) IS
    V_CNT NUMBER;
  BEGIN
    SELECT COUNT(*) INTO V_CNT FROM DIGI_CAMPAIGNS WHERE PLAYLIST_ID = P_ID;
    IF V_CNT > 0 THEN
      P_OK := 0;
      P_MSG := 'Используется в ' || V_CNT || ' кампаниях';
      RETURN;
    END IF;
    DELETE FROM DIGI_PLAYLISTS WHERE ID = P_ID;
    COMMIT;
    P_OK := 1;
    P_MSG := 'OK';
  END;

  -- ===== Кампании =====
  PROCEDURE GET_CAMPAIGNS (P_STATUS IN VARCHAR2 DEFAULT NULL, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT * FROM V_DIGI_CAMPAIGNS
      WHERE (P_STATUS IS NULL OR STATUS = P_STATUS)
      ORDER BY CREATED_AT DESC;
  END;

  PROCEDURE GET_CAMPAIGN_BY_ID (P_ID IN NUMBER, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT * FROM V_DIGI_CAMPAIGNS WHERE ID = P_ID;
  END;

  PROCEDURE UPSERT_CAMPAIGN (
    P_ID                IN OUT NUMBER,
    P_NAME              IN VARCHAR2,
    P_DESCRIPTION       IN VARCHAR2 DEFAULT NULL,
    P_PLAYLIST_ID       IN NUMBER DEFAULT NULL,
    P_PRIORITY          IN NUMBER DEFAULT 5,
    P_STATUS            IN VARCHAR2 DEFAULT 'draft',
    P_SCHEDULE_START    IN DATE DEFAULT NULL,
    P_SCHEDULE_END      IN DATE DEFAULT NULL,
    P_SCHEDULE_TIME_FROM IN VARCHAR2 DEFAULT NULL,
    P_SCHEDULE_TIME_TO  IN VARCHAR2 DEFAULT NULL,
    P_SCHEDULE_DAYS     IN VARCHAR2 DEFAULT NULL,
    P_CREATED_BY        IN VARCHAR2 DEFAULT NULL
  ) IS
  BEGIN
    IF P_ID IS NULL OR P_ID = 0 THEN
      INSERT INTO DIGI_CAMPAIGNS (NAME, DESCRIPTION, PLAYLIST_ID, PRIORITY, STATUS,
                                  SCHEDULE_START, SCHEDULE_END, SCHEDULE_TIME_FROM,
                                  SCHEDULE_TIME_TO, SCHEDULE_DAYS, CREATED_BY)
      VALUES (P_NAME, P_DESCRIPTION, P_PLAYLIST_ID, P_PRIORITY, P_STATUS,
              P_SCHEDULE_START, P_SCHEDULE_END, P_SCHEDULE_TIME_FROM,
              P_SCHEDULE_TIME_TO, P_SCHEDULE_DAYS, P_CREATED_BY)
      RETURNING ID INTO P_ID;
    ELSE
      UPDATE DIGI_CAMPAIGNS SET
        NAME = P_NAME, DESCRIPTION = P_DESCRIPTION, PLAYLIST_ID = P_PLAYLIST_ID,
        PRIORITY = P_PRIORITY, STATUS = P_STATUS,
        SCHEDULE_START = P_SCHEDULE_START, SCHEDULE_END = P_SCHEDULE_END,
        SCHEDULE_TIME_FROM = P_SCHEDULE_TIME_FROM, SCHEDULE_TIME_TO = P_SCHEDULE_TIME_TO,
        SCHEDULE_DAYS = P_SCHEDULE_DAYS
      WHERE ID = P_ID;
    END IF;
    COMMIT;
  END;

  PROCEDURE SET_CAMPAIGN_TARGETS (
    P_CAMPAIGN_ID IN NUMBER,
    P_TARGET_TYPE IN VARCHAR2,
    P_TARGET_IDS  IN VARCHAR2
  ) IS
    V_NUMS T_NUM_TAB;
  BEGIN
    -- Удаляем старые таргеты
    DELETE FROM DIGI_CAMPAIGN_TARGETS WHERE CAMPAIGN_ID = P_CAMPAIGN_ID;

    IF P_TARGET_TYPE = 'all' OR P_TARGET_IDS IS NULL THEN
      -- "all" = нет записей в таргетах
      NULL;
    ELSE
      V_NUMS := SPLIT_CSV_NUMS(P_TARGET_IDS);
      FOR i IN 1..V_NUMS.COUNT LOOP
        INSERT INTO DIGI_CAMPAIGN_TARGETS (CAMPAIGN_ID, TARGET_TYPE, TARGET_ID)
        VALUES (P_CAMPAIGN_ID, P_TARGET_TYPE, V_NUMS(i));
      END LOOP;
    END IF;

    -- Пересчитываем целевые устройства
    DECLARE
      V_CNT NUMBER := 0;
    BEGIN
      IF P_TARGET_TYPE = 'all' OR P_TARGET_IDS IS NULL THEN
        SELECT COUNT(*) INTO V_CNT FROM DIGI_DEVICES;
      ELSIF P_TARGET_TYPE = 'store' THEN
        SELECT COUNT(*) INTO V_CNT FROM DIGI_DEVICES
        WHERE STORE_ID IN (SELECT TARGET_ID FROM DIGI_CAMPAIGN_TARGETS WHERE CAMPAIGN_ID = P_CAMPAIGN_ID);
      ELSIF P_TARGET_TYPE = 'department' THEN
        SELECT COUNT(*) INTO V_CNT FROM DIGI_DEVICES
        WHERE DEPARTMENT_ID IN (SELECT TARGET_ID FROM DIGI_CAMPAIGN_TARGETS WHERE CAMPAIGN_ID = P_CAMPAIGN_ID);
      ELSIF P_TARGET_TYPE = 'device' THEN
        SELECT COUNT(*) INTO V_CNT FROM DIGI_CAMPAIGN_TARGETS WHERE CAMPAIGN_ID = P_CAMPAIGN_ID;
      END IF;
      UPDATE DIGI_CAMPAIGNS SET DEVICES_TOTAL = V_CNT WHERE ID = P_CAMPAIGN_ID;
    END;

    COMMIT;
  END;

  PROCEDURE PUBLISH_CAMPAIGN (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2) IS
    V_PL NUMBER;
  BEGIN
    SELECT PLAYLIST_ID INTO V_PL FROM DIGI_CAMPAIGNS WHERE ID = P_ID;
    IF V_PL IS NULL THEN
      P_OK := 0;
      P_MSG := 'Не выбран плейлист';
      RETURN;
    END IF;
    UPDATE DIGI_CAMPAIGNS SET STATUS = 'active', DELIVERY_STATUS = 'delivering', PUBLISHED_AT = SYSTIMESTAMP WHERE ID = P_ID;
    COMMIT;
    SIMULATE_DELIVERY(P_ID);
    P_OK := 1;
    P_MSG := 'OK';
  END;

  PROCEDURE PAUSE_CAMPAIGN (P_ID IN NUMBER) IS
  BEGIN
    UPDATE DIGI_CAMPAIGNS SET STATUS = 'paused' WHERE ID = P_ID;
    COMMIT;
  END;

  PROCEDURE STOP_CAMPAIGN (P_ID IN NUMBER) IS
  BEGIN
    UPDATE DIGI_CAMPAIGNS SET STATUS = 'stopped', DELIVERY_STATUS = 'stopped' WHERE ID = P_ID;
    COMMIT;
  END;

  PROCEDURE DELETE_CAMPAIGN (P_ID IN NUMBER, P_OK OUT NUMBER, P_MSG OUT VARCHAR2) IS
    V_STATUS VARCHAR2(20);
  BEGIN
    SELECT STATUS INTO V_STATUS FROM DIGI_CAMPAIGNS WHERE ID = P_ID;
    IF V_STATUS = 'active' THEN
      P_OK := 0;
      P_MSG := 'Нельзя удалить активную кампанию';
      RETURN;
    END IF;
    DELETE FROM DIGI_CAMPAIGNS WHERE ID = P_ID;
    COMMIT;
    P_OK := 1;
    P_MSG := 'OK';
  END;

  -- ===== Синхронизация =====
  PROCEDURE LOG_SYNC (P_CAMPAIGN_ID IN NUMBER, P_DEVICE_ID IN NUMBER, P_STATUS IN VARCHAR2 DEFAULT 'delivered') IS
  BEGIN
    INSERT INTO DIGI_SYNC_LOG (CAMPAIGN_ID, DEVICE_ID, STATUS) VALUES (P_CAMPAIGN_ID, P_DEVICE_ID, P_STATUS);
    UPDATE DIGI_DEVICES SET LAST_SYNC = SYSTIMESTAMP WHERE ID = P_DEVICE_ID;
    COMMIT;
  END;

  PROCEDURE SIMULATE_DELIVERY (P_CAMPAIGN_ID IN NUMBER) IS
    V_SYNCED NUMBER := 0;
    V_TOTAL  NUMBER := 0;
  BEGIN
    SELECT DEVICES_TOTAL INTO V_TOTAL FROM DIGI_CAMPAIGNS WHERE ID = P_CAMPAIGN_ID;

    -- Доставка на все целевые устройства
    FOR rec IN (
      SELECT d.ID FROM DIGI_DEVICES d
      WHERE d.ID IN (
        -- По таргетам или все, если нет записей
        SELECT d2.ID FROM DIGI_DEVICES d2
        WHERE NOT EXISTS (SELECT 1 FROM DIGI_CAMPAIGN_TARGETS t WHERE t.CAMPAIGN_ID = P_CAMPAIGN_ID)
        UNION
        SELECT d3.ID FROM DIGI_DEVICES d3
        JOIN DIGI_CAMPAIGN_TARGETS t ON (
          (t.TARGET_TYPE = 'store'      AND d3.STORE_ID      = t.TARGET_ID) OR
          (t.TARGET_TYPE = 'department'  AND d3.DEPARTMENT_ID = t.TARGET_ID) OR
          (t.TARGET_TYPE = 'device'     AND d3.ID            = t.TARGET_ID)
        )
        WHERE t.CAMPAIGN_ID = P_CAMPAIGN_ID
      )
    ) LOOP
      LOG_SYNC(P_CAMPAIGN_ID, rec.ID, 'delivered');
      V_SYNCED := V_SYNCED + 1;
    END LOOP;

    UPDATE DIGI_CAMPAIGNS SET DEVICES_SYNCED = V_SYNCED,
           DELIVERY_STATUS = CASE WHEN V_SYNCED >= V_TOTAL THEN 'completed' ELSE 'delivering' END
    WHERE ID = P_CAMPAIGN_ID;
    COMMIT;
  END;

  PROCEDURE GET_SYNC_LOG (P_CAMPAIGN_ID IN NUMBER DEFAULT NULL, P_DEVICE_ID IN NUMBER DEFAULT NULL, P_LIMIT IN NUMBER DEFAULT 50, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT * FROM V_DIGI_SYNC_LOG
      WHERE (P_CAMPAIGN_ID IS NULL OR CAMPAIGN_ID = P_CAMPAIGN_ID)
        AND (P_DEVICE_ID IS NULL OR DEVICE_ID = P_DEVICE_ID)
      FETCH FIRST P_LIMIT ROWS ONLY;
  END;

  PROCEDURE GET_DELIVERY_REPORT (P_CAMPAIGN_ID IN NUMBER DEFAULT NULL, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    IF P_CAMPAIGN_ID IS NOT NULL THEN
      OPEN P_CUR FOR
        SELECT c.ID AS CAMPAIGN_ID, c.NAME AS CAMPAIGN_NAME, c.STATUS, c.DELIVERY_STATUS,
               c.DEVICES_TOTAL, c.DEVICES_SYNCED
        FROM DIGI_CAMPAIGNS c WHERE c.ID = P_CAMPAIGN_ID;
    ELSE
      OPEN P_CUR FOR
        SELECT c.ID AS CAMPAIGN_ID, c.NAME AS CAMPAIGN_NAME, c.STATUS, c.DELIVERY_STATUS,
               c.DEVICES_TOTAL, c.DEVICES_SYNCED
        FROM DIGI_CAMPAIGNS c ORDER BY c.CREATED_AT DESC;
    END IF;
  END;

  -- ===== Статистика =====
  PROCEDURE GET_DASHBOARD_STATS (P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT * FROM V_DIGI_DASHBOARD_STATS;
  END;

  PROCEDURE GET_EVENT_LOG (P_LIMIT IN NUMBER DEFAULT 100, P_ENTITY_TYPE IN VARCHAR2 DEFAULT NULL, P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT ID, ACTION, ENTITY_TYPE, ENTITY_ID, DETAILS, USERNAME, CREATED_AT
      FROM DIGI_EVENT_LOG
      WHERE (P_ENTITY_TYPE IS NULL OR ENTITY_TYPE = P_ENTITY_TYPE)
      ORDER BY CREATED_AT DESC
      FETCH FIRST P_LIMIT ROWS ONLY;
  END;

  PROCEDURE ADD_EVENT (P_ACTION IN VARCHAR2, P_ENTITY_TYPE IN VARCHAR2, P_ENTITY_ID IN NUMBER, P_DETAILS IN VARCHAR2 DEFAULT NULL, P_USERNAME IN VARCHAR2 DEFAULT NULL) IS
  BEGIN
    INSERT INTO DIGI_EVENT_LOG (ACTION, ENTITY_TYPE, ENTITY_ID, DETAILS, USERNAME)
    VALUES (P_ACTION, P_ENTITY_TYPE, P_ENTITY_ID, P_DETAILS, P_USERNAME);
    COMMIT;
  END;

  -- ===== Справочники =====
  PROCEDURE GET_REF_DEPT_TYPES (P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT CODE AS ID, NAME FROM DIGI_REF_DEPT_TYPES ORDER BY SORT_ORDER, CODE;
  END;

  PROCEDURE GET_REF_DEVICE_TYPES (P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR
      SELECT dt.CODE AS ID, dt.NAME,
             (SELECT LISTAGG(dr.RESOLUTION_CODE, ',') WITHIN GROUP (ORDER BY dr.RESOLUTION_CODE)
              FROM DIGI_REF_DEVICE_RESOLUTIONS dr WHERE dr.DEVICE_TYPE_CODE = dt.CODE) AS RESOLUTIONS
      FROM DIGI_REF_DEVICE_TYPES dt ORDER BY dt.SORT_ORDER, dt.CODE;
  END;

  PROCEDURE GET_REF_RESOLUTIONS (P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT CODE FROM DIGI_REF_RESOLUTIONS ORDER BY SORT_ORDER, CODE;
  END;

  PROCEDURE GET_REF_ROLES (P_CUR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CUR FOR SELECT CODE AS ID, NAME, PERMISSIONS FROM DIGI_REF_ROLES ORDER BY CODE;
  END;

END DIGI_MARKETING_PKG;
/
