-- ============================================================
-- Nufarul: Миграция заказов на Immutable Tables
-- Oracle 23ai — гарантированная неизменяемость (фискальная память)
--
-- Immutable Table: INSERT ONLY, NO UPDATE, NO DELETE
-- Oracle ADB Cloud: IMMUTABLE TABLE (эквивалент blockchain)
-- ORA-05715 блокирует UPDATE и DELETE
-- ============================================================

-- ====== Шаг 1: Создаём immutable-таблицу для заказов ======

CREATE IMMUTABLE TABLE NUF_ORDERS_LEDGER (
    ID            NUMBER NOT NULL,
    ORDER_NUMBER  VARCHAR2(50) NOT NULL,
    BARCODE       VARCHAR2(100),
    CLIENT_NAME   VARCHAR2(200) NOT NULL,
    CLIENT_PHONE  VARCHAR2(50),
    STATUS_ID     NUMBER NOT NULL,
    TOTAL_AMOUNT  NUMBER DEFAULT 0,
    NOTES         VARCHAR2(4000),
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY    VARCHAR2(100),
    CONSTRAINT PK_NUF_ORDERS_LEDGER PRIMARY KEY (ID)
) NO DROP UNTIL 365 DAYS IDLE
  NO DELETE UNTIL 365 DAYS AFTER INSERT;

CREATE UNIQUE INDEX UQ_NUF_ORDERS_LEDGER_NUM ON NUF_ORDERS_LEDGER (ORDER_NUMBER);
CREATE INDEX IX_NUF_ORDERS_LEDGER_BC ON NUF_ORDERS_LEDGER (BARCODE);
CREATE INDEX IX_NUF_ORDERS_LEDGER_DT ON NUF_ORDERS_LEDGER (CREATED_AT);

-- ====== Шаг 2: Immutable-таблица для позиций заказов ======

CREATE IMMUTABLE TABLE NUF_ORDER_ITEMS_LEDGER (
    ID          NUMBER NOT NULL,
    ORDER_ID    NUMBER NOT NULL,
    SERVICE_ID  NUMBER NOT NULL,
    QTY         NUMBER NOT NULL,
    PRICE       NUMBER NOT NULL,
    AMOUNT      NUMBER NOT NULL,
    NOTES       VARCHAR2(500),
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_NUF_ITEMS_LEDGER PRIMARY KEY (ID)
) NO DROP UNTIL 365 DAYS IDLE
  NO DELETE UNTIL 365 DAYS AFTER INSERT;

CREATE INDEX IX_NUF_ITEMS_LEDGER_OID ON NUF_ORDER_ITEMS_LEDGER (ORDER_ID);
CREATE INDEX IX_NUF_ITEMS_LEDGER_SID ON NUF_ORDER_ITEMS_LEDGER (SERVICE_ID);

-- ====== Шаг 3: Миграция данных из старых таблиц ======

-- Переносим заказы
INSERT INTO NUF_ORDERS_LEDGER (ID, ORDER_NUMBER, BARCODE, CLIENT_NAME, CLIENT_PHONE,
    STATUS_ID, TOTAL_AMOUNT, NOTES, CREATED_AT, CREATED_BY)
SELECT ID, ORDER_NUMBER, BARCODE, CLIENT_NAME, CLIENT_PHONE,
    STATUS_ID, TOTAL_AMOUNT, NOTES, CREATED_AT, CREATED_BY
FROM NUF_ORDERS
ORDER BY ID;

-- Переносим позиции
INSERT INTO NUF_ORDER_ITEMS_LEDGER (ID, ORDER_ID, SERVICE_ID, QTY, PRICE, AMOUNT, NOTES, CREATED_AT)
SELECT ID, ORDER_ID, SERVICE_ID, QTY, PRICE, AMOUNT, NOTES, SYSTIMESTAMP
FROM NUF_ORDER_ITEMS
ORDER BY ID;

COMMIT;

-- ====== Шаг 4: Таблица изменений статуса (тоже immutable) ======
-- Т.к. immutable нельзя обновлять, изменения статуса пишем в отдельный лог

CREATE IMMUTABLE TABLE NUF_ORDER_STATUS_LOG (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID      NUMBER NOT NULL,
    OLD_STATUS_ID NUMBER,
    NEW_STATUS_ID NUMBER NOT NULL,
    CHANGED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CHANGED_BY    VARCHAR2(100),
    CONSTRAINT PK_NUF_STATUS_LOG PRIMARY KEY (ID)
) NO DROP UNTIL 365 DAYS IDLE
  NO DELETE UNTIL 365 DAYS AFTER INSERT;

CREATE INDEX IX_NUF_STATUS_LOG_OID ON NUF_ORDER_STATUS_LOG (ORDER_ID);

-- ====== Шаг 5: View для текущего статуса заказа ======
-- Актуальный статус = последняя запись в логе (или исходный STATUS_ID)

CREATE OR REPLACE VIEW V_NUF_ORDERS_BLOCKCHAIN AS
SELECT
    o.ID, o.ORDER_NUMBER, o.BARCODE, o.CLIENT_NAME, o.CLIENT_PHONE,
    COALESCE(sl.CURRENT_STATUS_ID, o.STATUS_ID) AS STATUS_ID,
    s.CODE AS STATUS_CODE,
    s.NAME_RO AS STATUS_NAME,
    s.NAME_RU AS STATUS_NAME_RU,
    o.TOTAL_AMOUNT, o.NOTES, o.CREATED_AT, o.CREATED_BY,
    sl.LAST_CHANGED AS UPDATED_AT
FROM NUF_ORDERS_LEDGER o
LEFT JOIN (
    SELECT ORDER_ID,
           NEW_STATUS_ID AS CURRENT_STATUS_ID,
           CHANGED_AT AS LAST_CHANGED,
           ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY CHANGED_AT DESC, ID DESC) AS RN
    FROM NUF_ORDER_STATUS_LOG
) sl ON sl.ORDER_ID = o.ID AND sl.RN = 1
JOIN NUF_ORDER_STATUSES s ON s.ID = COALESCE(sl.CURRENT_STATUS_ID, o.STATUS_ID);

-- ====== Шаг 6: View для позиций из blockchain ======

CREATE OR REPLACE VIEW V_NUF_ORDER_ITEMS_BLOCKCHAIN AS
SELECT
    i.ID, i.ORDER_ID, i.SERVICE_ID,
    sv.NAME AS SERVICE_NAME,
    sv.NAME_RO AS SERVICE_NAME_RO,
    i.QTY, i.PRICE, i.AMOUNT, i.NOTES
FROM NUF_ORDER_ITEMS_LEDGER i
JOIN NUF_SERVICES sv ON sv.ID = i.SERVICE_ID;

-- ====== Шаг 7: Sequence для blockchain таблиц ======
-- Используем существующие sequences, но обновим NEXTVAL

DECLARE
    v_max_oid NUMBER;
    v_max_iid NUMBER;
BEGIN
    SELECT NVL(MAX(ID), 0) INTO v_max_oid FROM NUF_ORDERS_LEDGER;
    SELECT NVL(MAX(ID), 0) INTO v_max_iid FROM NUF_ORDER_ITEMS_LEDGER;

    -- Создаём новые sequence с правильным стартом
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE NUF_ORDERS_LEDGER_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE NUF_ITEMS_LEDGER_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE NUF_ORDERS_LEDGER_SEQ START WITH ' || (v_max_oid + 1) || ' INCREMENT BY 1 NOCACHE';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE NUF_ITEMS_LEDGER_SEQ START WITH ' || (v_max_iid + 1) || ' INCREMENT BY 1 NOCACHE';
END;
/

-- ====== Шаг 8: Переносим фото-ссылки на новую таблицу ======
-- NUF_ORDER_PHOTOS ссылается на NUF_ORDERS.ID — те же ID сохранены в LEDGER

-- Удаляем старый FK
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE NUF_ORDER_PHOTOS DROP CONSTRAINT FK_NUF_OP_ORDER';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Примечание: Blockchain таблицы не поддерживают внешние ключи ОТ других таблиц.
-- Целостность обеспечивается на уровне приложения + ID совпадают.

-- ====== Шаг 9: Переименовываем старые таблицы (бэкап) ======

ALTER TABLE NUF_ORDER_ITEMS RENAME TO NUF_ORDER_ITEMS_OLD;
ALTER TABLE NUF_ORDERS RENAME TO NUF_ORDERS_OLD;

-- ====== Информация ======
-- Старые таблицы: NUF_ORDERS_OLD, NUF_ORDER_ITEMS_OLD (бэкап)
-- Новые immutable: NUF_ORDERS_LEDGER, NUF_ORDER_ITEMS_LEDGER
-- Status changes: NUF_ORDER_STATUS_LOG (immutable)
-- Views: V_NUF_ORDERS_BLOCKCHAIN, V_NUF_ORDER_ITEMS_BLOCKCHAIN
-- Гарантии: INSERT ONLY, UPDATE/DELETE → ORA-05715
