CREATE TABLE DECOR_MATERIALS (
  ID NUMBER PRIMARY KEY,
  CODE VARCHAR2(80) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  NAME_ORIGINAL VARCHAR2(300),
  ORIGINAL_LANG VARCHAR2(16),
  NAME_RO VARCHAR2(300),
  IMAGE_URL VARCHAR2(1000),
  CATEGORY VARCHAR2(50),
  UNIT VARCHAR2(20),
  UNIT_PRICE NUMBER(14,2),
  CURRENCY VARCHAR2(10),
  SOURCE_FILE VARCHAR2(300),
  SOURCE_SHEET VARCHAR2(200),
  NOTES VARCHAR2(1000),
  ACTIVE CHAR(1),
  CREATED_AT VARCHAR2(40),
  UPDATED_AT VARCHAR2(40)
);
/
CREATE UNIQUE INDEX UQ_DECOR_MATERIALS_CODE ON DECOR_MATERIALS (CODE);
/

CREATE TABLE DECOR_STATUSES (
  ID NUMBER PRIMARY KEY,
  CODE VARCHAR2(50) NOT NULL,
  NAME VARCHAR2(200) NOT NULL
);
/
CREATE UNIQUE INDEX UQ_DECOR_STATUSES_CODE ON DECOR_STATUSES (CODE);
/

CREATE TABLE DECOR_SETTINGS (
  SETTINGS_ID NUMBER PRIMARY KEY,
  CURRENCY VARCHAR2(10),
  EXCHANGE_RATE_USD_TO_MDL NUMBER(14,4),
  MARKUP_PERCENT NUMBER(14,4),
  WASTE_PERCENT NUMBER(14,4),
  PROFILE_WEIGHT_KG_PER_M2 NUMBER(14,4),
  ACCESSORY_FIXED_PER_M2 NUMBER(14,4),
  DRAINAGE_FIXED NUMBER(14,4),
  TRANSPORT_FIXED NUMBER(14,4),
  INSTALL_RATE_M2 NUMBER(14,4)
);
/

CREATE TABLE DECOR_SETTING_GLASS_RATES (
  SETTINGS_ID NUMBER NOT NULL,
  SYSTEM_TYPE VARCHAR2(50) NOT NULL,
  RATE NUMBER(14,4),
  CONSTRAINT PK_DECOR_SETTING_GLASS_RATES PRIMARY KEY (SETTINGS_ID, SYSTEM_TYPE),
  CONSTRAINT FK_DECOR_SET_GLASS_SETTINGS FOREIGN KEY (SETTINGS_ID) REFERENCES DECOR_SETTINGS(SETTINGS_ID) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_SETTING_LED_OPTIONS (
  SETTINGS_ID NUMBER NOT NULL,
  OPTION_CODE VARCHAR2(50) NOT NULL,
  RATE NUMBER(14,4),
  CONSTRAINT PK_DECOR_SETTING_LED_OPTIONS PRIMARY KEY (SETTINGS_ID, OPTION_CODE),
  CONSTRAINT FK_DECOR_SET_LED_SETTINGS FOREIGN KEY (SETTINGS_ID) REFERENCES DECOR_SETTINGS(SETTINGS_ID) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_SETTING_LIST_VALUES (
  SETTINGS_ID NUMBER NOT NULL,
  LIST_TYPE VARCHAR2(50) NOT NULL,
  VALUE_TEXT VARCHAR2(300) NOT NULL,
  SORT_ORDER NUMBER NOT NULL,
  CONSTRAINT PK_DECOR_SETTING_LIST_VALUES PRIMARY KEY (SETTINGS_ID, LIST_TYPE, SORT_ORDER),
  CONSTRAINT FK_DECOR_SET_LIST_SETTINGS FOREIGN KEY (SETTINGS_ID) REFERENCES DECOR_SETTINGS(SETTINGS_ID) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_COUNTERS (
  COUNTER_KEY VARCHAR2(50) PRIMARY KEY,
  COUNTER_VALUE NUMBER NOT NULL
);
/

CREATE TABLE DECOR_ORDERS (
  ID NUMBER PRIMARY KEY,
  ORDER_NUMBER VARCHAR2(50) NOT NULL,
  BARCODE VARCHAR2(50),
  PRODUCT_TYPE VARCHAR2(20),
  CLIENT_NAME VARCHAR2(300),
  CLIENT_PHONE VARCHAR2(100),
  CLIENT_EMAIL VARCHAR2(300),
  PROJECT_TYPE VARCHAR2(200),
  PROJECT_NAME VARCHAR2(300),
  LOCATION VARCHAR2(300),
  COLOR VARCHAR2(200),
  NOTES VARCHAR2(2000),
  STATUS_ID NUMBER,
  CURRENCY VARCHAR2(10),
  TOTAL_AMOUNT NUMBER(14,2),
  CREATED_AT VARCHAR2(40),
  UPDATED_AT VARCHAR2(40),
  CONSTRAINT FK_DECOR_ORD_STATUS FOREIGN KEY (STATUS_ID) REFERENCES DECOR_STATUSES(ID)
);
/
CREATE UNIQUE INDEX UQ_DECOR_ORDERS_NUMBER ON DECOR_ORDERS (ORDER_NUMBER);
/

CREATE TABLE DECOR_ORDER_INPUTS (
  ORDER_ID NUMBER PRIMARY KEY,
  WIDTH_MM NUMBER(14,3),
  PROJECTION_MM NUMBER(14,3),
  FRONT_HEIGHT_MM NUMBER(14,3),
  REAR_HEIGHT_MM NUMBER(14,3),
  SYSTEM_TYPE VARCHAR2(50),
  LED_OPTION VARCHAR2(50),
  INCLUDE_INSTALLATION CHAR(1),
  INCLUDE_TRANSPORT CHAR(1),
  INCLUDE_DRAINAGE CHAR(1),
  EXTRA_ITEMS_COUNT NUMBER,
  VARIANT_KEY VARCHAR2(100),
  VARIANT_LABEL VARCHAR2(200),
  FAMILY VARCHAR2(50),
  HEIGHT_MM NUMBER(14,3),
  ORIENTATION VARCHAR2(20),
  INCLUDE_THRESHOLD CHAR(1),
  INCLUDE_GLASS CHAR(1),
  GLASS_SYSTEM VARCHAR2(50),
  GLASS_FINISH VARCHAR2(50),
  GLASS_THICKNESS VARCHAR2(50),
  INCLUDE_ASSEMBLY CHAR(1),
  CONSTRAINT FK_DECOR_ORD_INPUTS FOREIGN KEY (ORDER_ID) REFERENCES DECOR_ORDERS(ID) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_ORDER_METRICS (
  ORDER_ID NUMBER PRIMARY KEY,
  AREA_M2 NUMBER(14,3),
  PERIMETER_M NUMBER(14,3),
  SLOPE_MM NUMBER(14,3),
  SLOPE_PERCENT NUMBER(14,3),
  POST_COUNT NUMBER,
  SECTION_COUNT NUMBER,
  BEAM_COUNT NUMBER,
  RAFTER_LENGTH_M NUMBER(14,3),
  FRAME_LENGTH_M NUMBER(14,3),
  PROFILE_WEIGHT_TOTAL_KG NUMBER(14,3),
  GLASS_PANEL_COUNT NUMBER,
  GLASS_PANEL_AREA_M2 NUMBER(14,3),
  GLASS_PANEL_WIDTH_M NUMBER(14,3),
  GLASS_PANEL_LENGTH_M NUMBER(14,3),
  TOTAL_PANELS NUMBER,
  PANEL_WIDTH_MM NUMBER(14,3),
  PROFILE_WEIGHT_KG NUMBER(14,3),
  CONSTRAINT FK_DECOR_ORD_METRICS FOREIGN KEY (ORDER_ID) REFERENCES DECOR_ORDERS(ID) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_ORDER_SUMMARY (
  ORDER_ID NUMBER PRIMARY KEY,
  CURRENCY VARCHAR2(10),
  PROFILE_COST NUMBER(14,2),
  ACCESSORY_COST NUMBER(14,2),
  GLASS_COST NUMBER(14,2),
  ASSEMBLY_COST NUMBER(14,2),
  INSTALLATION_COST NUMBER(14,2),
  DIRECT_COST NUMBER(14,2),
  WASTE_AMOUNT NUMBER(14,2),
  SUBTOTAL NUMBER(14,2),
  MARGIN_AMOUNT NUMBER(14,2),
  TOTAL NUMBER(14,2),
  EXCHANGE_RATE_USD_TO_MDL NUMBER(14,4),
  TOTAL_MDL NUMBER(14,2),
  EXTRA_ITEMS_AMOUNT NUMBER(14,2),
  TOTAL_USD NUMBER(14,2),
  CONSTRAINT FK_DECOR_ORD_SUMMARY FOREIGN KEY (ORDER_ID) REFERENCES DECOR_ORDERS(ID) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_ORDER_ITEMS (
  ORDER_ID NUMBER NOT NULL,
  LINE_NO NUMBER NOT NULL,
  CODE VARCHAR2(80),
  NAME VARCHAR2(300),
  QTY NUMBER(14,4),
  UNIT VARCHAR2(20),
  UNIT_PRICE NUMBER(14,4),
  AMOUNT NUMBER(14,2),
  CATEGORY VARCHAR2(50),
  SOURCE_NAME VARCHAR2(50),
  IMAGE_URL VARCHAR2(1000),
  LENGTH_M NUMBER(14,4),
  TOTAL_LENGTH_M NUMBER(14,4),
  WEIGHT_KG NUMBER(14,4),
  CONSTRAINT PK_DECOR_ORDER_ITEMS PRIMARY KEY (ORDER_ID, LINE_NO),
  CONSTRAINT FK_DECOR_ORD_ITEMS FOREIGN KEY (ORDER_ID) REFERENCES DECOR_ORDERS(ID) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_SLIDING_MATERIALS (
  ID NUMBER PRIMARY KEY,
  CODE VARCHAR2(80) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  NAME_RO VARCHAR2(300),
  UNIT VARCHAR2(20),
  CURRENCY VARCHAR2(10),
  FAMILY VARCHAR2(50),
  CATEGORY VARCHAR2(50),
  UNIT_PRICE NUMBER(14,2),
  WEIGHT_G_PER_M NUMBER(14,3),
  ACTIVE CHAR(1)
);
/
CREATE UNIQUE INDEX UQ_DECOR_SLIDING_MAT_CODE ON DECOR_SLIDING_MATERIALS (CODE);
/

CREATE TABLE DECOR_SLIDING_SETTINGS (
  SETTINGS_ID NUMBER PRIMARY KEY,
  CURRENCY VARCHAR2(10),
  ASSEMBLY_RATE NUMBER(14,4),
  INSTALLATION_RATE NUMBER(14,4),
  PAINTING_RATE_M2 NUMBER(14,4),
  MARKUP_PERCENT NUMBER(14,4),
  WASTE_PERCENT NUMBER(14,4),
  EXCHANGE_RATE_MDL_TO_USD NUMBER(14,4),
  ASSEMBLY_BASIS VARCHAR2(20),
  INSTALLATION_BASIS VARCHAR2(20)
);
/

CREATE TABLE DECOR_SLIDING_GLASS_RATES (
  SETTINGS_ID NUMBER NOT NULL,
  SYSTEM_TYPE VARCHAR2(50) NOT NULL,
  FINISH_KEY VARCHAR2(100) NOT NULL,
  RATE NUMBER(14,4),
  CONSTRAINT PK_DECOR_SLIDING_GLASS_RATES PRIMARY KEY (SETTINGS_ID, SYSTEM_TYPE, FINISH_KEY),
  CONSTRAINT FK_DECOR_SL_GLASS_SET FOREIGN KEY (SETTINGS_ID) REFERENCES DECOR_SLIDING_SETTINGS(SETTINGS_ID) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_SLIDING_LIST_VALUES (
  SETTINGS_ID NUMBER NOT NULL,
  LIST_TYPE VARCHAR2(50) NOT NULL,
  VALUE_TEXT VARCHAR2(300) NOT NULL,
  SORT_ORDER NUMBER NOT NULL,
  CONSTRAINT PK_DECOR_SLIDING_LIST_VALUES PRIMARY KEY (SETTINGS_ID, LIST_TYPE, SORT_ORDER),
  CONSTRAINT FK_DECOR_SL_LIST_SET FOREIGN KEY (SETTINGS_ID) REFERENCES DECOR_SLIDING_SETTINGS(SETTINGS_ID) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_SLIDING_VARIANTS (
  VARIANT_KEY VARCHAR2(100) PRIMARY KEY,
  FAMILY VARCHAR2(50),
  PANELS VARCHAR2(20),
  LABEL VARCHAR2(200),
  WIDTH_MIN_MM NUMBER(14,3),
  WIDTH_MAX_MM NUMBER(14,3),
  HEIGHT_MIN_MM NUMBER(14,3),
  HEIGHT_MAX_MM NUMBER(14,3),
  MAX_AREA_M2 NUMBER(14,3),
  MAX_PANEL_WIDTH_MM NUMBER(14,3),
  IS_DOUBLE CHAR(1)
);
/

CREATE TABLE DECOR_SLIDING_VARIANT_PROFILES (
  VARIANT_KEY VARCHAR2(100) NOT NULL,
  PROFILE_KIND VARCHAR2(20) NOT NULL,
  CODE VARCHAR2(80) NOT NULL,
  DESC_TEXT VARCHAR2(300),
  PIECES NUMBER,
  PER_PANEL CHAR(1),
  LENGTH_BASIS VARCHAR2(20),
  LENGTH_OFFSET_MM NUMBER(14,3),
  LENGTH_MM NUMBER(14,3),
  CONDITION_EXPR VARCHAR2(50),
  CONSTRAINT PK_DECOR_SLIDING_VAR_PROF PRIMARY KEY (VARIANT_KEY, PROFILE_KIND, CODE),
  CONSTRAINT FK_DECOR_SL_VAR_PROF FOREIGN KEY (VARIANT_KEY) REFERENCES DECOR_SLIDING_VARIANTS(VARIANT_KEY) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_SLIDING_PANEL_OFFSETS (
  VARIANT_KEY VARCHAR2(100) NOT NULL,
  PROFILE_KIND VARCHAR2(20) NOT NULL,
  CODE VARCHAR2(80) NOT NULL,
  PANEL_LABEL VARCHAR2(50) NOT NULL,
  OFFSET_MM NUMBER(14,3),
  CONSTRAINT PK_DECOR_SLIDING_PANEL_OFFSETS PRIMARY KEY (VARIANT_KEY, PROFILE_KIND, CODE, PANEL_LABEL),
  CONSTRAINT FK_DECOR_SL_PANEL_PROF FOREIGN KEY (VARIANT_KEY, PROFILE_KIND, CODE) REFERENCES DECOR_SLIDING_VARIANT_PROFILES(VARIANT_KEY, PROFILE_KIND, CODE) ON DELETE CASCADE
);
/

CREATE TABLE DECOR_SLIDING_VARIANT_ACCESSORIES (
  VARIANT_KEY VARCHAR2(100) NOT NULL,
  CODE VARCHAR2(80) NOT NULL,
  QTY NUMBER,
  CONDITION_EXPR VARCHAR2(50),
  CONSTRAINT PK_DECOR_SLIDING_VAR_ACC PRIMARY KEY (VARIANT_KEY, CODE),
  CONSTRAINT FK_DECOR_SL_VAR_ACC FOREIGN KEY (VARIANT_KEY) REFERENCES DECOR_SLIDING_VARIANTS(VARIANT_KEY) ON DELETE CASCADE
);
/

CREATE TABLE CRED_EVENT_LOG (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TS_ISO VARCHAR2(40) NOT NULL,
  LEVEL_NAME VARCHAR2(16) NOT NULL,
  SOURCE_NAME VARCHAR2(200) NOT NULL,
  MESSAGE_TEXT CLOB,
  PAYLOAD_JSON CLOB
);
/
CREATE INDEX IX_CRED_EVENT_LOG_TS ON CRED_EVENT_LOG (TS_ISO);
/