-- ============================================================
-- Colass module (CLS_) - catalog + estimator
-- Tables: 8
-- Sequences: 7
-- Triggers: 7
-- Views: 3
-- ============================================================

CREATE TABLE CLS_RESOURCE_TYPES (
  ID             NUMBER         NOT NULL,
  CODE           VARCHAR2(30)   NOT NULL,
  NAME_RU        VARCHAR2(200)  NOT NULL,
  NAME_RO        VARCHAR2(200),
  NAME_EN        VARCHAR2(200),
  SORT_ORDER     NUMBER         DEFAULT 0 NOT NULL,
  IS_ACTIVE      CHAR(1)        DEFAULT 'Y' NOT NULL,
  CREATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_RESOURCE_TYPES PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_RESOURCE_TYPES_CODE UNIQUE (CODE),
  CONSTRAINT CHK_CLS_RESOURCE_TYPES_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);
/

CREATE TABLE CLS_RESOURCES (
  ID             NUMBER          NOT NULL,
  RESOURCE_CODE  VARCHAR2(120)   NOT NULL,
  TYPE_ID        NUMBER          NOT NULL,
  NAME           VARCHAR2(2000)  NOT NULL,
  UNIT           VARCHAR2(32),
  BASE_QTY       NUMBER(18,4),
  PRICE          NUMBER(18,4),
  AMOUNT         NUMBER(18,4),
  SOURCE_DOC     VARCHAR2(30)    DEFAULT 'F3' NOT NULL,
  SOURCE_ROW     NUMBER,
  NRDOC          NUMBER,
  NRR            NUMBER,
  IS_ACTIVE      CHAR(1)         DEFAULT 'Y' NOT NULL,
  CREATED_AT     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_RESOURCES PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_RESOURCES_CODE UNIQUE (RESOURCE_CODE),
  CONSTRAINT FK_CLS_RESOURCES_TYPE FOREIGN KEY (TYPE_ID) REFERENCES CLS_RESOURCE_TYPES(ID),
  CONSTRAINT CHK_CLS_RESOURCES_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);
/

CREATE TABLE CLS_WORK_CATALOG (
  ID              NUMBER          NOT NULL,
  WORK_NO         NUMBER          NOT NULL,
  NUM1            NUMBER,
  NUM2            NUMBER,
  NUM3            NUMBER,
  NUM4            NUMBER,
  WORK_CODE       VARCHAR2(120),
  WORK_NAME       VARCHAR2(2000)  NOT NULL,
  UNIT            VARCHAR2(32),
  PRICE           NUMBER(18,4),
  AMOUNT          NUMBER(18,4),
  LEVEL1_NAME     VARCHAR2(500),
  LEVEL2_NAME     VARCHAR2(500),
  LEVEL3_NAME     VARCHAR2(500),
  SORT_ORDER      NUMBER          DEFAULT 0 NOT NULL,
  SOURCE_DOC      VARCHAR2(30)    DEFAULT 'F5' NOT NULL,
  SOURCE_ROW      NUMBER,
  NRDOC           NUMBER,
  IS_ACTIVE       CHAR(1)         DEFAULT 'Y' NOT NULL,
  CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_WORK_CATALOG PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_WORK_CATALOG_WORK_NO UNIQUE (WORK_NO),
  CONSTRAINT CHK_CLS_WORK_CATALOG_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);
/

CREATE TABLE CLS_WORK_RESOURCES (
  ID              NUMBER          NOT NULL,
  WORK_ID         NUMBER          NOT NULL,
  RESOURCE_ID     NUMBER,
  RESOURCE_CODE   VARCHAR2(120),
  RESOURCE_NAME   VARCHAR2(2000)  NOT NULL,
  UNIT            VARCHAR2(32),
  QTY_NORM        NUMBER(18,6),
  UNIT_PRICE      NUMBER(18,4),
  AMOUNT          NUMBER(18,4),
  SORT_ORDER      NUMBER          DEFAULT 0 NOT NULL,
  SOURCE_DOC      VARCHAR2(30)    DEFAULT 'F5' NOT NULL,
  SOURCE_ROW      NUMBER,
  CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_WORK_RESOURCES PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_WORK_RESOURCES_UQ UNIQUE (WORK_ID, SORT_ORDER),
  CONSTRAINT FK_CLS_WORK_RESOURCES_WORK FOREIGN KEY (WORK_ID) REFERENCES CLS_WORK_CATALOG(ID),
  CONSTRAINT FK_CLS_WORK_RESOURCES_RESOURCE FOREIGN KEY (RESOURCE_ID) REFERENCES CLS_RESOURCES(ID)
);
/

CREATE TABLE CLS_PROJECTS (
  ID              NUMBER          NOT NULL,
  CODE            VARCHAR2(80)    NOT NULL,
  NAME            VARCHAR2(500)   NOT NULL,
  CUSTOMER_NAME   VARCHAR2(500),
  OBJECT_TYPE     VARCHAR2(120),
  LOCATION        VARCHAR2(500),
  CURRENCY        VARCHAR2(10)    DEFAULT 'MDL' NOT NULL,
  STATUS          VARCHAR2(40)    DEFAULT 'ACTIVE' NOT NULL,
  NOTES           VARCHAR2(2000),
  CREATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_PROJECTS PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_PROJECTS_CODE UNIQUE (CODE)
);
/

CREATE TABLE CLS_ESTIMATES (
  ID               NUMBER         NOT NULL,
  PROJECT_ID       NUMBER         NOT NULL,
  CODE             VARCHAR2(80)   NOT NULL,
  NAME             VARCHAR2(500)  NOT NULL,
  CURRENCY         VARCHAR2(10)   DEFAULT 'MDL' NOT NULL,
  STATUS           VARCHAR2(40)   DEFAULT 'DRAFT' NOT NULL,
  TOTAL_MANOPERA   NUMBER(18,4)   DEFAULT 0 NOT NULL,
  TOTAL_MATERIALE  NUMBER(18,4)   DEFAULT 0 NOT NULL,
  TOTAL_UTILAJE    NUMBER(18,4)   DEFAULT 0 NOT NULL,
  TOTAL_AMOUNT     NUMBER(18,4)   DEFAULT 0 NOT NULL,
  SOURCE_DOC       VARCHAR2(30)   DEFAULT 'F7',
  SOURCE_REF       VARCHAR2(120),
  CREATED_AT       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_ESTIMATES PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_ESTIMATES_CODE UNIQUE (CODE),
  CONSTRAINT FK_CLS_ESTIMATES_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES CLS_PROJECTS(ID)
);
/

CREATE TABLE CLS_ESTIMATE_SECTIONS (
  ID               NUMBER          NOT NULL,
  ESTIMATE_ID      NUMBER          NOT NULL,
  CODE             VARCHAR2(40)    NOT NULL,
  NAME             VARCHAR2(500)   NOT NULL,
  SORT_ORDER       NUMBER          DEFAULT 0 NOT NULL,
  TOTAL_AMOUNT     NUMBER(18,4)    DEFAULT 0 NOT NULL,
  CREATED_AT       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_ESTIMATE_SECTIONS PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_ESTIMATE_SECTIONS_CODE UNIQUE (ESTIMATE_ID, CODE),
  CONSTRAINT FK_CLS_ESTIMATE_SECTIONS_EST FOREIGN KEY (ESTIMATE_ID) REFERENCES CLS_ESTIMATES(ID)
);
/

CREATE TABLE CLS_ESTIMATE_ITEMS (
  ID                NUMBER          NOT NULL,
  ESTIMATE_ID       NUMBER          NOT NULL,
  SECTION_ID        NUMBER,
  WORK_ID           NUMBER,
  RESOURCE_TYPE_ID  NUMBER,
  RESOURCE_ID       NUMBER,
  ITEM_CODE         VARCHAR2(120),
  ITEM_NAME         VARCHAR2(2000)  NOT NULL,
  UNIT              VARCHAR2(32),
  QTY               NUMBER(18,6)    DEFAULT 0 NOT NULL,
  PRICE             NUMBER(18,4)    DEFAULT 0 NOT NULL,
  AMOUNT            NUMBER(18,4)    DEFAULT 0 NOT NULL,
  NOTES             VARCHAR2(2000),
  SOURCE_DOC        VARCHAR2(30)    DEFAULT 'MANUAL',
  SOURCE_ROW        NUMBER,
  CREATED_BY        VARCHAR2(120),
  CREATED_AT        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_ESTIMATE_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_CLS_EST_ITEMS_EST FOREIGN KEY (ESTIMATE_ID) REFERENCES CLS_ESTIMATES(ID),
  CONSTRAINT FK_CLS_EST_ITEMS_SEC FOREIGN KEY (SECTION_ID) REFERENCES CLS_ESTIMATE_SECTIONS(ID),
  CONSTRAINT FK_CLS_EST_ITEMS_WORK FOREIGN KEY (WORK_ID) REFERENCES CLS_WORK_CATALOG(ID),
  CONSTRAINT FK_CLS_EST_ITEMS_TYPE FOREIGN KEY (RESOURCE_TYPE_ID) REFERENCES CLS_RESOURCE_TYPES(ID),
  CONSTRAINT FK_CLS_EST_ITEMS_RES FOREIGN KEY (RESOURCE_ID) REFERENCES CLS_RESOURCES(ID),
  CONSTRAINT CHK_CLS_EST_ITEMS_QTY CHECK (QTY >= 0),
  CONSTRAINT CHK_CLS_EST_ITEMS_PRICE CHECK (PRICE >= 0),
  CONSTRAINT CHK_CLS_EST_ITEMS_AMOUNT CHECK (AMOUNT >= 0)
);
/

-- ============================================================
-- Sequences
-- ============================================================

CREATE SEQUENCE CLS_RESOURCES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_WORK_CATALOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_WORK_RESOURCES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_PROJECTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_ESTIMATES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_ESTIMATE_SECTIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_ESTIMATE_ITEMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- ============================================================
-- Triggers (ID autoincrement)
-- ============================================================

CREATE OR REPLACE TRIGGER CLS_RESOURCES_BI
BEFORE INSERT ON CLS_RESOURCES FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_RESOURCES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_WORK_CATALOG_BI
BEFORE INSERT ON CLS_WORK_CATALOG FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_WORK_CATALOG_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_WORK_RESOURCES_BI
BEFORE INSERT ON CLS_WORK_RESOURCES FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_WORK_RESOURCES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_PROJECTS_BI
BEFORE INSERT ON CLS_PROJECTS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_PROJECTS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_ESTIMATES_BI
BEFORE INSERT ON CLS_ESTIMATES FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_ESTIMATES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_ESTIMATE_SECTIONS_BI
BEFORE INSERT ON CLS_ESTIMATE_SECTIONS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_ESTIMATE_SECTIONS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_ESTIMATE_ITEMS_BI
BEFORE INSERT ON CLS_ESTIMATE_ITEMS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_ESTIMATE_ITEMS_SEQ.NEXTVAL;
END;
/

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX IX_CLS_RESOURCES_TYPE ON CLS_RESOURCES(TYPE_ID);

CREATE INDEX IX_CLS_WORK_CATALOG_SORT ON CLS_WORK_CATALOG(SORT_ORDER, WORK_NO);
CREATE INDEX IX_CLS_WORK_CATALOG_LVL ON CLS_WORK_CATALOG(NUM1, NUM2, NUM3, WORK_NO);

CREATE INDEX IX_CLS_WORK_RESOURCES_WORK ON CLS_WORK_RESOURCES(WORK_ID);
CREATE INDEX IX_CLS_WORK_RESOURCES_RESOURCE ON CLS_WORK_RESOURCES(RESOURCE_ID);

CREATE INDEX IX_CLS_ESTIMATES_PROJECT ON CLS_ESTIMATES(PROJECT_ID);
CREATE INDEX IX_CLS_ESTIMATE_SECTIONS_EST ON CLS_ESTIMATE_SECTIONS(ESTIMATE_ID, SORT_ORDER);

CREATE INDEX IX_CLS_EST_ITEMS_EST ON CLS_ESTIMATE_ITEMS(ESTIMATE_ID);
CREATE INDEX IX_CLS_EST_ITEMS_SECTION ON CLS_ESTIMATE_ITEMS(SECTION_ID);
CREATE INDEX IX_CLS_EST_ITEMS_TYPE ON CLS_ESTIMATE_ITEMS(RESOURCE_TYPE_ID);
CREATE INDEX IX_CLS_EST_ITEMS_RESOURCE ON CLS_ESTIMATE_ITEMS(RESOURCE_ID);
/

-- ============================================================
-- Views
-- ============================================================

CREATE OR REPLACE VIEW V_CLS_RESOURCE_CATALOG AS
SELECT
  r.ID,
  r.RESOURCE_CODE,
  r.NAME,
  r.UNIT,
  r.BASE_QTY,
  r.PRICE,
  r.AMOUNT,
  r.SOURCE_DOC,
  r.SOURCE_ROW,
  r.NRDOC,
  r.NRR,
  r.IS_ACTIVE,
  rt.ID AS TYPE_ID,
  rt.CODE AS TYPE_CODE,
  rt.NAME_RU AS TYPE_NAME_RU,
  rt.NAME_RO AS TYPE_NAME_RO,
  rt.NAME_EN AS TYPE_NAME_EN
FROM CLS_RESOURCES r
JOIN CLS_RESOURCE_TYPES rt ON rt.ID = r.TYPE_ID;
/

CREATE OR REPLACE VIEW V_CLS_WORK_TREE AS
SELECT
  w.ID,
  w.WORK_NO,
  w.NUM1,
  w.NUM2,
  w.NUM3,
  w.NUM4,
  w.WORK_CODE,
  w.WORK_NAME,
  w.UNIT,
  w.PRICE,
  w.AMOUNT,
  w.LEVEL1_NAME,
  w.LEVEL2_NAME,
  w.LEVEL3_NAME,
  NVL(w.LEVEL1_NAME, '-') || ' / ' || NVL(w.LEVEL2_NAME, '-') || ' / ' || NVL(w.LEVEL3_NAME, '-') AS HIERARCHY_PATH,
  w.SORT_ORDER,
  w.SOURCE_DOC,
  w.SOURCE_ROW,
  w.NRDOC,
  w.IS_ACTIVE
FROM CLS_WORK_CATALOG w;
/

CREATE OR REPLACE VIEW V_CLS_ESTIMATE_TOTALS AS
SELECT
  e.ID AS ESTIMATE_ID,
  e.CODE AS ESTIMATE_CODE,
  rt.ID AS RESOURCE_TYPE_ID,
  rt.CODE AS RESOURCE_TYPE_CODE,
  rt.NAME_RU AS RESOURCE_TYPE_NAME,
  COUNT(i.ID) AS ITEMS_COUNT,
  NVL(SUM(i.AMOUNT), 0) AS TOTAL_AMOUNT
FROM CLS_ESTIMATES e
LEFT JOIN CLS_ESTIMATE_ITEMS i ON i.ESTIMATE_ID = e.ID
LEFT JOIN CLS_RESOURCE_TYPES rt ON rt.ID = i.RESOURCE_TYPE_ID
GROUP BY e.ID, e.CODE, rt.ID, rt.CODE, rt.NAME_RU;
/

COMMIT;
/
