-- ============================================================
-- Colass CRM module (CLS_CRM_)
-- Classic funnel: lead -> qualification -> estimate -> negotiation -> contract registration
-- Tables: 5
-- Sequences: 5
-- Triggers: 5
-- Views: 2
-- ============================================================

CREATE TABLE CLS_CRM_SOURCES (
  ID             NUMBER         NOT NULL,
  CODE           VARCHAR2(40)   NOT NULL,
  NAME_RU        VARCHAR2(200)  NOT NULL,
  NAME_RO        VARCHAR2(200)  NOT NULL,
  SORT_ORDER     NUMBER         DEFAULT 0 NOT NULL,
  IS_ACTIVE      CHAR(1)        DEFAULT 'Y' NOT NULL,
  CREATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CRM_SOURCES PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_CRM_SOURCES_CODE UNIQUE (CODE),
  CONSTRAINT CHK_CLS_CRM_SOURCES_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE CLS_CRM_STAGES (
  ID             NUMBER         NOT NULL,
  CODE           VARCHAR2(40)   NOT NULL,
  NAME_RU        VARCHAR2(200)  NOT NULL,
  NAME_RO        VARCHAR2(200)  NOT NULL,
  SORT_ORDER     NUMBER         DEFAULT 0 NOT NULL,
  IS_FINAL       CHAR(1)        DEFAULT 'N' NOT NULL,
  IS_WON         CHAR(1)        DEFAULT 'N' NOT NULL,
  IS_LOST        CHAR(1)        DEFAULT 'N' NOT NULL,
  IS_ACTIVE      CHAR(1)        DEFAULT 'Y' NOT NULL,
  CREATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CRM_STAGES PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_CRM_STAGES_CODE UNIQUE (CODE),
  CONSTRAINT CHK_CLS_CRM_STAGES_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CHK_CLS_CRM_STAGES_FINAL CHECK (IS_FINAL IN ('Y','N')),
  CONSTRAINT CHK_CLS_CRM_STAGES_WON CHECK (IS_WON IN ('Y','N')),
  CONSTRAINT CHK_CLS_CRM_STAGES_LOST CHECK (IS_LOST IN ('Y','N'))
);
/

CREATE TABLE CLS_CRM_LEADS (
  ID                  NUMBER          NOT NULL,
  LEAD_NO             VARCHAR2(80)    NOT NULL,
  SOURCE_ID           NUMBER          NOT NULL,
  STAGE_ID            NUMBER          NOT NULL,
  LANG_PREF           VARCHAR2(2)     DEFAULT 'ru' NOT NULL,
  CONTACT_NAME        VARCHAR2(300),
  COMPANY_NAME        VARCHAR2(500),
  PHONE               VARCHAR2(120),
  EMAIL               VARCHAR2(320),
  LOCATION            VARCHAR2(500),
  SUBJECT             VARCHAR2(1000),
  NEEDS_TEXT          CLOB,
  BUDGET_AMOUNT       NUMBER(18,4),
  CURRENCY            VARCHAR2(10)    DEFAULT 'MDL' NOT NULL,
  EXPECTED_CLOSE_DATE DATE,
  ASSIGNED_TO         VARCHAR2(120),
  PROJECT_ID          NUMBER,
  ESTIMATE_ID         NUMBER,
  CONTRACT_ID         NUMBER,
  EMAIL_FROM          VARCHAR2(500),
  EMAIL_SUBJECT       VARCHAR2(1000),
  EMAIL_MESSAGE_ID    VARCHAR2(1000),
  EMAIL_RECEIVED_AT   TIMESTAMP,
  EXTERNAL_REF        VARCHAR2(500),
  IS_ACTIVE           CHAR(1)         DEFAULT 'Y' NOT NULL,
  CREATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_ACTIVITY_AT    TIMESTAMP,
  CONSTRAINT PK_CLS_CRM_LEADS PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_CRM_LEADS_NO UNIQUE (LEAD_NO),
  CONSTRAINT UK_CLS_CRM_LEADS_MSG UNIQUE (EMAIL_MESSAGE_ID),
  CONSTRAINT FK_CLS_CRM_LEADS_SOURCE FOREIGN KEY (SOURCE_ID) REFERENCES CLS_CRM_SOURCES(ID),
  CONSTRAINT FK_CLS_CRM_LEADS_STAGE FOREIGN KEY (STAGE_ID) REFERENCES CLS_CRM_STAGES(ID),
  CONSTRAINT FK_CLS_CRM_LEADS_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES CLS_PROJECTS(ID),
  CONSTRAINT FK_CLS_CRM_LEADS_ESTIMATE FOREIGN KEY (ESTIMATE_ID) REFERENCES CLS_ESTIMATES(ID),
  CONSTRAINT CHK_CLS_CRM_LEADS_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE CLS_CRM_ACTIVITIES (
  ID             NUMBER          NOT NULL,
  LEAD_ID        NUMBER          NOT NULL,
  ACTIVITY_TYPE  VARCHAR2(60)    NOT NULL,
  NOTE_TEXT      CLOB,
  PAYLOAD_JSON   CLOB,
  CREATED_BY     VARCHAR2(120),
  CREATED_AT     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CRM_ACTIVITIES PRIMARY KEY (ID),
  CONSTRAINT FK_CLS_CRM_ACT_LEAD FOREIGN KEY (LEAD_ID) REFERENCES CLS_CRM_LEADS(ID)
);
/

CREATE TABLE CLS_CRM_CONTRACTS (
  ID               NUMBER          NOT NULL,
  CONTRACT_NO      VARCHAR2(80)    NOT NULL,
  LEAD_ID          NUMBER          NOT NULL,
  PROJECT_ID       NUMBER,
  ESTIMATE_ID      NUMBER,
  CONTRACT_DATE    DATE            DEFAULT TRUNC(SYSDATE) NOT NULL,
  AMOUNT           NUMBER(18,4)    DEFAULT 0 NOT NULL,
  CURRENCY         VARCHAR2(10)    DEFAULT 'MDL' NOT NULL,
  STATUS           VARCHAR2(40)    DEFAULT 'REGISTERED' NOT NULL,
  REGISTRY_NO      VARCHAR2(120),
  REGISTERED_AT    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
  NOTES            CLOB,
  CREATED_BY       VARCHAR2(120),
  CREATED_AT       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CRM_CONTRACTS PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_CRM_CONTRACT_NO UNIQUE (CONTRACT_NO),
  CONSTRAINT FK_CLS_CRM_CONTRACT_LEAD FOREIGN KEY (LEAD_ID) REFERENCES CLS_CRM_LEADS(ID),
  CONSTRAINT FK_CLS_CRM_CONTRACT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES CLS_PROJECTS(ID),
  CONSTRAINT FK_CLS_CRM_CONTRACT_ESTIMATE FOREIGN KEY (ESTIMATE_ID) REFERENCES CLS_ESTIMATES(ID)
);
/

ALTER TABLE CLS_CRM_LEADS
  ADD CONSTRAINT FK_CLS_CRM_LEADS_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CLS_CRM_CONTRACTS(ID);
/

CREATE SEQUENCE CLS_CRM_SOURCES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CRM_STAGES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CRM_LEADS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CRM_ACTIVITIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CRM_CONTRACTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE OR REPLACE TRIGGER CLS_CRM_SOURCES_BI
BEFORE INSERT ON CLS_CRM_SOURCES FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CRM_SOURCES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CRM_STAGES_BI
BEFORE INSERT ON CLS_CRM_STAGES FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CRM_STAGES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CRM_LEADS_BI
BEFORE INSERT ON CLS_CRM_LEADS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CRM_LEADS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CRM_ACTIVITIES_BI
BEFORE INSERT ON CLS_CRM_ACTIVITIES FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CRM_ACTIVITIES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CRM_CONTRACTS_BI
BEFORE INSERT ON CLS_CRM_CONTRACTS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CRM_CONTRACTS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_CLS_CRM_LEADS_STAGE ON CLS_CRM_LEADS(STAGE_ID, IS_ACTIVE);
CREATE INDEX IX_CLS_CRM_LEADS_SOURCE ON CLS_CRM_LEADS(SOURCE_ID, CREATED_AT);
CREATE INDEX IX_CLS_CRM_LEADS_EMAIL ON CLS_CRM_LEADS(EMAIL);
CREATE INDEX IX_CLS_CRM_LEADS_PHONE ON CLS_CRM_LEADS(PHONE);
CREATE INDEX IX_CLS_CRM_ACTIVITIES_LEAD ON CLS_CRM_ACTIVITIES(LEAD_ID, CREATED_AT);
CREATE INDEX IX_CLS_CRM_CONTRACTS_LEAD ON CLS_CRM_CONTRACTS(LEAD_ID, CONTRACT_DATE);
/

CREATE OR REPLACE VIEW V_CLS_CRM_LEADS AS
SELECT
  l.ID,
  l.LEAD_NO,
  l.LANG_PREF,
  l.CONTACT_NAME,
  l.COMPANY_NAME,
  l.PHONE,
  l.EMAIL,
  l.LOCATION,
  l.SUBJECT,
  l.NEEDS_TEXT,
  l.BUDGET_AMOUNT,
  l.CURRENCY,
  l.EXPECTED_CLOSE_DATE,
  l.ASSIGNED_TO,
  l.PROJECT_ID,
  p.NAME AS PROJECT_NAME,
  l.ESTIMATE_ID,
  e.NAME AS ESTIMATE_NAME,
  l.CONTRACT_ID,
  c.CONTRACT_NO,
  l.EMAIL_FROM,
  l.EMAIL_SUBJECT,
  l.EMAIL_MESSAGE_ID,
  l.EMAIL_RECEIVED_AT,
  l.EXTERNAL_REF,
  l.IS_ACTIVE,
  l.CREATED_AT,
  l.UPDATED_AT,
  l.LAST_ACTIVITY_AT,
  s.ID AS SOURCE_ID,
  s.CODE AS SOURCE_CODE,
  s.NAME_RU AS SOURCE_NAME_RU,
  s.NAME_RO AS SOURCE_NAME_RO,
  st.ID AS STAGE_ID,
  st.CODE AS STAGE_CODE,
  st.NAME_RU AS STAGE_NAME_RU,
  st.NAME_RO AS STAGE_NAME_RO,
  st.SORT_ORDER AS STAGE_SORT_ORDER,
  st.IS_FINAL,
  st.IS_WON,
  st.IS_LOST
FROM CLS_CRM_LEADS l
JOIN CLS_CRM_SOURCES s ON s.ID = l.SOURCE_ID
JOIN CLS_CRM_STAGES st ON st.ID = l.STAGE_ID
LEFT JOIN CLS_PROJECTS p ON p.ID = l.PROJECT_ID
LEFT JOIN CLS_ESTIMATES e ON e.ID = l.ESTIMATE_ID
LEFT JOIN CLS_CRM_CONTRACTS c ON c.ID = l.CONTRACT_ID;
/

CREATE OR REPLACE VIEW V_CLS_CRM_FUNNEL AS
SELECT
  st.ID AS STAGE_ID,
  st.CODE AS STAGE_CODE,
  st.NAME_RU AS STAGE_NAME_RU,
  st.NAME_RO AS STAGE_NAME_RO,
  st.SORT_ORDER,
  st.IS_FINAL,
  st.IS_WON,
  st.IS_LOST,
  COUNT(l.ID) AS LEADS_COUNT,
  NVL(SUM(l.BUDGET_AMOUNT), 0) AS BUDGET_TOTAL
FROM CLS_CRM_STAGES st
LEFT JOIN CLS_CRM_LEADS l ON l.STAGE_ID = st.ID AND l.IS_ACTIVE = 'Y'
WHERE st.IS_ACTIVE = 'Y'
GROUP BY st.ID, st.CODE, st.NAME_RU, st.NAME_RO, st.SORT_ORDER, st.IS_FINAL, st.IS_WON, st.IS_LOST;
/

MERGE INTO CLS_CRM_SOURCES t
USING (
  SELECT 'MANUAL' AS CODE, 'Ручной ввод' AS NAME_RU, 'Introducere manuală' AS NAME_RO, 10 AS SORT_ORDER FROM dual
  UNION ALL SELECT 'EMAIL', 'Email', 'Email', 20 FROM dual
  UNION ALL SELECT 'PHONE', 'Телефон', 'Telefon', 30 FROM dual
  UNION ALL SELECT 'WEBSITE', 'Сайт', 'Website', 40 FROM dual
  UNION ALL SELECT 'REFERRAL', 'Рекомендация', 'Recomandare', 50 FROM dual
) s
ON (t.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  t.NAME_RU = s.NAME_RU,
  t.NAME_RO = s.NAME_RO,
  t.SORT_ORDER = s.SORT_ORDER,
  t.IS_ACTIVE = 'Y',
  t.UPDATED_AT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (ID, CODE, NAME_RU, NAME_RO, SORT_ORDER, IS_ACTIVE)
  VALUES (NULL, s.CODE, s.NAME_RU, s.NAME_RO, s.SORT_ORDER, 'Y');
/

MERGE INTO CLS_CRM_STAGES t
USING (
  SELECT 'NEW' AS CODE, 'Новый лид' AS NAME_RU, 'Lead nou' AS NAME_RO, 10 AS SORT_ORDER, 'N' AS IS_FINAL, 'N' AS IS_WON, 'N' AS IS_LOST FROM dual
  UNION ALL SELECT 'QUALIFICATION', 'Квалификация', 'Calificare', 20, 'N', 'N', 'N' FROM dual
  UNION ALL SELECT 'ESTIMATE_PREP', 'Подготовка сметы', 'Pregătire deviz', 30, 'N', 'N', 'N' FROM dual
  UNION ALL SELECT 'NEGOTIATION', 'Переговоры', 'Negociere', 40, 'N', 'N', 'N' FROM dual
  UNION ALL SELECT 'APPROVED', 'Согласовано', 'Aprobat', 50, 'N', 'N', 'N' FROM dual
  UNION ALL SELECT 'CONTRACT_REGISTERED', 'Контракт зарегистрирован', 'Contract înregistrat', 60, 'Y', 'Y', 'N' FROM dual
  UNION ALL SELECT 'LOST', 'Потерян', 'Pierdut', 70, 'Y', 'N', 'Y' FROM dual
) s
ON (t.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  t.NAME_RU = s.NAME_RU,
  t.NAME_RO = s.NAME_RO,
  t.SORT_ORDER = s.SORT_ORDER,
  t.IS_FINAL = s.IS_FINAL,
  t.IS_WON = s.IS_WON,
  t.IS_LOST = s.IS_LOST,
  t.IS_ACTIVE = 'Y',
  t.UPDATED_AT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (ID, CODE, NAME_RU, NAME_RO, SORT_ORDER, IS_FINAL, IS_WON, IS_LOST, IS_ACTIVE)
  VALUES (NULL, s.CODE, s.NAME_RU, s.NAME_RO, s.SORT_ORDER, s.IS_FINAL, s.IS_WON, s.IS_LOST, 'Y');
/

COMMIT;
/
