-- ============================================================
-- Colass Contracts module (CLS_CONTRACT_*)
-- Conceptual clone of classic contract registry from GARA contracte module
-- Integrated with Colass CRM leads and Estimator
-- ============================================================

CREATE TABLE CLS_CONTRACTS (
  ID               NUMBER          NOT NULL,
  CONTRACT_NO      VARCHAR2(80)    NOT NULL,
  CONTRACT_DATE    DATE            DEFAULT TRUNC(SYSDATE) NOT NULL,
  LEGAL_FORM       VARCHAR2(60),
  COMPANY_NAME     VARCHAR2(500),
  ADDRESS          VARCHAR2(1000),
  FISCAL_CODE      VARCHAR2(120),
  VAT_CODE         VARCHAR2(120),
  BANK_NAME        VARCHAR2(500),
  BANK_BRANCH      VARCHAR2(500),
  BANK_BIC         VARCHAR2(120),
  IBAN_MDL         VARCHAR2(120),
  IBAN_EUR         VARCHAR2(120),
  IBAN_USD         VARCHAR2(120),
  CURRENCY         VARCHAR2(10)    DEFAULT 'MDL' NOT NULL,
  TOTAL_AMOUNT     NUMBER(18,4)    DEFAULT 0 NOT NULL,
  STATUS           VARCHAR2(40)    DEFAULT 'DRAFT' NOT NULL,
  NOTES            CLOB,
  PROJECT_ID       NUMBER,
  ESTIMATE_ID      NUMBER,
  CRM_LEAD_ID      NUMBER,
  CRM_CONTRACT_ID  NUMBER,
  CREATED_BY       VARCHAR2(120),
  CREATED_AT       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CONTRACTS PRIMARY KEY (ID),
  CONSTRAINT UK_CLS_CONTRACTS_NO UNIQUE (CONTRACT_NO),
  CONSTRAINT FK_CLS_CONTRACTS_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES CLS_PROJECTS(ID),
  CONSTRAINT FK_CLS_CONTRACTS_ESTIMATE FOREIGN KEY (ESTIMATE_ID) REFERENCES CLS_ESTIMATES(ID),
  CONSTRAINT FK_CLS_CONTRACTS_LEAD FOREIGN KEY (CRM_LEAD_ID) REFERENCES CLS_CRM_LEADS(ID),
  CONSTRAINT FK_CLS_CONTRACTS_CRM_CONTRACT FOREIGN KEY (CRM_CONTRACT_ID) REFERENCES CLS_CRM_CONTRACTS(ID)
);
/

CREATE TABLE CLS_CONTRACT_EMAILS (
  ID            NUMBER          NOT NULL,
  CONTRACT_ID   NUMBER          NOT NULL,
  SORT_ORDER    NUMBER          DEFAULT 0 NOT NULL,
  EMAIL         VARCHAR2(500)   NOT NULL,
  IS_PRIMARY    CHAR(1)         DEFAULT 'N' NOT NULL,
  CREATED_AT    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CONTRACT_EMAILS PRIMARY KEY (ID),
  CONSTRAINT FK_CLS_CONTRACT_EMAILS_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CLS_CONTRACTS(ID),
  CONSTRAINT CHK_CLS_CONTRACT_EMAILS_PRIMARY CHECK (IS_PRIMARY IN ('Y','N'))
);
/

CREATE TABLE CLS_CONTRACT_PHONES (
  ID            NUMBER          NOT NULL,
  CONTRACT_ID   NUMBER          NOT NULL,
  SORT_ORDER    NUMBER          DEFAULT 0 NOT NULL,
  PHONE         VARCHAR2(120)   NOT NULL,
  IS_PRIMARY    CHAR(1)         DEFAULT 'N' NOT NULL,
  CREATED_AT    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CONTRACT_PHONES PRIMARY KEY (ID),
  CONSTRAINT FK_CLS_CONTRACT_PHONES_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CLS_CONTRACTS(ID),
  CONSTRAINT CHK_CLS_CONTRACT_PHONES_PRIMARY CHECK (IS_PRIMARY IN ('Y','N'))
);
/

CREATE TABLE CLS_CONTRACT_ROUTES (
  ID            NUMBER          NOT NULL,
  CONTRACT_ID   NUMBER          NOT NULL,
  SORT_ORDER    NUMBER          DEFAULT 0 NOT NULL,
  ROUTE_NAME    VARCHAR2(1000)  NOT NULL,
  CREATED_AT    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CONTRACT_ROUTES PRIMARY KEY (ID),
  CONSTRAINT FK_CLS_CONTRACT_ROUTES_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CLS_CONTRACTS(ID)
);
/

CREATE TABLE CLS_CONTRACT_ITEMS (
  ID                NUMBER          NOT NULL,
  CONTRACT_ID       NUMBER          NOT NULL,
  ESTIMATE_ITEM_ID  NUMBER,
  RESOURCE_TYPE_ID  NUMBER,
  ITEM_CODE         VARCHAR2(120),
  ITEM_NAME         VARCHAR2(2000)  NOT NULL,
  UNIT              VARCHAR2(32),
  QTY               NUMBER(18,6)    DEFAULT 0 NOT NULL,
  PRICE             NUMBER(18,4)    DEFAULT 0 NOT NULL,
  AMOUNT            NUMBER(18,4)    DEFAULT 0 NOT NULL,
  SOURCE_DOC        VARCHAR2(30),
  SOURCE_ROW        NUMBER,
  CREATED_AT        TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CONTRACT_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_CLS_CONTRACT_ITEMS_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CLS_CONTRACTS(ID),
  CONSTRAINT FK_CLS_CONTRACT_ITEMS_EST_ITEM FOREIGN KEY (ESTIMATE_ITEM_ID) REFERENCES CLS_ESTIMATE_ITEMS(ID),
  CONSTRAINT FK_CLS_CONTRACT_ITEMS_TYPE FOREIGN KEY (RESOURCE_TYPE_ID) REFERENCES CLS_RESOURCE_TYPES(ID)
);
/

CREATE SEQUENCE CLS_CONTRACTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CONTRACT_EMAILS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CONTRACT_PHONES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CONTRACT_ROUTES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CONTRACT_ITEMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE OR REPLACE TRIGGER CLS_CONTRACTS_BI
BEFORE INSERT ON CLS_CONTRACTS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CONTRACTS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CONTRACT_EMAILS_BI
BEFORE INSERT ON CLS_CONTRACT_EMAILS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CONTRACT_EMAILS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CONTRACT_PHONES_BI
BEFORE INSERT ON CLS_CONTRACT_PHONES FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CONTRACT_PHONES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CONTRACT_ROUTES_BI
BEFORE INSERT ON CLS_CONTRACT_ROUTES FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CONTRACT_ROUTES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CONTRACT_ITEMS_BI
BEFORE INSERT ON CLS_CONTRACT_ITEMS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CONTRACT_ITEMS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_CLS_CONTRACTS_PROJECT ON CLS_CONTRACTS(PROJECT_ID);
CREATE INDEX IX_CLS_CONTRACTS_ESTIMATE ON CLS_CONTRACTS(ESTIMATE_ID);
CREATE INDEX IX_CLS_CONTRACTS_LEAD ON CLS_CONTRACTS(CRM_LEAD_ID);
CREATE INDEX IX_CLS_CONTRACTS_STATUS ON CLS_CONTRACTS(STATUS, CONTRACT_DATE);
CREATE INDEX IX_CLS_CONTRACT_EMAILS_CONTRACT ON CLS_CONTRACT_EMAILS(CONTRACT_ID);
CREATE INDEX IX_CLS_CONTRACT_PHONES_CONTRACT ON CLS_CONTRACT_PHONES(CONTRACT_ID);
CREATE INDEX IX_CLS_CONTRACT_ROUTES_CONTRACT ON CLS_CONTRACT_ROUTES(CONTRACT_ID);
CREATE INDEX IX_CLS_CONTRACT_ITEMS_CONTRACT ON CLS_CONTRACT_ITEMS(CONTRACT_ID);
/

CREATE OR REPLACE VIEW V_CLS_CONTRACTS AS
SELECT
  c.ID,
  c.CONTRACT_NO,
  c.CONTRACT_DATE,
  c.LEGAL_FORM,
  c.COMPANY_NAME,
  c.ADDRESS,
  c.FISCAL_CODE,
  c.VAT_CODE,
  c.BANK_NAME,
  c.BANK_BRANCH,
  c.BANK_BIC,
  c.IBAN_MDL,
  c.IBAN_EUR,
  c.IBAN_USD,
  c.CURRENCY,
  c.TOTAL_AMOUNT,
  c.STATUS,
  c.NOTES,
  c.PROJECT_ID,
  p.NAME AS PROJECT_NAME,
  c.ESTIMATE_ID,
  e.NAME AS ESTIMATE_NAME,
  c.CRM_LEAD_ID,
  l.LEAD_NO,
  l.CONTACT_NAME AS LEAD_CONTACT_NAME,
  l.COMPANY_NAME AS LEAD_COMPANY_NAME,
  c.CRM_CONTRACT_ID,
  cc.CONTRACT_NO AS CRM_CONTRACT_NO,
  (SELECT COUNT(*) FROM CLS_CONTRACT_ITEMS ci WHERE ci.CONTRACT_ID = c.ID) AS ITEMS_COUNT,
  (SELECT NVL(SUM(ci.AMOUNT),0) FROM CLS_CONTRACT_ITEMS ci WHERE ci.CONTRACT_ID = c.ID) AS ITEMS_TOTAL_AMOUNT,
  c.CREATED_BY,
  c.CREATED_AT,
  c.UPDATED_AT
FROM CLS_CONTRACTS c
LEFT JOIN CLS_PROJECTS p ON p.ID = c.PROJECT_ID
LEFT JOIN CLS_ESTIMATES e ON e.ID = c.ESTIMATE_ID
LEFT JOIN CLS_CRM_LEADS l ON l.ID = c.CRM_LEAD_ID
LEFT JOIN CLS_CRM_CONTRACTS cc ON cc.ID = c.CRM_CONTRACT_ID;
/

CREATE OR REPLACE VIEW V_CLS_CONTRACT_ITEMS_TOTALS AS
SELECT
  ci.CONTRACT_ID,
  NVL(rt.CODE, 'OTHER') AS TYPE_CODE,
  NVL(rt.NAME_RU, 'Прочее') AS TYPE_NAME_RU,
  NVL(rt.NAME_RO, 'Altele') AS TYPE_NAME_RO,
  COUNT(ci.ID) AS ITEMS_COUNT,
  NVL(SUM(ci.AMOUNT), 0) AS TOTAL_AMOUNT
FROM CLS_CONTRACT_ITEMS ci
LEFT JOIN CLS_RESOURCE_TYPES rt ON rt.ID = ci.RESOURCE_TYPE_ID
GROUP BY ci.CONTRACT_ID, NVL(rt.CODE, 'OTHER'), NVL(rt.NAME_RU, 'Прочее'), NVL(rt.NAME_RO, 'Altele');
/

COMMIT;
/
