-- ============================================================
-- Colass Contracts demo data
-- ============================================================

INSERT INTO CLS_CONTRACTS (
  ID, CONTRACT_NO, CONTRACT_DATE, LEGAL_FORM, COMPANY_NAME, ADDRESS,
  FISCAL_CODE, VAT_CODE, BANK_NAME, BANK_BRANCH, BANK_BIC,
  IBAN_MDL, CURRENCY, TOTAL_AMOUNT, STATUS,
  PROJECT_ID, ESTIMATE_ID, CRM_LEAD_ID, CRM_CONTRACT_ID, CREATED_BY, NOTES
)
SELECT
  NULL,
  'CLS-CON-DEMO-2026-0001',
  TRUNC(SYSDATE),
  'SRL',
  COALESCE(l.COMPANY_NAME, 'Moldovagaz Contracting'),
  COALESCE(l.LOCATION, 'Chisinau'),
  NULL,
  NULL,
  'BC MAIB SA',
  'Chisinau',
  'AGRNMD2X',
  'MD00AG000000000000000000',
  'MDL',
  COALESCE(e.TOTAL_AMOUNT, l.BUDGET_AMOUNT, 0),
  'REGISTERED',
  COALESCE(l.PROJECT_ID, e.PROJECT_ID),
  l.ESTIMATE_ID,
  l.ID,
  l.CONTRACT_ID,
  'demo',
  'Demo shell contract linked to CRM + estimate.'
FROM CLS_CRM_LEADS l
LEFT JOIN CLS_ESTIMATES e ON e.ID = l.ESTIMATE_ID
WHERE l.LEAD_NO = 'LEAD-CLS-2026-0001'
  AND NOT EXISTS (SELECT 1 FROM CLS_CONTRACTS c WHERE c.CONTRACT_NO = 'CLS-CON-DEMO-2026-0001');
/

INSERT INTO CLS_CONTRACT_EMAILS (ID, CONTRACT_ID, SORT_ORDER, EMAIL, IS_PRIMARY)
SELECT NULL, c.ID, 1, 'contracts@moldovagaz.example', 'Y'
FROM CLS_CONTRACTS c
WHERE c.CONTRACT_NO = 'CLS-CON-DEMO-2026-0001'
  AND NOT EXISTS (SELECT 1 FROM CLS_CONTRACT_EMAILS e WHERE e.CONTRACT_ID = c.ID AND e.EMAIL = 'contracts@moldovagaz.example');
/

INSERT INTO CLS_CONTRACT_PHONES (ID, CONTRACT_ID, SORT_ORDER, PHONE, IS_PRIMARY)
SELECT NULL, c.ID, 1, '+37322000001', 'Y'
FROM CLS_CONTRACTS c
WHERE c.CONTRACT_NO = 'CLS-CON-DEMO-2026-0001'
  AND NOT EXISTS (SELECT 1 FROM CLS_CONTRACT_PHONES p WHERE p.CONTRACT_ID = c.ID AND p.PHONE = '+37322000001');
/

INSERT INTO CLS_CONTRACT_ROUTES (ID, CONTRACT_ID, SORT_ORDER, ROUTE_NAME)
SELECT NULL, c.ID, 1, 'Chișinău - Sector Centru - Rețea gaze exterioară'
FROM CLS_CONTRACTS c
WHERE c.CONTRACT_NO = 'CLS-CON-DEMO-2026-0001'
  AND NOT EXISTS (SELECT 1 FROM CLS_CONTRACT_ROUTES r WHERE r.CONTRACT_ID = c.ID AND r.ROUTE_NAME = 'Chișinău - Sector Centru - Rețea gaze exterioară');
/

INSERT INTO CLS_CONTRACT_ITEMS (
  ID, CONTRACT_ID, ESTIMATE_ITEM_ID, RESOURCE_TYPE_ID, ITEM_CODE, ITEM_NAME, UNIT, QTY, PRICE, AMOUNT, SOURCE_DOC, SOURCE_ROW
)
SELECT
  NULL,
  c.ID,
  i.ID,
  i.RESOURCE_TYPE_ID,
  i.ITEM_CODE,
  i.ITEM_NAME,
  i.UNIT,
  i.QTY,
  i.PRICE,
  i.AMOUNT,
  i.SOURCE_DOC,
  i.SOURCE_ROW
FROM CLS_CONTRACTS c
JOIN CLS_ESTIMATE_ITEMS i ON i.ESTIMATE_ID = c.ESTIMATE_ID
WHERE c.CONTRACT_NO = 'CLS-CON-DEMO-2026-0001'
  AND NOT EXISTS (SELECT 1 FROM CLS_CONTRACT_ITEMS ci WHERE ci.CONTRACT_ID = c.ID)
  AND ROWNUM <= 40;
/

COMMIT;
/
