-- ============================================================
-- Colass Contracts: attachments + group approval workflow
-- ============================================================

CREATE TABLE CLS_CONTRACT_ATTACHMENTS (
  ID               NUMBER           NOT NULL,
  CONTRACT_ID      NUMBER           NOT NULL,
  TYPE_CODE        VARCHAR2(40)     NOT NULL,
  TYPE_NAME_RU     VARCHAR2(200),
  TYPE_NAME_RO     VARCHAR2(200),
  FILE_NAME        VARCHAR2(500)    NOT NULL,
  MIME_TYPE        VARCHAR2(200),
  FILE_SIZE        NUMBER,
  FILE_BLOB        BLOB             NOT NULL,
  IS_ACTIVE        CHAR(1)          DEFAULT 'Y' NOT NULL,
  UPLOADED_BY      VARCHAR2(120),
  CREATED_AT       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CLS_CONTRACT_ATTACHMENTS PRIMARY KEY (ID),
  CONSTRAINT FK_CLS_CONTRACT_ATTACH_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CLS_CONTRACTS(ID),
  CONSTRAINT CHK_CLS_CONTRACT_ATTACH_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);
/

CREATE TABLE CLS_CONTRACT_APPROVALS (
  ID               NUMBER           NOT NULL,
  CONTRACT_ID      NUMBER           NOT NULL,
  STATUS           VARCHAR2(30)     DEFAULT 'PENDING' NOT NULL,
  STARTED_BY       VARCHAR2(120),
  STARTED_AT       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FINISHED_AT      TIMESTAMP,
  COMMENT_TEXT     VARCHAR2(2000),
  CONSTRAINT PK_CLS_CONTRACT_APPROVALS PRIMARY KEY (ID),
  CONSTRAINT FK_CLS_CONTRACT_APPROVALS_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CLS_CONTRACTS(ID)
);
/

CREATE TABLE CLS_CONTRACT_APPROVAL_STEPS (
  ID               NUMBER           NOT NULL,
  APPROVAL_ID      NUMBER           NOT NULL,
  STEP_NO          NUMBER           NOT NULL,
  APPROVER_NAME    VARCHAR2(300)    NOT NULL,
  APPROVER_ROLE    VARCHAR2(200),
  DECISION         VARCHAR2(30)     DEFAULT 'PENDING' NOT NULL,
  DECIDED_BY       VARCHAR2(120),
  DECIDED_AT       TIMESTAMP,
  COMMENT_TEXT     VARCHAR2(2000),
  CONSTRAINT PK_CLS_CONTRACT_APPROVAL_STEPS PRIMARY KEY (ID),
  CONSTRAINT FK_CLS_CONTRACT_APPROVAL_STEP_APP FOREIGN KEY (APPROVAL_ID) REFERENCES CLS_CONTRACT_APPROVALS(ID)
);
/

CREATE SEQUENCE CLS_CONTRACT_ATTACHMENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CONTRACT_APPROVALS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE CLS_CONTRACT_APPROVAL_STEPS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE OR REPLACE TRIGGER CLS_CONTRACT_ATTACHMENTS_BI
BEFORE INSERT ON CLS_CONTRACT_ATTACHMENTS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CONTRACT_ATTACHMENTS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CONTRACT_APPROVALS_BI
BEFORE INSERT ON CLS_CONTRACT_APPROVALS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CONTRACT_APPROVALS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER CLS_CONTRACT_APPROVAL_STEPS_BI
BEFORE INSERT ON CLS_CONTRACT_APPROVAL_STEPS FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := CLS_CONTRACT_APPROVAL_STEPS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_CLS_CONTRACT_ATTACH_CONTRACT ON CLS_CONTRACT_ATTACHMENTS(CONTRACT_ID, TYPE_CODE, IS_ACTIVE);
CREATE INDEX IX_CLS_CONTRACT_APPROVALS_CONTRACT ON CLS_CONTRACT_APPROVALS(CONTRACT_ID, STATUS);
CREATE INDEX IX_CLS_CONTRACT_APPROVAL_STEPS_APP ON CLS_CONTRACT_APPROVAL_STEPS(APPROVAL_ID, STEP_NO, DECISION);
/

CREATE OR REPLACE VIEW V_CLS_CONTRACT_ATTACHMENT_CHECK AS
SELECT
  c.ID AS CONTRACT_ID,
  c.CONTRACT_NO,
  MAX(CASE WHEN a.TYPE_CODE = 'FINANCIAL_TERMS' AND a.IS_ACTIVE = 'Y' THEN 1 ELSE 0 END) AS HAS_FINANCIAL_TERMS,
  MAX(CASE WHEN a.TYPE_CODE = 'ESTIMATE_TERMS' AND a.IS_ACTIVE = 'Y' THEN 1 ELSE 0 END) AS HAS_ESTIMATE_TERMS,
  MAX(CASE WHEN a.TYPE_CODE = 'PRICE_LIST' AND a.IS_ACTIVE = 'Y' THEN 1 ELSE 0 END) AS HAS_PRICE_LIST,
  COUNT(CASE WHEN a.IS_ACTIVE = 'Y' THEN 1 END) AS ATTACHMENTS_COUNT
FROM CLS_CONTRACTS c
LEFT JOIN CLS_CONTRACT_ATTACHMENTS a ON a.CONTRACT_ID = c.ID
GROUP BY c.ID, c.CONTRACT_NO;
/

COMMIT;
/
