-- ============================================================
-- AGRO module (AGRO_*) — fruit/vegetable warehouse management
-- Tables:    36
-- Sequences: 36
-- Triggers:  (separate file)
-- Views:     (separate file)
--
-- Covers: suppliers, customers, warehouses, storage cells,
--         items, packaging, vehicles, currencies, exchange rates,
--         formula params, module config, barcodes, crates,
--         purchase docs/lines, batches, batch-crates,
--         stock movements, storage readings/alerts,
--         processing tasks, QA checklists/checks,
--         HACCP plans/CCPs/records, sales docs/lines,
--         export declarations, batch allocations,
--         audit log, attachments, event log.
-- ============================================================

-- ============================================================
-- 1. SEQUENCES (36)
-- ============================================================

CREATE SEQUENCE AGRO_SUPPLIERS_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_CUSTOMERS_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_WAREHOUSES_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_STORAGE_CELLS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_ITEMS_SEQ            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_PACKAGING_TYPES_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_VEHICLES_SEQ         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_CURRENCIES_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_EXCHANGE_RATES_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_FORMULA_PARAMS_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_MODULE_CONFIG_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_BARCODES_SEQ         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_CRATES_SEQ           START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_PURCHASE_DOCS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_PURCHASE_LINES_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_BATCHES_SEQ          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_BATCH_CRATES_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_STOCK_MOVEMENTS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_STORAGE_READINGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_STORAGE_ALERTS_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_PROCESSING_TASKS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_QA_CHECKLISTS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_QA_CHECKLIST_ITEMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_QA_CHECKS_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_QA_CHECK_VALUES_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_BATCH_BLOCKS_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_HACCP_PLANS_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_HACCP_CCPS_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_HACCP_RECORDS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_SALES_DOCS_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_SALES_LINES_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_EXPORT_DECLS_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_BATCH_ALLOCATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_AUDIT_LOG_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_ATTACHMENTS_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_EVENT_LOG_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- 2. TABLES — Master Data (11 tables)
-- ============================================================

-- 1. AGRO_SUPPLIERS
CREATE TABLE AGRO_SUPPLIERS (
  ID             NUMBER          NOT NULL,
  CODE           VARCHAR2(50)    NOT NULL,
  NAME           VARCHAR2(300)   NOT NULL,
  COUNTRY        VARCHAR2(100),
  TAX_ID         VARCHAR2(50),
  CONTACT_PHONE  VARCHAR2(50),
  CONTACT_EMAIL  VARCHAR2(200),
  ADDRESS        VARCHAR2(500),
  ACTIVE         CHAR(1)         DEFAULT 'Y',
  CREATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_SUPPLIERS       PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_SUPPLIERS_CODE  UNIQUE (CODE),
  CONSTRAINT CK_AGRO_SUPPLIERS_ACT   CHECK (ACTIVE IN ('Y','N'))
);
/

-- 2. AGRO_CUSTOMERS
CREATE TABLE AGRO_CUSTOMERS (
  ID             NUMBER          NOT NULL,
  CODE           VARCHAR2(50)    NOT NULL,
  NAME           VARCHAR2(300)   NOT NULL,
  COUNTRY        VARCHAR2(100),
  TAX_ID         VARCHAR2(50),
  CONTACT_PHONE  VARCHAR2(50),
  CONTACT_EMAIL  VARCHAR2(200),
  ADDRESS        VARCHAR2(500),
  CUSTOMER_TYPE  VARCHAR2(20)    DEFAULT 'domestic',
  ACTIVE         CHAR(1)         DEFAULT 'Y',
  CREATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CUSTOMERS       PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_CUSTOMERS_CODE  UNIQUE (CODE),
  CONSTRAINT CK_AGRO_CUSTOMERS_TYPE  CHECK (CUSTOMER_TYPE IN ('domestic','export')),
  CONSTRAINT CK_AGRO_CUSTOMERS_ACT   CHECK (ACTIVE IN ('Y','N'))
);
/

-- 3. AGRO_WAREHOUSES
CREATE TABLE AGRO_WAREHOUSES (
  ID             NUMBER          NOT NULL,
  CODE           VARCHAR2(50)    NOT NULL,
  NAME           VARCHAR2(300)   NOT NULL,
  WAREHOUSE_TYPE VARCHAR2(20)    DEFAULT 'cold_storage',
  ADDRESS        VARCHAR2(500),
  CAPACITY_KG    NUMBER(14,2),
  ACTIVE         CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_WAREHOUSES       PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_WAREHOUSES_CODE  UNIQUE (CODE),
  CONSTRAINT CK_AGRO_WAREHOUSES_TYPE  CHECK (WAREHOUSE_TYPE IN ('cold_storage','dry','processing')),
  CONSTRAINT CK_AGRO_WAREHOUSES_ACT   CHECK (ACTIVE IN ('Y','N'))
);
/

-- 4. AGRO_STORAGE_CELLS (FK → AGRO_WAREHOUSES)
CREATE TABLE AGRO_STORAGE_CELLS (
  ID             NUMBER          NOT NULL,
  WAREHOUSE_ID   NUMBER          NOT NULL,
  CODE           VARCHAR2(50)    NOT NULL,
  NAME           VARCHAR2(300),
  CELL_TYPE      VARCHAR2(20)    DEFAULT 'chamber',
  TEMP_MIN       NUMBER(5,2),
  TEMP_MAX       NUMBER(5,2),
  HUMIDITY_MIN   NUMBER(5,2),
  HUMIDITY_MAX   NUMBER(5,2),
  CAPACITY_KG    NUMBER(14,2),
  ACTIVE         CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_STORAGE_CELLS      PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_SC_WAREHOUSE       FOREIGN KEY (WAREHOUSE_ID) REFERENCES AGRO_WAREHOUSES(ID),
  CONSTRAINT CK_AGRO_SC_TYPE            CHECK (CELL_TYPE IN ('chamber','section','zone')),
  CONSTRAINT CK_AGRO_SC_ACT             CHECK (ACTIVE IN ('Y','N'))
);
/

-- 5. AGRO_ITEMS
CREATE TABLE AGRO_ITEMS (
  ID              NUMBER          NOT NULL,
  CODE            VARCHAR2(50)    NOT NULL,
  NAME_RU         VARCHAR2(300)   NOT NULL,
  NAME_RO         VARCHAR2(300),
  ITEM_GROUP      VARCHAR2(20)    DEFAULT 'fruit',
  UNIT            VARCHAR2(10)    DEFAULT 'kg',
  DEFAULT_TARE_KG NUMBER(8,3)     DEFAULT 0,
  SHELF_LIFE_DAYS NUMBER,
  OPTIMAL_TEMP_MIN NUMBER(5,2),
  OPTIMAL_TEMP_MAX NUMBER(5,2),
  ACTIVE          CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_ITEMS       PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_ITEMS_CODE  UNIQUE (CODE),
  CONSTRAINT CK_AGRO_ITEMS_GRP   CHECK (ITEM_GROUP IN ('fruit','vegetable','berry')),
  CONSTRAINT CK_AGRO_ITEMS_ACT   CHECK (ACTIVE IN ('Y','N'))
);
/

-- 6. AGRO_PACKAGING_TYPES
CREATE TABLE AGRO_PACKAGING_TYPES (
  ID              NUMBER          NOT NULL,
  CODE            VARCHAR2(50)    NOT NULL,
  NAME_RU         VARCHAR2(300)   NOT NULL,
  NAME_RO         VARCHAR2(300),
  TARE_WEIGHT_KG  NUMBER(8,3)     DEFAULT 0,
  CAPACITY_KG     NUMBER(8,2),
  ACTIVE          CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_PACKAGING_TYPES      PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_PACKAGING_TYPES_CODE UNIQUE (CODE),
  CONSTRAINT CK_AGRO_PT_ACT              CHECK (ACTIVE IN ('Y','N'))
);
/

-- 7. AGRO_VEHICLES
CREATE TABLE AGRO_VEHICLES (
  ID            NUMBER          NOT NULL,
  PLATE_NUMBER  VARCHAR2(20)    NOT NULL,
  VEHICLE_TYPE  VARCHAR2(20)    DEFAULT 'truck',
  DRIVER_NAME   VARCHAR2(200),
  ACTIVE        CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_VEHICLES         PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_VEHICLES_PLATE   UNIQUE (PLATE_NUMBER),
  CONSTRAINT CK_AGRO_VEHICLES_TYPE    CHECK (VEHICLE_TYPE IN ('truck','van','refrigerator')),
  CONSTRAINT CK_AGRO_VEHICLES_ACT     CHECK (ACTIVE IN ('Y','N'))
);
/

-- 8. AGRO_CURRENCIES
CREATE TABLE AGRO_CURRENCIES (
  ID      NUMBER          NOT NULL,
  CODE    VARCHAR2(3)     NOT NULL,
  NAME    VARCHAR2(100),
  SYMBOL  VARCHAR2(10),
  ACTIVE  CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_CURRENCIES      PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_CURRENCIES_CODE UNIQUE (CODE),
  CONSTRAINT CK_AGRO_CURRENCIES_ACT  CHECK (ACTIVE IN ('Y','N'))
);
/

-- 9. AGRO_EXCHANGE_RATES
CREATE TABLE AGRO_EXCHANGE_RATES (
  ID             NUMBER          NOT NULL,
  FROM_CURRENCY  VARCHAR2(3)     NOT NULL,
  TO_CURRENCY    VARCHAR2(3)     NOT NULL,
  RATE           NUMBER(14,6)    NOT NULL,
  RATE_DATE      DATE            NOT NULL,
  SOURCE         VARCHAR2(100),
  CONSTRAINT PK_AGRO_EXCHANGE_RATES PRIMARY KEY (ID)
);
/

-- 10. AGRO_FORMULA_PARAMS
CREATE TABLE AGRO_FORMULA_PARAMS (
  ID           NUMBER          NOT NULL,
  ITEM_ID      NUMBER,
  PARAM_NAME   VARCHAR2(100)   NOT NULL,
  PARAM_VALUE  VARCHAR2(500),
  ACTIVE       CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_FORMULA_PARAMS  PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_FP_ITEM         FOREIGN KEY (ITEM_ID) REFERENCES AGRO_ITEMS(ID),
  CONSTRAINT CK_AGRO_FP_ACT          CHECK (ACTIVE IN ('Y','N'))
);
/

-- 11. AGRO_MODULE_CONFIG
CREATE TABLE AGRO_MODULE_CONFIG (
  ID            NUMBER          NOT NULL,
  CONFIG_KEY    VARCHAR2(100)   NOT NULL,
  CONFIG_VALUE  VARCHAR2(1000),
  CONFIG_GROUP  VARCHAR2(50),
  DESCRIPTION   VARCHAR2(500),
  CONSTRAINT PK_AGRO_MODULE_CONFIG      PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_MODULE_CONFIG_KEY  UNIQUE (CONFIG_KEY)
);
/

-- ============================================================
-- 3. TABLES — Barcodes & Crates (3 tables)
-- ============================================================

-- 12. AGRO_BARCODES (BATCH_ID is a nullable loose reference, no FK)
CREATE TABLE AGRO_BARCODES (
  ID            NUMBER          NOT NULL,
  BARCODE       VARCHAR2(100)   NOT NULL,
  BARCODE_TYPE  VARCHAR2(20)    DEFAULT 'internal',
  GENERATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP,
  PRINTED       CHAR(1)         DEFAULT 'N',
  ASSIGNED      CHAR(1)         DEFAULT 'N',
  BATCH_ID      NUMBER,
  CONSTRAINT PK_AGRO_BARCODES          PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_BARCODES_CODE     UNIQUE (BARCODE),
  CONSTRAINT CK_AGRO_BARCODES_TYPE     CHECK (BARCODE_TYPE IN ('internal','external','ean13','qr')),
  CONSTRAINT CK_AGRO_BARCODES_PRINTED  CHECK (PRINTED IN ('Y','N')),
  CONSTRAINT CK_AGRO_BARCODES_ASSIGNED CHECK (ASSIGNED IN ('Y','N'))
);
/

-- 13. AGRO_CRATES (FK → AGRO_BARCODES, AGRO_PACKAGING_TYPES)
CREATE TABLE AGRO_CRATES (
  ID                NUMBER          NOT NULL,
  BARCODE_ID        NUMBER,
  EXTERNAL_BARCODE  VARCHAR2(100),
  PACKAGING_TYPE_ID NUMBER,
  GROSS_WEIGHT_KG   NUMBER(10,3),
  TARE_WEIGHT_KG    NUMBER(10,3),
  NET_WEIGHT_KG     NUMBER(10,3),
  STATUS            VARCHAR2(20)    DEFAULT 'empty',
  CREATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_CRATES          PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_CRATES_BARCODE  FOREIGN KEY (BARCODE_ID) REFERENCES AGRO_BARCODES(ID),
  CONSTRAINT FK_AGRO_CRATES_PKG      FOREIGN KEY (PACKAGING_TYPE_ID) REFERENCES AGRO_PACKAGING_TYPES(ID),
  CONSTRAINT CK_AGRO_CRATES_STATUS   CHECK (STATUS IN ('empty','filled','weighed','accepted','stored','shipped'))
);
/

-- ============================================================
-- 4. TABLES — Purchases & Batches (4 tables)
-- ============================================================

-- 14. AGRO_PURCHASE_DOCS (FK → AGRO_SUPPLIERS, AGRO_WAREHOUSES, AGRO_VEHICLES, AGRO_CURRENCIES)
CREATE TABLE AGRO_PURCHASE_DOCS (
  ID               NUMBER          NOT NULL,
  DOC_NUMBER       VARCHAR2(50)    NOT NULL,
  DOC_DATE         DATE            NOT NULL,
  SUPPLIER_ID      NUMBER          NOT NULL,
  WAREHOUSE_ID     NUMBER          NOT NULL,
  VEHICLE_ID       NUMBER,
  CURRENCY_ID      NUMBER,
  STATUS           VARCHAR2(20)    DEFAULT 'draft',
  TOTAL_GROSS_KG   NUMBER(14,3),
  TOTAL_NET_KG     NUMBER(14,3),
  TOTAL_AMOUNT     NUMBER(14,2),
  ADVANCE_AMOUNT   NUMBER(14,2)    DEFAULT 0,
  TRANSFER_AMOUNT  NUMBER(14,2)    DEFAULT 0,
  E_FACTURA_REF    VARCHAR2(100),
  ADDITIONAL_COSTS NUMBER(14,2)    DEFAULT 0,
  NOTES            VARCHAR2(2000),
  CREATED_BY       VARCHAR2(100),
  CREATED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONFIRMED_AT     TIMESTAMP,
  CONSTRAINT PK_AGRO_PURCHASE_DOCS      PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_PD_DOCNUM          UNIQUE (DOC_NUMBER),
  CONSTRAINT FK_AGRO_PD_SUPPLIER        FOREIGN KEY (SUPPLIER_ID) REFERENCES AGRO_SUPPLIERS(ID),
  CONSTRAINT FK_AGRO_PD_WAREHOUSE       FOREIGN KEY (WAREHOUSE_ID) REFERENCES AGRO_WAREHOUSES(ID),
  CONSTRAINT FK_AGRO_PD_VEHICLE         FOREIGN KEY (VEHICLE_ID) REFERENCES AGRO_VEHICLES(ID),
  CONSTRAINT FK_AGRO_PD_CURRENCY        FOREIGN KEY (CURRENCY_ID) REFERENCES AGRO_CURRENCIES(ID),
  CONSTRAINT CK_AGRO_PD_STATUS          CHECK (STATUS IN ('draft','confirmed','closed','cancelled'))
);
/

-- 15. AGRO_PURCHASE_LINES (FK → AGRO_PURCHASE_DOCS, AGRO_ITEMS)
CREATE TABLE AGRO_PURCHASE_LINES (
  ID              NUMBER          NOT NULL,
  PURCHASE_DOC_ID NUMBER          NOT NULL,
  ITEM_ID         NUMBER          NOT NULL,
  PALLETS         NUMBER          DEFAULT 0,
  CRATES_COUNT    NUMBER          DEFAULT 0,
  GROSS_WEIGHT_KG NUMBER(14,3),
  TARE_WEIGHT_KG  NUMBER(14,3),
  NET_WEIGHT_KG   NUMBER(14,3),
  PRICE_PER_KG    NUMBER(14,4),
  AMOUNT          NUMBER(14,2),
  NOTES           VARCHAR2(1000),
  CONSTRAINT PK_AGRO_PURCHASE_LINES    PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_PL_DOC            FOREIGN KEY (PURCHASE_DOC_ID) REFERENCES AGRO_PURCHASE_DOCS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AGRO_PL_ITEM           FOREIGN KEY (ITEM_ID) REFERENCES AGRO_ITEMS(ID)
);
/

-- 16. AGRO_BATCHES (FK → AGRO_PURCHASE_LINES, AGRO_ITEMS, AGRO_WAREHOUSES, AGRO_STORAGE_CELLS)
CREATE TABLE AGRO_BATCHES (
  ID               NUMBER          NOT NULL,
  BATCH_NUMBER     VARCHAR2(50)    NOT NULL,
  PURCHASE_LINE_ID NUMBER,
  ITEM_ID          NUMBER          NOT NULL,
  WAREHOUSE_ID     NUMBER,
  CELL_ID          NUMBER,
  INITIAL_QTY_KG   NUMBER(14,3),
  CURRENT_QTY_KG   NUMBER(14,3),
  STATUS           VARCHAR2(20)    DEFAULT 'active',
  RECEIVED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
  EXPIRY_DATE      DATE,
  BLOCKED_BY       VARCHAR2(100),
  BLOCK_REASON     VARCHAR2(500),
  NOTES            VARCHAR2(1000),
  CONSTRAINT PK_AGRO_BATCHES           PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_BATCHES_NUM       UNIQUE (BATCH_NUMBER),
  CONSTRAINT FK_AGRO_BAT_PL            FOREIGN KEY (PURCHASE_LINE_ID) REFERENCES AGRO_PURCHASE_LINES(ID),
  CONSTRAINT FK_AGRO_BAT_ITEM          FOREIGN KEY (ITEM_ID) REFERENCES AGRO_ITEMS(ID),
  CONSTRAINT FK_AGRO_BAT_WH            FOREIGN KEY (WAREHOUSE_ID) REFERENCES AGRO_WAREHOUSES(ID),
  CONSTRAINT FK_AGRO_BAT_CELL          FOREIGN KEY (CELL_ID) REFERENCES AGRO_STORAGE_CELLS(ID),
  CONSTRAINT CK_AGRO_BAT_STATUS        CHECK (STATUS IN ('active','blocked','depleted','expired'))
);
/

-- 17. AGRO_BATCH_CRATES (FK → AGRO_BATCHES, AGRO_CRATES)
CREATE TABLE AGRO_BATCH_CRATES (
  ID        NUMBER          NOT NULL,
  BATCH_ID  NUMBER          NOT NULL,
  CRATE_ID  NUMBER          NOT NULL,
  CONSTRAINT PK_AGRO_BATCH_CRATES      PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_BC_BATCH          FOREIGN KEY (BATCH_ID) REFERENCES AGRO_BATCHES(ID),
  CONSTRAINT FK_AGRO_BC_CRATE          FOREIGN KEY (CRATE_ID) REFERENCES AGRO_CRATES(ID)
);
/

-- ============================================================
-- 5. TABLES — Warehouse & Storage (4 tables)
-- ============================================================

-- 18. AGRO_STOCK_MOVEMENTS (FK → AGRO_BATCHES)
CREATE TABLE AGRO_STOCK_MOVEMENTS (
  ID                NUMBER          NOT NULL,
  BATCH_ID          NUMBER          NOT NULL,
  MOVEMENT_TYPE     VARCHAR2(20)    NOT NULL,
  FROM_WAREHOUSE_ID NUMBER,
  FROM_CELL_ID      NUMBER,
  TO_WAREHOUSE_ID   NUMBER,
  TO_CELL_ID        NUMBER,
  QTY_KG            NUMBER(14,3)    NOT NULL,
  REASON            VARCHAR2(500),
  DOC_REF           VARCHAR2(100),
  CREATED_BY        VARCHAR2(100),
  CREATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_STOCK_MOVEMENTS   PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_SM_BATCH          FOREIGN KEY (BATCH_ID) REFERENCES AGRO_BATCHES(ID),
  CONSTRAINT CK_AGRO_SM_TYPE           CHECK (MOVEMENT_TYPE IN ('receipt','transfer','processing','shipment','adjustment','loss'))
);
/

-- 19. AGRO_STORAGE_READINGS (FK → AGRO_STORAGE_CELLS)
CREATE TABLE AGRO_STORAGE_READINGS (
  ID              NUMBER          NOT NULL,
  CELL_ID         NUMBER          NOT NULL,
  TEMPERATURE_C   NUMBER(5,2),
  HUMIDITY_PCT    NUMBER(5,2),
  O2_PCT          NUMBER(5,2),
  CO2_PCT         NUMBER(5,2),
  READING_SOURCE  VARCHAR2(10)    DEFAULT 'manual',
  SENSOR_ID       VARCHAR2(50),
  RECORDED_BY     VARCHAR2(100),
  RECORDED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_STORAGE_READINGS  PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_SR_CELL           FOREIGN KEY (CELL_ID) REFERENCES AGRO_STORAGE_CELLS(ID),
  CONSTRAINT CK_AGRO_SR_SOURCE         CHECK (READING_SOURCE IN ('manual','sensor'))
);
/

-- 20. AGRO_STORAGE_ALERTS (FK → AGRO_STORAGE_CELLS, AGRO_STORAGE_READINGS)
CREATE TABLE AGRO_STORAGE_ALERTS (
  ID               NUMBER          NOT NULL,
  CELL_ID          NUMBER          NOT NULL,
  READING_ID       NUMBER,
  ALERT_TYPE       VARCHAR2(20)    NOT NULL,
  THRESHOLD_VALUE  NUMBER(8,2),
  ACTUAL_VALUE     NUMBER(8,2),
  ACKNOWLEDGED     CHAR(1)         DEFAULT 'N',
  ACKNOWLEDGED_BY  VARCHAR2(100),
  ACKNOWLEDGED_AT  TIMESTAMP,
  CREATED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_STORAGE_ALERTS   PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_SA_CELL          FOREIGN KEY (CELL_ID) REFERENCES AGRO_STORAGE_CELLS(ID),
  CONSTRAINT FK_AGRO_SA_READING       FOREIGN KEY (READING_ID) REFERENCES AGRO_STORAGE_READINGS(ID),
  CONSTRAINT CK_AGRO_SA_TYPE          CHECK (ALERT_TYPE IN ('temp_high','temp_low','humidity','o2','co2')),
  CONSTRAINT CK_AGRO_SA_ACK           CHECK (ACKNOWLEDGED IN ('Y','N'))
);
/

-- 21. AGRO_PROCESSING_TASKS (FK → AGRO_BATCHES)
CREATE TABLE AGRO_PROCESSING_TASKS (
  ID             NUMBER          NOT NULL,
  BATCH_ID       NUMBER          NOT NULL,
  TASK_TYPE      VARCHAR2(20)    DEFAULT 'sorting',
  DESCRIPTION    VARCHAR2(500),
  ASSIGNED_TO    VARCHAR2(100),
  STATUS         VARCHAR2(20)    DEFAULT 'pending',
  INPUT_QTY_KG   NUMBER(14,3),
  OUTPUT_QTY_KG  NUMBER(14,3),
  WASTE_QTY_KG   NUMBER(14,3),
  STARTED_AT     TIMESTAMP,
  COMPLETED_AT   TIMESTAMP,
  NOTES          VARCHAR2(1000),
  CONSTRAINT PK_AGRO_PROCESSING_TASKS  PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_PT_BATCH          FOREIGN KEY (BATCH_ID) REFERENCES AGRO_BATCHES(ID),
  CONSTRAINT CK_AGRO_PT_TYPE           CHECK (TASK_TYPE IN ('sorting','washing','packing','labeling','other')),
  CONSTRAINT CK_AGRO_PT_STATUS         CHECK (STATUS IN ('pending','in_progress','completed','cancelled'))
);
/

-- ============================================================
-- 6. TABLES — Quality & HACCP (8 tables)
-- ============================================================

-- 22. AGRO_QA_CHECKLISTS
CREATE TABLE AGRO_QA_CHECKLISTS (
  ID              NUMBER          NOT NULL,
  CODE            VARCHAR2(50)    NOT NULL,
  NAME_RU         VARCHAR2(300)   NOT NULL,
  NAME_RO         VARCHAR2(300),
  CHECKLIST_TYPE  VARCHAR2(20)    DEFAULT 'incoming',
  ACTIVE          CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_QA_CHECKLISTS      PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_QA_CHECKLISTS_CODE UNIQUE (CODE),
  CONSTRAINT CK_AGRO_QAC_TYPE           CHECK (CHECKLIST_TYPE IN ('incoming','gmp','sanitary','packaging')),
  CONSTRAINT CK_AGRO_QAC_ACT            CHECK (ACTIVE IN ('Y','N'))
);
/

-- 23. AGRO_QA_CHECKLIST_ITEMS (FK → AGRO_QA_CHECKLISTS)
CREATE TABLE AGRO_QA_CHECKLIST_ITEMS (
  ID                 NUMBER          NOT NULL,
  CHECKLIST_ID       NUMBER          NOT NULL,
  ITEM_ORDER         NUMBER          DEFAULT 0,
  PARAMETER_NAME_RU  VARCHAR2(300)   NOT NULL,
  PARAMETER_NAME_RO  VARCHAR2(300),
  VALUE_TYPE         VARCHAR2(10)    DEFAULT 'boolean',
  MIN_VALUE          NUMBER(10,3),
  MAX_VALUE          NUMBER(10,3),
  CHOICES            VARCHAR2(1000),
  IS_CRITICAL        CHAR(1)         DEFAULT 'N',
  CONSTRAINT PK_AGRO_QA_CHECKLIST_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_QCI_CHECKLIST      FOREIGN KEY (CHECKLIST_ID) REFERENCES AGRO_QA_CHECKLISTS(ID) ON DELETE CASCADE,
  CONSTRAINT CK_AGRO_QCI_VTYPE          CHECK (VALUE_TYPE IN ('boolean','numeric','text','choice')),
  CONSTRAINT CK_AGRO_QCI_CRIT           CHECK (IS_CRITICAL IN ('Y','N'))
);
/

-- 24. AGRO_QA_CHECKS (FK → AGRO_BATCHES, AGRO_QA_CHECKLISTS)
CREATE TABLE AGRO_QA_CHECKS (
  ID            NUMBER          NOT NULL,
  BATCH_ID      NUMBER          NOT NULL,
  CHECKLIST_ID  NUMBER          NOT NULL,
  CHECK_DATE    DATE            DEFAULT TRUNC(SYSDATE),
  RESULT        VARCHAR2(20),
  INSPECTOR     VARCHAR2(100),
  NOTES         VARCHAR2(1000),
  CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_QA_CHECKS        PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_QAK_BATCH        FOREIGN KEY (BATCH_ID) REFERENCES AGRO_BATCHES(ID),
  CONSTRAINT FK_AGRO_QAK_CHECKLIST    FOREIGN KEY (CHECKLIST_ID) REFERENCES AGRO_QA_CHECKLISTS(ID),
  CONSTRAINT CK_AGRO_QAK_RESULT       CHECK (RESULT IN ('pass','fail','conditional'))
);
/

-- 25. AGRO_QA_CHECK_VALUES (FK → AGRO_QA_CHECKS, AGRO_QA_CHECKLIST_ITEMS)
CREATE TABLE AGRO_QA_CHECK_VALUES (
  ID                NUMBER          NOT NULL,
  CHECK_ID          NUMBER          NOT NULL,
  CHECKLIST_ITEM_ID NUMBER          NOT NULL,
  VALUE             VARCHAR2(500),
  IS_COMPLIANT      CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_QA_CHECK_VALUES   PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_QCV_CHECK         FOREIGN KEY (CHECK_ID) REFERENCES AGRO_QA_CHECKS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AGRO_QCV_ITEM          FOREIGN KEY (CHECKLIST_ITEM_ID) REFERENCES AGRO_QA_CHECKLIST_ITEMS(ID),
  CONSTRAINT CK_AGRO_QCV_COMPL         CHECK (IS_COMPLIANT IN ('Y','N'))
);
/

-- 26. AGRO_BATCH_BLOCKS (FK → AGRO_BATCHES)
CREATE TABLE AGRO_BATCH_BLOCKS (
  ID               NUMBER          NOT NULL,
  BATCH_ID         NUMBER          NOT NULL,
  REASON           VARCHAR2(500)   NOT NULL,
  BLOCKED_BY       VARCHAR2(100),
  BLOCKED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP,
  UNBLOCKED_BY     VARCHAR2(100),
  UNBLOCKED_AT     TIMESTAMP,
  RESOLUTION_NOTES VARCHAR2(1000),
  CONSTRAINT PK_AGRO_BATCH_BLOCKS     PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_BB_BATCH         FOREIGN KEY (BATCH_ID) REFERENCES AGRO_BATCHES(ID)
);
/

-- 27. AGRO_HACCP_PLANS
CREATE TABLE AGRO_HACCP_PLANS (
  ID             NUMBER          NOT NULL,
  CODE           VARCHAR2(50)    NOT NULL,
  NAME_RU        VARCHAR2(300)   NOT NULL,
  NAME_RO        VARCHAR2(300),
  PROCESS_STAGE  VARCHAR2(100),
  ACTIVE         CHAR(1)         DEFAULT 'Y',
  CONSTRAINT PK_AGRO_HACCP_PLANS      PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_HACCP_PLANS_CODE UNIQUE (CODE),
  CONSTRAINT CK_AGRO_HP_ACT           CHECK (ACTIVE IN ('Y','N'))
);
/

-- 28. AGRO_HACCP_CCPS (FK → AGRO_HACCP_PLANS)
CREATE TABLE AGRO_HACCP_CCPS (
  ID                    NUMBER          NOT NULL,
  PLAN_ID               NUMBER          NOT NULL,
  CCP_NUMBER            VARCHAR2(20)    NOT NULL,
  HAZARD_TYPE           VARCHAR2(20)    NOT NULL,
  HAZARD_DESCRIPTION    VARCHAR2(500),
  CRITICAL_LIMIT_MIN    NUMBER(10,3),
  CRITICAL_LIMIT_MAX    NUMBER(10,3),
  MONITORING_FREQUENCY  VARCHAR2(100),
  CORRECTIVE_ACTION     VARCHAR2(500),
  CONSTRAINT PK_AGRO_HACCP_CCPS       PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_CCP_PLAN         FOREIGN KEY (PLAN_ID) REFERENCES AGRO_HACCP_PLANS(ID),
  CONSTRAINT CK_AGRO_CCP_HAZARD       CHECK (HAZARD_TYPE IN ('biological','chemical','physical'))
);
/

-- 29. AGRO_HACCP_RECORDS (FK → AGRO_HACCP_CCPS, AGRO_BATCHES)
CREATE TABLE AGRO_HACCP_RECORDS (
  ID                       NUMBER          NOT NULL,
  CCP_ID                   NUMBER          NOT NULL,
  BATCH_ID                 NUMBER          NOT NULL,
  MEASURED_VALUE           NUMBER(10,3),
  IS_WITHIN_LIMITS         CHAR(1)         DEFAULT 'Y',
  DEVIATION_NOTES          VARCHAR2(500),
  CORRECTIVE_ACTION_TAKEN  VARCHAR2(500),
  RECORDED_BY              VARCHAR2(100),
  RECORDED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_HACCP_RECORDS    PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_HR_CCP           FOREIGN KEY (CCP_ID) REFERENCES AGRO_HACCP_CCPS(ID),
  CONSTRAINT FK_AGRO_HR_BATCH         FOREIGN KEY (BATCH_ID) REFERENCES AGRO_BATCHES(ID),
  CONSTRAINT CK_AGRO_HR_LIMITS        CHECK (IS_WITHIN_LIMITS IN ('Y','N'))
);
/

-- ============================================================
-- 7. TABLES — Sales & Export (4 tables)
-- ============================================================

-- 30. AGRO_SALES_DOCS (FK → AGRO_CUSTOMERS, AGRO_WAREHOUSES, AGRO_VEHICLES, AGRO_CURRENCIES)
CREATE TABLE AGRO_SALES_DOCS (
  ID              NUMBER          NOT NULL,
  DOC_NUMBER      VARCHAR2(50)    NOT NULL,
  DOC_DATE        DATE            NOT NULL,
  CUSTOMER_ID     NUMBER          NOT NULL,
  WAREHOUSE_ID    NUMBER,
  VEHICLE_ID      NUMBER,
  SALE_TYPE       VARCHAR2(20)    DEFAULT 'domestic',
  CURRENCY_ID     NUMBER,
  STATUS          VARCHAR2(20)    DEFAULT 'draft',
  TOTAL_GROSS_KG  NUMBER(14,3),
  TOTAL_NET_KG    NUMBER(14,3),
  TOTAL_AMOUNT    NUMBER(14,2),
  INVOICE_NUMBER  VARCHAR2(100),
  NOTES           VARCHAR2(2000),
  CREATED_BY      VARCHAR2(100),
  CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_SALES_DOCS       PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_SD_DOCNUM        UNIQUE (DOC_NUMBER),
  CONSTRAINT FK_AGRO_SD_CUSTOMER      FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT FK_AGRO_SD_WAREHOUSE     FOREIGN KEY (WAREHOUSE_ID) REFERENCES AGRO_WAREHOUSES(ID),
  CONSTRAINT FK_AGRO_SD_VEHICLE       FOREIGN KEY (VEHICLE_ID) REFERENCES AGRO_VEHICLES(ID),
  CONSTRAINT FK_AGRO_SD_CURRENCY      FOREIGN KEY (CURRENCY_ID) REFERENCES AGRO_CURRENCIES(ID),
  CONSTRAINT CK_AGRO_SD_SALETYPE      CHECK (SALE_TYPE IN ('domestic','export')),
  CONSTRAINT CK_AGRO_SD_STATUS        CHECK (STATUS IN ('draft','confirmed','shipped','closed','cancelled'))
);
/

-- 31. AGRO_SALES_LINES (FK → AGRO_SALES_DOCS, AGRO_ITEMS, AGRO_BATCHES)
CREATE TABLE AGRO_SALES_LINES (
  ID              NUMBER          NOT NULL,
  SALES_DOC_ID    NUMBER          NOT NULL,
  ITEM_ID         NUMBER          NOT NULL,
  BATCH_ID        NUMBER,
  PALLETS         NUMBER          DEFAULT 0,
  CRATES_COUNT    NUMBER          DEFAULT 0,
  GROSS_WEIGHT_KG NUMBER(14,3),
  NET_WEIGHT_KG   NUMBER(14,3),
  PRICE_PER_KG    NUMBER(14,4),
  AMOUNT          NUMBER(14,2),
  CONSTRAINT PK_AGRO_SALES_LINES      PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_SL_DOC           FOREIGN KEY (SALES_DOC_ID) REFERENCES AGRO_SALES_DOCS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AGRO_SL_ITEM          FOREIGN KEY (ITEM_ID) REFERENCES AGRO_ITEMS(ID),
  CONSTRAINT FK_AGRO_SL_BATCH         FOREIGN KEY (BATCH_ID) REFERENCES AGRO_BATCHES(ID)
);
/

-- 32. AGRO_EXPORT_DECLS (FK → AGRO_SALES_DOCS)
CREATE TABLE AGRO_EXPORT_DECLS (
  ID                  NUMBER          NOT NULL,
  SALES_DOC_ID        NUMBER          NOT NULL,
  DECL_NUMBER         VARCHAR2(50),
  DECL_DATE           DATE,
  CUSTOMS_WEIGHT_KG   NUMBER(14,3),
  DESTINATION_COUNTRY VARCHAR2(100),
  CUSTOMS_CODE        VARCHAR2(50),
  STATUS              VARCHAR2(20)    DEFAULT 'draft',
  NOTES               VARCHAR2(1000),
  CONSTRAINT PK_AGRO_EXPORT_DECLS     PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_ED_SALESDOC      FOREIGN KEY (SALES_DOC_ID) REFERENCES AGRO_SALES_DOCS(ID)
);
/

-- 33. AGRO_BATCH_ALLOCATIONS (FK → AGRO_SALES_LINES, AGRO_BATCHES)
CREATE TABLE AGRO_BATCH_ALLOCATIONS (
  ID                 NUMBER          NOT NULL,
  SALES_LINE_ID      NUMBER          NOT NULL,
  BATCH_ID           NUMBER          NOT NULL,
  ALLOCATED_QTY_KG   NUMBER(14,3)    NOT NULL,
  ALLOCATION_METHOD  VARCHAR2(10)    DEFAULT 'fifo',
  CONSTRAINT PK_AGRO_BATCH_ALLOCATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_BA_SALESLINE      FOREIGN KEY (SALES_LINE_ID) REFERENCES AGRO_SALES_LINES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AGRO_BA_BATCH          FOREIGN KEY (BATCH_ID) REFERENCES AGRO_BATCHES(ID),
  CONSTRAINT CK_AGRO_BA_METHOD         CHECK (ALLOCATION_METHOD IN ('fifo','manual'))
);
/

-- ============================================================
-- 8. TABLES — Audit & Event Log (3 tables)
-- ============================================================

-- 34. AGRO_AUDIT_LOG
CREATE TABLE AGRO_AUDIT_LOG (
  ID          NUMBER          NOT NULL,
  TABLE_NAME  VARCHAR2(100)   NOT NULL,
  RECORD_ID   NUMBER,
  ACTION      VARCHAR2(10)    NOT NULL,
  FIELD_NAME  VARCHAR2(100),
  OLD_VALUE   VARCHAR2(4000),
  NEW_VALUE   VARCHAR2(4000),
  CHANGED_BY  VARCHAR2(100),
  CHANGED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_AUDIT_LOG  PRIMARY KEY (ID),
  CONSTRAINT CK_AGRO_AL_ACTION  CHECK (ACTION IN ('insert','update','delete'))
);
/

-- 35. AGRO_ATTACHMENTS
CREATE TABLE AGRO_ATTACHMENTS (
  ID           NUMBER          NOT NULL,
  ENTITY_TYPE  VARCHAR2(20)    NOT NULL,
  ENTITY_ID    NUMBER          NOT NULL,
  FILE_NAME    VARCHAR2(300)   NOT NULL,
  FILE_TYPE    VARCHAR2(100),
  FILE_SIZE    NUMBER,
  FILE_DATA    BLOB,
  UPLOADED_BY  VARCHAR2(100),
  UPLOADED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_ATTACHMENTS      PRIMARY KEY (ID),
  CONSTRAINT CK_AGRO_ATT_ETYPE        CHECK (ENTITY_TYPE IN ('purchase','sale','batch','qa_check'))
);
/

-- 36. AGRO_EVENT_LOG
CREATE TABLE AGRO_EVENT_LOG (
  ID           NUMBER          NOT NULL,
  EVENT_TYPE   VARCHAR2(50)    NOT NULL,
  ENTITY_TYPE  VARCHAR2(50),
  ENTITY_ID    NUMBER,
  PAYLOAD      CLOB,
  CREATED_BY   VARCHAR2(100),
  CREATED_AT   TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_EVENT_LOG PRIMARY KEY (ID)
);
/

-- ============================================================
-- 9. INDEXES
-- ============================================================

-- AGRO_EXCHANGE_RATES
CREATE INDEX IX_AGRO_EXCH_DATE      ON AGRO_EXCHANGE_RATES (RATE_DATE DESC);

-- AGRO_PURCHASE_DOCS
CREATE INDEX IX_AGRO_PD_DATE        ON AGRO_PURCHASE_DOCS (DOC_DATE DESC);
CREATE INDEX IX_AGRO_PD_SUPP        ON AGRO_PURCHASE_DOCS (SUPPLIER_ID);

-- AGRO_BATCHES
CREATE INDEX IX_AGRO_BAT_ITEM       ON AGRO_BATCHES (ITEM_ID);
CREATE INDEX IX_AGRO_BAT_WH         ON AGRO_BATCHES (WAREHOUSE_ID);
CREATE INDEX IX_AGRO_BAT_STATUS     ON AGRO_BATCHES (STATUS);

-- AGRO_STOCK_MOVEMENTS
CREATE INDEX IX_AGRO_SM_BATCH       ON AGRO_STOCK_MOVEMENTS (BATCH_ID);
CREATE INDEX IX_AGRO_SM_DATE        ON AGRO_STOCK_MOVEMENTS (CREATED_AT DESC);

-- AGRO_STORAGE_READINGS
CREATE INDEX IX_AGRO_SR_CELL        ON AGRO_STORAGE_READINGS (CELL_ID);
CREATE INDEX IX_AGRO_SR_DATE        ON AGRO_STORAGE_READINGS (RECORDED_AT DESC);

-- AGRO_SALES_DOCS
CREATE INDEX IX_AGRO_SD_DATE        ON AGRO_SALES_DOCS (DOC_DATE DESC);
CREATE INDEX IX_AGRO_SD_CUST        ON AGRO_SALES_DOCS (CUSTOMER_ID);

-- AGRO_AUDIT_LOG
CREATE INDEX IX_AGRO_AL_TABLE       ON AGRO_AUDIT_LOG (TABLE_NAME, RECORD_ID);
CREATE INDEX IX_AGRO_AL_DATE        ON AGRO_AUDIT_LOG (CHANGED_AT DESC);

-- AGRO_EVENT_LOG
CREATE INDEX IX_AGRO_EL_TYPE        ON AGRO_EVENT_LOG (EVENT_TYPE);
CREATE INDEX IX_AGRO_EL_DATE        ON AGRO_EVENT_LOG (CREATED_AT DESC);

-- ============================================================
-- End of AGRO module DDL
-- ============================================================
