-- ============================================================
-- AGRO module — triggers
-- File:       sql/37_agro_triggers.sql
-- Depends on: sql/35_agro_tables.sql (tables + sequences)
--
-- Contents:
--   1. Auto-ID triggers (36) — populate ID from sequence
--   2. Audit triggers   (3)  — log field changes to AGRO_AUDIT_LOG
-- ============================================================

-- ============================================================
-- 1. AUTO-ID TRIGGERS (36)
-- ============================================================

-- 1. AGRO_SUPPLIERS
CREATE OR REPLACE TRIGGER AGRO_SUPPLIERS_BI
  BEFORE INSERT ON AGRO_SUPPLIERS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_SUPPLIERS_SEQ.NEXTVAL;
END;
/

-- 2. AGRO_CUSTOMERS
CREATE OR REPLACE TRIGGER AGRO_CUSTOMERS_BI
  BEFORE INSERT ON AGRO_CUSTOMERS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CUSTOMERS_SEQ.NEXTVAL;
END;
/

-- 3. AGRO_WAREHOUSES
CREATE OR REPLACE TRIGGER AGRO_WAREHOUSES_BI
  BEFORE INSERT ON AGRO_WAREHOUSES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_WAREHOUSES_SEQ.NEXTVAL;
END;
/

-- 4. AGRO_STORAGE_CELLS
CREATE OR REPLACE TRIGGER AGRO_STORAGE_CELLS_BI
  BEFORE INSERT ON AGRO_STORAGE_CELLS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_STORAGE_CELLS_SEQ.NEXTVAL;
END;
/

-- 5. AGRO_ITEMS
CREATE OR REPLACE TRIGGER AGRO_ITEMS_BI
  BEFORE INSERT ON AGRO_ITEMS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_ITEMS_SEQ.NEXTVAL;
END;
/

-- 6. AGRO_PACKAGING_TYPES
CREATE OR REPLACE TRIGGER AGRO_PACKAGING_TYPES_BI
  BEFORE INSERT ON AGRO_PACKAGING_TYPES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_PACKAGING_TYPES_SEQ.NEXTVAL;
END;
/

-- 7. AGRO_VEHICLES
CREATE OR REPLACE TRIGGER AGRO_VEHICLES_BI
  BEFORE INSERT ON AGRO_VEHICLES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_VEHICLES_SEQ.NEXTVAL;
END;
/

-- 8. AGRO_CURRENCIES
CREATE OR REPLACE TRIGGER AGRO_CURRENCIES_BI
  BEFORE INSERT ON AGRO_CURRENCIES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CURRENCIES_SEQ.NEXTVAL;
END;
/

-- 9. AGRO_EXCHANGE_RATES
CREATE OR REPLACE TRIGGER AGRO_EXCHANGE_RATES_BI
  BEFORE INSERT ON AGRO_EXCHANGE_RATES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_EXCHANGE_RATES_SEQ.NEXTVAL;
END;
/

-- 10. AGRO_FORMULA_PARAMS
CREATE OR REPLACE TRIGGER AGRO_FORMULA_PARAMS_BI
  BEFORE INSERT ON AGRO_FORMULA_PARAMS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_FORMULA_PARAMS_SEQ.NEXTVAL;
END;
/

-- 11. AGRO_MODULE_CONFIG
CREATE OR REPLACE TRIGGER AGRO_MODULE_CONFIG_BI
  BEFORE INSERT ON AGRO_MODULE_CONFIG FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_MODULE_CONFIG_SEQ.NEXTVAL;
END;
/

-- 12. AGRO_BARCODES
CREATE OR REPLACE TRIGGER AGRO_BARCODES_BI
  BEFORE INSERT ON AGRO_BARCODES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_BARCODES_SEQ.NEXTVAL;
END;
/

-- 13. AGRO_CRATES
CREATE OR REPLACE TRIGGER AGRO_CRATES_BI
  BEFORE INSERT ON AGRO_CRATES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_CRATES_SEQ.NEXTVAL;
END;
/

-- 14. AGRO_BATCH_CRATES
CREATE OR REPLACE TRIGGER AGRO_BATCH_CRATES_BI
  BEFORE INSERT ON AGRO_BATCH_CRATES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_BATCH_CRATES_SEQ.NEXTVAL;
END;
/

-- 15. AGRO_PURCHASE_DOCS
CREATE OR REPLACE TRIGGER AGRO_PURCHASE_DOCS_BI
  BEFORE INSERT ON AGRO_PURCHASE_DOCS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_PURCHASE_DOCS_SEQ.NEXTVAL;
END;
/

-- 16. AGRO_PURCHASE_LINES
CREATE OR REPLACE TRIGGER AGRO_PURCHASE_LINES_BI
  BEFORE INSERT ON AGRO_PURCHASE_LINES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_PURCHASE_LINES_SEQ.NEXTVAL;
END;
/

-- 17. AGRO_BATCHES
CREATE OR REPLACE TRIGGER AGRO_BATCHES_BI
  BEFORE INSERT ON AGRO_BATCHES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_BATCHES_SEQ.NEXTVAL;
END;
/

-- 18. AGRO_STOCK_MOVEMENTS
CREATE OR REPLACE TRIGGER AGRO_STOCK_MOVEMENTS_BI
  BEFORE INSERT ON AGRO_STOCK_MOVEMENTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_STOCK_MOVEMENTS_SEQ.NEXTVAL;
END;
/

-- 19. AGRO_STORAGE_READINGS
CREATE OR REPLACE TRIGGER AGRO_STORAGE_READINGS_BI
  BEFORE INSERT ON AGRO_STORAGE_READINGS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_STORAGE_READINGS_SEQ.NEXTVAL;
END;
/

-- 20. AGRO_STORAGE_ALERTS
CREATE OR REPLACE TRIGGER AGRO_STORAGE_ALERTS_BI
  BEFORE INSERT ON AGRO_STORAGE_ALERTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_STORAGE_ALERTS_SEQ.NEXTVAL;
END;
/

-- 21. AGRO_PROCESSING_TASKS
CREATE OR REPLACE TRIGGER AGRO_PROCESSING_TASKS_BI
  BEFORE INSERT ON AGRO_PROCESSING_TASKS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_PROCESSING_TASKS_SEQ.NEXTVAL;
END;
/

-- 22. AGRO_QA_CHECKLISTS
CREATE OR REPLACE TRIGGER AGRO_QA_CHECKLISTS_BI
  BEFORE INSERT ON AGRO_QA_CHECKLISTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_QA_CHECKLISTS_SEQ.NEXTVAL;
END;
/

-- 23. AGRO_QA_CHECKLIST_ITEMS
CREATE OR REPLACE TRIGGER AGRO_QA_CHECKLIST_ITEMS_BI
  BEFORE INSERT ON AGRO_QA_CHECKLIST_ITEMS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_QA_CHECKLIST_ITEMS_SEQ.NEXTVAL;
END;
/

-- 24. AGRO_QA_CHECKS
CREATE OR REPLACE TRIGGER AGRO_QA_CHECKS_BI
  BEFORE INSERT ON AGRO_QA_CHECKS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_QA_CHECKS_SEQ.NEXTVAL;
END;
/

-- 25. AGRO_QA_CHECK_VALUES
CREATE OR REPLACE TRIGGER AGRO_QA_CHECK_VALUES_BI
  BEFORE INSERT ON AGRO_QA_CHECK_VALUES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_QA_CHECK_VALUES_SEQ.NEXTVAL;
END;
/

-- 26. AGRO_BATCH_BLOCKS
CREATE OR REPLACE TRIGGER AGRO_BATCH_BLOCKS_BI
  BEFORE INSERT ON AGRO_BATCH_BLOCKS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_BATCH_BLOCKS_SEQ.NEXTVAL;
END;
/

-- 27. AGRO_HACCP_PLANS
CREATE OR REPLACE TRIGGER AGRO_HACCP_PLANS_BI
  BEFORE INSERT ON AGRO_HACCP_PLANS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_HACCP_PLANS_SEQ.NEXTVAL;
END;
/

-- 28. AGRO_HACCP_CCPS
CREATE OR REPLACE TRIGGER AGRO_HACCP_CCPS_BI
  BEFORE INSERT ON AGRO_HACCP_CCPS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_HACCP_CCPS_SEQ.NEXTVAL;
END;
/

-- 29. AGRO_HACCP_RECORDS
CREATE OR REPLACE TRIGGER AGRO_HACCP_RECORDS_BI
  BEFORE INSERT ON AGRO_HACCP_RECORDS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_HACCP_RECORDS_SEQ.NEXTVAL;
END;
/

-- 30. AGRO_SALES_DOCS
CREATE OR REPLACE TRIGGER AGRO_SALES_DOCS_BI
  BEFORE INSERT ON AGRO_SALES_DOCS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_SALES_DOCS_SEQ.NEXTVAL;
END;
/

-- 31. AGRO_SALES_LINES
CREATE OR REPLACE TRIGGER AGRO_SALES_LINES_BI
  BEFORE INSERT ON AGRO_SALES_LINES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_SALES_LINES_SEQ.NEXTVAL;
END;
/

-- 32. AGRO_EXPORT_DECLS
CREATE OR REPLACE TRIGGER AGRO_EXPORT_DECLS_BI
  BEFORE INSERT ON AGRO_EXPORT_DECLS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_EXPORT_DECLS_SEQ.NEXTVAL;
END;
/

-- 33. AGRO_BATCH_ALLOCATIONS
CREATE OR REPLACE TRIGGER AGRO_BATCH_ALLOCATIONS_BI
  BEFORE INSERT ON AGRO_BATCH_ALLOCATIONS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_BATCH_ALLOCATIONS_SEQ.NEXTVAL;
END;
/

-- 34. AGRO_AUDIT_LOG
CREATE OR REPLACE TRIGGER AGRO_AUDIT_LOG_BI
  BEFORE INSERT ON AGRO_AUDIT_LOG FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_AUDIT_LOG_SEQ.NEXTVAL;
END;
/

-- 35. AGRO_ATTACHMENTS
CREATE OR REPLACE TRIGGER AGRO_ATTACHMENTS_BI
  BEFORE INSERT ON AGRO_ATTACHMENTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_ATTACHMENTS_SEQ.NEXTVAL;
END;
/

-- 36. AGRO_EVENT_LOG
CREATE OR REPLACE TRIGGER AGRO_EVENT_LOG_BI
  BEFORE INSERT ON AGRO_EVENT_LOG FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_EVENT_LOG_SEQ.NEXTVAL;
END;
/

-- ============================================================
-- 2. AUDIT TRIGGERS (3)
--    Log field-level changes to AGRO_AUDIT_LOG.
--    CHANGED_BY is taken from SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER').
-- ============================================================

-- 2a. AGRO_BATCHES — track STATUS, CURRENT_QTY_KG, WAREHOUSE_ID, CELL_ID, BLOCKED_BY
CREATE OR REPLACE TRIGGER AGRO_BATCHES_AUDIT
  AFTER UPDATE ON AGRO_BATCHES FOR EACH ROW
DECLARE
  v_user VARCHAR2(100) := SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER');

  PROCEDURE log_change(p_field VARCHAR2, p_old VARCHAR2, p_new VARCHAR2) IS
  BEGIN
    IF NVL(p_old,'~') != NVL(p_new,'~') THEN
      INSERT INTO AGRO_AUDIT_LOG (TABLE_NAME, RECORD_ID, ACTION, FIELD_NAME, OLD_VALUE, NEW_VALUE, CHANGED_BY)
      VALUES ('AGRO_BATCHES', :OLD.ID, 'update', p_field, p_old, p_new, v_user);
    END IF;
  END log_change;

BEGIN
  log_change('STATUS',          :OLD.STATUS,                        :NEW.STATUS);
  log_change('CURRENT_QTY_KG',  TO_CHAR(:OLD.CURRENT_QTY_KG),      TO_CHAR(:NEW.CURRENT_QTY_KG));
  log_change('WAREHOUSE_ID',    TO_CHAR(:OLD.WAREHOUSE_ID),         TO_CHAR(:NEW.WAREHOUSE_ID));
  log_change('CELL_ID',         TO_CHAR(:OLD.CELL_ID),              TO_CHAR(:NEW.CELL_ID));
  log_change('BLOCKED_BY',      :OLD.BLOCKED_BY,                    :NEW.BLOCKED_BY);
END;
/

-- 2b. AGRO_PURCHASE_DOCS — track STATUS, TOTAL_NET_KG, TOTAL_AMOUNT
CREATE OR REPLACE TRIGGER AGRO_PURCHASE_DOCS_AUDIT
  AFTER UPDATE ON AGRO_PURCHASE_DOCS FOR EACH ROW
DECLARE
  v_user VARCHAR2(100) := SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER');

  PROCEDURE log_change(p_field VARCHAR2, p_old VARCHAR2, p_new VARCHAR2) IS
  BEGIN
    IF NVL(p_old,'~') != NVL(p_new,'~') THEN
      INSERT INTO AGRO_AUDIT_LOG (TABLE_NAME, RECORD_ID, ACTION, FIELD_NAME, OLD_VALUE, NEW_VALUE, CHANGED_BY)
      VALUES ('AGRO_PURCHASE_DOCS', :OLD.ID, 'update', p_field, p_old, p_new, v_user);
    END IF;
  END log_change;

BEGIN
  log_change('STATUS',          :OLD.STATUS,                        :NEW.STATUS);
  log_change('TOTAL_NET_KG',    TO_CHAR(:OLD.TOTAL_NET_KG),         TO_CHAR(:NEW.TOTAL_NET_KG));
  log_change('TOTAL_AMOUNT',    TO_CHAR(:OLD.TOTAL_AMOUNT),          TO_CHAR(:NEW.TOTAL_AMOUNT));
END;
/

-- 2c. AGRO_SALES_DOCS — track STATUS, TOTAL_NET_KG, TOTAL_AMOUNT
CREATE OR REPLACE TRIGGER AGRO_SALES_DOCS_AUDIT
  AFTER UPDATE ON AGRO_SALES_DOCS FOR EACH ROW
DECLARE
  v_user VARCHAR2(100) := SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER');

  PROCEDURE log_change(p_field VARCHAR2, p_old VARCHAR2, p_new VARCHAR2) IS
  BEGIN
    IF NVL(p_old,'~') != NVL(p_new,'~') THEN
      INSERT INTO AGRO_AUDIT_LOG (TABLE_NAME, RECORD_ID, ACTION, FIELD_NAME, OLD_VALUE, NEW_VALUE, CHANGED_BY)
      VALUES ('AGRO_SALES_DOCS', :OLD.ID, 'update', p_field, p_old, p_new, v_user);
    END IF;
  END log_change;

BEGIN
  log_change('STATUS',          :OLD.STATUS,                        :NEW.STATUS);
  log_change('TOTAL_NET_KG',    TO_CHAR(:OLD.TOTAL_NET_KG),         TO_CHAR(:NEW.TOTAL_NET_KG));
  log_change('TOTAL_AMOUNT',    TO_CHAR(:OLD.TOTAL_AMOUNT),          TO_CHAR(:NEW.TOTAL_AMOUNT));
END;
/

-- ============================================================
-- End of AGRO triggers
-- ============================================================
