-- ============================================================
-- AGRO module — acceptance extension
-- Tables:    6 new + ALTER on 2 existing
-- Sequences: 6
-- Triggers:  6 (auto-ID) + 1 (audit)
-- Indexes:   9
--
-- Covers: item varieties, acceptance profiles,
--         field requests (zayvki), batch inspections
--         with scoring engine.
-- ============================================================

-- ============================================================
-- 1. SEQUENCES
-- ============================================================

CREATE SEQUENCE AGRO_ITEM_VARIETIES_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_ACCEPTANCE_PROFILES_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_FIELD_REQUESTS_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_FIELD_REQUEST_LINES_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_BATCH_INSPECTIONS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE AGRO_BATCH_INSPECTION_VALUES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- 2. TABLES
-- ============================================================

-- 2.1 AGRO_ITEM_VARIETIES — varieties per product item
CREATE TABLE AGRO_ITEM_VARIETIES (
  ID                NUMBER          NOT NULL,
  ITEM_ID           NUMBER          NOT NULL,
  CODE              VARCHAR2(50)    NOT NULL,
  NAME_RU           VARCHAR2(300)   NOT NULL,
  NAME_RO           VARCHAR2(300),
  MIN_CALIBRE_MM    NUMBER(6,1),
  MIN_BRIX          NUMBER(5,2),
  SHELF_LIFE_DAYS   NUMBER,
  OPTIMAL_TEMP_MIN  NUMBER(5,2),
  OPTIMAL_TEMP_MAX  NUMBER(5,2),
  COLOR_COVERAGE_PCT NUMBER(5,2),
  NOTES             VARCHAR2(1000),
  ACTIVE            CHAR(1)         DEFAULT 'Y',
  CREATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_ITEM_VARIETIES      PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_IV_ITEM             FOREIGN KEY (ITEM_ID) REFERENCES AGRO_ITEMS(ID),
  CONSTRAINT UQ_AGRO_IV_ITEM_CODE        UNIQUE (ITEM_ID, CODE),
  CONSTRAINT CK_AGRO_IV_ACT             CHECK (ACTIVE IN ('Y','N'))
);

-- 2.2 AGRO_ACCEPTANCE_PROFILES — retailer acceptance thresholds
CREATE TABLE AGRO_ACCEPTANCE_PROFILES (
  ID                        NUMBER          NOT NULL,
  CODE                      VARCHAR2(50)    NOT NULL,
  NAME_RU                   VARCHAR2(300)   NOT NULL,
  NAME_RO                   VARCHAR2(300),
  CUSTOMER_ID               NUMBER,
  -- Quality class
  REQUIRED_CLASS            VARCHAR2(10)    DEFAULT 'I',
  ALLOW_CLASS_II            CHAR(1)         DEFAULT 'N',
  -- Calibre
  MIN_CALIBRE_MM            NUMBER(6,1),
  MAX_BELOW_MIN_PCT         NUMBER(5,2),
  MAX_MIXED_SIZE_PCT        NUMBER(5,2),
  -- Defects
  MAX_MINOR_DEFECTS_PCT     NUMBER(5,2),
  MAX_SERIOUS_DEFECTS_PCT   NUMBER(5,2),
  -- Maturity
  MIN_BRIX                  NUMBER(5,2),
  -- Temperature
  TEMP_MIN_C                NUMBER(5,2),
  TEMP_MAX_C                NUMBER(5,2),
  -- Document requirements (Y/N)
  LAB_REQ                   CHAR(1)         DEFAULT 'N',
  PHYTO_REQ                 CHAR(1)         DEFAULT 'N',
  TRACE_REQ                 CHAR(1)         DEFAULT 'N',
  PACK_REQ                  CHAR(1)         DEFAULT 'N',
  LABEL_REQ                 CHAR(1)         DEFAULT 'N',
  -- Pesticide limits
  MAX_ACTIVES               NUMBER(3),
  MAX_SINGLE_RESIDUE_PCT_MRL NUMBER(5,2),
  MAX_TOTAL_RESIDUE_PCT     NUMBER(5,2),
  MAX_GLYPHOSATE_PCT_MRL    NUMBER(5,2),
  -- Scoring
  ACCEPT_MIN_SCORE          NUMBER(5,2)     DEFAULT 85,
  -- Meta
  ACTIVE                    CHAR(1)         DEFAULT 'Y',
  CREATED_AT                TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_ACCEPT_PROFILES     PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_AP_CODE             UNIQUE (CODE),
  CONSTRAINT FK_AGRO_AP_CUSTOMER         FOREIGN KEY (CUSTOMER_ID) REFERENCES AGRO_CUSTOMERS(ID),
  CONSTRAINT CK_AGRO_AP_CLASS            CHECK (REQUIRED_CLASS IN ('Extra','I','II')),
  CONSTRAINT CK_AGRO_AP_ACT             CHECK (ACTIVE IN ('Y','N')),
  CONSTRAINT CK_AGRO_AP_CL2             CHECK (ALLOW_CLASS_II IN ('Y','N')),
  CONSTRAINT CK_AGRO_AP_LAB             CHECK (LAB_REQ IN ('Y','N')),
  CONSTRAINT CK_AGRO_AP_PHYTO           CHECK (PHYTO_REQ IN ('Y','N')),
  CONSTRAINT CK_AGRO_AP_TRACE           CHECK (TRACE_REQ IN ('Y','N')),
  CONSTRAINT CK_AGRO_AP_PACK            CHECK (PACK_REQ IN ('Y','N')),
  CONSTRAINT CK_AGRO_AP_LABEL           CHECK (LABEL_REQ IN ('Y','N'))
);

-- 2.3 AGRO_FIELD_REQUESTS — procurement request header
CREATE TABLE AGRO_FIELD_REQUESTS (
  ID                NUMBER          NOT NULL,
  REQUEST_NUMBER    VARCHAR2(50)    NOT NULL,
  REQUEST_DATE      DATE            NOT NULL,
  EXPECTED_DATE     DATE,
  SUPPLIER_ID       NUMBER,
  WAREHOUSE_ID      NUMBER,
  PROFILE_ID        NUMBER,
  STATUS            VARCHAR2(20)    DEFAULT 'draft',
  NOTES             VARCHAR2(2000),
  CREATED_BY        VARCHAR2(100),
  CREATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP,
  APPROVED_BY       VARCHAR2(100),
  APPROVED_AT       TIMESTAMP,
  CONSTRAINT PK_AGRO_FIELD_REQUESTS      PRIMARY KEY (ID),
  CONSTRAINT UQ_AGRO_FR_NUM              UNIQUE (REQUEST_NUMBER),
  CONSTRAINT FK_AGRO_FR_SUPPLIER         FOREIGN KEY (SUPPLIER_ID) REFERENCES AGRO_SUPPLIERS(ID),
  CONSTRAINT FK_AGRO_FR_WAREHOUSE        FOREIGN KEY (WAREHOUSE_ID) REFERENCES AGRO_WAREHOUSES(ID),
  CONSTRAINT FK_AGRO_FR_PROFILE          FOREIGN KEY (PROFILE_ID) REFERENCES AGRO_ACCEPTANCE_PROFILES(ID),
  CONSTRAINT CK_AGRO_FR_STATUS           CHECK (STATUS IN ('draft','approved','in_progress','fulfilled','cancelled'))
);

-- 2.4 AGRO_FIELD_REQUEST_LINES — request line items
CREATE TABLE AGRO_FIELD_REQUEST_LINES (
  ID                NUMBER          NOT NULL,
  REQUEST_ID        NUMBER          NOT NULL,
  ITEM_ID           NUMBER          NOT NULL,
  VARIETY_ID        NUMBER,
  EXPECTED_QTY_KG   NUMBER(14,3),
  ACTUAL_QTY_KG     NUMBER(14,3),
  PRICE_LIMIT_PER_KG NUMBER(14,4),
  NOTES             VARCHAR2(1000),
  CONSTRAINT PK_AGRO_FR_LINES           PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_FRL_REQUEST         FOREIGN KEY (REQUEST_ID) REFERENCES AGRO_FIELD_REQUESTS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AGRO_FRL_ITEM            FOREIGN KEY (ITEM_ID) REFERENCES AGRO_ITEMS(ID),
  CONSTRAINT FK_AGRO_FRL_VARIETY         FOREIGN KEY (VARIETY_ID) REFERENCES AGRO_ITEM_VARIETIES(ID)
);

-- 2.5 AGRO_BATCH_INSPECTIONS — batch acceptance inspection header
CREATE TABLE AGRO_BATCH_INSPECTIONS (
  ID                  NUMBER          NOT NULL,
  BATCH_ID            NUMBER          NOT NULL,
  PROFILE_ID          NUMBER          NOT NULL,
  VARIETY_ID          NUMBER,
  INSPECTION_DATE     DATE            DEFAULT TRUNC(SYSDATE),
  INSPECTOR           VARCHAR2(100),
  TOTAL_SCORE         NUMBER(5,2),
  CRITICAL_FAILS      NUMBER(3)       DEFAULT 0,
  DECISION            VARCHAR2(30),
  DISCOUNT_PCT        NUMBER(5,2),
  FRESHNESS_SCORE     NUMBER(2,1),
  NOTES               VARCHAR2(2000),
  CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_AGRO_BATCH_INSPECTIONS   PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_BI_BATCH            FOREIGN KEY (BATCH_ID) REFERENCES AGRO_BATCHES(ID),
  CONSTRAINT FK_AGRO_BI_PROFILE          FOREIGN KEY (PROFILE_ID) REFERENCES AGRO_ACCEPTANCE_PROFILES(ID),
  CONSTRAINT FK_AGRO_BI_VARIETY          FOREIGN KEY (VARIETY_ID) REFERENCES AGRO_ITEM_VARIETIES(ID),
  CONSTRAINT CK_AGRO_BI_DECISION        CHECK (DECISION IN ('ACCEPT','ACCEPT_WITH_SORTING','REJECT'))
);

-- 2.6 AGRO_BATCH_INSPECTION_VALUES — individual check values
CREATE TABLE AGRO_BATCH_INSPECTION_VALUES (
  ID                  NUMBER          NOT NULL,
  INSPECTION_ID       NUMBER          NOT NULL,
  PARAM_CODE          VARCHAR2(50)    NOT NULL,
  PARAM_LABEL         VARCHAR2(200),
  MEASURED_VALUE      VARCHAR2(200),
  THRESHOLD_VALUE     VARCHAR2(200),
  IS_PASS             CHAR(1)         DEFAULT 'Y',
  IS_CRITICAL         CHAR(1)         DEFAULT 'N',
  WEIGHT              NUMBER(5,2)     DEFAULT 0,
  SCORE_CONTRIBUTION  NUMBER(5,2)     DEFAULT 0,
  CONSTRAINT PK_AGRO_BIV                PRIMARY KEY (ID),
  CONSTRAINT FK_AGRO_BIV_INSPECTION     FOREIGN KEY (INSPECTION_ID) REFERENCES AGRO_BATCH_INSPECTIONS(ID) ON DELETE CASCADE,
  CONSTRAINT CK_AGRO_BIV_PASS           CHECK (IS_PASS IN ('Y','N')),
  CONSTRAINT CK_AGRO_BIV_CRIT           CHECK (IS_CRITICAL IN ('Y','N'))
);

-- ============================================================
-- 3. ALTER TABLE — link purchases to requests/varieties
-- ============================================================

ALTER TABLE AGRO_PURCHASE_DOCS ADD (
  FIELD_REQUEST_ID NUMBER
);

ALTER TABLE AGRO_PURCHASE_DOCS ADD CONSTRAINT FK_AGRO_PD_FIELD_REQ
  FOREIGN KEY (FIELD_REQUEST_ID) REFERENCES AGRO_FIELD_REQUESTS(ID);

ALTER TABLE AGRO_PURCHASE_LINES ADD (
  VARIETY_ID NUMBER
);

ALTER TABLE AGRO_PURCHASE_LINES ADD CONSTRAINT FK_AGRO_PL_VARIETY
  FOREIGN KEY (VARIETY_ID) REFERENCES AGRO_ITEM_VARIETIES(ID);

-- ============================================================
-- 4. INDEXES
-- ============================================================

CREATE INDEX IX_AGRO_IV_ITEM       ON AGRO_ITEM_VARIETIES (ITEM_ID);
CREATE INDEX IX_AGRO_FR_DATE       ON AGRO_FIELD_REQUESTS (REQUEST_DATE DESC);
CREATE INDEX IX_AGRO_FR_SUPPLIER   ON AGRO_FIELD_REQUESTS (SUPPLIER_ID);
CREATE INDEX IX_AGRO_FR_STATUS     ON AGRO_FIELD_REQUESTS (STATUS);
CREATE INDEX IX_AGRO_FRL_REQUEST   ON AGRO_FIELD_REQUEST_LINES (REQUEST_ID);
CREATE INDEX IX_AGRO_BI_BATCH      ON AGRO_BATCH_INSPECTIONS (BATCH_ID);
CREATE INDEX IX_AGRO_BI_DATE       ON AGRO_BATCH_INSPECTIONS (INSPECTION_DATE DESC);
CREATE INDEX IX_AGRO_BIV_INSP      ON AGRO_BATCH_INSPECTION_VALUES (INSPECTION_ID);
CREATE INDEX IX_AGRO_PD_FREQ       ON AGRO_PURCHASE_DOCS (FIELD_REQUEST_ID);

-- ============================================================
-- 5. TRIGGERS — auto-ID
-- ============================================================
/

CREATE OR REPLACE TRIGGER AGRO_ITEM_VARIETIES_BI
  BEFORE INSERT ON AGRO_ITEM_VARIETIES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_ITEM_VARIETIES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER AGRO_ACCEPTANCE_PROFILES_BI
  BEFORE INSERT ON AGRO_ACCEPTANCE_PROFILES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_ACCEPTANCE_PROFILES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER AGRO_FIELD_REQUESTS_BI
  BEFORE INSERT ON AGRO_FIELD_REQUESTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_FIELD_REQUESTS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER AGRO_FIELD_REQUEST_LINES_BI
  BEFORE INSERT ON AGRO_FIELD_REQUEST_LINES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_FIELD_REQUEST_LINES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER AGRO_BATCH_INSPECTIONS_BI
  BEFORE INSERT ON AGRO_BATCH_INSPECTIONS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_BATCH_INSPECTIONS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER AGRO_BATCH_INSPECTION_VALUES_BI
  BEFORE INSERT ON AGRO_BATCH_INSPECTION_VALUES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_BATCH_INSPECTION_VALUES_SEQ.NEXTVAL;
END;
/

-- 5.1 Audit trigger for field requests status changes
CREATE OR REPLACE TRIGGER AGRO_FIELD_REQUESTS_AUDIT
  AFTER UPDATE ON AGRO_FIELD_REQUESTS FOR EACH ROW
DECLARE
  v_user VARCHAR2(100) := SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER');
  PROCEDURE log_change(p_field VARCHAR2, p_old VARCHAR2, p_new VARCHAR2) IS
  BEGIN
    IF NVL(p_old,'~') != NVL(p_new,'~') THEN
      INSERT INTO AGRO_AUDIT_LOG (TABLE_NAME, RECORD_ID, ACTION, FIELD_NAME, OLD_VALUE, NEW_VALUE, CHANGED_BY)
      VALUES ('AGRO_FIELD_REQUESTS', :OLD.ID, 'update', p_field, p_old, p_new, v_user);
    END IF;
  END log_change;
BEGIN
  log_change('STATUS', :OLD.STATUS, :NEW.STATUS);
END;
/

-- ============================================================
-- 6. ALTER TABLE — passport/quality fields on purchase lines
-- ============================================================

ALTER TABLE AGRO_PURCHASE_LINES ADD (
  CALIBRE_MM          NUMBER(6,1),
  BRIX                NUMBER(5,2),
  COLOR_COVERAGE_PCT  NUMBER(5,2),
  FRESHNESS_SCORE     NUMBER(2,1),
  TEMP_C              NUMBER(5,2),
  PACKAGING           VARCHAR2(20),
  LABELING            VARCHAR2(20),
  DEFECTS             VARCHAR2(20),
  DEFECT_PCT          NUMBER(5,2),
  PASSPORT_NOTES      VARCHAR2(2000)
);
