-- ============================================================
-- AGRO acceptance extension — demo / seed data
-- Item varieties, acceptance profiles
-- ============================================================

-- ============================================================
-- 1. Item Varieties
-- ============================================================

-- Apple varieties
INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='APPLE'), 'GALA', 'Гала', 'Gala', 65, 12.0, 90, 0, 4, 60, 'Y');

INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='APPLE'), 'GOLDEN', 'Голден Делишес', 'Golden Delicious', 70, 12.5, 120, 0, 4, NULL, 'Y');

INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='APPLE'), 'FUJI', 'Фуджи', 'Fuji', 70, 13.0, 150, 0, 4, 50, 'Y');

-- Grape varieties
INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='GRAPE'), 'MOLDOVA', 'Молдова', 'Moldova', NULL, 16.0, 60, -1, 2, NULL, 'Y');

INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='GRAPE'), 'MUSCAT', 'Мускат', 'Muscat', NULL, 18.0, 45, -1, 2, NULL, 'Y');

-- Plum varieties
INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='PLUM'), 'STANLEY', 'Стенли', 'Stanley', 30, 14.0, 30, 0, 2, NULL, 'Y');

INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='PLUM'), 'RENKLOD', 'Ренклод', 'Renclod', 30, 15.0, 21, 0, 2, NULL, 'Y');

-- Peach varieties
INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='PEACH'), 'REDHAVEN', 'Ред Хейвен', 'Redhaven', 55, 10.0, 14, 0, 4, 50, 'Y');

INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='PEACH'), 'ELBERTA', 'Эльберта', 'Elberta', 55, 11.0, 14, 0, 4, 40, 'Y');

-- Cherry varieties
INSERT INTO AGRO_ITEM_VARIETIES (ID, ITEM_ID, CODE, NAME_RU, NAME_RO, MIN_CALIBRE_MM, MIN_BRIX, SHELF_LIFE_DAYS, OPTIMAL_TEMP_MIN, OPTIMAL_TEMP_MAX, COLOR_COVERAGE_PCT, ACTIVE)
VALUES (NULL, (SELECT ID FROM AGRO_ITEMS WHERE CODE='CHERRY'), 'SHOKOLADNICA', 'Шоколадница', 'Shokoladnita', 18, 14.0, 10, 0, 2, NULL, 'Y');

-- ============================================================
-- 2. Acceptance Profiles (from procurement standards)
-- ============================================================

INSERT INTO AGRO_ACCEPTANCE_PROFILES (
  ID, CODE, NAME_RU, NAME_RO,
  REQUIRED_CLASS, ALLOW_CLASS_II,
  MIN_CALIBRE_MM, MAX_BELOW_MIN_PCT, MAX_MIXED_SIZE_PCT,
  MAX_MINOR_DEFECTS_PCT, MAX_SERIOUS_DEFECTS_PCT,
  MIN_BRIX, TEMP_MIN_C, TEMP_MAX_C,
  LAB_REQ, PHYTO_REQ, TRACE_REQ, PACK_REQ, LABEL_REQ,
  MAX_ACTIVES, MAX_SINGLE_RESIDUE_PCT_MRL, MAX_TOTAL_RESIDUE_PCT, MAX_GLYPHOSATE_PCT_MRL,
  ACCEPT_MIN_SCORE, ACTIVE
) VALUES (
  NULL, 'KAUFLAND_DEFAULT', 'Kaufland стандарт', 'Kaufland standard',
  'I', 'N',
  65, 5, 10,
  5, 1,
  10, 0, 6,
  'Y', 'Y', 'Y', 'Y', 'Y',
  NULL, NULL, NULL, NULL,
  85, 'Y'
);

INSERT INTO AGRO_ACCEPTANCE_PROFILES (
  ID, CODE, NAME_RU, NAME_RO,
  REQUIRED_CLASS, ALLOW_CLASS_II,
  MIN_CALIBRE_MM, MAX_BELOW_MIN_PCT, MAX_MIXED_SIZE_PCT,
  MAX_MINOR_DEFECTS_PCT, MAX_SERIOUS_DEFECTS_PCT,
  MIN_BRIX, TEMP_MIN_C, TEMP_MAX_C,
  LAB_REQ, PHYTO_REQ, TRACE_REQ, PACK_REQ, LABEL_REQ,
  MAX_ACTIVES, MAX_SINGLE_RESIDUE_PCT_MRL, MAX_TOTAL_RESIDUE_PCT, MAX_GLYPHOSATE_PCT_MRL,
  ACCEPT_MIN_SCORE, ACTIVE
) VALUES (
  NULL, 'METRO_BENCHMARK', 'Metro бенчмарк', 'Metro benchmark',
  'I', 'N',
  65, 5, 10,
  5, 1,
  10, 0, 6,
  'Y', 'Y', 'Y', 'Y', 'Y',
  5, 50, 80, 20,
  85, 'Y'
);

INSERT INTO AGRO_ACCEPTANCE_PROFILES (
  ID, CODE, NAME_RU, NAME_RO,
  REQUIRED_CLASS, ALLOW_CLASS_II,
  MIN_CALIBRE_MM, MAX_BELOW_MIN_PCT, MAX_MIXED_SIZE_PCT,
  MAX_MINOR_DEFECTS_PCT, MAX_SERIOUS_DEFECTS_PCT,
  MIN_BRIX, TEMP_MIN_C, TEMP_MAX_C,
  LAB_REQ, PHYTO_REQ, TRACE_REQ, PACK_REQ, LABEL_REQ,
  MAX_ACTIVES, MAX_SINGLE_RESIDUE_PCT_MRL, MAX_TOTAL_RESIDUE_PCT, MAX_GLYPHOSATE_PCT_MRL,
  ACCEPT_MIN_SCORE, ACTIVE
) VALUES (
  NULL, 'LINELLA_DEFAULT', 'Linella стандарт', 'Linella standard',
  'I', 'N',
  65, 5, 10,
  5, 1,
  10, 0, 6,
  'Y', 'Y', 'Y', 'Y', 'Y',
  NULL, NULL, NULL, NULL,
  85, 'Y'
);

COMMIT;
