-- sql/41_agro_weight_tickets.sql
-- Weight tickets for sales weighing module

-- Sequences
CREATE SEQUENCE AGRO_WEIGHT_TICKETS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE AGRO_WEIGHT_TICKET_LINES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- Header table
CREATE TABLE AGRO_WEIGHT_TICKETS (
    ID              NUMBER PRIMARY KEY,
    TICKET_NUMBER   VARCHAR2(30) NOT NULL,
    SALES_DOC_ID    NUMBER REFERENCES AGRO_SALES_DOCS(ID),
    CUSTOMER_ID     NUMBER REFERENCES AGRO_CUSTOMERS(ID),
    WAREHOUSE_ID    NUMBER REFERENCES AGRO_WAREHOUSES(ID),
    TICKET_DATE     DATE DEFAULT SYSDATE,
    STATUS          VARCHAR2(20) DEFAULT 'draft',
    OPERATOR        VARCHAR2(100),
    NOTES           VARCHAR2(500),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

-- Lines table
CREATE TABLE AGRO_WEIGHT_TICKET_LINES (
    ID              NUMBER PRIMARY KEY,
    TICKET_ID       NUMBER NOT NULL REFERENCES AGRO_WEIGHT_TICKETS(ID),
    LINE_NO         NUMBER,
    BATCH_ID        NUMBER REFERENCES AGRO_BATCHES(ID),
    CRATE_CODE      VARCHAR2(50),
    ITEM_ID         NUMBER REFERENCES AGRO_ITEMS(ID),
    GROSS_KG        NUMBER(12,3),
    TARE_KG         NUMBER(12,3),
    NET_KG          NUMBER(12,3),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

-- Auto-ID triggers
CREATE OR REPLACE TRIGGER AGRO_WEIGHT_TICKETS_BI
  BEFORE INSERT ON AGRO_WEIGHT_TICKETS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_WEIGHT_TICKETS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER AGRO_WEIGHT_TICKET_LINES_BI
  BEFORE INSERT ON AGRO_WEIGHT_TICKET_LINES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := AGRO_WEIGHT_TICKET_LINES_SEQ.NEXTVAL;
END;
/

-- Indexes on FK columns
CREATE INDEX IX_AGRO_WT_SALESDOC ON AGRO_WEIGHT_TICKETS(SALES_DOC_ID);
/
CREATE INDEX IX_AGRO_WT_CUSTOMER ON AGRO_WEIGHT_TICKETS(CUSTOMER_ID);
/
CREATE INDEX IX_AGRO_WT_WAREHOUSE ON AGRO_WEIGHT_TICKETS(WAREHOUSE_ID);
/
CREATE INDEX IX_AGRO_WTL_TICKET ON AGRO_WEIGHT_TICKET_LINES(TICKET_ID);
/
CREATE INDEX IX_AGRO_WTL_BATCH ON AGRO_WEIGHT_TICKET_LINES(BATCH_ID);
/
CREATE INDEX IX_AGRO_WTL_ITEM ON AGRO_WEIGHT_TICKET_LINES(ITEM_ID);
/

-- Extend AGRO_ATTACHMENTS CHECK constraint for batch_inspection
ALTER TABLE AGRO_ATTACHMENTS DROP CONSTRAINT CK_AGRO_ATT_ETYPE;
/
ALTER TABLE AGRO_ATTACHMENTS ADD CONSTRAINT CK_AGRO_ATT_ETYPE
  CHECK (ENTITY_TYPE IN ('purchase','sale','batch','qa_check','batch_inspection'));
/
