-- Add PAYMENT_METHOD column to NUF_ORDERS_LEDGER
ALTER TABLE NUF_ORDERS_LEDGER ADD (PAYMENT_METHOD VARCHAR2(50))
/
COMMENT ON COLUMN NUF_ORDERS_LEDGER.PAYMENT_METHOD IS 'cash | card | mia | mpay'
/
COMMIT
/
