-- ============================================================
-- TBControl: таблицы, последовательности, триггеры
-- Платформа контроля софта и оборудования магазинов:
-- Front Office, POS, Self-Service (SCO), Android-устройства.
-- Спецификация: docs/TBControl/TECHNICAL-OPS.md
-- Префикс объектов: TBC_
-- ============================================================

-- Последовательности
CREATE SEQUENCE TBC_STORES_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_DEVICES_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_APPS_SEQ          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_DEVICE_APPS_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_HEALTH_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_EVENTS_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_INCIDENTS_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_CHANGES_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_DEPLOY_CHECKS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_SLA_SEQ           START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_EVENT_LOG_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_INCIDENT_NUM_SEQ  START WITH 10001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_CHANGE_NUM_SEQ    START WITH 101 INCREMENT BY 1 NOCACHE;

-- ==================== Справочники ====================

-- Типы устройств (POS, SCO, AND, SRV, NET, PRN)
CREATE TABLE TBC_REF_DEVICE_TYPES (
  CODE       VARCHAR2(10)  NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  ICON       VARCHAR2(10),
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_TBC_REF_DEVICE_TYPES PRIMARY KEY (CODE)
);

-- Приоритеты событий P1..P4
CREATE TABLE TBC_REF_SEVERITIES (
  CODE       VARCHAR2(5)   NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  COLOR      VARCHAR2(20),
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_TBC_REF_SEVERITIES PRIMARY KEY (CODE)
);

-- Release channels (DEV, TEST, PILOT, PRODUCTION)
CREATE TABLE TBC_REF_CHANNELS (
  CODE       VARCHAR2(20)  NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_TBC_REF_CHANNELS PRIMARY KEY (CODE)
);

-- Группы ответственности (Customer IT / Developer / Service Desk / Management)
CREATE TABLE TBC_REF_SUPPORT_GROUPS (
  CODE       VARCHAR2(30)  NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_TBC_REF_SUPPORT_GROUPS PRIMARY KEY (CODE)
);

-- Сервисы магазина (модель "Everything is a service")
CREATE TABLE TBC_REF_SERVICES (
  CODE       VARCHAR2(30)  NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_TBC_REF_SERVICES PRIMARY KEY (CODE)
);

-- ==================== Master data ====================

-- Магазины
CREATE TABLE TBC_STORES (
  ID              NUMBER        NOT NULL,
  CODE            VARCHAR2(30)  NOT NULL,      -- MD-CHS-001
  NAME            VARCHAR2(200) NOT NULL,
  COUNTRY         VARCHAR2(5)   DEFAULT 'MD',
  CITY            VARCHAR2(100),
  ADDRESS         VARCHAR2(500),
  TIMEZONE        VARCHAR2(50)  DEFAULT 'Europe/Chisinau',
  STATUS          VARCHAR2(20)  DEFAULT 'active',
  MAINT_DOW       NUMBER,                      -- день недели maintenance window (1=Пн..7=Вс)
  MAINT_TIME_FROM VARCHAR2(5),                 -- '02:00'
  MAINT_TIME_TO   VARCHAR2(5),                 -- '04:00'
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_STORES PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_STORES_CODE UNIQUE (CODE),
  CONSTRAINT CHK_TBC_STORE_STATUS CHECK (STATUS IN ('active','inactive','maintenance'))
);
/

CREATE OR REPLACE TRIGGER TBC_STORES_BI
  BEFORE INSERT ON TBC_STORES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_STORES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TBC_STORES_BU
  BEFORE UPDATE ON TBC_STORES FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Устройства (технический паспорт, раздел 9 ТЗ)
CREATE TABLE TBC_DEVICES (
  ID              NUMBER        NOT NULL,
  CODE            VARCHAR2(40)  NOT NULL,      -- MD-CHS-001-POS-01
  STORE_ID        NUMBER        NOT NULL,
  DEVICE_TYPE     VARCHAR2(10)  NOT NULL,      -- POS/SCO/AND/SRV/NET/PRN
  HOSTNAME        VARCHAR2(100),
  SERIAL_NUMBER   VARCHAR2(100),
  ASSET_ID        VARCHAR2(50),
  MANUFACTURER    VARCHAR2(100),
  MODEL           VARCHAR2(100),
  OS              VARCHAR2(50),                -- Windows / Android / Linux
  OS_VERSION      VARCHAR2(50),
  IP_ADDRESS      VARCHAR2(45),
  MAC_ADDRESS     VARCHAR2(20),
  INSTALL_DATE    DATE,
  STATUS          VARCHAR2(20)  DEFAULT 'offline',
  OWNER_SIDE      VARCHAR2(20)  DEFAULT 'customer',  -- customer / developer
  SUPPORT_GROUP   VARCHAR2(30),
  CRITICALITY     VARCHAR2(10)  DEFAULT 'medium',
  CPU_PCT         NUMBER,
  RAM_PCT         NUMBER,
  DISK_PCT        NUMBER,
  BATTERY_PCT     NUMBER,                      -- только Android
  STORAGE_FREE_MB NUMBER,
  PENDING_OPS     NUMBER        DEFAULT 0,
  LAST_SEEN       TIMESTAMP,
  LAST_SYNC       TIMESTAMP,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_DEVICES PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_DEVICES_CODE UNIQUE (CODE),
  CONSTRAINT FK_TBC_DEV_STORE FOREIGN KEY (STORE_ID) REFERENCES TBC_STORES(ID),
  CONSTRAINT FK_TBC_DEV_TYPE  FOREIGN KEY (DEVICE_TYPE) REFERENCES TBC_REF_DEVICE_TYPES(CODE),
  CONSTRAINT FK_TBC_DEV_GRP   FOREIGN KEY (SUPPORT_GROUP) REFERENCES TBC_REF_SUPPORT_GROUPS(CODE),
  CONSTRAINT CHK_TBC_DEV_STATUS CHECK (STATUS IN ('online','degraded','offline','maintenance')),
  CONSTRAINT CHK_TBC_DEV_CRIT   CHECK (CRITICALITY IN ('high','medium','low'))
);
/

CREATE OR REPLACE TRIGGER TBC_DEVICES_BI
  BEFORE INSERT ON TBC_DEVICES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_DEVICES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TBC_DEVICES_BU
  BEFORE UPDATE ON TBC_DEVICES FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ==================== Приложения и версии ====================

-- Реестр приложений (раздел 30 ТЗ)
CREATE TABLE TBC_APPLICATIONS (
  ID               NUMBER        NOT NULL,
  CODE             VARCHAR2(30)  NOT NULL,     -- frontoffice, pos, sco, storeapp, android
  NAME             VARCHAR2(200) NOT NULL,
  APP_TYPE         VARCHAR2(30)  DEFAULT 'frontoffice',
  EXPECTED_VERSION VARCHAR2(30),
  EXPECTED_BUILD   VARCHAR2(50),
  RELEASE_CHANNEL  VARCHAR2(20)  DEFAULT 'PRODUCTION',
  HEALTH_URL       VARCHAR2(300),              -- endpoint Health API (/health)
  STATUS           VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_APPS PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_APPS_CODE UNIQUE (CODE),
  CONSTRAINT FK_TBC_APP_CHANNEL FOREIGN KEY (RELEASE_CHANNEL) REFERENCES TBC_REF_CHANNELS(CODE)
);
/

CREATE OR REPLACE TRIGGER TBC_APPS_BI
  BEFORE INSERT ON TBC_APPLICATIONS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_APPS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TBC_APPS_BU
  BEFORE UPDATE ON TBC_APPLICATIONS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Установленные версии на устройствах
CREATE TABLE TBC_DEVICE_APPS (
  ID              NUMBER       NOT NULL,
  DEVICE_ID       NUMBER       NOT NULL,
  APP_ID          NUMBER       NOT NULL,
  CURRENT_VERSION VARCHAR2(30),
  BUILD           VARCHAR2(50),
  CONFIG_VERSION  VARCHAR2(30),
  STATUS          VARCHAR2(20) DEFAULT 'UNKNOWN',   -- OK/OUTDATED/FAILED/UNKNOWN
  DEPLOYED_AT     TIMESTAMP,
  LAST_CHECK      TIMESTAMP,
  CONSTRAINT PK_TBC_DEVICE_APPS PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_DEVICE_APPS UNIQUE (DEVICE_ID, APP_ID),
  CONSTRAINT FK_TBC_DA_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES TBC_DEVICES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_TBC_DA_APP    FOREIGN KEY (APP_ID) REFERENCES TBC_APPLICATIONS(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_TBC_DA_STATUS CHECK (STATUS IN ('OK','OUTDATED','FAILED','UNKNOWN'))
);
/

CREATE OR REPLACE TRIGGER TBC_DEVICE_APPS_BI
  BEFORE INSERT ON TBC_DEVICE_APPS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_DEVICE_APPS_SEQ.NEXTVAL;
END;
/

-- ==================== Health checks (append-only) ====================

-- Результаты проверок компонентов устройства (разделы 16, 39-40 ТЗ)
CREATE TABLE TBC_HEALTH_CHECKS (
  ID         NUMBER       NOT NULL,
  DEVICE_ID  NUMBER       NOT NULL,
  COMPONENT  VARCHAR2(30) NOT NULL,   -- network/dns/gateway/agent/process/database/api/payment/fiscal/printer/scanner/sync/battery/storage
  STATUS     VARCHAR2(10) NOT NULL,   -- OK/WARN/FAIL
  LATENCY_MS NUMBER,
  DETAILS    VARCHAR2(500),
  CHECKED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_HEALTH PRIMARY KEY (ID),
  CONSTRAINT FK_TBC_HC_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES TBC_DEVICES(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_TBC_HC_STATUS CHECK (STATUS IN ('OK','WARN','FAIL'))
);
/

CREATE OR REPLACE TRIGGER TBC_HEALTH_BI
  BEFORE INSERT ON TBC_HEALTH_CHECKS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_HEALTH_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_TBC_HEALTH_DEV ON TBC_HEALTH_CHECKS (DEVICE_ID, CHECKED_AT);

-- ==================== События ====================

-- События мониторинга (разделы 23-28 ТЗ)
CREATE TABLE TBC_EVENTS (
  ID              NUMBER        NOT NULL,
  SEVERITY        VARCHAR2(5)   NOT NULL,
  STORE_ID        NUMBER,
  DEVICE_ID       NUMBER,
  SERVICE_CODE    VARCHAR2(30),
  PROBLEM         VARCHAR2(500) NOT NULL,
  STATUS          VARCHAR2(20)  DEFAULT 'open',
  SOURCE          VARCHAR2(30)  DEFAULT 'zabbix',   -- zabbix/agent/manual/correlation
  CORRELATION_ID  VARCHAR2(30),
  PARENT_EVENT_ID NUMBER,                            -- dependency model: root cause event
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  ACKED_AT        TIMESTAMP,
  RESOLVED_AT     TIMESTAMP,
  CONSTRAINT PK_TBC_EVENTS PRIMARY KEY (ID),
  CONSTRAINT FK_TBC_EV_SEV    FOREIGN KEY (SEVERITY) REFERENCES TBC_REF_SEVERITIES(CODE),
  CONSTRAINT FK_TBC_EV_STORE  FOREIGN KEY (STORE_ID) REFERENCES TBC_STORES(ID),
  CONSTRAINT FK_TBC_EV_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES TBC_DEVICES(ID),
  CONSTRAINT FK_TBC_EV_SVC    FOREIGN KEY (SERVICE_CODE) REFERENCES TBC_REF_SERVICES(CODE),
  CONSTRAINT FK_TBC_EV_PARENT FOREIGN KEY (PARENT_EVENT_ID) REFERENCES TBC_EVENTS(ID),
  CONSTRAINT CHK_TBC_EV_STATUS CHECK (STATUS IN ('open','ack','resolved','suppressed'))
);
/

CREATE OR REPLACE TRIGGER TBC_EVENTS_BI
  BEFORE INSERT ON TBC_EVENTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_EVENTS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_TBC_EVENTS_STORE ON TBC_EVENTS (STORE_ID, STATUS);

-- ==================== Инциденты ====================

-- Инциденты Service Desk (разделы 35, 56-57 ТЗ)
CREATE TABLE TBC_INCIDENTS (
  ID                NUMBER        NOT NULL,
  CODE              VARCHAR2(20)  NOT NULL,   -- INC-2026-10452
  EVENT_ID          NUMBER,
  STORE_ID          NUMBER,
  DEVICE_ID         NUMBER,
  SEVERITY          VARCHAR2(5)   NOT NULL,
  TITLE             VARCHAR2(300) NOT NULL,
  DESCRIPTION       VARCHAR2(2000),
  ASSIGNED_GROUP    VARCHAR2(30),
  ASSIGNEE          VARCHAR2(100),
  STATUS            VARCHAR2(20)  DEFAULT 'new',
  ROOT_CAUSE        VARCHAR2(1000),
  TECH_CAUSE        VARCHAR2(1000),
  BUSINESS_IMPACT   VARCHAR2(1000),
  RESOLUTION        VARCHAR2(1000),
  CORRECTIVE_ACTION VARCHAR2(1000),
  PREVENTIVE_ACTION VARCHAR2(1000),
  OPENED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CLOSED_AT         TIMESTAMP,
  SLA_DEADLINE      TIMESTAMP,
  CONSTRAINT PK_TBC_INCIDENTS PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_INC_CODE UNIQUE (CODE),
  CONSTRAINT FK_TBC_INC_EVENT  FOREIGN KEY (EVENT_ID) REFERENCES TBC_EVENTS(ID),
  CONSTRAINT FK_TBC_INC_STORE  FOREIGN KEY (STORE_ID) REFERENCES TBC_STORES(ID),
  CONSTRAINT FK_TBC_INC_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES TBC_DEVICES(ID),
  CONSTRAINT FK_TBC_INC_SEV    FOREIGN KEY (SEVERITY) REFERENCES TBC_REF_SEVERITIES(CODE),
  CONSTRAINT FK_TBC_INC_GRP    FOREIGN KEY (ASSIGNED_GROUP) REFERENCES TBC_REF_SUPPORT_GROUPS(CODE),
  CONSTRAINT CHK_TBC_INC_STATUS CHECK (STATUS IN ('new','assigned','diagnosing','resolving','verification','closed'))
);
/

CREATE OR REPLACE TRIGGER TBC_INCIDENTS_BI
  BEFORE INSERT ON TBC_INCIDENTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_INCIDENTS_SEQ.NEXTVAL;
END;
/

-- ==================== Изменения / Deployment ====================

-- Change management (разделы 32, 55 ТЗ)
CREATE TABLE TBC_CHANGES (
  ID                NUMBER        NOT NULL,
  CODE              VARCHAR2(20)  NOT NULL,   -- CHG-2026-0812
  APP_ID            NUMBER        NOT NULL,
  VERSION           VARCHAR2(30)  NOT NULL,
  ROLLBACK_VERSION  VARCHAR2(30),
  DESCRIPTION       VARCHAR2(1000),
  REASON            VARCHAR2(500),
  OWNER             VARCHAR2(100),
  RELEASE_CHANNEL   VARCHAR2(20)  DEFAULT 'PILOT',
  WINDOW_START      TIMESTAMP,
  WINDOW_END        TIMESTAMP,
  STATUS            VARCHAR2(20)  DEFAULT 'planned',
  VALIDATION_RESULT VARCHAR2(20),             -- SUCCESS / FAILED
  CREATED_BY        VARCHAR2(100),
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_CHANGES PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_CHG_CODE UNIQUE (CODE),
  CONSTRAINT FK_TBC_CHG_APP     FOREIGN KEY (APP_ID) REFERENCES TBC_APPLICATIONS(ID),
  CONSTRAINT FK_TBC_CHG_CHANNEL FOREIGN KEY (RELEASE_CHANNEL) REFERENCES TBC_REF_CHANNELS(CODE),
  CONSTRAINT CHK_TBC_CHG_STATUS CHECK (STATUS IN ('planned','in_progress','success','failed','rolled_back'))
);
/

CREATE OR REPLACE TRIGGER TBC_CHANGES_BI
  BEFORE INSERT ON TBC_CHANGES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_CHANGES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TBC_CHANGES_BU
  BEFORE UPDATE ON TBC_CHANGES FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Магазины, затронутые изменением
CREATE TABLE TBC_CHANGE_STORES (
  CHANGE_ID NUMBER NOT NULL,
  STORE_ID  NUMBER NOT NULL,
  CONSTRAINT PK_TBC_CHANGE_STORES PRIMARY KEY (CHANGE_ID, STORE_ID),
  CONSTRAINT FK_TBC_CS_CHANGE FOREIGN KEY (CHANGE_ID) REFERENCES TBC_CHANGES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_TBC_CS_STORE  FOREIGN KEY (STORE_ID) REFERENCES TBC_STORES(ID)
);

-- Deployment verification (раздел 32 ТЗ)
CREATE TABLE TBC_DEPLOY_CHECKS (
  ID         NUMBER       NOT NULL,
  CHANGE_ID  NUMBER       NOT NULL,
  DEVICE_ID  NUMBER       NOT NULL,
  CHECK_TYPE VARCHAR2(30) NOT NULL,   -- process/version/health/database/api/sync/peripheral/business
  STATUS     VARCHAR2(10) NOT NULL,   -- OK/FAIL
  DETAILS    VARCHAR2(500),
  CHECKED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_DEPLOY_CHECKS PRIMARY KEY (ID),
  CONSTRAINT FK_TBC_DC_CHANGE FOREIGN KEY (CHANGE_ID) REFERENCES TBC_CHANGES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_TBC_DC_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES TBC_DEVICES(ID) ON DELETE CASCADE
);
/

CREATE OR REPLACE TRIGGER TBC_DEPLOY_CHECKS_BI
  BEFORE INSERT ON TBC_DEPLOY_CHECKS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_DEPLOY_CHECKS_SEQ.NEXTVAL;
END;
/

-- ==================== SLA ====================

-- Целевые и фактические SLA по сервисам (раздел 51 ТЗ)
CREATE TABLE TBC_SLA_TARGETS (
  ID           NUMBER       NOT NULL,
  SERVICE_CODE VARCHAR2(30) NOT NULL,
  TARGET_PCT   NUMBER(6,3)  NOT NULL,
  CURRENT_PCT  NUMBER(6,3),
  PERIOD       VARCHAR2(20) DEFAULT 'monthly',
  UPDATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_SLA PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_SLA_SVC UNIQUE (SERVICE_CODE, PERIOD),
  CONSTRAINT FK_TBC_SLA_SVC FOREIGN KEY (SERVICE_CODE) REFERENCES TBC_REF_SERVICES(CODE)
);
/

CREATE OR REPLACE TRIGGER TBC_SLA_BI
  BEFORE INSERT ON TBC_SLA_TARGETS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_SLA_SEQ.NEXTVAL;
END;
/

-- ==================== Аудит модуля (append-only) ====================

CREATE TABLE TBC_EVENT_LOG (
  ID          NUMBER        NOT NULL,
  ACTION      VARCHAR2(50)  NOT NULL,
  ENTITY_TYPE VARCHAR2(30)  NOT NULL,
  ENTITY_ID   NUMBER,
  DETAILS     VARCHAR2(2000),
  USERNAME    VARCHAR2(100),
  CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_EVENT_LOG PRIMARY KEY (ID)
);
/

CREATE OR REPLACE TRIGGER TBC_EVENT_LOG_BI
  BEFORE INSERT ON TBC_EVENT_LOG FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_EVENT_LOG_SEQ.NEXTVAL;
END;
/
