-- ============================================================
-- TBControl: представления (V_TBC_*)
-- ============================================================

-- Устройства с контекстом магазина и версий
CREATE OR REPLACE VIEW V_TBC_DEVICES AS
SELECT
  d.ID, d.CODE, d.STORE_ID, s.CODE AS STORE_CODE, s.NAME AS STORE_NAME, s.CITY,
  d.DEVICE_TYPE, dt.NAME AS DEVICE_TYPE_NAME, dt.ICON AS DEVICE_ICON,
  d.HOSTNAME, d.SERIAL_NUMBER, d.ASSET_ID, d.MANUFACTURER, d.MODEL,
  d.OS, d.OS_VERSION, d.IP_ADDRESS, d.MAC_ADDRESS, d.INSTALL_DATE,
  d.STATUS, d.OWNER_SIDE, d.SUPPORT_GROUP, sg.NAME AS SUPPORT_GROUP_NAME,
  d.CRITICALITY, d.CPU_PCT, d.RAM_PCT, d.DISK_PCT, d.BATTERY_PCT,
  d.STORAGE_FREE_MB, d.PENDING_OPS, d.LAST_SEEN, d.LAST_SYNC,
  d.CREATED_AT, d.UPDATED_AT,
  (SELECT COUNT(*) FROM TBC_DEVICE_APPS da WHERE da.DEVICE_ID = d.ID) AS APP_COUNT,
  (SELECT COUNT(*) FROM TBC_DEVICE_APPS da WHERE da.DEVICE_ID = d.ID AND da.STATUS = 'OUTDATED') AS OUTDATED_COUNT,
  (SELECT COUNT(*) FROM TBC_EVENTS e WHERE e.DEVICE_ID = d.ID AND e.STATUS IN ('open','ack')) AS OPEN_EVENTS
FROM TBC_DEVICES d
JOIN TBC_STORES s ON s.ID = d.STORE_ID
JOIN TBC_REF_DEVICE_TYPES dt ON dt.CODE = d.DEVICE_TYPE
LEFT JOIN TBC_REF_SUPPORT_GROUPS sg ON sg.CODE = d.SUPPORT_GROUP;

-- Business Health магазина (разделы 20-21 ТЗ):
-- CRITICAL: открытое P1 или все POS offline. DEGRADED: открытые P2/P3
-- или часть устройств offline/degraded. Иначе OK.
CREATE OR REPLACE VIEW V_TBC_STORE_HEALTH AS
SELECT
  s.ID, s.CODE, s.NAME, s.COUNTRY, s.CITY, s.STATUS AS STORE_STATUS,
  s.MAINT_DOW, s.MAINT_TIME_FROM, s.MAINT_TIME_TO,
  NVL(d.DEVICE_TOTAL, 0)   AS DEVICE_TOTAL,
  NVL(d.DEVICE_ONLINE, 0)  AS DEVICE_ONLINE,
  NVL(d.DEVICE_OFFLINE, 0) AS DEVICE_OFFLINE,
  NVL(d.POS_TOTAL, 0)      AS POS_TOTAL,
  NVL(d.POS_ONLINE, 0)     AS POS_ONLINE,
  NVL(d.SCO_TOTAL, 0)      AS SCO_TOTAL,
  NVL(d.SCO_ONLINE, 0)     AS SCO_ONLINE,
  NVL(d.AND_TOTAL, 0)      AS AND_TOTAL,
  NVL(d.AND_ONLINE, 0)     AS AND_ONLINE,
  NVL(e.P1_OPEN, 0) AS P1_OPEN,
  NVL(e.P2_OPEN, 0) AS P2_OPEN,
  NVL(e.P3_OPEN, 0) AS P3_OPEN,
  NVL(e.P4_OPEN, 0) AS P4_OPEN,
  CASE
    WHEN NVL(e.P1_OPEN, 0) > 0 THEN 'CRITICAL'
    WHEN NVL(d.POS_TOTAL, 0) > 0 AND NVL(d.POS_ONLINE, 0) = 0 THEN 'CRITICAL'
    WHEN NVL(e.P2_OPEN, 0) > 0 OR NVL(e.P3_OPEN, 0) > 0 THEN 'DEGRADED'
    WHEN NVL(d.DEVICE_OFFLINE, 0) > 0 THEN 'DEGRADED'
    ELSE 'OK'
  END AS HEALTH
FROM TBC_STORES s
LEFT JOIN (
  SELECT STORE_ID,
    COUNT(*) AS DEVICE_TOTAL,
    SUM(CASE WHEN STATUS = 'online' THEN 1 ELSE 0 END) AS DEVICE_ONLINE,
    SUM(CASE WHEN STATUS = 'offline' THEN 1 ELSE 0 END) AS DEVICE_OFFLINE,
    SUM(CASE WHEN DEVICE_TYPE = 'POS' THEN 1 ELSE 0 END) AS POS_TOTAL,
    SUM(CASE WHEN DEVICE_TYPE = 'POS' AND STATUS = 'online' THEN 1 ELSE 0 END) AS POS_ONLINE,
    SUM(CASE WHEN DEVICE_TYPE = 'SCO' THEN 1 ELSE 0 END) AS SCO_TOTAL,
    SUM(CASE WHEN DEVICE_TYPE = 'SCO' AND STATUS = 'online' THEN 1 ELSE 0 END) AS SCO_ONLINE,
    SUM(CASE WHEN DEVICE_TYPE = 'AND' THEN 1 ELSE 0 END) AS AND_TOTAL,
    SUM(CASE WHEN DEVICE_TYPE = 'AND' AND STATUS = 'online' THEN 1 ELSE 0 END) AS AND_ONLINE
  FROM TBC_DEVICES GROUP BY STORE_ID
) d ON d.STORE_ID = s.ID
LEFT JOIN (
  SELECT STORE_ID,
    SUM(CASE WHEN SEVERITY = 'P1' THEN 1 ELSE 0 END) AS P1_OPEN,
    SUM(CASE WHEN SEVERITY = 'P2' THEN 1 ELSE 0 END) AS P2_OPEN,
    SUM(CASE WHEN SEVERITY = 'P3' THEN 1 ELSE 0 END) AS P3_OPEN,
    SUM(CASE WHEN SEVERITY = 'P4' THEN 1 ELSE 0 END) AS P4_OPEN
  FROM TBC_EVENTS WHERE STATUS IN ('open','ack') GROUP BY STORE_ID
) e ON e.STORE_ID = s.ID;

-- Контроль версий ПО (раздел 30 ТЗ)
CREATE OR REPLACE VIEW V_TBC_VERSIONS AS
SELECT
  da.ID, da.DEVICE_ID, d.CODE AS DEVICE_CODE, d.DEVICE_TYPE, d.STATUS AS DEVICE_STATUS,
  s.ID AS STORE_ID, s.CODE AS STORE_CODE, s.NAME AS STORE_NAME,
  a.ID AS APP_ID, a.CODE AS APP_CODE, a.NAME AS APP_NAME, a.APP_TYPE,
  a.EXPECTED_VERSION, a.RELEASE_CHANNEL,
  da.CURRENT_VERSION, da.BUILD, da.CONFIG_VERSION, da.STATUS,
  da.DEPLOYED_AT, da.LAST_CHECK
FROM TBC_DEVICE_APPS da
JOIN TBC_DEVICES d ON d.ID = da.DEVICE_ID
JOIN TBC_STORES s ON s.ID = d.STORE_ID
JOIN TBC_APPLICATIONS a ON a.ID = da.APP_ID;

-- События с контекстом
CREATE OR REPLACE VIEW V_TBC_EVENTS AS
SELECT
  e.ID, e.SEVERITY, sv.NAME AS SEVERITY_NAME, sv.COLOR AS SEVERITY_COLOR,
  e.STORE_ID, s.CODE AS STORE_CODE, s.NAME AS STORE_NAME,
  e.DEVICE_ID, d.CODE AS DEVICE_CODE, d.DEVICE_TYPE,
  e.SERVICE_CODE, svc.NAME AS SERVICE_NAME,
  e.PROBLEM, e.STATUS, e.SOURCE, e.CORRELATION_ID, e.PARENT_EVENT_ID,
  e.CREATED_AT, e.ACKED_AT, e.RESOLVED_AT,
  (SELECT COUNT(*) FROM TBC_EVENTS c WHERE c.PARENT_EVENT_ID = e.ID) AS CHILD_COUNT
FROM TBC_EVENTS e
JOIN TBC_REF_SEVERITIES sv ON sv.CODE = e.SEVERITY
LEFT JOIN TBC_STORES s ON s.ID = e.STORE_ID
LEFT JOIN TBC_DEVICES d ON d.ID = e.DEVICE_ID
LEFT JOIN TBC_REF_SERVICES svc ON svc.CODE = e.SERVICE_CODE;

-- Инциденты с контекстом
CREATE OR REPLACE VIEW V_TBC_INCIDENTS AS
SELECT
  i.ID, i.CODE, i.EVENT_ID, i.SEVERITY, sv.COLOR AS SEVERITY_COLOR,
  i.STORE_ID, s.CODE AS STORE_CODE, s.NAME AS STORE_NAME,
  i.DEVICE_ID, d.CODE AS DEVICE_CODE,
  i.TITLE, i.DESCRIPTION, i.ASSIGNED_GROUP, sg.NAME AS ASSIGNED_GROUP_NAME,
  i.ASSIGNEE, i.STATUS,
  i.ROOT_CAUSE, i.TECH_CAUSE, i.BUSINESS_IMPACT, i.RESOLUTION,
  i.CORRECTIVE_ACTION, i.PREVENTIVE_ACTION,
  i.OPENED_AT, i.CLOSED_AT, i.SLA_DEADLINE
FROM TBC_INCIDENTS i
JOIN TBC_REF_SEVERITIES sv ON sv.CODE = i.SEVERITY
LEFT JOIN TBC_STORES s ON s.ID = i.STORE_ID
LEFT JOIN TBC_DEVICES d ON d.ID = i.DEVICE_ID
LEFT JOIN TBC_REF_SUPPORT_GROUPS sg ON sg.CODE = i.ASSIGNED_GROUP;

-- Изменения / deployment
CREATE OR REPLACE VIEW V_TBC_CHANGES AS
SELECT
  c.ID, c.CODE, c.APP_ID, a.CODE AS APP_CODE, a.NAME AS APP_NAME,
  c.VERSION, c.ROLLBACK_VERSION, c.DESCRIPTION, c.REASON, c.OWNER,
  c.RELEASE_CHANNEL, c.WINDOW_START, c.WINDOW_END, c.STATUS,
  c.VALIDATION_RESULT, c.CREATED_BY, c.CREATED_AT, c.UPDATED_AT,
  (SELECT COUNT(*) FROM TBC_CHANGE_STORES cs WHERE cs.CHANGE_ID = c.ID) AS STORE_COUNT,
  (SELECT COUNT(*) FROM TBC_DEPLOY_CHECKS dc WHERE dc.CHANGE_ID = c.ID) AS CHECK_COUNT,
  (SELECT COUNT(*) FROM TBC_DEPLOY_CHECKS dc WHERE dc.CHANGE_ID = c.ID AND dc.STATUS = 'FAIL') AS CHECK_FAILED
FROM TBC_CHANGES c
JOIN TBC_APPLICATIONS a ON a.ID = c.APP_ID;

-- Сводная статистика для дашборда (раздел 34 ТЗ, уровень Executive)
CREATE OR REPLACE VIEW V_TBC_DASHBOARD_STATS AS
SELECT
  (SELECT COUNT(*) FROM TBC_STORES WHERE STATUS = 'active') AS TOTAL_STORES,
  (SELECT COUNT(*) FROM V_TBC_STORE_HEALTH WHERE HEALTH = 'OK' AND STORE_STATUS = 'active') AS OK_STORES,
  (SELECT COUNT(*) FROM V_TBC_STORE_HEALTH WHERE HEALTH = 'DEGRADED' AND STORE_STATUS = 'active') AS DEGRADED_STORES,
  (SELECT COUNT(*) FROM V_TBC_STORE_HEALTH WHERE HEALTH = 'CRITICAL' AND STORE_STATUS = 'active') AS CRITICAL_STORES,
  (SELECT COUNT(*) FROM TBC_DEVICES) AS TOTAL_DEVICES,
  (SELECT COUNT(*) FROM TBC_DEVICES WHERE STATUS = 'online') AS ONLINE_DEVICES,
  (SELECT COUNT(*) FROM TBC_DEVICES WHERE STATUS = 'offline') AS OFFLINE_DEVICES,
  (SELECT COUNT(*) FROM TBC_DEVICES WHERE STATUS = 'degraded') AS DEGRADED_DEVICES,
  (SELECT COUNT(*) FROM TBC_DEVICES WHERE DEVICE_TYPE = 'POS') AS POS_TOTAL,
  (SELECT COUNT(*) FROM TBC_DEVICES WHERE DEVICE_TYPE = 'POS' AND STATUS = 'online') AS POS_ONLINE,
  (SELECT COUNT(*) FROM TBC_DEVICES WHERE DEVICE_TYPE = 'SCO') AS SCO_TOTAL,
  (SELECT COUNT(*) FROM TBC_DEVICES WHERE DEVICE_TYPE = 'SCO' AND STATUS = 'online') AS SCO_ONLINE,
  (SELECT COUNT(*) FROM TBC_DEVICES WHERE DEVICE_TYPE = 'AND') AS AND_TOTAL,
  (SELECT COUNT(*) FROM TBC_DEVICES WHERE DEVICE_TYPE = 'AND' AND STATUS = 'online') AS AND_ONLINE,
  (SELECT COUNT(*) FROM TBC_EVENTS WHERE STATUS IN ('open','ack') AND SEVERITY = 'P1') AS P1_OPEN,
  (SELECT COUNT(*) FROM TBC_EVENTS WHERE STATUS IN ('open','ack') AND SEVERITY = 'P2') AS P2_OPEN,
  (SELECT COUNT(*) FROM TBC_EVENTS WHERE STATUS IN ('open','ack') AND SEVERITY = 'P3') AS P3_OPEN,
  (SELECT COUNT(*) FROM TBC_EVENTS WHERE STATUS IN ('open','ack') AND SEVERITY = 'P4') AS P4_OPEN,
  (SELECT COUNT(*) FROM TBC_INCIDENTS WHERE STATUS <> 'closed') AS OPEN_INCIDENTS,
  (SELECT COUNT(*) FROM TBC_DEVICE_APPS WHERE STATUS = 'OUTDATED') AS OUTDATED_APPS,
  (SELECT COUNT(*) FROM TBC_CHANGES WHERE STATUS IN ('planned','in_progress')) AS PENDING_CHANGES
FROM DUAL;
