-- ============================================================
-- TBControl: справочники + демо-данные (DML)
-- ============================================================

-- ===== Справочники =====

INSERT INTO TBC_REF_DEVICE_TYPES (CODE, NAME, ICON, SORT_ORDER) VALUES ('POS', 'POS-касса (Windows)', '🖥️', 1);
INSERT INTO TBC_REF_DEVICE_TYPES (CODE, NAME, ICON, SORT_ORDER) VALUES ('SCO', 'Self-Service касса', '🛒', 2);
INSERT INTO TBC_REF_DEVICE_TYPES (CODE, NAME, ICON, SORT_ORDER) VALUES ('AND', 'Android-устройство', '📱', 3);
INSERT INTO TBC_REF_DEVICE_TYPES (CODE, NAME, ICON, SORT_ORDER) VALUES ('SRV', 'Store Server', '🗄️', 4);
INSERT INTO TBC_REF_DEVICE_TYPES (CODE, NAME, ICON, SORT_ORDER) VALUES ('NET', 'Сетевое оборудование', '🌐', 5);
INSERT INTO TBC_REF_DEVICE_TYPES (CODE, NAME, ICON, SORT_ORDER) VALUES ('PRN', 'Принтер / периферия', '🖨️', 6);

INSERT INTO TBC_REF_SEVERITIES (CODE, NAME, COLOR, SORT_ORDER) VALUES ('P1', 'Critical — магазин не может продавать', '#e94560', 1);
INSERT INTO TBC_REF_SEVERITIES (CODE, NAME, COLOR, SORT_ORDER) VALUES ('P2', 'High — существенная деградация', '#ff8c42', 2);
INSERT INTO TBC_REF_SEVERITIES (CODE, NAME, COLOR, SORT_ORDER) VALUES ('P3', 'Medium — проблема одного устройства', '#ffc107', 3);
INSERT INTO TBC_REF_SEVERITIES (CODE, NAME, COLOR, SORT_ORDER) VALUES ('P4', 'Low — информационное событие', '#17a2b8', 4);

INSERT INTO TBC_REF_CHANNELS (CODE, NAME, SORT_ORDER) VALUES ('DEV', 'Development', 1);
INSERT INTO TBC_REF_CHANNELS (CODE, NAME, SORT_ORDER) VALUES ('TEST', 'Test', 2);
INSERT INTO TBC_REF_CHANNELS (CODE, NAME, SORT_ORDER) VALUES ('PILOT', 'Pilot', 3);
INSERT INTO TBC_REF_CHANNELS (CODE, NAME, SORT_ORDER) VALUES ('PRODUCTION', 'Production', 4);

INSERT INTO TBC_REF_SUPPORT_GROUPS (CODE, NAME, SORT_ORDER) VALUES ('customer_it', 'IT заказчика', 1);
INSERT INTO TBC_REF_SUPPORT_GROUPS (CODE, NAME, SORT_ORDER) VALUES ('developer', 'Разработчик', 2);
INSERT INTO TBC_REF_SUPPORT_GROUPS (CODE, NAME, SORT_ORDER) VALUES ('service_desk', 'Service Desk', 3);
INSERT INTO TBC_REF_SUPPORT_GROUPS (CODE, NAME, SORT_ORDER) VALUES ('management', 'Руководство', 4);

INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('network', 'Сеть магазина', 1);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('pos', 'POS', 2);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('sco', 'Self-Service', 3);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('android', 'Android', 4);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('store_app', 'Store Application', 5);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('payment', 'Оплата', 6);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('fiscal', 'Фискализация', 7);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('inventory', 'Inventory', 8);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('sync', 'Синхронизация', 9);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('api', 'Критические API', 10);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('database', 'База данных', 11);

-- ===== Магазины =====

INSERT INTO TBC_STORES (CODE, NAME, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-CHS-001', 'Магазин №1 Центр', 'MD', 'Chisinau', 'бул. Штефан чел Маре 1', 7, '02:00', '04:00');
INSERT INTO TBC_STORES (CODE, NAME, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-CHS-002', 'Магазин №2 Ботаника', 'MD', 'Chisinau', 'бул. Дачия 20', 7, '02:00', '04:00');
INSERT INTO TBC_STORES (CODE, NAME, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-CHS-003', 'Магазин №3 Рышкановка', 'MD', 'Chisinau', 'ул. Киевская 7', 1, '02:00', '04:00');
INSERT INTO TBC_STORES (CODE, NAME, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-BLT-101', 'Магазин №101 Бельцы', 'MD', 'Balti', 'ул. Индепенденцей 5', 2, '01:00', '03:00');

-- ===== Приложения =====

INSERT INTO TBC_APPLICATIONS (CODE, NAME, APP_TYPE, EXPECTED_VERSION, EXPECTED_BUILD, RELEASE_CHANNEL, HEALTH_URL)
VALUES ('frontoffice', 'Front Office', 'frontoffice', '7.4.12', '2026.08.07.3', 'PRODUCTION', 'http://localhost:9080/health');
INSERT INTO TBC_APPLICATIONS (CODE, NAME, APP_TYPE, EXPECTED_VERSION, EXPECTED_BUILD, RELEASE_CHANNEL, HEALTH_URL)
VALUES ('sco_app', 'SCO Application', 'sco', '3.8.4', '2026.07.30.1', 'PRODUCTION', 'http://localhost:9081/health');
INSERT INTO TBC_APPLICATIONS (CODE, NAME, APP_TYPE, EXPECTED_VERSION, EXPECTED_BUILD, RELEASE_CHANNEL, HEALTH_URL)
VALUES ('storeapp_android', 'Store App (Android)', 'android', '5.12.3', '2026.08.01.2', 'PRODUCTION', NULL);
INSERT INTO TBC_APPLICATIONS (CODE, NAME, APP_TYPE, EXPECTED_VERSION, EXPECTED_BUILD, RELEASE_CHANNEL, HEALTH_URL)
VALUES ('store_service', 'Store Service (сервер)', 'store_app', '2.4.0', '2026.07.15.4', 'PRODUCTION', 'http://localhost:9082/health');

-- ===== Устройства (магазин 001: полный, 002/003/101: частично) =====

INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, ASSET_ID, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, MAC_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-001-POS-01', 1, 'POS', 'POS01-S001', 'SN-P1001', 'AST-0101', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.1.11', '00:1A:2B:01:01:11', DATE '2025-03-10', 'online', 'customer', 'customer_it', 'high', 22, 48, 61, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, ASSET_ID, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, MAC_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-001-POS-02', 1, 'POS', 'POS02-S001', 'SN-P1002', 'AST-0102', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.1.12', '00:1A:2B:01:01:12', DATE '2025-03-10', 'online', 'customer', 'customer_it', 'high', 35, 52, 58, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, ASSET_ID, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, MAC_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-001-POS-03', 1, 'POS', 'POS03-S001', 'SN-P1003', 'AST-0103', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.1.13', '00:1A:2B:01:01:13', DATE '2025-06-22', 'degraded', 'customer', 'customer_it', 'high', 78, 84, 91, SYSTIMESTAMP - INTERVAL '4' MINUTE, SYSTIMESTAMP - INTERVAL '35' MINUTE);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, ASSET_ID, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, MAC_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-001-SCO-01', 1, 'SCO', 'SCO01-S001', 'SN-S1001', 'AST-0111', 'NCR', 'FastLane R6C', 'Windows', '10 IoT LTSC', '10.10.1.21', '00:1A:2B:01:02:21', DATE '2025-09-01', 'online', 'customer', 'customer_it', 'high', 18, 40, 44, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, ASSET_ID, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, MAC_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-001-SCO-02', 1, 'SCO', 'SCO02-S001', 'SN-S1002', 'AST-0112', 'NCR', 'FastLane R6C', 'Windows', '10 IoT LTSC', '10.10.1.22', '00:1A:2B:01:02:22', DATE '2025-09-01', 'offline', 'customer', 'customer_it', 'high', NULL, NULL, NULL, SYSTIMESTAMP - INTERVAL '3' HOUR, SYSTIMESTAMP - INTERVAL '3' HOUR);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, ASSET_ID, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, MAC_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, BATTERY_PCT, STORAGE_FREE_MB, PENDING_OPS, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-001-AND-01', 1, 'AND', 'AND01-S001', 'SN-A1001', 'AST-0121', 'Zebra', 'TC26', 'Android', '13', '10.10.1.31', '00:1A:2B:01:03:31', DATE '2025-11-15', 'online', 'customer', 'customer_it', 'medium', 87, 32100, 0, SYSTIMESTAMP, SYSTIMESTAMP - INTERVAL '2' MINUTE);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, ASSET_ID, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, MAC_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, BATTERY_PCT, STORAGE_FREE_MB, PENDING_OPS, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-001-AND-02', 1, 'AND', 'AND02-S001', 'SN-A1002', 'AST-0122', 'Zebra', 'TC26', 'Android', '13', '10.10.1.32', '00:1A:2B:01:03:32', DATE '2025-11-15', 'degraded', 'customer', 'customer_it', 'medium', 12, 900, 47, SYSTIMESTAMP - INTERVAL '10' MINUTE, SYSTIMESTAMP - INTERVAL '55' MINUTE);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, ASSET_ID, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, MAC_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-001-SRV-01', 1, 'SRV', 'SRV01-S001', 'SN-V1001', 'AST-0131', 'HPE', 'ProLiant ML30', 'Linux', 'Ubuntu 24.04', '10.10.1.5', '00:1A:2B:01:00:05', DATE '2025-03-01', 'online', 'customer', 'customer_it', 'high', 30, 55, 72, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-002-POS-01', 2, 'POS', 'POS01-S002', 'SN-P2001', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.2.11', DATE '2025-04-18', 'online', 'customer', 'customer_it', 'high', 25, 45, 50, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-002-POS-02', 2, 'POS', 'POS02-S002', 'SN-P2002', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.2.12', DATE '2025-04-18', 'online', 'customer', 'customer_it', 'high', 28, 50, 47, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, BATTERY_PCT, STORAGE_FREE_MB, PENDING_OPS, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-002-AND-01', 2, 'AND', 'AND01-S002', 'SN-A2001', 'Zebra', 'TC21', 'Android', '11', '10.10.2.31', DATE '2025-10-02', 'online', 'customer', 'customer_it', 'medium', 64, 18000, 2, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-003-POS-01', 3, 'POS', 'POS01-S003', 'SN-P3001', 'Toshiba', 'TCx 700', 'Windows', '10 IoT LTSC', '10.10.3.11', DATE '2025-05-20', 'offline', 'customer', 'customer_it', 'high', SYSTIMESTAMP - INTERVAL '6' HOUR, SYSTIMESTAMP - INTERVAL '6' HOUR);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-003-POS-02', 3, 'POS', 'POS02-S003', 'SN-P3002', 'Toshiba', 'TCx 700', 'Windows', '10 IoT LTSC', '10.10.3.12', DATE '2025-05-20', 'offline', 'customer', 'customer_it', 'high', SYSTIMESTAMP - INTERVAL '6' HOUR, SYSTIMESTAMP - INTERVAL '6' HOUR);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, LAST_SEEN, LAST_SYNC)
VALUES ('MD-CHS-003-NET-01', 3, 'NET', 'RTR01-S003', 'SN-N3001', 'MikroTik', 'RB4011', 'RouterOS', '7.15', '10.10.3.1', DATE '2025-05-19', 'offline', 'customer', 'customer_it', 'high', SYSTIMESTAMP - INTERVAL '6' HOUR, NULL);

INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
VALUES ('MD-BLT-101-POS-01', 4, 'POS', 'POS01-S101', 'SN-P9001', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.20.1.11', DATE '2025-08-30', 'online', 'customer', 'customer_it', 'high', 20, 38, 55, SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, SERIAL_NUMBER, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, INSTALL_DATE, STATUS, OWNER_SIDE, SUPPORT_GROUP, CRITICALITY, BATTERY_PCT, STORAGE_FREE_MB, PENDING_OPS, LAST_SEEN, LAST_SYNC)
VALUES ('MD-BLT-101-AND-01', 4, 'AND', 'AND01-S101', 'SN-A9001', 'Honeywell', 'EDA52', 'Android', '12', '10.20.1.31', DATE '2025-12-01', 'online', 'customer', 'customer_it', 'medium', 91, 41000, 0, SYSTIMESTAMP, SYSTIMESTAMP);

-- ===== Версии приложений на устройствах =====

INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (1, 1, '7.4.12', '2026.08.07.3', 'cfg-118', 'OK', SYSTIMESTAMP - 2, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (2, 1, '7.4.12', '2026.08.07.3', 'cfg-118', 'OK', SYSTIMESTAMP - 2, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (3, 1, '7.3.9', '2026.06.11.1', 'cfg-104', 'OUTDATED', SYSTIMESTAMP - 58, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (4, 2, '3.8.4', '2026.07.30.1', 'cfg-52', 'OK', SYSTIMESTAMP - 9, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (5, 2, '3.8.4', '2026.07.30.1', 'cfg-52', 'UNKNOWN', SYSTIMESTAMP - 9, SYSTIMESTAMP - INTERVAL '3' HOUR);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (6, 3, '5.12.3', '2026.08.01.2', 'cfg-30', 'OK', SYSTIMESTAMP - 7, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (7, 3, '5.11.0', '2026.06.20.5', 'cfg-27', 'OUTDATED', SYSTIMESTAMP - 49, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (8, 4, '2.4.0', '2026.07.15.4', 'cfg-15', 'OK', SYSTIMESTAMP - 24, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (9, 1, '7.4.12', '2026.08.07.3', 'cfg-118', 'OK', SYSTIMESTAMP - 2, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (10, 1, '7.4.12', '2026.08.07.3', 'cfg-118', 'OK', SYSTIMESTAMP - 2, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (11, 3, '5.12.3', '2026.08.01.2', 'cfg-30', 'OK', SYSTIMESTAMP - 7, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (12, 1, '7.4.11', '2026.07.28.2', 'cfg-115', 'OUTDATED', SYSTIMESTAMP - 12, SYSTIMESTAMP - INTERVAL '6' HOUR);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (15, 1, '7.4.12', '2026.08.07.3', 'cfg-118', 'OK', SYSTIMESTAMP - 2, SYSTIMESTAMP);
INSERT INTO TBC_DEVICE_APPS (DEVICE_ID, APP_ID, CURRENT_VERSION, BUILD, CONFIG_VERSION, STATUS, DEPLOYED_AT, LAST_CHECK)
VALUES (16, 3, '5.12.3', '2026.08.01.2', 'cfg-30', 'OK', SYSTIMESTAMP - 7, SYSTIMESTAMP);

-- ===== События (корреляция: сеть 003 → POS suppressed) =====

INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
VALUES ('P1', 3, 15, 'network', 'Store network unavailable — router MD-CHS-003-NET-01 не отвечает', 'open', 'zabbix', 'c1a2b3');
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID, PARENT_EVENT_ID)
VALUES ('P3', 3, 13, 'pos', 'POS-01 unavailable', 'suppressed', 'correlation', 'c1a2b3', 1);
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID, PARENT_EVENT_ID)
VALUES ('P3', 3, 14, 'pos', 'POS-02 unavailable', 'suppressed', 'correlation', 'c1a2b3', 1);
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
VALUES ('P3', 1, 5, 'sco', 'SCO-02 offline — не отвечает 3 часа', 'ack', 'zabbix', 'd4e5f6');
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
VALUES ('P3', 1, 3, 'payment', 'Payment terminal timeout на POS-03', 'open', 'agent', 'a82d91');
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE)
VALUES ('P4', 1, 3, 'pos', 'Low disk space: 91% used', 'open', 'zabbix');
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE)
VALUES ('P4', 1, 7, 'android', 'Battery low (12%), 47 pending operations', 'open', 'agent');
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, RESOLVED_AT)
VALUES ('P2', 2, 'sync', 'Synchronization delay > 30 min', 'resolved', 'zabbix', SYSTIMESTAMP - INTERVAL '2' HOUR);

-- ===== Инциденты =====

INSERT INTO TBC_INCIDENTS (CODE, EVENT_ID, STORE_ID, DEVICE_ID, SEVERITY, TITLE, DESCRIPTION, ASSIGNED_GROUP, ASSIGNEE, STATUS, SLA_DEADLINE)
VALUES ('INC-2026-10452', 1, 3, 15, 'P1', 'Магазин 003: сеть недоступна', 'Router не отвечает, все POS offline. Root cause: store network. Downstream события подавлены.', 'customer_it', 'n.ivanov', 'diagnosing', SYSTIMESTAMP + INTERVAL '2' HOUR);
INSERT INTO TBC_INCIDENTS (CODE, EVENT_ID, STORE_ID, DEVICE_ID, SEVERITY, TITLE, DESCRIPTION, ASSIGNED_GROUP, ASSIGNEE, STATUS, SLA_DEADLINE)
VALUES ('INC-2026-10453', 5, 1, 3, 'P3', 'POS-03: таймаут платёжного терминала', 'Payment timeout, сеть OK. Диагностика: терминал недоступен.', 'customer_it', 'p.rusu', 'assigned', SYSTIMESTAMP + INTERVAL '8' HOUR);
INSERT INTO TBC_INCIDENTS (CODE, STORE_ID, DEVICE_ID, SEVERITY, TITLE, DESCRIPTION, ASSIGNED_GROUP, STATUS, ROOT_CAUSE, TECH_CAUSE, BUSINESS_IMPACT, RESOLUTION, CORRECTIVE_ACTION, PREVENTIVE_ACTION, OPENED_AT, CLOSED_AT)
VALUES ('INC-2026-10401', 2, NULL, 'P2', 'Магазин 002: остановка синхронизации', 'Sync delay > 30 минут', 'developer', 'closed', 'Переполнение очереди synchronization после релиза 7.4.11', 'Утечка соединений в sync-модуле', 'Задержка обновления остатков 40 мин, продажи не блокированы', 'Патч 7.4.12, перезапуск sync-службы', 'Hotfix в 7.4.12', 'Автотест на leak в CI, мониторинг queue size', SYSTIMESTAMP - 3, SYSTIMESTAMP - 2);

-- ===== Изменения / deployment =====

INSERT INTO TBC_CHANGES (CODE, APP_ID, VERSION, ROLLBACK_VERSION, DESCRIPTION, REASON, OWNER, RELEASE_CHANNEL, WINDOW_START, WINDOW_END, STATUS, VALIDATION_RESULT, CREATED_BY)
VALUES ('CHG-2026-0812', 1, '7.4.13', '7.4.12', 'Front Office 7.4.13: исправление payment retry', 'Bugfix PAYMENT_TIMEOUT', 'dev-team', 'PILOT', SYSTIMESTAMP + 1, SYSTIMESTAMP + 1 + INTERVAL '2' HOUR, 'planned', NULL, 'admin');
INSERT INTO TBC_CHANGES (CODE, APP_ID, VERSION, ROLLBACK_VERSION, DESCRIPTION, REASON, OWNER, RELEASE_CHANNEL, WINDOW_START, WINDOW_END, STATUS, VALIDATION_RESULT, CREATED_BY)
VALUES ('CHG-2026-0798', 1, '7.4.12', '7.4.11', 'Front Office 7.4.12: hotfix sync leak', 'Инцидент INC-2026-10401', 'dev-team', 'PRODUCTION', SYSTIMESTAMP - 2, SYSTIMESTAMP - 2 + INTERVAL '2' HOUR, 'success', 'SUCCESS', 'admin');

INSERT INTO TBC_CHANGE_STORES (CHANGE_ID, STORE_ID) VALUES (1, 1);
INSERT INTO TBC_CHANGE_STORES (CHANGE_ID, STORE_ID) VALUES (2, 1);
INSERT INTO TBC_CHANGE_STORES (CHANGE_ID, STORE_ID) VALUES (2, 2);
INSERT INTO TBC_CHANGE_STORES (CHANGE_ID, STORE_ID) VALUES (2, 4);

INSERT INTO TBC_DEPLOY_CHECKS (CHANGE_ID, DEVICE_ID, CHECK_TYPE, STATUS, DETAILS) VALUES (2, 1, 'process', 'OK', 'POS.exe running');
INSERT INTO TBC_DEPLOY_CHECKS (CHANGE_ID, DEVICE_ID, CHECK_TYPE, STATUS, DETAILS) VALUES (2, 1, 'version', 'OK', '7.4.12 = expected');
INSERT INTO TBC_DEPLOY_CHECKS (CHANGE_ID, DEVICE_ID, CHECK_TYPE, STATUS, DETAILS) VALUES (2, 1, 'health', 'OK', '/health 200, 8 ms');
INSERT INTO TBC_DEPLOY_CHECKS (CHANGE_ID, DEVICE_ID, CHECK_TYPE, STATUS, DETAILS) VALUES (2, 1, 'business', 'OK', 'Test transaction OK');

-- ===== Health checks (диагностика POS-03, раздел 40 ТЗ) =====

INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'network', 'OK', 2, NULL);
INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'dns', 'OK', 5, NULL);
INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'gateway', 'OK', 3, NULL);
INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'agent', 'OK', NULL, 'Zabbix Agent 2 running');
INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'process', 'OK', NULL, 'POS.exe running');
INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'database', 'OK', 8, NULL);
INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'api', 'OK', 32, NULL);
INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'payment', 'FAIL', NULL, 'Payment terminal timeout');
INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'fiscal', 'OK', 45, NULL);
INSERT INTO TBC_HEALTH_CHECKS (DEVICE_ID, COMPONENT, STATUS, LATENCY_MS, DETAILS) VALUES (3, 'printer', 'OK', NULL, NULL);

-- ===== SLA (раздел 51 ТЗ) =====

INSERT INTO TBC_SLA_TARGETS (SERVICE_CODE, TARGET_PCT, CURRENT_PCT) VALUES ('pos', 99.95, 99.97);
INSERT INTO TBC_SLA_TARGETS (SERVICE_CODE, TARGET_PCT, CURRENT_PCT) VALUES ('sco', 99.90, 99.84);
INSERT INTO TBC_SLA_TARGETS (SERVICE_CODE, TARGET_PCT, CURRENT_PCT) VALUES ('store_app', 99.95, 99.99);
INSERT INTO TBC_SLA_TARGETS (SERVICE_CODE, TARGET_PCT, CURRENT_PCT) VALUES ('api', 99.99, 99.99);
INSERT INTO TBC_SLA_TARGETS (SERVICE_CODE, TARGET_PCT, CURRENT_PCT) VALUES ('payment', 99.95, 99.91);
INSERT INTO TBC_SLA_TARGETS (SERVICE_CODE, TARGET_PCT, CURRENT_PCT) VALUES ('fiscal', 99.95, 99.98);

COMMIT;
