-- ============================================================
-- TBControl: Monitoring Center + Processing Center + AI Dossiers
-- Разделы 72-75 ТЗ docs/TBControl/TECHNICAL-OPS.md
-- ============================================================

CREATE SEQUENCE TBC_METRICS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_NODES_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_FLOWS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_FLOW_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_DOSSIERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ==================== Time series метрик касс (раздел 72) ====================

CREATE TABLE TBC_METRIC_SAMPLES (
  ID         NUMBER       NOT NULL,
  DEVICE_ID  NUMBER       NOT NULL,
  SCOPE      VARCHAR2(5)  NOT NULL,     -- hw (касса-компьютер) / app (Front Office)
  METRIC     VARCHAR2(30) NOT NULL,     -- cpu/ram/disk/uptime | app_latency/tx_count/app_errors
  NUM_VALUE  NUMBER,
  SAMPLED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_METRICS PRIMARY KEY (ID),
  CONSTRAINT FK_TBC_MS_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES TBC_DEVICES(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_TBC_MS_SCOPE CHECK (SCOPE IN ('hw','app'))
);
/

CREATE OR REPLACE TRIGGER TBC_METRICS_BI
  BEFORE INSERT ON TBC_METRIC_SAMPLES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_METRICS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_TBC_MS_DEV ON TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, SAMPLED_AT);

-- ==================== Узлы обработки (раздел 73.3) ====================

CREATE TABLE TBC_NODES (
  ID             NUMBER        NOT NULL,
  CODE           VARCHAR2(40)  NOT NULL,   -- MD-CHS-001-ISRV-A, CENTRAL-01, BACKOFFICE-01
  NAME           VARCHAR2(200) NOT NULL,
  NODE_TYPE      VARCHAR2(20)  NOT NULL,   -- store_srv / central / backoffice
  STORE_ID       NUMBER,                   -- NULL для central/backoffice
  HOSTNAME       VARCHAR2(100),
  IP_ADDRESS     VARCHAR2(45),
  OS             VARCHAR2(50),
  STATUS         VARCHAR2(20)  DEFAULT 'offline',
  CPU_PCT        NUMBER,
  RAM_PCT        NUMBER,
  DISK_PCT       NUMBER,
  APP_NAME       VARCHAR2(100),            -- сервис обмена/консолидации
  APP_VERSION    VARCHAR2(30),
  APP_STATUS     VARCHAR2(10)  DEFAULT 'UNKNOWN',   -- OK/WARN/FAIL/UNKNOWN
  DB_ENGINE      VARCHAR2(20),             -- oracle/sqlite/mssql/mysql/postgres
  DB_VERSION     VARCHAR2(50),
  DB_STATUS      VARCHAR2(10)  DEFAULT 'UNKNOWN',
  DB_SIZE_MB     NUMBER,
  DB_CONNECTIONS NUMBER,
  LAST_SEEN      TIMESTAMP,
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_NODES PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_NODES_CODE UNIQUE (CODE),
  CONSTRAINT FK_TBC_ND_STORE FOREIGN KEY (STORE_ID) REFERENCES TBC_STORES(ID),
  CONSTRAINT CHK_TBC_ND_TYPE CHECK (NODE_TYPE IN ('store_srv','central','backoffice')),
  CONSTRAINT CHK_TBC_ND_STATUS CHECK (STATUS IN ('online','degraded','offline','maintenance')),
  CONSTRAINT CHK_TBC_ND_ENGINE CHECK (DB_ENGINE IN ('oracle','sqlite','mssql','mysql','postgres'))
);
/

CREATE OR REPLACE TRIGGER TBC_NODES_BI
  BEFORE INSERT ON TBC_NODES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_NODES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TBC_NODES_BU
  BEFORE UPDATE ON TBC_NODES FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ==================== Потоки обмена (раздел 73.1) ====================

CREATE TABLE TBC_FLOWS (
  ID            NUMBER        NOT NULL,
  CODE          VARCHAR2(60)  NOT NULL,
  NAME          VARCHAR2(200),
  SRC_KIND      VARCHAR2(10)  NOT NULL,   -- device (касса, SQLite) / node (сервер)
  SRC_DEVICE_ID NUMBER,
  SRC_NODE_ID   NUMBER,
  DST_NODE_ID   NUMBER        NOT NULL,
  FLOW_TYPE     VARCHAR2(20)  DEFAULT 'sales',   -- sales/docs/prices/stock/sync
  SCHEDULE_MIN  NUMBER        DEFAULT 15,        -- периодичность обмена, мин
  STATUS        VARCHAR2(10)  DEFAULT 'OK',      -- OK/LAGGING/STALLED/FAIL
  LAG_MIN       NUMBER        DEFAULT 0,
  PENDING_ROWS  NUMBER        DEFAULT 0,
  LAST_OK_AT    TIMESTAMP,
  LAST_ERROR    VARCHAR2(500),
  UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_FLOWS PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_FLOWS_CODE UNIQUE (CODE),
  CONSTRAINT FK_TBC_FL_SDEV  FOREIGN KEY (SRC_DEVICE_ID) REFERENCES TBC_DEVICES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_TBC_FL_SNODE FOREIGN KEY (SRC_NODE_ID) REFERENCES TBC_NODES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_TBC_FL_DNODE FOREIGN KEY (DST_NODE_ID) REFERENCES TBC_NODES(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_TBC_FL_KIND CHECK (SRC_KIND IN ('device','node')),
  CONSTRAINT CHK_TBC_FL_STATUS CHECK (STATUS IN ('OK','LAGGING','STALLED','FAIL'))
);
/

CREATE OR REPLACE TRIGGER TBC_FLOWS_BI
  BEFORE INSERT ON TBC_FLOWS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_FLOWS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TBC_FLOWS_BU
  BEFORE UPDATE ON TBC_FLOWS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Журнал батчей (append-only)
CREATE TABLE TBC_FLOW_LOG (
  ID            NUMBER       NOT NULL,
  FLOW_ID       NUMBER       NOT NULL,
  BATCH_CODE    VARCHAR2(40),
  ROWS_SENT     NUMBER       DEFAULT 0,
  ROWS_ACCEPTED NUMBER       DEFAULT 0,
  STATUS        VARCHAR2(10) NOT NULL,   -- OK/FAIL/PARTIAL
  ERROR_MSG     VARCHAR2(500),
  STARTED_AT    TIMESTAMP    DEFAULT SYSTIMESTAMP,
  FINISHED_AT   TIMESTAMP,
  CONSTRAINT PK_TBC_FLOW_LOG PRIMARY KEY (ID),
  CONSTRAINT FK_TBC_FLOG_FLOW FOREIGN KEY (FLOW_ID) REFERENCES TBC_FLOWS(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_TBC_FLOG_ST CHECK (STATUS IN ('OK','FAIL','PARTIAL'))
);
/

CREATE OR REPLACE TRIGGER TBC_FLOW_LOG_BI
  BEFORE INSERT ON TBC_FLOW_LOG FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_FLOW_LOG_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_TBC_FLOG ON TBC_FLOW_LOG (FLOW_ID, STARTED_AT);

-- ==================== AI Diagnostic Dossiers (раздел 74) ====================

CREATE TABLE TBC_AI_DOSSIERS (
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(40)  NOT NULL,   -- DSR-2026-000123
  SOURCE_TYPE  VARCHAR2(20)  NOT NULL,   -- event/incident/flow/node/device
  REF_ID       NUMBER        NOT NULL,
  TITLE        VARCHAR2(300) NOT NULL,
  SEVERITY     VARCHAR2(5),
  STATUS       VARCHAR2(20)  DEFAULT 'new',   -- new/sent/analyzed/resolved
  MD_CONTENT   CLOB,
  ACCESS_TOKEN VARCHAR2(64)  NOT NULL,
  READS_COUNT  NUMBER        DEFAULT 0,
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_DOSSIERS PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_DOSSIERS UNIQUE (CODE),
  CONSTRAINT CHK_TBC_DSR_SRC CHECK (SOURCE_TYPE IN ('event','incident','flow','node','device')),
  CONSTRAINT CHK_TBC_DSR_ST CHECK (STATUS IN ('new','sent','analyzed','resolved'))
);
/

CREATE OR REPLACE TRIGGER TBC_DOSSIERS_BI
  BEFORE INSERT ON TBC_AI_DOSSIERS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_DOSSIERS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TBC_DOSSIERS_BU
  BEFORE UPDATE ON TBC_AI_DOSSIERS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ==================== Представления ====================

CREATE OR REPLACE VIEW V_TBC_NODES AS
SELECT
  n.ID, n.CODE, n.NAME, n.NODE_TYPE, n.STORE_ID,
  s.CODE AS STORE_CODE, s.NAME AS STORE_NAME,
  n.HOSTNAME, n.IP_ADDRESS, n.OS, n.STATUS,
  n.CPU_PCT, n.RAM_PCT, n.DISK_PCT,
  n.APP_NAME, n.APP_VERSION, n.APP_STATUS,
  n.DB_ENGINE, n.DB_VERSION, n.DB_STATUS, n.DB_SIZE_MB, n.DB_CONNECTIONS,
  n.LAST_SEEN, n.UPDATED_AT,
  (SELECT COUNT(*) FROM TBC_FLOWS f WHERE (f.SRC_NODE_ID = n.ID OR f.DST_NODE_ID = n.ID)) AS FLOW_COUNT,
  (SELECT COUNT(*) FROM TBC_FLOWS f WHERE (f.SRC_NODE_ID = n.ID OR f.DST_NODE_ID = n.ID)
     AND f.STATUS IN ('STALLED','FAIL')) AS FLOW_PROBLEMS
FROM TBC_NODES n
LEFT JOIN TBC_STORES s ON s.ID = n.STORE_ID;

CREATE OR REPLACE VIEW V_TBC_FLOWS AS
SELECT
  f.ID, f.CODE, f.NAME, f.SRC_KIND, f.FLOW_TYPE, f.SCHEDULE_MIN,
  f.SRC_DEVICE_ID, d.CODE AS SRC_DEVICE_CODE, d.STATUS AS SRC_DEVICE_STATUS,
  f.SRC_NODE_ID, sn.CODE AS SRC_NODE_CODE, sn.STATUS AS SRC_NODE_STATUS,
  f.DST_NODE_ID, dn.CODE AS DST_NODE_CODE, dn.NODE_TYPE AS DST_NODE_TYPE, dn.STATUS AS DST_NODE_STATUS,
  COALESCE(d.CODE, sn.CODE) AS SRC_CODE,
  COALESCE(ds.CODE, ss.CODE) AS STORE_CODE,
  f.STATUS, f.LAG_MIN, f.PENDING_ROWS, f.LAST_OK_AT, f.LAST_ERROR, f.UPDATED_AT,
  (SELECT COUNT(*) FROM TBC_FLOW_LOG l WHERE l.FLOW_ID = f.ID AND l.STATUS = 'FAIL'
     AND l.STARTED_AT > SYSTIMESTAMP - 1) AS FAILS_24H
FROM TBC_FLOWS f
LEFT JOIN TBC_DEVICES d ON d.ID = f.SRC_DEVICE_ID
LEFT JOIN TBC_STORES ds ON ds.ID = d.STORE_ID
LEFT JOIN TBC_NODES sn ON sn.ID = f.SRC_NODE_ID
LEFT JOIN TBC_STORES ss ON ss.ID = sn.STORE_ID
JOIN TBC_NODES dn ON dn.ID = f.DST_NODE_ID;

CREATE OR REPLACE VIEW V_TBC_PROC_STATS AS
SELECT
  (SELECT COUNT(*) FROM TBC_FLOWS) AS FLOWS_TOTAL,
  (SELECT COUNT(*) FROM TBC_FLOWS WHERE STATUS = 'OK') AS FLOWS_OK,
  (SELECT COUNT(*) FROM TBC_FLOWS WHERE STATUS = 'LAGGING') AS FLOWS_LAGGING,
  (SELECT COUNT(*) FROM TBC_FLOWS WHERE STATUS = 'STALLED') AS FLOWS_STALLED,
  (SELECT COUNT(*) FROM TBC_FLOWS WHERE STATUS = 'FAIL') AS FLOWS_FAIL,
  (SELECT NVL(SUM(PENDING_ROWS), 0) FROM TBC_FLOWS) AS PENDING_TOTAL,
  (SELECT NVL(MAX(LAG_MIN), 0) FROM TBC_FLOWS) AS MAX_LAG_MIN,
  (SELECT COUNT(*) FROM TBC_NODES) AS NODES_TOTAL,
  (SELECT COUNT(*) FROM TBC_NODES WHERE STATUS = 'online') AS NODES_ONLINE,
  (SELECT COUNT(*) FROM TBC_NODES WHERE STATUS = 'offline') AS NODES_OFFLINE,
  (SELECT COUNT(*) FROM TBC_NODES WHERE DB_STATUS = 'FAIL') AS NODES_DB_FAIL,
  (SELECT COUNT(*) FROM TBC_FLOW_LOG WHERE STATUS = 'FAIL' AND STARTED_AT > SYSTIMESTAMP - 1) AS BATCH_FAILS_24H,
  (SELECT COUNT(*) FROM TBC_AI_DOSSIERS) AS DOSSIERS_TOTAL,
  (SELECT COUNT(*) FROM TBC_AI_DOSSIERS WHERE STATUS = 'new') AS DOSSIERS_NEW
FROM DUAL;
