-- ============================================================
-- TBControl: демо-данные Processing Center + телеметрия касс
-- Требует загруженных 72_tbc_demo_data.sql (магазины 1-4, устройства 1-16)
-- ============================================================

-- ===== Узлы обработки =====
-- Магазин 001: ДВА промежуточных сервера (A: MySQL, B: PostgreSQL)
INSERT INTO TBC_NODES (CODE, NAME, NODE_TYPE, STORE_ID, HOSTNAME, IP_ADDRESS, OS, STATUS, CPU_PCT, RAM_PCT, DISK_PCT, APP_NAME, APP_VERSION, APP_STATUS, DB_ENGINE, DB_VERSION, DB_STATUS, DB_SIZE_MB, DB_CONNECTIONS, LAST_SEEN)
VALUES ('MD-CHS-001-ISRV-A', 'Промежуточный сервер A (Магазин 001)', 'store_srv', 1, 'ISRVA-S001', '10.10.1.6', 'Ubuntu 24.04', 'online', 34, 58, 66, 'StoreSync Service', '2.4.0', 'OK', 'mysql', '8.0.36', 'OK', 12400, 14, SYSTIMESTAMP);
INSERT INTO TBC_NODES (CODE, NAME, NODE_TYPE, STORE_ID, HOSTNAME, IP_ADDRESS, OS, STATUS, CPU_PCT, RAM_PCT, DISK_PCT, APP_NAME, APP_VERSION, APP_STATUS, DB_ENGINE, DB_VERSION, DB_STATUS, DB_SIZE_MB, DB_CONNECTIONS, LAST_SEEN)
VALUES ('MD-CHS-001-ISRV-B', 'Промежуточный сервер B (Магазин 001)', 'store_srv', 1, 'ISRVB-S001', '10.10.1.7', 'Ubuntu 24.04', 'degraded', 81, 90, 94, 'StoreSync Service', '2.3.1', 'WARN', 'postgres', '16.2', 'WARN', 41800, 47, SYSTIMESTAMP - INTERVAL '7' MINUTE);
-- Магазин 002: один промежуточный сервер (MSSQL)
INSERT INTO TBC_NODES (CODE, NAME, NODE_TYPE, STORE_ID, HOSTNAME, IP_ADDRESS, OS, STATUS, CPU_PCT, RAM_PCT, DISK_PCT, APP_NAME, APP_VERSION, APP_STATUS, DB_ENGINE, DB_VERSION, DB_STATUS, DB_SIZE_MB, DB_CONNECTIONS, LAST_SEEN)
VALUES ('MD-CHS-002-ISRV-A', 'Промежуточный сервер (Магазин 002)', 'store_srv', 2, 'ISRVA-S002', '10.10.2.6', 'Windows Server 2022', 'online', 28, 44, 51, 'StoreSync Service', '2.4.0', 'OK', 'mssql', '2022 CU12', 'OK', 22100, 22, SYSTIMESTAMP);
-- Магазин 003: сервер офлайн (сеть магазина лежит)
INSERT INTO TBC_NODES (CODE, NAME, NODE_TYPE, STORE_ID, HOSTNAME, IP_ADDRESS, OS, STATUS, CPU_PCT, RAM_PCT, DISK_PCT, APP_NAME, APP_VERSION, APP_STATUS, DB_ENGINE, DB_VERSION, DB_STATUS, DB_SIZE_MB, DB_CONNECTIONS, LAST_SEEN)
VALUES ('MD-CHS-003-ISRV-A', 'Промежуточный сервер (Магазин 003)', 'store_srv', 3, 'ISRVA-S003', '10.10.3.6', 'Ubuntu 22.04', 'offline', NULL, NULL, NULL, 'StoreSync Service', '2.4.0', 'UNKNOWN', 'mysql', '8.0.36', 'UNKNOWN', 8700, NULL, SYSTIMESTAMP - INTERVAL '6' HOUR);
-- Магазин 101: sqlite-узел (малый формат)
INSERT INTO TBC_NODES (CODE, NAME, NODE_TYPE, STORE_ID, HOSTNAME, IP_ADDRESS, OS, STATUS, CPU_PCT, RAM_PCT, DISK_PCT, APP_NAME, APP_VERSION, APP_STATUS, DB_ENGINE, DB_VERSION, DB_STATUS, DB_SIZE_MB, DB_CONNECTIONS, LAST_SEEN)
VALUES ('MD-BLT-101-ISRV-A', 'Мини-сервер (Магазин 101)', 'store_srv', 4, 'ISRVA-S101', '10.20.1.6', 'Ubuntu 24.04', 'online', 15, 30, 38, 'StoreSync Lite', '2.4.0', 'OK', 'sqlite', '3.45', 'OK', 950, 1, SYSTIMESTAMP);
-- Центральный сервер офиса (Oracle) и бэк-офис (PostgreSQL)
INSERT INTO TBC_NODES (CODE, NAME, NODE_TYPE, STORE_ID, HOSTNAME, IP_ADDRESS, OS, STATUS, CPU_PCT, RAM_PCT, DISK_PCT, APP_NAME, APP_VERSION, APP_STATUS, DB_ENGINE, DB_VERSION, DB_STATUS, DB_SIZE_MB, DB_CONNECTIONS, LAST_SEEN)
VALUES ('CENTRAL-01', 'Центральный сервер офиса', 'central', NULL, 'CENTRAL01', '10.0.0.10', 'Oracle Linux 9', 'online', 42, 61, 70, 'Central Exchange Hub', '3.1.2', 'OK', 'oracle', '19.22', 'OK', 512000, 120, SYSTIMESTAMP);
INSERT INTO TBC_NODES (CODE, NAME, NODE_TYPE, STORE_ID, HOSTNAME, IP_ADDRESS, OS, STATUS, CPU_PCT, RAM_PCT, DISK_PCT, APP_NAME, APP_VERSION, APP_STATUS, DB_ENGINE, DB_VERSION, DB_STATUS, DB_SIZE_MB, DB_CONNECTIONS, LAST_SEEN)
VALUES ('BACKOFFICE-01', 'Сервер бэк-офиса', 'backoffice', NULL, 'BACKOFF01', '10.0.0.20', 'Ubuntu 24.04', 'online', 55, 72, 63, 'BackOffice ERP', '12.6.1', 'OK', 'postgres', '16.2', 'OK', 380000, 85, SYSTIMESTAMP);

-- ===== Потоки: POS (SQLite) -> промежуточный сервер магазина =====
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-001-POS01-ISRVA', 'POS-01 → ISRV-A (продажи)', 'device', 1, 1, 'sales', 15, 'OK', 4, 0, SYSTIMESTAMP - INTERVAL '4' MINUTE);
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-001-POS02-ISRVA', 'POS-02 → ISRV-A (продажи)', 'device', 2, 1, 'sales', 15, 'OK', 7, 0, SYSTIMESTAMP - INTERVAL '7' MINUTE);
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT, LAST_ERROR)
VALUES ('F-001-POS03-ISRVB', 'POS-03 → ISRV-B (продажи)', 'device', 3, 2, 'sales', 15, 'LAGGING', 48, 1240, SYSTIMESTAMP - INTERVAL '48' MINUTE, 'SQLite locked: database is locked (retry 3)');
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-001-SCO01-ISRVA', 'SCO-01 → ISRV-A (продажи)', 'device', 4, 1, 'sales', 15, 'OK', 2, 0, SYSTIMESTAMP - INTERVAL '2' MINUTE);
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT, LAST_ERROR)
VALUES ('F-001-SCO02-ISRVA', 'SCO-02 → ISRV-A (продажи)', 'device', 5, 1, 'sales', 15, 'STALLED', 185, 3320, SYSTIMESTAMP - INTERVAL '185' MINUTE, 'SCO-02 offline: no heartbeat');
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-002-POS01-ISRVA', 'POS-01 → ISRV-A 002 (продажи)', 'device', 9, 3, 'sales', 15, 'OK', 5, 0, SYSTIMESTAMP - INTERVAL '5' MINUTE);
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-002-POS02-ISRVA', 'POS-02 → ISRV-A 002 (продажи)', 'device', 10, 3, 'sales', 15, 'OK', 3, 0, SYSTIMESTAMP - INTERVAL '3' MINUTE);
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT, LAST_ERROR)
VALUES ('F-003-POS01-ISRVA', 'POS-01 → ISRV-A 003 (продажи)', 'device', 12, 4, 'sales', 15, 'STALLED', 370, 5100, SYSTIMESTAMP - INTERVAL '370' MINUTE, 'Store network unavailable');
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT, LAST_ERROR)
VALUES ('F-003-POS02-ISRVA', 'POS-02 → ISRV-A 003 (продажи)', 'device', 13, 4, 'sales', 15, 'STALLED', 370, 4640, SYSTIMESTAMP - INTERVAL '370' MINUTE, 'Store network unavailable');
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_DEVICE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-101-POS01-ISRVA', 'POS-01 → мини-сервер 101 (продажи)', 'device', 15, 5, 'sales', 15, 'OK', 6, 0, SYSTIMESTAMP - INTERVAL '6' MINUTE);

-- ===== Потоки: промежуточные серверы -> центральный =====
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_NODE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-ISRVA001-CENTRAL', 'ISRV-A 001 → Центральный (консолидация)', 'node', 1, 6, 'sync', 30, 'OK', 11, 0, SYSTIMESTAMP - INTERVAL '11' MINUTE);
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_NODE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT, LAST_ERROR)
VALUES ('F-ISRVB001-CENTRAL', 'ISRV-B 001 → Центральный (консолидация)', 'node', 2, 6, 'sync', 30, 'LAGGING', 95, 8900, SYSTIMESTAMP - INTERVAL '95' MINUTE, 'postgres: disk 94%, vacuum required, slow copy');
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_NODE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-ISRVA002-CENTRAL', 'ISRV-A 002 → Центральный (консолидация)', 'node', 3, 6, 'sync', 30, 'OK', 18, 0, SYSTIMESTAMP - INTERVAL '18' MINUTE);
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_NODE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT, LAST_ERROR)
VALUES ('F-ISRVA003-CENTRAL', 'ISRV-A 003 → Центральный (консолидация)', 'node', 4, 6, 'sync', 30, 'STALLED', 370, 12400, SYSTIMESTAMP - INTERVAL '370' MINUTE, 'Node offline: store network unavailable');
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_NODE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-ISRVA101-CENTRAL', 'Мини-сервер 101 → Центральный', 'node', 5, 6, 'sync', 60, 'OK', 25, 0, SYSTIMESTAMP - INTERVAL '25' MINUTE);

-- ===== Поток: центральный -> бэк-офис (демо сбоя) =====
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_NODE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT, LAST_ERROR)
VALUES ('F-CENTRAL-BACKOFF', 'Центральный → Бэк-офис (ERP)', 'node', 6, 7, 'docs', 60, 'FAIL', 130, 21500, SYSTIMESTAMP - INTERVAL '130' MINUTE, 'ORA-02291 integrity constraint on staging import: batch B-88412 rejected');
-- Обратный поток: цены/номенклатура вниз
INSERT INTO TBC_FLOWS (CODE, NAME, SRC_KIND, SRC_NODE_ID, DST_NODE_ID, FLOW_TYPE, SCHEDULE_MIN, STATUS, LAG_MIN, PENDING_ROWS, LAST_OK_AT)
VALUES ('F-CENTRAL-ISRVA001-PRICES', 'Центральный → ISRV-A 001 (цены)', 'node', 6, 1, 'prices', 120, 'OK', 40, 0, SYSTIMESTAMP - INTERVAL '40' MINUTE);

-- ===== Журнал батчей =====
INSERT INTO TBC_FLOW_LOG (FLOW_ID, BATCH_CODE, ROWS_SENT, ROWS_ACCEPTED, STATUS, STARTED_AT, FINISHED_AT)
VALUES (1, 'B-10001', 340, 340, 'OK', SYSTIMESTAMP - INTERVAL '4' MINUTE, SYSTIMESTAMP - INTERVAL '4' MINUTE);
INSERT INTO TBC_FLOW_LOG (FLOW_ID, BATCH_CODE, ROWS_SENT, ROWS_ACCEPTED, STATUS, STARTED_AT, FINISHED_AT)
VALUES (2, 'B-10002', 295, 295, 'OK', SYSTIMESTAMP - INTERVAL '7' MINUTE, SYSTIMESTAMP - INTERVAL '7' MINUTE);
INSERT INTO TBC_FLOW_LOG (FLOW_ID, BATCH_CODE, ROWS_SENT, ROWS_ACCEPTED, STATUS, ERROR_MSG, STARTED_AT)
VALUES (3, 'B-10003', 400, 0, 'FAIL', 'SQLite locked: database is locked', SYSTIMESTAMP - INTERVAL '18' MINUTE);
INSERT INTO TBC_FLOW_LOG (FLOW_ID, BATCH_CODE, ROWS_SENT, ROWS_ACCEPTED, STATUS, ERROR_MSG, STARTED_AT)
VALUES (3, 'B-10004', 400, 120, 'PARTIAL', 'SQLite locked mid-batch', SYSTIMESTAMP - INTERVAL '48' MINUTE);
INSERT INTO TBC_FLOW_LOG (FLOW_ID, BATCH_CODE, ROWS_SENT, ROWS_ACCEPTED, STATUS, ERROR_MSG, STARTED_AT)
VALUES (16, 'B-88412', 21500, 0, 'FAIL', 'ORA-02291 integrity constraint on staging import', SYSTIMESTAMP - INTERVAL '130' MINUTE);
INSERT INTO TBC_FLOW_LOG (FLOW_ID, BATCH_CODE, ROWS_SENT, ROWS_ACCEPTED, STATUS, STARTED_AT, FINISHED_AT)
VALUES (16, 'B-88411', 18200, 18200, 'OK', SYSTIMESTAMP - INTERVAL '190' MINUTE, SYSTIMESTAMP - INTERVAL '188' MINUTE);
INSERT INTO TBC_FLOW_LOG (FLOW_ID, BATCH_CODE, ROWS_SENT, ROWS_ACCEPTED, STATUS, ERROR_MSG, STARTED_AT)
VALUES (12, 'B-55021', 8900, 3100, 'PARTIAL', 'slow copy: postgres disk 94%', SYSTIMESTAMP - INTERVAL '95' MINUTE);

-- ===== Телеметрия касс: 7 дней почасовых сэмплов (device 1 - норма, 3 - деградация) =====
-- HW: касса как компьютер
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 1, 'hw', 'cpu', ROUND(18 + 14 * ABS(SIN(LEVEL / 6)) + DBMS_RANDOM.VALUE(0, 8)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 1, 'hw', 'ram', ROUND(40 + 10 * ABS(SIN(LEVEL / 9)) + DBMS_RANDOM.VALUE(0, 6)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 1, 'hw', 'disk', ROUND(58 + LEVEL / 60), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 2, 'hw', 'cpu', ROUND(22 + 16 * ABS(SIN(LEVEL / 5)) + DBMS_RANDOM.VALUE(0, 9)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 2, 'hw', 'ram', ROUND(45 + 9 * ABS(SIN(LEVEL / 8)) + DBMS_RANDOM.VALUE(0, 6)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 3, 'hw', 'cpu', ROUND(45 + 30 * ABS(SIN(LEVEL / 4)) + DBMS_RANDOM.VALUE(0, 15)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 3, 'hw', 'ram', ROUND(65 + 18 * ABS(SIN(LEVEL / 7)) + DBMS_RANDOM.VALUE(0, 10)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 3, 'hw', 'disk', ROUND(84 + LEVEL / 35), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
-- APP: Front Office внутри кассы
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 1, 'app', 'app_latency', ROUND(20 + 15 * ABS(SIN(LEVEL / 6)) + DBMS_RANDOM.VALUE(0, 12)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 1, 'app', 'tx_count', GREATEST(0, ROUND(35 + 30 * SIN((MOD(LEVEL, 24) - 6) / 3.8) + DBMS_RANDOM.VALUE(0, 10))), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 1, 'app', 'app_errors', CASE WHEN DBMS_RANDOM.VALUE(0, 100) > 93 THEN 1 ELSE 0 END, SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 2, 'app', 'app_latency', ROUND(24 + 14 * ABS(SIN(LEVEL / 7)) + DBMS_RANDOM.VALUE(0, 10)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 2, 'app', 'tx_count', GREATEST(0, ROUND(30 + 26 * SIN((MOD(LEVEL, 24) - 6) / 3.8) + DBMS_RANDOM.VALUE(0, 8))), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 3, 'app', 'app_latency', ROUND(90 + 80 * ABS(SIN(LEVEL / 5)) + DBMS_RANDOM.VALUE(0, 60)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 3, 'app', 'tx_count', GREATEST(0, ROUND(22 + 20 * SIN((MOD(LEVEL, 24) - 6) / 3.8) + DBMS_RANDOM.VALUE(0, 6))), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT 3, 'app', 'app_errors', CASE WHEN DBMS_RANDOM.VALUE(0, 100) > 70 THEN ROUND(DBMS_RANDOM.VALUE(1, 4)) ELSE 0 END, SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 168;

COMMIT;
