-- ============================================================
-- TBControl: операционный контур сети франшизы
-- Бренды/форматы магазинов, действия персонала, обращения в
-- поддержку/банки/MEV, климат и UPS-телеметрия, очереди на кассах
-- (очереди пишутся в TBC_METRIC_SAMPLES: scope=app, metric=queue_len)
-- ============================================================

-- Бренд и формат магазина (сеть: Bonus, Super Bonus, Local, Local Expres, Foxi)
ALTER TABLE TBC_STORES ADD (BRAND VARCHAR2(30), STORE_FORMAT VARCHAR2(20));

CREATE SEQUENCE TBC_ACTIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_TICKETS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_ENV_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE TBC_TICKET_NUM_SEQ START WITH 5101 INCREMENT BY 1 NOCACHE;

-- ==================== Действия персонала магазина ====================
-- Включая фиксацию ненужных перезагрузок касс (IS_JUSTIFIED='N')

CREATE TABLE TBC_ACTIONS (
  ID           NUMBER        NOT NULL,
  STORE_ID     NUMBER        NOT NULL,
  DEVICE_ID    NUMBER,
  EVENT_ID     NUMBER,
  ACTION_TYPE  VARCHAR2(30)  NOT NULL,  -- restart_pos/restart_router/restart_server/switch_ups/generator_on/call_support/call_bank/call_mev/other
  PERFORMED_BY VARCHAR2(100),
  NOTE         VARCHAR2(500),
  IS_JUSTIFIED CHAR(1)       DEFAULT 'Y',   -- N = ненужное действие (например, перезагрузка кассы при проблеме банка)
  RESULT       VARCHAR2(20)  DEFAULT 'fixed',   -- fixed / no_effect / escalated
  STARTED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  FINISHED_AT  TIMESTAMP,
  CONSTRAINT PK_TBC_ACTIONS PRIMARY KEY (ID),
  CONSTRAINT FK_TBC_ACT_STORE  FOREIGN KEY (STORE_ID) REFERENCES TBC_STORES(ID),
  CONSTRAINT FK_TBC_ACT_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES TBC_DEVICES(ID) ON DELETE SET NULL,
  CONSTRAINT FK_TBC_ACT_EVENT  FOREIGN KEY (EVENT_ID) REFERENCES TBC_EVENTS(ID),
  CONSTRAINT CHK_TBC_ACT_JUST CHECK (IS_JUSTIFIED IN ('Y','N')),
  CONSTRAINT CHK_TBC_ACT_RES CHECK (RESULT IN ('fixed','no_effect','escalated'))
);
/

CREATE OR REPLACE TRIGGER TBC_ACTIONS_BI
  BEFORE INSERT ON TBC_ACTIONS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_ACTIONS_SEQ.NEXTVAL;
END;
/

-- ==================== Обращения в поддержку / банк / MEV ====================

CREATE TABLE TBC_SUPPORT_TICKETS (
  ID                NUMBER        NOT NULL,
  TICKET_NO         VARCHAR2(20)  NOT NULL,  -- TSK-2026-5001
  STORE_ID          NUMBER        NOT NULL,
  TARGET            VARCHAR2(20)  NOT NULL,  -- network_support / bank / mev / power_company / isp
  PROVIDER_NAME     VARCHAR2(100),           -- Техподдержка сети / Victoriabank / MAIB / MEV (SFS) / Premier Energy / StarNet
  RELATED_EVENT_ID  NUMBER,
  SUBJECT           VARCHAR2(300) NOT NULL,
  DESCRIPTION       VARCHAR2(1000),
  STATUS            VARCHAR2(20)  DEFAULT 'open',   -- open / answered / resolved
  OPENED_BY         VARCHAR2(100),                  -- администратор магазина
  OPENED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP,
  FIRST_RESPONSE_AT TIMESTAMP,
  RESOLVED_AT       TIMESTAMP,
  RESOLUTION        VARCHAR2(500),
  CONSTRAINT PK_TBC_TICKETS PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_TICKETS UNIQUE (TICKET_NO),
  CONSTRAINT FK_TBC_TKT_STORE FOREIGN KEY (STORE_ID) REFERENCES TBC_STORES(ID),
  CONSTRAINT FK_TBC_TKT_EVENT FOREIGN KEY (RELATED_EVENT_ID) REFERENCES TBC_EVENTS(ID),
  CONSTRAINT CHK_TBC_TKT_TGT CHECK (TARGET IN ('network_support','bank','mev','power_company','isp')),
  CONSTRAINT CHK_TBC_TKT_ST CHECK (STATUS IN ('open','answered','resolved'))
);
/

CREATE OR REPLACE TRIGGER TBC_TICKETS_BI
  BEFORE INSERT ON TBC_SUPPORT_TICKETS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_TICKETS_SEQ.NEXTVAL;
END;
/

-- ==================== Климат / электропитание / UPS (append-only) ====================

CREATE TABLE TBC_ENV_SAMPLES (
  ID         NUMBER       NOT NULL,
  STORE_ID   NUMBER,                 -- NULL = центральная серверная
  NODE_ID    NUMBER,                 -- конкретный узел (серверная), NULL = магазин в целом
  METRIC     VARCHAR2(30) NOT NULL,  -- temp_air/temp_server_room/grid_voltage/on_ups/ups_load_pct/ups_battery_pct/ups_runtime_min
  NUM_VALUE  NUMBER       NOT NULL,
  SAMPLED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_ENV PRIMARY KEY (ID),
  CONSTRAINT FK_TBC_ENV_STORE FOREIGN KEY (STORE_ID) REFERENCES TBC_STORES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_TBC_ENV_NODE  FOREIGN KEY (NODE_ID) REFERENCES TBC_NODES(ID) ON DELETE CASCADE
);
/

CREATE OR REPLACE TRIGGER TBC_ENV_BI
  BEFORE INSERT ON TBC_ENV_SAMPLES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_ENV_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_TBC_ENV ON TBC_ENV_SAMPLES (STORE_ID, NODE_ID, METRIC, SAMPLED_AT);

-- ==================== Представления ====================

CREATE OR REPLACE VIEW V_TBC_ACTIONS AS
SELECT
  a.ID, a.STORE_ID, s.CODE AS STORE_CODE, s.BRAND, a.DEVICE_ID, d.CODE AS DEVICE_CODE,
  a.EVENT_ID, e.SEVERITY AS EVENT_SEVERITY, e.PROBLEM AS EVENT_PROBLEM,
  a.ACTION_TYPE, a.PERFORMED_BY, a.NOTE, a.IS_JUSTIFIED, a.RESULT,
  a.STARTED_AT, a.FINISHED_AT
FROM TBC_ACTIONS a
JOIN TBC_STORES s ON s.ID = a.STORE_ID
LEFT JOIN TBC_DEVICES d ON d.ID = a.DEVICE_ID
LEFT JOIN TBC_EVENTS e ON e.ID = a.EVENT_ID;

CREATE OR REPLACE VIEW V_TBC_TICKETS AS
SELECT
  t.ID, t.TICKET_NO, t.STORE_ID, s.CODE AS STORE_CODE, s.BRAND,
  t.TARGET, t.PROVIDER_NAME, t.RELATED_EVENT_ID, e.SEVERITY AS EVENT_SEVERITY,
  t.SUBJECT, t.DESCRIPTION, t.STATUS, t.OPENED_BY, t.OPENED_AT,
  t.FIRST_RESPONSE_AT, t.RESOLVED_AT, t.RESOLUTION,
  ROUND((CAST(t.FIRST_RESPONSE_AT AS DATE) - CAST(t.OPENED_AT AS DATE)) * 1440) AS RESPONSE_MIN,
  ROUND((CAST(t.RESOLVED_AT AS DATE) - CAST(t.OPENED_AT AS DATE)) * 1440) AS RESOLVE_MIN
FROM TBC_SUPPORT_TICKETS t
JOIN TBC_STORES s ON s.ID = t.STORE_ID
LEFT JOIN TBC_EVENTS e ON e.ID = t.RELATED_EVENT_ID;

-- Store Health с брендом и форматом
CREATE OR REPLACE VIEW V_TBC_STORE_HEALTH AS
SELECT
  s.ID, s.CODE, s.NAME, s.BRAND, s.STORE_FORMAT, s.COUNTRY, s.CITY, s.STATUS AS STORE_STATUS,
  s.MAINT_DOW, s.MAINT_TIME_FROM, s.MAINT_TIME_TO,
  NVL(d.DEVICE_TOTAL, 0)   AS DEVICE_TOTAL,
  NVL(d.DEVICE_ONLINE, 0)  AS DEVICE_ONLINE,
  NVL(d.DEVICE_OFFLINE, 0) AS DEVICE_OFFLINE,
  NVL(d.POS_TOTAL, 0)      AS POS_TOTAL,
  NVL(d.POS_ONLINE, 0)     AS POS_ONLINE,
  NVL(d.SCO_TOTAL, 0)      AS SCO_TOTAL,
  NVL(d.SCO_ONLINE, 0)     AS SCO_ONLINE,
  NVL(d.AND_TOTAL, 0)      AS AND_TOTAL,
  NVL(d.AND_ONLINE, 0)     AS AND_ONLINE,
  NVL(e.P1_OPEN, 0) AS P1_OPEN,
  NVL(e.P2_OPEN, 0) AS P2_OPEN,
  NVL(e.P3_OPEN, 0) AS P3_OPEN,
  NVL(e.P4_OPEN, 0) AS P4_OPEN,
  CASE
    WHEN NVL(e.P1_OPEN, 0) > 0 THEN 'CRITICAL'
    WHEN NVL(d.POS_TOTAL, 0) > 0 AND NVL(d.POS_ONLINE, 0) = 0 THEN 'CRITICAL'
    WHEN NVL(e.P2_OPEN, 0) > 0 OR NVL(e.P3_OPEN, 0) > 0 THEN 'DEGRADED'
    WHEN NVL(d.DEVICE_OFFLINE, 0) > 0 THEN 'DEGRADED'
    ELSE 'OK'
  END AS HEALTH
FROM TBC_STORES s
LEFT JOIN (
  SELECT STORE_ID,
    COUNT(*) AS DEVICE_TOTAL,
    SUM(CASE WHEN STATUS = 'online' THEN 1 ELSE 0 END) AS DEVICE_ONLINE,
    SUM(CASE WHEN STATUS = 'offline' THEN 1 ELSE 0 END) AS DEVICE_OFFLINE,
    SUM(CASE WHEN DEVICE_TYPE = 'POS' THEN 1 ELSE 0 END) AS POS_TOTAL,
    SUM(CASE WHEN DEVICE_TYPE = 'POS' AND STATUS = 'online' THEN 1 ELSE 0 END) AS POS_ONLINE,
    SUM(CASE WHEN DEVICE_TYPE = 'SCO' THEN 1 ELSE 0 END) AS SCO_TOTAL,
    SUM(CASE WHEN DEVICE_TYPE = 'SCO' AND STATUS = 'online' THEN 1 ELSE 0 END) AS SCO_ONLINE,
    SUM(CASE WHEN DEVICE_TYPE = 'AND' THEN 1 ELSE 0 END) AS AND_TOTAL,
    SUM(CASE WHEN DEVICE_TYPE = 'AND' AND STATUS = 'online' THEN 1 ELSE 0 END) AS AND_ONLINE
  FROM TBC_DEVICES GROUP BY STORE_ID
) d ON d.STORE_ID = s.ID
LEFT JOIN (
  SELECT STORE_ID,
    SUM(CASE WHEN SEVERITY = 'P1' THEN 1 ELSE 0 END) AS P1_OPEN,
    SUM(CASE WHEN SEVERITY = 'P2' THEN 1 ELSE 0 END) AS P2_OPEN,
    SUM(CASE WHEN SEVERITY = 'P3' THEN 1 ELSE 0 END) AS P3_OPEN,
    SUM(CASE WHEN SEVERITY = 'P4' THEN 1 ELSE 0 END) AS P4_OPEN
  FROM TBC_EVENTS WHERE STATUS IN ('open','ack') GROUP BY STORE_ID
) e ON e.STORE_ID = s.ID;
