-- ============================================================
-- TBControl: демо-данные сети франшизы
-- Бренды: Bonus, Super Bonus, Local, Local Expres, Foxi
-- Кейсы: отключение света/интернета, сбой банка, MEV, жара/мороз,
-- перегрузка сети, UPS, ненужные перезагрузки, тикеты в поддержку
-- ============================================================

-- ===== Новые сервисы =====
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('power', 'Электроснабжение', 12);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('climate', 'Климат / серверная', 13);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('bank_pos', 'Банковские POS-терминалы', 14);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('mev', 'MEV (SFS) фискализация', 15);
INSERT INTO TBC_REF_SERVICES (CODE, NAME, SORT_ORDER) VALUES ('isp', 'Интернет-провайдер', 16);

-- ===== Бренды существующих магазинов =====
UPDATE TBC_STORES SET BRAND = 'Bonus',        STORE_FORMAT = 'large' WHERE CODE = 'MD-CHS-001';
UPDATE TBC_STORES SET BRAND = 'Local',        STORE_FORMAT = 'small' WHERE CODE = 'MD-CHS-002';
UPDATE TBC_STORES SET BRAND = 'Local Expres', STORE_FORMAT = 'mini'  WHERE CODE = 'MD-CHS-003';
UPDATE TBC_STORES SET BRAND = 'Foxi',         STORE_FORMAT = 'small' WHERE CODE = 'MD-BLT-101';

-- ===== Новые магазины сети (адреса — Кишинёв, Орхей, Бельцы) =====
INSERT INTO TBC_STORES (CODE, NAME, BRAND, STORE_FORMAT, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-CHS-010', 'Bonus Дачия', 'Bonus', 'large', 'MD', 'Chisinau', 'бул. Дачия 47/1', 7, '02:00', '04:00');
INSERT INTO TBC_STORES (CODE, NAME, BRAND, STORE_FORMAT, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-CHS-011', 'Super Bonus Мунчешть', 'Super Bonus', 'hyper', 'MD', 'Chisinau', 'шос. Мунчешть 121', 7, '01:00', '04:00');
INSERT INTO TBC_STORES (CODE, NAME, BRAND, STORE_FORMAT, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-CHS-012', 'Local Крянгэ', 'Local', 'small', 'MD', 'Chisinau', 'ул. Ион Крянгэ 49', 1, '02:00', '03:30');
INSERT INTO TBC_STORES (CODE, NAME, BRAND, STORE_FORMAT, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-CHS-013', 'Local Expres Москова', 'Local Expres', 'mini', 'MD', 'Chisinau', 'бул. Москова 20', 2, '02:00', '03:00');
INSERT INTO TBC_STORES (CODE, NAME, BRAND, STORE_FORMAT, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-CHS-014', 'Foxi Петрикань', 'Foxi', 'mini', 'MD', 'Chisinau', 'ул. Петрикань 21', 3, '02:00', '03:00');
INSERT INTO TBC_STORES (CODE, NAME, BRAND, STORE_FORMAT, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-ORH-201', 'Local Орхей', 'Local', 'small', 'MD', 'Orhei', 'ул. Василе Лупу 36', 1, '02:00', '03:30');
INSERT INTO TBC_STORES (CODE, NAME, BRAND, STORE_FORMAT, COUNTRY, CITY, ADDRESS, MAINT_DOW, MAINT_TIME_FROM, MAINT_TIME_TO)
VALUES ('MD-BLT-102', 'Foxi Бельцы Центр', 'Foxi', 'mini', 'MD', 'Balti', 'ул. Штефан чел Маре 13', 2, '02:00', '03:00');

-- ===== Устройства новых магазинов =====
-- Bonus Дачия (large): 4 POS + 2 SCO + сервер + роутер
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-010-POS-01', ID, 'POS', 'POS01-S010', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.10.11', 'online', 'customer_it', 'high', 24, 46, 52, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-010';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-010-POS-02', ID, 'POS', 'POS02-S010', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.10.12', 'online', 'customer_it', 'high', 31, 50, 49, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-010';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-010-POS-03', ID, 'POS', 'POS03-S010', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.10.13', 'online', 'customer_it', 'high', 27, 44, 55, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-010';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-010-POS-04', ID, 'POS', 'POS04-S010', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.10.14', 'online', 'customer_it', 'high', 22, 41, 47, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-010';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-010-SCO-01', ID, 'SCO', 'SCO01-S010', 'NCR', 'FastLane R6C', 'Windows', '10 IoT LTSC', '10.10.10.21', 'online', 'customer_it', 'high', 19, 39, 42, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-010';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-010-SCO-02', ID, 'SCO', 'SCO02-S010', 'NCR', 'FastLane R6C', 'Windows', '10 IoT LTSC', '10.10.10.22', 'online', 'customer_it', 'high', 21, 40, 45, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-010';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-010-SRV-01', ID, 'SRV', 'SRV01-S010', 'HPE', 'ProLiant ML30', 'Linux', 'Ubuntu 24.04', '10.10.10.5', 'online', 'customer_it', 'high', 33, 57, 68, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-010';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, LAST_SEEN)
SELECT 'MD-CHS-010-NET-01', ID, 'NET', 'RTR01-S010', 'MikroTik', 'RB4011', 'RouterOS', '7.15', '10.10.10.1', 'online', 'customer_it', 'high', SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-010';

-- Super Bonus Мунчешть (hyper): 3 POS + SCO + сервер (перегрев) + роутер
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-011-POS-01', ID, 'POS', 'POS01-S011', 'Toshiba', 'TCx 700', 'Windows', '10 IoT LTSC', '10.10.11.11', 'online', 'customer_it', 'high', 29, 48, 51, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-011';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-011-POS-02', ID, 'POS', 'POS02-S011', 'Toshiba', 'TCx 700', 'Windows', '10 IoT LTSC', '10.10.11.12', 'online', 'customer_it', 'high', 35, 52, 48, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-011';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-011-POS-03', ID, 'POS', 'POS03-S011', 'Toshiba', 'TCx 700', 'Windows', '10 IoT LTSC', '10.10.11.13', 'degraded', 'customer_it', 'high', 88, 79, 66, SYSTIMESTAMP - INTERVAL '3' MINUTE, SYSTIMESTAMP - INTERVAL '20' MINUTE FROM TBC_STORES WHERE CODE = 'MD-CHS-011';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-011-SCO-01', ID, 'SCO', 'SCO01-S011', 'NCR', 'FastLane R6C', 'Windows', '10 IoT LTSC', '10.10.11.21', 'online', 'customer_it', 'high', 20, 38, 41, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-011';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-011-SRV-01', ID, 'SRV', 'SRV01-S011', 'Dell', 'PowerEdge T150', 'Linux', 'Ubuntu 24.04', '10.10.11.5', 'degraded', 'customer_it', 'high', 71, 66, 74, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-011';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, LAST_SEEN)
SELECT 'MD-CHS-011-NET-01', ID, 'NET', 'RTR01-S011', 'MikroTik', 'RB5009', 'RouterOS', '7.15', '10.10.11.1', 'online', 'customer_it', 'high', SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-011';

-- Local Крянгэ (small): 2 POS
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-012-POS-01', ID, 'POS', 'POS01-S012', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.12.11', 'online', 'customer_it', 'high', 21, 42, 46, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-012';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-012-POS-02', ID, 'POS', 'POS02-S012', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.12.12', 'online', 'customer_it', 'medium', 18, 37, 44, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-012';

-- Local Expres Москова (mini): POS на UPS + роутер (отключение света)
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-013-POS-01', ID, 'POS', 'POS01-S013', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.13.11', 'online', 'customer_it', 'high', 26, 45, 50, SYSTIMESTAMP, SYSTIMESTAMP - INTERVAL '25' MINUTE FROM TBC_STORES WHERE CODE = 'MD-CHS-013';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, LAST_SEEN)
SELECT 'MD-CHS-013-NET-01', ID, 'NET', 'RTR01-S013', 'MikroTik', 'hAP ac3', 'RouterOS', '7.15', '10.10.13.1', 'online', 'customer_it', 'high', SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-013';

-- Foxi Петрикань (mini): 1 POS
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-CHS-014-POS-01', ID, 'POS', 'POS01-S014', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.10.14.11', 'online', 'customer_it', 'medium', 23, 40, 43, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-CHS-014';

-- Local Орхей (small): 2 POS, один offline после отключения света
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-ORH-201-POS-01', ID, 'POS', 'POS01-S201', 'Toshiba', 'TCx 300', 'Windows', '10 IoT LTSC', '10.30.1.11', 'online', 'customer_it', 'high', 25, 43, 48, SYSTIMESTAMP, SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-ORH-201';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, LAST_SEEN, LAST_SYNC)
SELECT 'MD-ORH-201-POS-02', ID, 'POS', 'POS02-S201', 'Toshiba', 'TCx 300', 'Windows', '10 IoT LTSC', '10.30.1.12', 'offline', 'customer_it', 'high', SYSTIMESTAMP - INTERVAL '95' MINUTE, SYSTIMESTAMP - INTERVAL '95' MINUTE FROM TBC_STORES WHERE CODE = 'MD-ORH-201';

-- Foxi Бельцы Центр (mini): POS + роутер offline (авария ISP)
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, CPU_PCT, RAM_PCT, DISK_PCT, LAST_SEEN, LAST_SYNC)
SELECT 'MD-BLT-102-POS-01', ID, 'POS', 'POS01-S102', 'Diebold Nixdorf', 'Beetle A1150', 'Windows', '10 IoT LTSC', '10.21.1.11', 'degraded', 'customer_it', 'high', 30, 47, 52, SYSTIMESTAMP - INTERVAL '2' MINUTE, SYSTIMESTAMP - INTERVAL '75' MINUTE FROM TBC_STORES WHERE CODE = 'MD-BLT-102';
INSERT INTO TBC_DEVICES (CODE, STORE_ID, DEVICE_TYPE, HOSTNAME, MANUFACTURER, MODEL, OS, OS_VERSION, IP_ADDRESS, STATUS, SUPPORT_GROUP, CRITICALITY, LAST_SEEN)
SELECT 'MD-BLT-102-NET-01', ID, 'NET', 'RTR01-S102', 'MikroTik', 'hAP ac3', 'RouterOS', '7.15', '10.21.1.1', 'degraded', 'customer_it', 'high', SYSTIMESTAMP FROM TBC_STORES WHERE CODE = 'MD-BLT-102';

-- ===== События сценариев =====
-- 1. Отключение света: Local Expres Москова работает на UPS
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
SELECT 'P2', s.ID, NULL, 'power', 'Отключение электроснабжения — магазин работает на UPS (осталось ~35% батареи)', 'open', 'agent', 'pw13a1'
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-013';
-- 2. Отключение света в Орхее: POS-02 выключился (UPS только на POS-01)
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
SELECT 'P3', s.ID, d.ID, 'power', 'POS-02 отключился при пропадании питания (не подключён к UPS)', 'ack', 'zabbix', 'pw201b'
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-ORH-201-POS-02' WHERE s.CODE = 'MD-ORH-201';
-- 3. Авария ISP: Foxi Бельцы без интернета → банковские POS и MEV подавлены как downstream
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
SELECT 'P2', s.ID, d.ID, 'isp', 'Интернет-канал StarNet недоступен (авария на линии), магазин в offline-режиме продаж', 'open', 'agent', 'isp102'
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-BLT-102-NET-01' WHERE s.CODE = 'MD-BLT-102';
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID, PARENT_EVENT_ID)
SELECT 'P3', s.ID, d.ID, 'bank_pos', 'Банковский POS-терминал не авторизует карты (нет связи с процессингом)', 'suppressed', 'correlation', 'isp102',
       (SELECT MAX(e.ID) FROM TBC_EVENTS e WHERE e.CORRELATION_ID = 'isp102' AND e.SERVICE_CODE = 'isp')
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-BLT-102-POS-01' WHERE s.CODE = 'MD-BLT-102';
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID, PARENT_EVENT_ID)
SELECT 'P3', s.ID, d.ID, 'mev', 'MEV: чеки не отправляются в SFS (offline-очередь растёт)', 'suppressed', 'correlation', 'isp102',
       (SELECT MAX(e.ID) FROM TBC_EVENTS e WHERE e.CORRELATION_ID = 'isp102' AND e.SERVICE_CODE = 'isp')
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-BLT-102-POS-01' WHERE s.CODE = 'MD-BLT-102';
-- 4. Сбой хоста банка: Bonus Дачия, интернет в норме
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
SELECT 'P2', s.ID, NULL, 'bank_pos', 'Банковские терминалы Victoriabank: отказ авторизации на всех кассах (интернет в норме — проблема на стороне банка)', 'ack', 'agent', 'bnk010'
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-010';
-- 5. Деградация MEV (SFS) по всей сети
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
SELECT 'P2', s.ID, NULL, 'mev', 'MEV (SFS): массовые таймауты сервиса фискализации, чеки уходят в offline-очередь', 'ack', 'zabbix', 'mev001'
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-011';
-- 6. Перегрев серверной Super Bonus (жара 38°C + перегрузка электросети)
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
SELECT 'P2', s.ID, d.ID, 'climate', 'Перегрев серверной: 34°C (на улице +38°C), кондиционер не справляется, сервер троттлит', 'open', 'agent', 'ht011a'
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-CHS-011-SRV-01' WHERE s.CODE = 'MD-CHS-011';
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
SELECT 'P4', s.ID, NULL, 'power', 'Просадки напряжения до 198V — перегрузка городской электросети (жара, кондиционеры)', 'open', 'agent', 'ht011a'
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-011';
-- 7. Перегрев центральной серверной (связан с UPS-нагрузкой)
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE, CORRELATION_ID)
VALUES ('P3', NULL, NULL, 'climate', 'Центральная серверная: температура выросла до 30°C, UPS-нагрузка 78% — проверить кондиционирование', 'open', 'zabbix', 'htcntr');
-- 8. Морозный кейс: Орхей, -18°C
INSERT INTO TBC_EVENTS (SEVERITY, STORE_ID, DEVICE_ID, SERVICE_CODE, PROBLEM, STATUS, SOURCE)
SELECT 'P4', s.ID, NULL, 'climate', 'Мороз -18°C: медленный старт оборудования утром, риск конденсата — прогрев перед включением', 'resolved', 'manual'
FROM TBC_STORES s WHERE s.CODE = 'MD-ORH-201';

-- ===== Действия персонала =====
-- Ненужные перезагрузки: кассир Bonus Дачия трижды перезагрузил POS-02 при сбое банка
INSERT INTO TBC_ACTIONS (STORE_ID, DEVICE_ID, EVENT_ID, ACTION_TYPE, PERFORMED_BY, NOTE, IS_JUSTIFIED, RESULT, STARTED_AT, FINISHED_AT)
SELECT s.ID, d.ID, (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'bnk010'), 'restart_pos', 'кассир М.Руссу', 'Перезагрузка кассы «не проходит карта» — причина была на стороне банка', 'N', 'no_effect', SYSTIMESTAMP - INTERVAL '52' MINUTE, SYSTIMESTAMP - INTERVAL '49' MINUTE
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-CHS-010-POS-02' WHERE s.CODE = 'MD-CHS-010';
INSERT INTO TBC_ACTIONS (STORE_ID, DEVICE_ID, EVENT_ID, ACTION_TYPE, PERFORMED_BY, NOTE, IS_JUSTIFIED, RESULT, STARTED_AT, FINISHED_AT)
SELECT s.ID, d.ID, (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'bnk010'), 'restart_pos', 'кассир М.Руссу', 'Повторная перезагрузка той же кассы', 'N', 'no_effect', SYSTIMESTAMP - INTERVAL '44' MINUTE, SYSTIMESTAMP - INTERVAL '41' MINUTE
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-CHS-010-POS-02' WHERE s.CODE = 'MD-CHS-010';
INSERT INTO TBC_ACTIONS (STORE_ID, DEVICE_ID, EVENT_ID, ACTION_TYPE, PERFORMED_BY, NOTE, IS_JUSTIFIED, RESULT, STARTED_AT, FINISHED_AT)
SELECT s.ID, d.ID, (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'bnk010'), 'restart_pos', 'кассир М.Руссу', 'Третья перезагрузка — после этого администратор остановил и позвонил в банк', 'N', 'no_effect', SYSTIMESTAMP - INTERVAL '36' MINUTE, SYSTIMESTAMP - INTERVAL '33' MINUTE
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-CHS-010-POS-02' WHERE s.CODE = 'MD-CHS-010';
INSERT INTO TBC_ACTIONS (STORE_ID, DEVICE_ID, EVENT_ID, ACTION_TYPE, PERFORMED_BY, NOTE, IS_JUSTIFIED, RESULT, STARTED_AT)
SELECT s.ID, NULL, (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'bnk010'), 'call_bank', 'админ И.Чобану', 'Звонок в Victoriabank: подтверждён сбой процессинга на стороне банка', 'Y', 'escalated', SYSTIMESTAMP - INTERVAL '30' MINUTE
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-010';
-- Отключение света: переход на UPS + звонок в электросети
INSERT INTO TBC_ACTIONS (STORE_ID, DEVICE_ID, EVENT_ID, ACTION_TYPE, PERFORMED_BY, NOTE, IS_JUSTIFIED, RESULT, STARTED_AT, FINISHED_AT)
SELECT s.ID, d.ID, (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'pw13a1'), 'switch_ups', 'админ В.Мунтяну', 'Касса и роутер переведены на UPS, продажи продолжаются', 'Y', 'fixed', SYSTIMESTAMP - INTERVAL '80' MINUTE, SYSTIMESTAMP - INTERVAL '78' MINUTE
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-CHS-013-POS-01' WHERE s.CODE = 'MD-CHS-013';
INSERT INTO TBC_ACTIONS (STORE_ID, EVENT_ID, ACTION_TYPE, PERFORMED_BY, NOTE, IS_JUSTIFIED, RESULT, STARTED_AT)
SELECT s.ID, (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'pw13a1'), 'other', 'админ В.Мунтяну', 'Заявка в Premier Energy, отключено холодильное оборудование 2-й линии для экономии UPS', 'Y', 'escalated', SYSTIMESTAMP - INTERVAL '74' MINUTE
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-013';
-- ISP-авария: перезагрузка роутера (оправданная попытка), затем звонок провайдеру
INSERT INTO TBC_ACTIONS (STORE_ID, DEVICE_ID, EVENT_ID, ACTION_TYPE, PERFORMED_BY, NOTE, IS_JUSTIFIED, RESULT, STARTED_AT, FINISHED_AT)
SELECT s.ID, d.ID, (SELECT MAX(e.ID) FROM TBC_EVENTS e WHERE e.CORRELATION_ID = 'isp102' AND e.SERVICE_CODE = 'isp'), 'restart_router', 'админ А.Гуцу', 'Перезагрузка роутера — линк не поднялся, авария на линии провайдера', 'Y', 'no_effect', SYSTIMESTAMP - INTERVAL '70' MINUTE, SYSTIMESTAMP - INTERVAL '66' MINUTE
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-BLT-102-NET-01' WHERE s.CODE = 'MD-BLT-102';
-- Перегрев: включение резервного кондиционера
INSERT INTO TBC_ACTIONS (STORE_ID, DEVICE_ID, EVENT_ID, ACTION_TYPE, PERFORMED_BY, NOTE, IS_JUSTIFIED, RESULT, STARTED_AT)
SELECT s.ID, d.ID, (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'ht011a' AND SERVICE_CODE = 'climate'), 'other', 'админ Д.Сырбу', 'Включён резервный кондиционер серверной, температура стабилизировалась на 31°C', 'Y', 'fixed', SYSTIMESTAMP - INTERVAL '40' MINUTE
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-CHS-011-SRV-01' WHERE s.CODE = 'MD-CHS-011';
-- Орхей: запуск POS-02 после подачи питания
INSERT INTO TBC_ACTIONS (STORE_ID, DEVICE_ID, EVENT_ID, ACTION_TYPE, PERFORMED_BY, NOTE, IS_JUSTIFIED, RESULT, STARTED_AT)
SELECT s.ID, d.ID, (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'pw201b'), 'restart_pos', 'админ Е.Кожокару', 'Штатный запуск POS-02 после восстановления питания', 'Y', 'fixed', SYSTIMESTAMP - INTERVAL '10' MINUTE
FROM TBC_STORES s JOIN TBC_DEVICES d ON d.CODE = 'MD-ORH-201-POS-02' WHERE s.CODE = 'MD-ORH-201';

-- ===== Обращения администраторов (техподдержка/банк/MEV/электросети/ISP) =====
-- Быстрый ответ техподдержки сети (12 мин)
INSERT INTO TBC_SUPPORT_TICKETS (TICKET_NO, STORE_ID, TARGET, PROVIDER_NAME, RELATED_EVENT_ID, SUBJECT, DESCRIPTION, STATUS, OPENED_BY, OPENED_AT, FIRST_RESPONSE_AT, RESOLUTION)
SELECT 'TSK-2026-5001', s.ID, 'network_support', 'Техподдержка сети', (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'ht011a' AND SERVICE_CODE = 'climate'),
 'Перегрев серверной Super Bonus Мунчешть', 'Температура 34°C и растёт, сервер деградирует', 'answered', 'админ Д.Сырбу', SYSTIMESTAMP - INTERVAL '55' MINUTE, SYSTIMESTAMP - INTERVAL '43' MINUTE, 'Рекомендован резервный кондиционер + заявка на сервис централи'
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-011';
-- Задержанный ответ техподдержки (247 мин) — магазин 003 offline
INSERT INTO TBC_SUPPORT_TICKETS (TICKET_NO, STORE_ID, TARGET, PROVIDER_NAME, RELATED_EVENT_ID, SUBJECT, DESCRIPTION, STATUS, OPENED_BY, OPENED_AT, FIRST_RESPONSE_AT)
SELECT 'TSK-2026-5002', s.ID, 'network_support', 'Техподдержка сети', (SELECT MIN(ID) FROM TBC_EVENTS WHERE STORE_ID = s.ID AND SEVERITY = 'P1'),
 'Магазин полностью offline — сеть недоступна', 'Роутер не отвечает, обе кассы недоступны, продажи в ручном режиме', 'answered', 'админ Н.Иванов', SYSTIMESTAMP - INTERVAL '6' HOUR, SYSTIMESTAMP - INTERVAL '113' MINUTE
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-003';
-- Банк подтвердил сбой (Victoriabank, решено за 95 мин)
INSERT INTO TBC_SUPPORT_TICKETS (TICKET_NO, STORE_ID, TARGET, PROVIDER_NAME, RELATED_EVENT_ID, SUBJECT, DESCRIPTION, STATUS, OPENED_BY, OPENED_AT, FIRST_RESPONSE_AT, RESOLVED_AT, RESOLUTION)
SELECT 'TSK-2026-5003', s.ID, 'bank', 'Victoriabank', (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'bnk010'),
 'Отказ авторизации карт на всех терминалах', 'Интернет в норме, терминалы получают отказ хоста', 'resolved', 'админ И.Чобану', SYSTIMESTAMP - INTERVAL '30' MINUTE, SYSTIMESTAMP - INTERVAL '22' MINUTE, SYSTIMESTAMP + INTERVAL '65' MINUTE, 'Банк подтвердил сбой процессинга и восстановил сервис'
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-010';
-- Банк: «проблема на вашей стороне» (MAIB, Foxi Бельцы без интернета)
INSERT INTO TBC_SUPPORT_TICKETS (TICKET_NO, STORE_ID, TARGET, PROVIDER_NAME, RELATED_EVENT_ID, SUBJECT, DESCRIPTION, STATUS, OPENED_BY, OPENED_AT, FIRST_RESPONSE_AT, RESOLUTION)
SELECT 'TSK-2026-5004', s.ID, 'bank', 'MAIB', (SELECT MAX(e.ID) FROM TBC_EVENTS e WHERE e.CORRELATION_ID = 'isp102' AND e.SERVICE_CODE = 'bank_pos'),
 'Терминал не авторизует карты', 'Карты отклоняются на единственной кассе', 'answered', 'админ А.Гуцу', SYSTIMESTAMP - INTERVAL '60' MINUTE, SYSTIMESTAMP - INTERVAL '35' MINUTE, 'Банк: процессинг в норме, у магазина нет интернета — обратитесь к провайдеру'
FROM TBC_STORES s WHERE s.CODE = 'MD-BLT-102';
-- MEV (SFS): подтверждение деградации
INSERT INTO TBC_SUPPORT_TICKETS (TICKET_NO, STORE_ID, TARGET, PROVIDER_NAME, RELATED_EVENT_ID, SUBJECT, DESCRIPTION, STATUS, OPENED_BY, OPENED_AT, FIRST_RESPONSE_AT, RESOLVED_AT, RESOLUTION)
SELECT 'TSK-2026-5005', s.ID, 'mev', 'MEV (SFS)', (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'mev001'),
 'Таймауты сервиса фискализации по всей сети', 'Чеки копятся в offline-очереди на всех магазинах', 'resolved', 'ИТ-координатор сети', SYSTIMESTAMP - INTERVAL '3' HOUR, SYSTIMESTAMP - INTERVAL '140' MINUTE, SYSTIMESTAMP - INTERVAL '60' MINUTE, 'SFS подтвердил деградацию MEV, сервис восстановлен, offline-очереди отправлены'
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-011';
-- ISP: авария на линии, ETA 4 часа
INSERT INTO TBC_SUPPORT_TICKETS (TICKET_NO, STORE_ID, TARGET, PROVIDER_NAME, RELATED_EVENT_ID, SUBJECT, DESCRIPTION, STATUS, OPENED_BY, OPENED_AT, FIRST_RESPONSE_AT, RESOLUTION)
SELECT 'TSK-2026-5006', s.ID, 'isp', 'StarNet', (SELECT MAX(e.ID) FROM TBC_EVENTS e WHERE e.CORRELATION_ID = 'isp102' AND e.SERVICE_CODE = 'isp'),
 'Пропал интернет-канал', 'Роутер перезагружали — линк не поднимается', 'answered', 'админ А.Гуцу', SYSTIMESTAMP - INTERVAL '65' MINUTE, SYSTIMESTAMP - INTERVAL '34' MINUTE, 'Авария на магистрали, бригада выехала, ETA 4 часа'
FROM TBC_STORES s WHERE s.CODE = 'MD-BLT-102';
-- Электросети: плановое-аварийное отключение
INSERT INTO TBC_SUPPORT_TICKETS (TICKET_NO, STORE_ID, TARGET, PROVIDER_NAME, RELATED_EVENT_ID, SUBJECT, DESCRIPTION, STATUS, OPENED_BY, OPENED_AT, FIRST_RESPONSE_AT, RESOLUTION)
SELECT 'TSK-2026-5007', s.ID, 'power_company', 'Premier Energy', (SELECT MAX(ID) FROM TBC_EVENTS WHERE CORRELATION_ID = 'pw13a1'),
 'Отключение электроснабжения', 'Магазин на UPS, батареи хватит на ~50 минут', 'answered', 'админ В.Мунтяну', SYSTIMESTAMP - INTERVAL '75' MINUTE, SYSTIMESTAMP - INTERVAL '57' MINUTE, 'Аварийное отключение фидера, восстановление в течение 1.5 часов'
FROM TBC_STORES s WHERE s.CODE = 'MD-CHS-013';

-- ===== Очереди на кассах (metric queue_len, scope app, чел. в очереди) =====
-- Все POS/SCO сети, 7 дней почасово. Пики обед/вечер. В магазине MD-CHS-001
-- SCO-02 не работает — очереди заметно длиннее (польза мониторинга очередей).
INSERT INTO TBC_METRIC_SAMPLES (DEVICE_ID, SCOPE, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT d.ID, 'app', 'queue_len',
       GREATEST(0, ROUND(
         (CASE WHEN s.CODE = 'MD-CHS-001' THEN 4.5 ELSE 1.5 END)
         + 3 * ABS(SIN((MOD(h.LVL, 24) - 5) / 2.5))
         + DBMS_RANDOM.VALUE(0, 2))),
       SYSTIMESTAMP - NUMTODSINTERVAL(h.LVL, 'HOUR')
FROM (SELECT LEVEL AS LVL FROM DUAL CONNECT BY LEVEL <= 168) h
CROSS JOIN TBC_DEVICES d
JOIN TBC_STORES s ON s.ID = d.STORE_ID
WHERE d.DEVICE_TYPE IN ('POS', 'SCO') AND d.STATUS <> 'offline';

-- ===== Климат / питание / UPS =====
-- Жара: Super Bonus, воздух на улице до +38
INSERT INTO TBC_ENV_SAMPLES (STORE_ID, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT (SELECT ID FROM TBC_STORES WHERE CODE = 'MD-CHS-011'), 'temp_air', ROUND(28 + 10 * ABS(SIN((MOD(LEVEL, 24) - 3) / 7)) + DBMS_RANDOM.VALUE(0, 1), 1), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 48;
-- Серверная Super Bonus: рост 26 → 34
INSERT INTO TBC_ENV_SAMPLES (STORE_ID, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT (SELECT ID FROM TBC_STORES WHERE CODE = 'MD-CHS-011'), 'temp_server_room', ROUND(34 - LEVEL / 6.0, 1), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 48;
-- Напряжение сети Super Bonus: просадки до 198V
INSERT INTO TBC_ENV_SAMPLES (STORE_ID, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT (SELECT ID FROM TBC_STORES WHERE CODE = 'MD-CHS-011'), 'grid_voltage', ROUND(218 - 12 * ABS(SIN(LEVEL / 3)) - DBMS_RANDOM.VALUE(0, 8)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 48;
-- Центральная серверная (узел CENTRAL-01): температура растёт 24 → 30, UPS-нагрузка ~78%
INSERT INTO TBC_ENV_SAMPLES (NODE_ID, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT (SELECT ID FROM TBC_NODES WHERE CODE = 'CENTRAL-01'), 'temp_server_room', ROUND(30 - LEVEL / 8.0, 1), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 48;
INSERT INTO TBC_ENV_SAMPLES (NODE_ID, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT (SELECT ID FROM TBC_NODES WHERE CODE = 'CENTRAL-01'), 'ups_load_pct', ROUND(60 + 18 * ABS(SIN(LEVEL / 9)) + DBMS_RANDOM.VALUE(0, 4)), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 48;
-- Отключение света Local Expres: разряд батареи UPS 100% → 35% за последние ~80 минут
INSERT INTO TBC_ENV_SAMPLES (STORE_ID, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT (SELECT ID FROM TBC_STORES WHERE CODE = 'MD-CHS-013'), 'ups_battery_pct', 100 - (9 - LEVEL) * 8, SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL * 10, 'MINUTE') FROM DUAL CONNECT BY LEVEL <= 9;
INSERT INTO TBC_ENV_SAMPLES (STORE_ID, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT (SELECT ID FROM TBC_STORES WHERE CODE = 'MD-CHS-013'), 'on_ups', 1, SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL * 10, 'MINUTE') FROM DUAL CONNECT BY LEVEL <= 9;
INSERT INTO TBC_ENV_SAMPLES (STORE_ID, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT (SELECT ID FROM TBC_STORES WHERE CODE = 'MD-CHS-013'), 'ups_runtime_min', GREATEST(5, 90 - (9 - LEVEL) * 9), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL * 10, 'MINUTE') FROM DUAL CONNECT BY LEVEL <= 9;
-- Мороз в Орхее: до -18 ночью
INSERT INTO TBC_ENV_SAMPLES (STORE_ID, METRIC, NUM_VALUE, SAMPLED_AT)
SELECT (SELECT ID FROM TBC_STORES WHERE CODE = 'MD-ORH-201'), 'temp_air', ROUND(-10 - 8 * ABS(SIN((MOD(LEVEL, 24) - 16) / 7)), 1), SYSTIMESTAMP - NUMTODSINTERVAL(LEVEL, 'HOUR') FROM DUAL CONNECT BY LEVEL <= 48;

COMMIT;
