-- ============================================================
-- TBControl: SSL-сертификаты публичных доменов — TBC_CERTS.
-- Проверка: models/tbc_certs.py (TLS-рукопожатие, cryptography).
-- Статусы: OK (>14 дн) | EXPIRING (<=14) | EXPIRED | ERROR.
-- Восстановлено 02.09.2026 по фактической схеме ADB.
-- ============================================================

CREATE SEQUENCE TBC_CERTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE TABLE TBC_CERTS (
  ID           NUMBER         NOT NULL,
  DOMAIN_NAME  VARCHAR2(200)  NOT NULL,
  PORT         NUMBER         DEFAULT 443,
  NOTE         VARCHAR2(300),
  ENABLED      CHAR(1)        DEFAULT 'Y',
  ISSUER       VARCHAR2(200),
  SUBJECT_CN   VARCHAR2(200),
  SERIAL_NO    VARCHAR2(80),
  VALID_FROM   TIMESTAMP,
  VALID_TO     TIMESTAMP,
  DAYS_LEFT    NUMBER,
  AUTO_RENEW   VARCHAR2(20),              -- letsencrypt | manual
  STATUS       VARCHAR2(15),
  LAST_ERROR   VARCHAR2(500),
  CHECKED_AT   TIMESTAMP,
  CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_TBC_CERTS PRIMARY KEY (ID),
  CONSTRAINT UQ_TBC_CERTS UNIQUE (DOMAIN_NAME, PORT),
  CONSTRAINT CHK_TBC_CERTS_EN CHECK (ENABLED IN ('Y','N')),
  CONSTRAINT CHK_TBC_CERTS_ST CHECK (STATUS IN ('OK','EXPIRING','EXPIRED','ERROR'))
);
/

CREATE OR REPLACE TRIGGER TBC_CERTS_BI
  BEFORE INSERT ON TBC_CERTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := TBC_CERTS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE VIEW V_TBC_CERTS_STATS AS
SELECT
  (SELECT COUNT(*) FROM TBC_CERTS WHERE ENABLED = 'Y') AS TOTAL,
  (SELECT COUNT(*) FROM TBC_CERTS WHERE STATUS = 'OK') AS OK_CNT,
  (SELECT COUNT(*) FROM TBC_CERTS WHERE STATUS = 'EXPIRING') AS EXPIRING_CNT,
  (SELECT COUNT(*) FROM TBC_CERTS WHERE STATUS = 'EXPIRED') AS EXPIRED_CNT,
  (SELECT COUNT(*) FROM TBC_CERTS WHERE STATUS = 'ERROR') AS ERROR_CNT,
  (SELECT MIN(DAYS_LEFT) FROM TBC_CERTS WHERE ENABLED = 'Y' AND DAYS_LEFT IS NOT NULL) AS MIN_DAYS_LEFT,
  (SELECT MAX(CHECKED_AT) FROM TBC_CERTS) AS CHECKED_AT
FROM DUAL;
/

INSERT INTO TBC_CERTS (DOMAIN_NAME, PORT, NOTE) VALUES
  ('nufarul.eminescu.md', 443, 'Production Artgranit/TBControl. certbot.timer + deploy-hook nginx reload');
INSERT INTO TBC_CERTS (DOMAIN_NAME, PORT, NOTE) VALUES ('officeplus.md', 443, 'Витрина OfficePlus');
INSERT INTO TBC_CERTS (DOMAIN_NAME, PORT, NOTE) VALUES ('unisim-dashboard.una.md', 443, 'UaMenu Dashboard (эталон касс)');
COMMIT;
