-- ============================================================
-- Планограммы (Planograms): таблицы, последовательности, триггеры
-- Модуль управления выкладкой товара, зонами магазина, проходимостью,
-- акциями, задачами мерчандайзинга и версионированием планограмм.
--
-- Префикс объектов: PLG_
-- Мультиязычность: RU / RO / EN
--   * справочники и master-data — колонки NAME_RU / NAME_RO / NAME_EN
--   * строки интерфейса — словарь PLG_I18N (sql/83_plg_i18n.sql)
-- Спецификация: docs/Planograms/PLANOGRAMS_MODULE.md
-- ============================================================

-- ==================== Последовательности ====================

CREATE SEQUENCE PLG_STORES_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_ZONES_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_FIXTURES_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_CATEGORIES_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_PRODUCTS_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_PLANOGRAMS_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_PLG_ITEMS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_HISTORY_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_PROMOS_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_TASKS_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_DOCUMENTS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_NOTIFY_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_ZONE_TRAFFIC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_STORE_METRIC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_CAT_METRIC_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_EVENT_LOG_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_PLG_NUM_SEQ      START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_TASK_NUM_SEQ     START WITH 5001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_DOC_NUM_SEQ      START WITH 3001 INCREMENT BY 1 NOCACHE;

-- ==================== Справочники (мультиязычные) ====================

-- Поддерживаемые языки модуля
CREATE TABLE PLG_REF_LANGS (
  CODE       VARCHAR2(5)   NOT NULL,     -- ru / ro / en
  NAME_RU    VARCHAR2(60)  NOT NULL,
  NAME_RO    VARCHAR2(60)  NOT NULL,
  NAME_EN    VARCHAR2(60)  NOT NULL,
  IS_DEFAULT NUMBER(1)     DEFAULT 0,
  SORT_ORDER NUMBER        DEFAULT 0,
  CONSTRAINT PK_PLG_REF_LANGS PRIMARY KEY (CODE),
  CONSTRAINT CHK_PLG_LANG_DEF CHECK (IS_DEFAULT IN (0,1))
);

-- Типы зон торгового зала (отдел, касса, склад, служебное помещение, остров акций)
CREATE TABLE PLG_REF_ZONE_TYPES (
  CODE       VARCHAR2(20)  NOT NULL,     -- dept / checkout / entrance / storage / service / promo_island / wc
  NAME_RU    VARCHAR2(100) NOT NULL,
  NAME_RO    VARCHAR2(100) NOT NULL,
  NAME_EN    VARCHAR2(100) NOT NULL,
  COLOR      VARCHAR2(20),
  ICON       VARCHAR2(10),
  IS_SELLING NUMBER(1)     DEFAULT 1,    -- участвует ли в торговой площади
  SORT_ORDER NUMBER        DEFAULT 0,
  CONSTRAINT PK_PLG_REF_ZONE_TYPES PRIMARY KEY (CODE),
  CONSTRAINT CHK_PLG_ZT_SELLING CHECK (IS_SELLING IN (0,1))
);

-- Типы торгового оборудования (стеллаж, холодильник, паллета, островная витрина)
CREATE TABLE PLG_REF_FIXTURE_TYPES (
  CODE         VARCHAR2(20)  NOT NULL,   -- shelf / cooler / freezer / pallet / island / rack / endcap
  NAME_RU      VARCHAR2(100) NOT NULL,
  NAME_RO      VARCHAR2(100) NOT NULL,
  NAME_EN      VARCHAR2(100) NOT NULL,
  DEFAULT_W_MM NUMBER        DEFAULT 1000,
  DEFAULT_H_MM NUMBER        DEFAULT 1800,
  DEFAULT_D_MM NUMBER        DEFAULT 500,
  SHELF_COUNT  NUMBER        DEFAULT 4,
  ICON         VARCHAR2(10),
  SORT_ORDER   NUMBER        DEFAULT 0,
  CONSTRAINT PK_PLG_REF_FIXTURE_TYPES PRIMARY KEY (CODE)
);

-- Статусы планограммы (жизненный цикл документа)
CREATE TABLE PLG_REF_PLG_STATUSES (
  CODE       VARCHAR2(20)  NOT NULL,     -- draft / review / approved / active / archived / rejected
  NAME_RU    VARCHAR2(100) NOT NULL,
  NAME_RO    VARCHAR2(100) NOT NULL,
  NAME_EN    VARCHAR2(100) NOT NULL,
  COLOR      VARCHAR2(20),
  IS_FINAL   NUMBER(1)     DEFAULT 0,
  SORT_ORDER NUMBER        DEFAULT 0,
  CONSTRAINT PK_PLG_REF_PLG_STATUSES PRIMARY KEY (CODE),
  CONSTRAINT CHK_PLG_ST_FINAL CHECK (IS_FINAL IN (0,1))
);

-- Типы задач мерчандайзинга
CREATE TABLE PLG_REF_TASK_TYPES (
  CODE       VARCHAR2(20)  NOT NULL,     -- relayout / restock / promo_setup / audit / price_tag / fix
  NAME_RU    VARCHAR2(100) NOT NULL,
  NAME_RO    VARCHAR2(100) NOT NULL,
  NAME_EN    VARCHAR2(100) NOT NULL,
  ICON       VARCHAR2(10),
  SORT_ORDER NUMBER        DEFAULT 0,
  CONSTRAINT PK_PLG_REF_TASK_TYPES PRIMARY KEY (CODE)
);

-- Типы акций
CREATE TABLE PLG_REF_PROMO_TYPES (
  CODE       VARCHAR2(20)  NOT NULL,     -- discount / bundle / gift / price_lock / loyalty
  NAME_RU    VARCHAR2(100) NOT NULL,
  NAME_RO    VARCHAR2(100) NOT NULL,
  NAME_EN    VARCHAR2(100) NOT NULL,
  COLOR      VARCHAR2(20),
  SORT_ORDER NUMBER        DEFAULT 0,
  CONSTRAINT PK_PLG_REF_PROMO_TYPES PRIMARY KEY (CODE)
);

-- Типы документов модуля
CREATE TABLE PLG_REF_DOC_TYPES (
  CODE       VARCHAR2(20)  NOT NULL,     -- planogram_pdf / instruction / photo_report / act / schema
  NAME_RU    VARCHAR2(100) NOT NULL,
  NAME_RO    VARCHAR2(100) NOT NULL,
  NAME_EN    VARCHAR2(100) NOT NULL,
  ICON       VARCHAR2(10),
  SORT_ORDER NUMBER        DEFAULT 0,
  CONSTRAINT PK_PLG_REF_DOC_TYPES PRIMARY KEY (CODE)
);

-- ==================== Master data ====================

-- Магазины модуля планограмм (габариты торгового зала и координатная сетка карты)
CREATE TABLE PLG_STORES (
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(30)  NOT NULL,   -- MD-CHS-024
  NAME_RU      VARCHAR2(200) NOT NULL,
  NAME_RO      VARCHAR2(200),
  NAME_EN      VARCHAR2(200),
  CITY         VARCHAR2(100),
  ADDRESS_RU   VARCHAR2(400),
  ADDRESS_RO   VARCHAR2(400),
  ADDRESS_EN   VARCHAR2(400),
  AREA_SQM     NUMBER(10,2),             -- площадь торгового зала
  MAP_WIDTH    NUMBER        DEFAULT 780, -- ширина координатной сетки SVG-плана
  MAP_HEIGHT   NUMBER        DEFAULT 460, -- высота координатной сетки SVG-плана
  CHECKOUT_QTY NUMBER        DEFAULT 6,
  MANAGER_NAME VARCHAR2(150),
  STATUS       VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_STORES PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_STORES_CODE UNIQUE (CODE),
  CONSTRAINT CHK_PLG_STORE_STATUS CHECK (STATUS IN ('active','inactive','remodeling'))
);
/

CREATE OR REPLACE TRIGGER PLG_STORES_BI
  BEFORE INSERT ON PLG_STORES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_STORES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER PLG_STORES_BU
  BEFORE UPDATE ON PLG_STORES FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Категории товара (иерархический справочник)
CREATE TABLE PLG_CATEGORIES (
  ID         NUMBER        NOT NULL,
  CODE       VARCHAR2(30)  NOT NULL,     -- produce, drinks, snacks…
  PARENT_ID  NUMBER,
  NAME_RU    VARCHAR2(200) NOT NULL,
  NAME_RO    VARCHAR2(200),
  NAME_EN    VARCHAR2(200),
  COLOR      VARCHAR2(20),
  ICON       VARCHAR2(10),
  SORT_ORDER NUMBER        DEFAULT 0,
  STATUS     VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_CATEGORIES PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_CAT_CODE UNIQUE (CODE),
  CONSTRAINT FK_PLG_CAT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PLG_CATEGORIES(ID)
);
/

CREATE OR REPLACE TRIGGER PLG_CATEGORIES_BI
  BEFORE INSERT ON PLG_CATEGORIES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_CATEGORIES_SEQ.NEXTVAL;
END;
/

-- Зоны торгового зала: отделы, кассовая зона, склад, острова акций.
-- X/Y/W/H — координаты в системе MAP_WIDTH x MAP_HEIGHT магазина.
CREATE TABLE PLG_ZONES (
  ID          NUMBER        NOT NULL,
  STORE_ID    NUMBER        NOT NULL,
  CODE        VARCHAR2(30)  NOT NULL,    -- produce, drinks, checkout…
  ZONE_TYPE   VARCHAR2(20)  NOT NULL,
  CATEGORY_ID NUMBER,
  NAME_RU     VARCHAR2(200) NOT NULL,
  NAME_RO     VARCHAR2(200),
  NAME_EN     VARCHAR2(200),
  POS_X       NUMBER        DEFAULT 0,
  POS_Y       NUMBER        DEFAULT 0,
  WIDTH       NUMBER        DEFAULT 72,
  HEIGHT      NUMBER        DEFAULT 55,
  COLOR       VARCHAR2(20),
  AREA_SQM    NUMBER(10,2),
  SORT_ORDER  NUMBER        DEFAULT 0,
  STATUS      VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_ZONES PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_ZONES_CODE UNIQUE (STORE_ID, CODE),
  CONSTRAINT FK_PLG_ZONE_STORE FOREIGN KEY (STORE_ID) REFERENCES PLG_STORES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_ZONE_TYPE  FOREIGN KEY (ZONE_TYPE) REFERENCES PLG_REF_ZONE_TYPES(CODE),
  CONSTRAINT FK_PLG_ZONE_CAT   FOREIGN KEY (CATEGORY_ID) REFERENCES PLG_CATEGORIES(ID),
  CONSTRAINT CHK_PLG_ZONE_STATUS CHECK (STATUS IN ('active','inactive'))
);
/

CREATE OR REPLACE TRIGGER PLG_ZONES_BI
  BEFORE INSERT ON PLG_ZONES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_ZONES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER PLG_ZONES_BU
  BEFORE UPDATE ON PLG_ZONES FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Торговое оборудование (стеллажи, холодильники, паллеты) внутри зоны
CREATE TABLE PLG_FIXTURES (
  ID           NUMBER        NOT NULL,
  STORE_ID     NUMBER        NOT NULL,
  ZONE_ID      NUMBER,
  CODE         VARCHAR2(40)  NOT NULL,   -- ST-24-A01
  FIXTURE_TYPE VARCHAR2(20)  NOT NULL,
  NAME_RU      VARCHAR2(200),
  NAME_RO      VARCHAR2(200),
  NAME_EN      VARCHAR2(200),
  POS_X        NUMBER        DEFAULT 0,
  POS_Y        NUMBER        DEFAULT 0,
  WIDTH        NUMBER        DEFAULT 80,
  HEIGHT       NUMBER        DEFAULT 42,
  ORIENTATION  VARCHAR2(10)  DEFAULT 'H',  -- H / V
  SHELF_COUNT  NUMBER        DEFAULT 4,
  WIDTH_MM     NUMBER        DEFAULT 1000,
  HEIGHT_MM    NUMBER        DEFAULT 1800,
  DEPTH_MM     NUMBER        DEFAULT 500,
  SERIAL_NUMBER VARCHAR2(60),
  STATUS       VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_FIXTURES PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_FIXT_CODE UNIQUE (STORE_ID, CODE),
  CONSTRAINT FK_PLG_FIXT_STORE FOREIGN KEY (STORE_ID) REFERENCES PLG_STORES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_FIXT_ZONE  FOREIGN KEY (ZONE_ID) REFERENCES PLG_ZONES(ID) ON DELETE SET NULL,
  CONSTRAINT FK_PLG_FIXT_TYPE  FOREIGN KEY (FIXTURE_TYPE) REFERENCES PLG_REF_FIXTURE_TYPES(CODE),
  CONSTRAINT CHK_PLG_FIXT_ORIENT CHECK (ORIENTATION IN ('H','V')),
  CONSTRAINT CHK_PLG_FIXT_STATUS CHECK (STATUS IN ('active','repair','decommissioned'))
);
/

CREATE OR REPLACE TRIGGER PLG_FIXTURES_BI
  BEFORE INSERT ON PLG_FIXTURES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_FIXTURES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER PLG_FIXTURES_BU
  BEFORE UPDATE ON PLG_FIXTURES FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Товары (карточка для выкладки: габариты фейсинга, штрихкод, цена)
CREATE TABLE PLG_PRODUCTS (
  ID          NUMBER        NOT NULL,
  CODE        VARCHAR2(40)  NOT NULL,
  CATEGORY_ID NUMBER,
  NAME_RU     VARCHAR2(300) NOT NULL,
  NAME_RO     VARCHAR2(300),
  NAME_EN     VARCHAR2(300),
  BARCODE     VARCHAR2(40),
  BRAND       VARCHAR2(150),
  UOM         VARCHAR2(20)  DEFAULT 'pcs',
  PRICE       NUMBER(14,2),
  CURRENCY    VARCHAR2(5)   DEFAULT 'MDL',
  WIDTH_MM    NUMBER        DEFAULT 80,
  HEIGHT_MM   NUMBER        DEFAULT 200,
  DEPTH_MM    NUMBER        DEFAULT 60,
  MIN_FACINGS NUMBER        DEFAULT 1,
  IMAGE_URL   VARCHAR2(400),
  STATUS      VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_PRODUCTS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_PROD_CODE UNIQUE (CODE),
  CONSTRAINT FK_PLG_PROD_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES PLG_CATEGORIES(ID),
  CONSTRAINT CHK_PLG_PROD_STATUS CHECK (STATUS IN ('active','inactive','discontinued'))
);
/

CREATE OR REPLACE TRIGGER PLG_PRODUCTS_BI
  BEFORE INSERT ON PLG_PRODUCTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_PRODUCTS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER PLG_PRODUCTS_BU
  BEFORE UPDATE ON PLG_PRODUCTS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE INDEX IX_PLG_PROD_CAT ON PLG_PRODUCTS (CATEGORY_ID, STATUS);

-- ==================== Документ «Планограмма» ====================

-- Заголовок планограммы: версия выкладки зоны магазина
CREATE TABLE PLG_PLANOGRAMS (
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(30)  NOT NULL,   -- PLG-2026-1001
  STORE_ID     NUMBER        NOT NULL,
  ZONE_ID      NUMBER,
  NAME_RU      VARCHAR2(300) NOT NULL,
  NAME_RO      VARCHAR2(300),
  NAME_EN      VARCHAR2(300),
  VERSION_NO   NUMBER        DEFAULT 1,
  STATUS       VARCHAR2(20)  DEFAULT 'draft',
  VALID_FROM   DATE,
  VALID_TO     DATE,
  AUTHOR       VARCHAR2(150),
  APPROVED_BY  VARCHAR2(150),
  APPROVED_AT  TIMESTAMP,
  NOTES        VARCHAR2(2000),
  SHELF_SHARE_PCT NUMBER(6,2),           -- доля полочного пространства зоны
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_PLANOGRAMS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_PLG_CODE UNIQUE (CODE),
  CONSTRAINT FK_PLG_PLG_STORE  FOREIGN KEY (STORE_ID) REFERENCES PLG_STORES(ID),
  CONSTRAINT FK_PLG_PLG_ZONE   FOREIGN KEY (ZONE_ID) REFERENCES PLG_ZONES(ID),
  CONSTRAINT FK_PLG_PLG_STATUS FOREIGN KEY (STATUS) REFERENCES PLG_REF_PLG_STATUSES(CODE)
);
/

CREATE OR REPLACE TRIGGER PLG_PLANOGRAMS_BI
  BEFORE INSERT ON PLG_PLANOGRAMS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := PLG_PLANOGRAMS_SEQ.NEXTVAL;
  END IF;
  IF :NEW.CODE IS NULL THEN
    :NEW.CODE := 'PLG-' || TO_CHAR(SYSDATE, 'YYYY') || '-' || TO_CHAR(PLG_PLG_NUM_SEQ.NEXTVAL);
  END IF;
END;
/

CREATE OR REPLACE TRIGGER PLG_PLANOGRAMS_BU
  BEFORE UPDATE ON PLG_PLANOGRAMS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE INDEX IX_PLG_PLG_STORE ON PLG_PLANOGRAMS (STORE_ID, STATUS);

-- Позиции планограммы: конкретный товар на конкретной полке оборудования
CREATE TABLE PLG_PLANOGRAM_ITEMS (
  ID           NUMBER       NOT NULL,
  PLANOGRAM_ID NUMBER       NOT NULL,
  FIXTURE_ID   NUMBER,
  PRODUCT_ID   NUMBER       NOT NULL,
  SHELF_NO     NUMBER       DEFAULT 1,
  POSITION_NO  NUMBER       DEFAULT 1,
  FACINGS      NUMBER       DEFAULT 1,
  DEPTH_QTY    NUMBER       DEFAULT 1,
  X_MM         NUMBER,
  WIDTH_MM     NUMBER,
  IS_PROMO     NUMBER(1)    DEFAULT 0,
  NOTES        VARCHAR2(500),
  CREATED_AT   TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_PLG_ITEMS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_ITEM_POS UNIQUE (PLANOGRAM_ID, FIXTURE_ID, SHELF_NO, POSITION_NO),
  CONSTRAINT FK_PLG_ITEM_PLG  FOREIGN KEY (PLANOGRAM_ID) REFERENCES PLG_PLANOGRAMS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_ITEM_FIXT FOREIGN KEY (FIXTURE_ID) REFERENCES PLG_FIXTURES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_ITEM_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PLG_PRODUCTS(ID),
  CONSTRAINT CHK_PLG_ITEM_PROMO CHECK (IS_PROMO IN (0,1)),
  CONSTRAINT CHK_PLG_ITEM_FACINGS CHECK (FACINGS > 0)
);
/

CREATE OR REPLACE TRIGGER PLG_PLG_ITEMS_BI
  BEFORE INSERT ON PLG_PLANOGRAM_ITEMS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_PLG_ITEMS_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_PLG_ITEM_PROD ON PLG_PLANOGRAM_ITEMS (PRODUCT_ID);

-- История изменений планограмм (append-only, раздел «История изменений»)
CREATE TABLE PLG_PLANOGRAM_HISTORY (
  ID           NUMBER        NOT NULL,
  PLANOGRAM_ID NUMBER        NOT NULL,
  VERSION_NO   NUMBER,
  ACTION       VARCHAR2(30)  NOT NULL,   -- created / updated / status_change / item_added / item_removed / approved
  FIELD_NAME   VARCHAR2(60),
  OLD_VALUE    VARCHAR2(500),
  NEW_VALUE    VARCHAR2(500),
  SUMMARY_RU   VARCHAR2(500),
  SUMMARY_RO   VARCHAR2(500),
  SUMMARY_EN   VARCHAR2(500),
  CHANGED_BY   VARCHAR2(150),
  CHANGED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_PLG_HISTORY PRIMARY KEY (ID),
  CONSTRAINT FK_PLG_HIST_PLG FOREIGN KEY (PLANOGRAM_ID) REFERENCES PLG_PLANOGRAMS(ID) ON DELETE CASCADE
);
/

CREATE OR REPLACE TRIGGER PLG_HISTORY_BI
  BEFORE INSERT ON PLG_PLANOGRAM_HISTORY FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_HISTORY_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_PLG_HIST_PLG ON PLG_PLANOGRAM_HISTORY (PLANOGRAM_ID, CHANGED_AT);

-- ==================== Акции ====================

CREATE TABLE PLG_PROMOS (
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(30)  NOT NULL,
  STORE_ID     NUMBER,
  PROMO_TYPE   VARCHAR2(20)  NOT NULL,
  NAME_RU      VARCHAR2(300) NOT NULL,
  NAME_RO      VARCHAR2(300),
  NAME_EN      VARCHAR2(300),
  LABEL        VARCHAR2(20),             -- '-20%', '2+1'
  DISCOUNT_PCT NUMBER(6,2),
  DATE_FROM    DATE          NOT NULL,
  DATE_TO      DATE          NOT NULL,
  COLOR        VARCHAR2(20),
  STATUS       VARCHAR2(20)  DEFAULT 'planned',
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_PROMOS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_PROMO_CODE UNIQUE (CODE),
  CONSTRAINT FK_PLG_PROMO_STORE FOREIGN KEY (STORE_ID) REFERENCES PLG_STORES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_PROMO_TYPE  FOREIGN KEY (PROMO_TYPE) REFERENCES PLG_REF_PROMO_TYPES(CODE),
  CONSTRAINT CHK_PLG_PROMO_STATUS CHECK (STATUS IN ('planned','active','finished','cancelled')),
  CONSTRAINT CHK_PLG_PROMO_DATES CHECK (DATE_TO >= DATE_FROM)
);
/

CREATE OR REPLACE TRIGGER PLG_PROMOS_BI
  BEFORE INSERT ON PLG_PROMOS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_PROMOS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER PLG_PROMOS_BU
  BEFORE UPDATE ON PLG_PROMOS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Зоны, задействованные в акции
CREATE TABLE PLG_PROMO_ZONES (
  PROMO_ID NUMBER NOT NULL,
  ZONE_ID  NUMBER NOT NULL,
  CONSTRAINT PK_PLG_PROMO_ZONES PRIMARY KEY (PROMO_ID, ZONE_ID),
  CONSTRAINT FK_PLG_PZ_PROMO FOREIGN KEY (PROMO_ID) REFERENCES PLG_PROMOS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_PZ_ZONE  FOREIGN KEY (ZONE_ID) REFERENCES PLG_ZONES(ID) ON DELETE CASCADE
);

-- Товары, участвующие в акции
CREATE TABLE PLG_PROMO_PRODUCTS (
  PROMO_ID    NUMBER NOT NULL,
  PRODUCT_ID  NUMBER NOT NULL,
  PROMO_PRICE NUMBER(14,2),
  CONSTRAINT PK_PLG_PROMO_PRODUCTS PRIMARY KEY (PROMO_ID, PRODUCT_ID),
  CONSTRAINT FK_PLG_PP_PROMO FOREIGN KEY (PROMO_ID) REFERENCES PLG_PROMOS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_PP_PROD  FOREIGN KEY (PRODUCT_ID) REFERENCES PLG_PRODUCTS(ID) ON DELETE CASCADE
);

-- ==================== Метрики (append-only факты) ====================

-- Проходимость зон по дням (тепловая карта плана магазина)
CREATE TABLE PLG_ZONE_TRAFFIC (
  ID           NUMBER      NOT NULL,
  ZONE_ID      NUMBER      NOT NULL,
  METRIC_DATE  DATE        NOT NULL,
  METRIC_HOUR  NUMBER,                   -- NULL = агрегат за день
  TRAFFIC_PCT  NUMBER(6,2) NOT NULL,     -- 0..100, нормированная проходимость
  VISITORS     NUMBER      DEFAULT 0,
  DWELL_SEC    NUMBER      DEFAULT 0,    -- среднее время в зоне
  PICKUPS      NUMBER      DEFAULT 0,    -- взятий товара с полки
  CONSTRAINT PK_PLG_ZONE_TRAFFIC PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_ZT UNIQUE (ZONE_ID, METRIC_DATE, METRIC_HOUR),
  CONSTRAINT FK_PLG_ZT_ZONE FOREIGN KEY (ZONE_ID) REFERENCES PLG_ZONES(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_PLG_ZT_PCT CHECK (TRAFFIC_PCT BETWEEN 0 AND 100)
);
/

CREATE OR REPLACE TRIGGER PLG_ZONE_TRAFFIC_BI
  BEFORE INSERT ON PLG_ZONE_TRAFFIC FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_ZONE_TRAFFIC_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_PLG_ZT_DATE ON PLG_ZONE_TRAFFIC (METRIC_DATE, ZONE_ID);

-- Дневные показатели магазина (карточки «Динамика показателей»)
CREATE TABLE PLG_STORE_METRICS (
  ID             NUMBER       NOT NULL,
  STORE_ID       NUMBER       NOT NULL,
  METRIC_DATE    DATE         NOT NULL,
  TRAFFIC        NUMBER       DEFAULT 0,   -- общий трафик
  BUYERS         NUMBER       DEFAULT 0,   -- покупатели
  CONVERSION_PCT NUMBER(6,2),
  AVG_CHECK      NUMBER(14,2),
  REVENUE        NUMBER(16,2),
  CURRENCY       VARCHAR2(5)  DEFAULT 'MDL',
  CONSTRAINT PK_PLG_STORE_METRICS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_SM UNIQUE (STORE_ID, METRIC_DATE),
  CONSTRAINT FK_PLG_SM_STORE FOREIGN KEY (STORE_ID) REFERENCES PLG_STORES(ID) ON DELETE CASCADE
);
/

CREATE OR REPLACE TRIGGER PLG_STORE_METRICS_BI
  BEFORE INSERT ON PLG_STORE_METRICS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_STORE_METRIC_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_PLG_SM_DATE ON PLG_STORE_METRICS (METRIC_DATE);

-- Показатели по категориям (топ категорий по проходимости)
CREATE TABLE PLG_CATEGORY_METRICS (
  ID          NUMBER       NOT NULL,
  STORE_ID    NUMBER       NOT NULL,
  CATEGORY_ID NUMBER       NOT NULL,
  METRIC_DATE DATE         NOT NULL,
  VISITS      NUMBER       DEFAULT 0,
  SALES_QTY   NUMBER       DEFAULT 0,
  SALES_AMT   NUMBER(16,2) DEFAULT 0,
  CONSTRAINT PK_PLG_CAT_METRICS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_CM UNIQUE (STORE_ID, CATEGORY_ID, METRIC_DATE),
  CONSTRAINT FK_PLG_CM_STORE FOREIGN KEY (STORE_ID) REFERENCES PLG_STORES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_CM_CAT   FOREIGN KEY (CATEGORY_ID) REFERENCES PLG_CATEGORIES(ID) ON DELETE CASCADE
);
/

CREATE OR REPLACE TRIGGER PLG_CAT_METRICS_BI
  BEFORE INSERT ON PLG_CATEGORY_METRICS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_CAT_METRIC_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_PLG_CM_DATE ON PLG_CATEGORY_METRICS (METRIC_DATE, STORE_ID);

-- ==================== Задачи мерчандайзинга ====================

CREATE TABLE PLG_TASKS (
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(30)  NOT NULL,   -- TSK-2026-5001
  STORE_ID     NUMBER        NOT NULL,
  ZONE_ID      NUMBER,
  PLANOGRAM_ID NUMBER,
  TASK_TYPE    VARCHAR2(20)  NOT NULL,
  TITLE_RU     VARCHAR2(300) NOT NULL,
  TITLE_RO     VARCHAR2(300),
  TITLE_EN     VARCHAR2(300),
  DESCRIPTION  VARCHAR2(2000),
  PRIORITY     VARCHAR2(10)  DEFAULT 'medium',
  STATUS       VARCHAR2(20)  DEFAULT 'new',
  ASSIGNEE     VARCHAR2(150),
  DUE_DATE     DATE,
  DONE_AT      TIMESTAMP,
  CREATED_BY   VARCHAR2(150),
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_TASKS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_TASK_CODE UNIQUE (CODE),
  CONSTRAINT FK_PLG_TASK_STORE FOREIGN KEY (STORE_ID) REFERENCES PLG_STORES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_TASK_ZONE  FOREIGN KEY (ZONE_ID) REFERENCES PLG_ZONES(ID) ON DELETE SET NULL,
  CONSTRAINT FK_PLG_TASK_PLG   FOREIGN KEY (PLANOGRAM_ID) REFERENCES PLG_PLANOGRAMS(ID) ON DELETE SET NULL,
  CONSTRAINT FK_PLG_TASK_TYPE  FOREIGN KEY (TASK_TYPE) REFERENCES PLG_REF_TASK_TYPES(CODE),
  CONSTRAINT CHK_PLG_TASK_PRIO   CHECK (PRIORITY IN ('high','medium','low')),
  CONSTRAINT CHK_PLG_TASK_STATUS CHECK (STATUS IN ('new','in_progress','review','done','cancelled'))
);
/

CREATE OR REPLACE TRIGGER PLG_TASKS_BI
  BEFORE INSERT ON PLG_TASKS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := PLG_TASKS_SEQ.NEXTVAL;
  END IF;
  IF :NEW.CODE IS NULL THEN
    :NEW.CODE := 'TSK-' || TO_CHAR(SYSDATE, 'YYYY') || '-' || TO_CHAR(PLG_TASK_NUM_SEQ.NEXTVAL);
  END IF;
END;
/

CREATE OR REPLACE TRIGGER PLG_TASKS_BU
  BEFORE UPDATE ON PLG_TASKS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE INDEX IX_PLG_TASK_STORE ON PLG_TASKS (STORE_ID, STATUS);

-- ==================== Документы ====================

CREATE TABLE PLG_DOCUMENTS (
  ID           NUMBER        NOT NULL,
  CODE         VARCHAR2(30)  NOT NULL,   -- DOC-2026-3001
  STORE_ID     NUMBER,
  PLANOGRAM_ID NUMBER,
  DOC_TYPE     VARCHAR2(20)  NOT NULL,
  TITLE_RU     VARCHAR2(300) NOT NULL,
  TITLE_RO     VARCHAR2(300),
  TITLE_EN     VARCHAR2(300),
  FILE_NAME    VARCHAR2(300),
  MIME_TYPE    VARCHAR2(100),
  FILE_URL     VARCHAR2(500),
  FILE_SIZE_KB NUMBER,
  VERSION_NO   NUMBER        DEFAULT 1,
  CREATED_BY   VARCHAR2(150),
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_DOCUMENTS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_DOC_CODE UNIQUE (CODE),
  CONSTRAINT FK_PLG_DOC_STORE FOREIGN KEY (STORE_ID) REFERENCES PLG_STORES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_DOC_PLG   FOREIGN KEY (PLANOGRAM_ID) REFERENCES PLG_PLANOGRAMS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_DOC_TYPE  FOREIGN KEY (DOC_TYPE) REFERENCES PLG_REF_DOC_TYPES(CODE)
);
/

CREATE OR REPLACE TRIGGER PLG_DOCUMENTS_BI
  BEFORE INSERT ON PLG_DOCUMENTS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := PLG_DOCUMENTS_SEQ.NEXTVAL;
  END IF;
  IF :NEW.CODE IS NULL THEN
    :NEW.CODE := 'DOC-' || TO_CHAR(SYSDATE, 'YYYY') || '-' || TO_CHAR(PLG_DOC_NUM_SEQ.NEXTVAL);
  END IF;
END;
/

-- ==================== Уведомления ====================

CREATE TABLE PLG_NOTIFICATIONS (
  ID          NUMBER        NOT NULL,
  STORE_ID    NUMBER,
  LEVEL_CODE  VARCHAR2(10)  DEFAULT 'info',   -- info / warn / alert
  ENTITY_TYPE VARCHAR2(30),
  ENTITY_ID   NUMBER,
  TEXT_RU     VARCHAR2(500) NOT NULL,
  TEXT_RO     VARCHAR2(500),
  TEXT_EN     VARCHAR2(500),
  IS_READ     NUMBER(1)     DEFAULT 0,
  CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_NOTIFICATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_PLG_NOTIFY_STORE FOREIGN KEY (STORE_ID) REFERENCES PLG_STORES(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_PLG_NOTIFY_LEVEL CHECK (LEVEL_CODE IN ('info','warn','alert')),
  CONSTRAINT CHK_PLG_NOTIFY_READ  CHECK (IS_READ IN (0,1))
);
/

CREATE OR REPLACE TRIGGER PLG_NOTIFICATIONS_BI
  BEFORE INSERT ON PLG_NOTIFICATIONS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_NOTIFY_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_PLG_NOTIFY_READ ON PLG_NOTIFICATIONS (IS_READ, CREATED_AT);

-- ==================== Настройки модуля ====================

CREATE TABLE PLG_SETTINGS (
  PARAM_CODE  VARCHAR2(50)   NOT NULL,
  PARAM_VALUE VARCHAR2(1000),
  DESCR_RU    VARCHAR2(300),
  DESCR_RO    VARCHAR2(300),
  DESCR_EN    VARCHAR2(300),
  UPDATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_SETTINGS PRIMARY KEY (PARAM_CODE)
);

-- ==================== Аудит модуля (append-only) ====================

CREATE TABLE PLG_EVENT_LOG (
  ID          NUMBER        NOT NULL,
  ACTION      VARCHAR2(50)  NOT NULL,
  ENTITY_TYPE VARCHAR2(30)  NOT NULL,
  ENTITY_ID   NUMBER,
  DETAILS     VARCHAR2(2000),
  USERNAME    VARCHAR2(150),
  CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_EVENT_LOG PRIMARY KEY (ID)
);
/

CREATE OR REPLACE TRIGGER PLG_EVENT_LOG_BI
  BEFORE INSERT ON PLG_EVENT_LOG FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_EVENT_LOG_SEQ.NEXTVAL;
END;
/
