-- ============================================================
-- Планограммы: представления (V_PLG_*)
--
-- Все представления отдают названия сразу в трёх языках
-- (NAME_RU / NAME_RO / NAME_EN). Выбор языка делает контроллер
-- controllers/planogram_controller.py по параметру lang.
-- ============================================================

-- Зоны торгового зала с типом, категорией и актуальной проходимостью
CREATE OR REPLACE VIEW V_PLG_ZONES AS
SELECT
  z.ID, z.STORE_ID, s.CODE AS STORE_CODE,
  z.CODE, z.ZONE_TYPE,
  zt.NAME_RU AS ZONE_TYPE_RU, zt.NAME_RO AS ZONE_TYPE_RO, zt.NAME_EN AS ZONE_TYPE_EN,
  zt.IS_SELLING,
  z.CATEGORY_ID,
  c.NAME_RU AS CATEGORY_RU, c.NAME_RO AS CATEGORY_RO, c.NAME_EN AS CATEGORY_EN,
  z.NAME_RU, z.NAME_RO, z.NAME_EN,
  z.POS_X, z.POS_Y, z.WIDTH, z.HEIGHT,
  NVL(z.COLOR, zt.COLOR) AS COLOR,
  z.AREA_SQM, z.SORT_ORDER, z.STATUS,
  NVL(t.TRAFFIC_PCT, 0)  AS TRAFFIC_PCT,
  NVL(t.VISITORS, 0)     AS VISITORS,
  NVL(t.DWELL_SEC, 0)    AS DWELL_SEC,
  NVL(t.PICKUPS, 0)      AS PICKUPS,
  t.METRIC_DATE          AS TRAFFIC_DATE,
  CASE
    WHEN NVL(t.TRAFFIC_PCT, 0) >= 80 THEN 'peak'
    WHEN NVL(t.TRAFFIC_PCT, 0) >= 60 THEN 'high'
    WHEN NVL(t.TRAFFIC_PCT, 0) >= 40 THEN 'medium'
    ELSE 'low'
  END AS TRAFFIC_LEVEL,
  (SELECT COUNT(*) FROM PLG_FIXTURES f WHERE f.ZONE_ID = z.ID) AS FIXTURE_COUNT
FROM PLG_ZONES z
JOIN PLG_STORES s ON s.ID = z.STORE_ID
JOIN PLG_REF_ZONE_TYPES zt ON zt.CODE = z.ZONE_TYPE
LEFT JOIN PLG_CATEGORIES c ON c.ID = z.CATEGORY_ID
LEFT JOIN (
  SELECT zt2.ZONE_ID, zt2.TRAFFIC_PCT, zt2.VISITORS, zt2.DWELL_SEC, zt2.PICKUPS, zt2.METRIC_DATE
  FROM PLG_ZONE_TRAFFIC zt2
  WHERE zt2.METRIC_HOUR IS NULL
    AND zt2.METRIC_DATE = (
      SELECT MAX(zt3.METRIC_DATE) FROM PLG_ZONE_TRAFFIC zt3
      WHERE zt3.ZONE_ID = zt2.ZONE_ID AND zt3.METRIC_HOUR IS NULL
    )
) t ON t.ZONE_ID = z.ID;

-- Торговое оборудование с контекстом зоны и заполненностью полок
CREATE OR REPLACE VIEW V_PLG_FIXTURES AS
SELECT
  f.ID, f.STORE_ID, s.CODE AS STORE_CODE, f.ZONE_ID,
  z.NAME_RU AS ZONE_RU, z.NAME_RO AS ZONE_RO, z.NAME_EN AS ZONE_EN,
  f.CODE, f.FIXTURE_TYPE,
  ft.NAME_RU AS FIXTURE_TYPE_RU, ft.NAME_RO AS FIXTURE_TYPE_RO, ft.NAME_EN AS FIXTURE_TYPE_EN,
  ft.ICON,
  f.NAME_RU, f.NAME_RO, f.NAME_EN,
  f.POS_X, f.POS_Y, f.WIDTH, f.HEIGHT, f.ORIENTATION,
  f.SHELF_COUNT, f.WIDTH_MM, f.HEIGHT_MM, f.DEPTH_MM,
  f.SERIAL_NUMBER, f.STATUS, f.CREATED_AT, f.UPDATED_AT,
  (SELECT COUNT(*) FROM PLG_PLANOGRAM_ITEMS i WHERE i.FIXTURE_ID = f.ID) AS ITEM_COUNT,
  (SELECT NVL(SUM(i.FACINGS), 0) FROM PLG_PLANOGRAM_ITEMS i WHERE i.FIXTURE_ID = f.ID) AS FACING_COUNT
FROM PLG_FIXTURES f
JOIN PLG_STORES s ON s.ID = f.STORE_ID
JOIN PLG_REF_FIXTURE_TYPES ft ON ft.CODE = f.FIXTURE_TYPE
LEFT JOIN PLG_ZONES z ON z.ID = f.ZONE_ID;

-- Товары с категорией и участием в активных акциях
CREATE OR REPLACE VIEW V_PLG_PRODUCTS AS
SELECT
  p.ID, p.CODE, p.CATEGORY_ID,
  c.CODE AS CATEGORY_CODE,
  c.NAME_RU AS CATEGORY_RU, c.NAME_RO AS CATEGORY_RO, c.NAME_EN AS CATEGORY_EN,
  c.COLOR AS CATEGORY_COLOR,
  p.NAME_RU, p.NAME_RO, p.NAME_EN,
  p.BARCODE, p.BRAND, p.UOM, p.PRICE, p.CURRENCY,
  p.WIDTH_MM, p.HEIGHT_MM, p.DEPTH_MM, p.MIN_FACINGS, p.IMAGE_URL,
  p.STATUS, p.CREATED_AT, p.UPDATED_AT,
  (SELECT COUNT(*) FROM PLG_PLANOGRAM_ITEMS i WHERE i.PRODUCT_ID = p.ID) AS PLACEMENT_COUNT,
  (SELECT COUNT(*) FROM PLG_PROMO_PRODUCTS pp
     JOIN PLG_PROMOS pr ON pr.ID = pp.PROMO_ID
    WHERE pp.PRODUCT_ID = p.ID AND pr.STATUS = 'active') AS ACTIVE_PROMO_COUNT
FROM PLG_PRODUCTS p
LEFT JOIN PLG_CATEGORIES c ON c.ID = p.CATEGORY_ID;

-- Список планограмм (раздел «Список планограмм»)
CREATE OR REPLACE VIEW V_PLG_PLANOGRAMS AS
SELECT
  pl.ID, pl.CODE, pl.STORE_ID,
  s.CODE AS STORE_CODE,
  s.NAME_RU AS STORE_RU, s.NAME_RO AS STORE_RO, s.NAME_EN AS STORE_EN,
  pl.ZONE_ID,
  z.NAME_RU AS ZONE_RU, z.NAME_RO AS ZONE_RO, z.NAME_EN AS ZONE_EN,
  pl.NAME_RU, pl.NAME_RO, pl.NAME_EN,
  pl.VERSION_NO, pl.STATUS,
  st.NAME_RU AS STATUS_RU, st.NAME_RO AS STATUS_RO, st.NAME_EN AS STATUS_EN,
  st.COLOR AS STATUS_COLOR, st.IS_FINAL,
  pl.VALID_FROM, pl.VALID_TO, pl.AUTHOR, pl.APPROVED_BY, pl.APPROVED_AT,
  pl.NOTES, pl.SHELF_SHARE_PCT, pl.CREATED_AT, pl.UPDATED_AT,
  (SELECT COUNT(*) FROM PLG_PLANOGRAM_ITEMS i WHERE i.PLANOGRAM_ID = pl.ID) AS ITEM_COUNT,
  (SELECT NVL(SUM(i.FACINGS), 0) FROM PLG_PLANOGRAM_ITEMS i WHERE i.PLANOGRAM_ID = pl.ID) AS FACING_COUNT,
  (SELECT COUNT(DISTINCT i.PRODUCT_ID) FROM PLG_PLANOGRAM_ITEMS i WHERE i.PLANOGRAM_ID = pl.ID) AS SKU_COUNT,
  (SELECT MAX(h.CHANGED_AT) FROM PLG_PLANOGRAM_HISTORY h WHERE h.PLANOGRAM_ID = pl.ID) AS LAST_CHANGE_AT
FROM PLG_PLANOGRAMS pl
JOIN PLG_STORES s ON s.ID = pl.STORE_ID
JOIN PLG_REF_PLG_STATUSES st ON st.CODE = pl.STATUS
LEFT JOIN PLG_ZONES z ON z.ID = pl.ZONE_ID;

-- Позиции планограммы с товаром и оборудованием
CREATE OR REPLACE VIEW V_PLG_PLANOGRAM_ITEMS AS
SELECT
  i.ID, i.PLANOGRAM_ID, pl.CODE AS PLANOGRAM_CODE,
  i.FIXTURE_ID, f.CODE AS FIXTURE_CODE, f.FIXTURE_TYPE,
  i.PRODUCT_ID, p.CODE AS PRODUCT_CODE,
  p.NAME_RU AS PRODUCT_RU, p.NAME_RO AS PRODUCT_RO, p.NAME_EN AS PRODUCT_EN,
  p.BARCODE, p.BRAND, p.PRICE, p.CURRENCY, p.IMAGE_URL,
  p.CATEGORY_ID,
  c.NAME_RU AS CATEGORY_RU, c.NAME_RO AS CATEGORY_RO, c.NAME_EN AS CATEGORY_EN,
  c.COLOR AS CATEGORY_COLOR,
  i.SHELF_NO, i.POSITION_NO, i.FACINGS, i.DEPTH_QTY,
  i.X_MM, NVL(i.WIDTH_MM, p.WIDTH_MM * i.FACINGS) AS WIDTH_MM,
  i.IS_PROMO, i.NOTES, i.CREATED_AT
FROM PLG_PLANOGRAM_ITEMS i
JOIN PLG_PLANOGRAMS pl ON pl.ID = i.PLANOGRAM_ID
JOIN PLG_PRODUCTS p ON p.ID = i.PRODUCT_ID
LEFT JOIN PLG_FIXTURES f ON f.ID = i.FIXTURE_ID
LEFT JOIN PLG_CATEGORIES c ON c.ID = p.CATEGORY_ID;

-- История изменений планограмм
CREATE OR REPLACE VIEW V_PLG_HISTORY AS
SELECT
  h.ID, h.PLANOGRAM_ID, pl.CODE AS PLANOGRAM_CODE,
  pl.STORE_ID, s.CODE AS STORE_CODE,
  pl.NAME_RU AS PLANOGRAM_RU, pl.NAME_RO AS PLANOGRAM_RO, pl.NAME_EN AS PLANOGRAM_EN,
  h.VERSION_NO, h.ACTION, h.FIELD_NAME, h.OLD_VALUE, h.NEW_VALUE,
  h.SUMMARY_RU, h.SUMMARY_RO, h.SUMMARY_EN,
  h.CHANGED_BY, h.CHANGED_AT
FROM PLG_PLANOGRAM_HISTORY h
JOIN PLG_PLANOGRAMS pl ON pl.ID = h.PLANOGRAM_ID
JOIN PLG_STORES s ON s.ID = pl.STORE_ID;

-- Акции с вычисленным фактическим состоянием по датам
CREATE OR REPLACE VIEW V_PLG_PROMOS AS
SELECT
  pr.ID, pr.CODE, pr.STORE_ID, pr.PROMO_TYPE,
  pt.NAME_RU AS PROMO_TYPE_RU, pt.NAME_RO AS PROMO_TYPE_RO, pt.NAME_EN AS PROMO_TYPE_EN,
  pr.NAME_RU, pr.NAME_RO, pr.NAME_EN,
  pr.LABEL, pr.DISCOUNT_PCT, pr.DATE_FROM, pr.DATE_TO,
  NVL(pr.COLOR, pt.COLOR) AS COLOR,
  pr.STATUS,
  CASE
    WHEN pr.STATUS = 'cancelled' THEN 'cancelled'
    WHEN TRUNC(SYSDATE) BETWEEN pr.DATE_FROM AND pr.DATE_TO THEN 'active'
    WHEN TRUNC(SYSDATE) < pr.DATE_FROM THEN 'planned'
    ELSE 'finished'
  END AS EFFECTIVE_STATUS,
  pr.DATE_TO - TRUNC(SYSDATE) AS DAYS_LEFT,
  pr.CREATED_AT, pr.UPDATED_AT,
  (SELECT COUNT(*) FROM PLG_PROMO_PRODUCTS pp WHERE pp.PROMO_ID = pr.ID) AS PRODUCT_COUNT,
  (SELECT COUNT(*) FROM PLG_PROMO_ZONES pz WHERE pz.PROMO_ID = pr.ID) AS ZONE_COUNT
FROM PLG_PROMOS pr
JOIN PLG_REF_PROMO_TYPES pt ON pt.CODE = pr.PROMO_TYPE;

-- Топ категорий по проходимости за последнюю доступную дату
CREATE OR REPLACE VIEW V_PLG_TOP_CATEGORIES AS
SELECT
  m.STORE_ID, m.CATEGORY_ID, m.METRIC_DATE,
  c.CODE AS CATEGORY_CODE,
  c.NAME_RU, c.NAME_RO, c.NAME_EN, c.COLOR,
  m.VISITS, m.SALES_QTY, m.SALES_AMT,
  ROUND(RATIO_TO_REPORT(m.VISITS) OVER (PARTITION BY m.STORE_ID, m.METRIC_DATE) * 100) AS SHARE_PCT,
  ROW_NUMBER() OVER (PARTITION BY m.STORE_ID, m.METRIC_DATE ORDER BY m.VISITS DESC) AS RANK_NO,
  m.VISITS - NVL(prev.VISITS, m.VISITS) AS VISITS_DELTA,
  CASE WHEN NVL(prev.VISITS, 0) > 0
       THEN ROUND((m.VISITS - prev.VISITS) / prev.VISITS * 100, 1)
       ELSE 0 END AS DELTA_PCT
FROM PLG_CATEGORY_METRICS m
JOIN PLG_CATEGORIES c ON c.ID = m.CATEGORY_ID
LEFT JOIN PLG_CATEGORY_METRICS prev
       ON prev.STORE_ID = m.STORE_ID
      AND prev.CATEGORY_ID = m.CATEGORY_ID
      AND prev.METRIC_DATE = m.METRIC_DATE - 1;

-- Дневная динамика показателей магазина с приростом к предыдущему дню
CREATE OR REPLACE VIEW V_PLG_STORE_METRICS AS
SELECT
  m.ID, m.STORE_ID, s.CODE AS STORE_CODE, m.METRIC_DATE,
  m.TRAFFIC, m.BUYERS, m.CONVERSION_PCT, m.AVG_CHECK, m.REVENUE, m.CURRENCY,
  prev.TRAFFIC AS PREV_TRAFFIC,
  CASE WHEN NVL(prev.TRAFFIC, 0) > 0
       THEN ROUND((m.TRAFFIC - prev.TRAFFIC) / prev.TRAFFIC * 100, 1) ELSE 0 END AS TRAFFIC_DELTA_PCT,
  CASE WHEN NVL(prev.BUYERS, 0) > 0
       THEN ROUND((m.BUYERS - prev.BUYERS) / prev.BUYERS * 100, 1) ELSE 0 END AS BUYERS_DELTA_PCT,
  CASE WHEN NVL(prev.CONVERSION_PCT, 0) > 0
       THEN ROUND((m.CONVERSION_PCT - prev.CONVERSION_PCT) / prev.CONVERSION_PCT * 100, 1) ELSE 0 END AS CONV_DELTA_PCT,
  CASE WHEN NVL(prev.AVG_CHECK, 0) > 0
       THEN ROUND((m.AVG_CHECK - prev.AVG_CHECK) / prev.AVG_CHECK * 100, 1) ELSE 0 END AS CHECK_DELTA_PCT,
  CASE WHEN NVL(prev.REVENUE, 0) > 0
       THEN ROUND((m.REVENUE - prev.REVENUE) / prev.REVENUE * 100, 1) ELSE 0 END AS REVENUE_DELTA_PCT
FROM PLG_STORE_METRICS m
JOIN PLG_STORES s ON s.ID = m.STORE_ID
LEFT JOIN PLG_STORE_METRICS prev
       ON prev.STORE_ID = m.STORE_ID AND prev.METRIC_DATE = m.METRIC_DATE - 1;

-- Задачи мерчандайзинга с контекстом
CREATE OR REPLACE VIEW V_PLG_TASKS AS
SELECT
  t.ID, t.CODE, t.STORE_ID, s.CODE AS STORE_CODE,
  t.ZONE_ID, z.NAME_RU AS ZONE_RU, z.NAME_RO AS ZONE_RO, z.NAME_EN AS ZONE_EN,
  t.PLANOGRAM_ID, pl.CODE AS PLANOGRAM_CODE,
  t.TASK_TYPE,
  tt.NAME_RU AS TASK_TYPE_RU, tt.NAME_RO AS TASK_TYPE_RO, tt.NAME_EN AS TASK_TYPE_EN,
  tt.ICON,
  t.TITLE_RU, t.TITLE_RO, t.TITLE_EN, t.DESCRIPTION,
  t.PRIORITY, t.STATUS, t.ASSIGNEE, t.DUE_DATE, t.DONE_AT,
  t.CREATED_BY, t.CREATED_AT, t.UPDATED_AT,
  CASE WHEN t.DUE_DATE IS NOT NULL AND t.DUE_DATE < TRUNC(SYSDATE)
            AND t.STATUS NOT IN ('done','cancelled') THEN 1 ELSE 0 END AS IS_OVERDUE
FROM PLG_TASKS t
JOIN PLG_STORES s ON s.ID = t.STORE_ID
JOIN PLG_REF_TASK_TYPES tt ON tt.CODE = t.TASK_TYPE
LEFT JOIN PLG_ZONES z ON z.ID = t.ZONE_ID
LEFT JOIN PLG_PLANOGRAMS pl ON pl.ID = t.PLANOGRAM_ID;

-- Документы модуля
CREATE OR REPLACE VIEW V_PLG_DOCUMENTS AS
SELECT
  d.ID, d.CODE, d.STORE_ID, s.CODE AS STORE_CODE,
  d.PLANOGRAM_ID, pl.CODE AS PLANOGRAM_CODE,
  d.DOC_TYPE,
  dt.NAME_RU AS DOC_TYPE_RU, dt.NAME_RO AS DOC_TYPE_RO, dt.NAME_EN AS DOC_TYPE_EN,
  dt.ICON,
  d.TITLE_RU, d.TITLE_RO, d.TITLE_EN,
  d.FILE_NAME, d.MIME_TYPE, d.FILE_URL, d.FILE_SIZE_KB,
  d.VERSION_NO, d.CREATED_BY, d.CREATED_AT
FROM PLG_DOCUMENTS d
JOIN PLG_REF_DOC_TYPES dt ON dt.CODE = d.DOC_TYPE
LEFT JOIN PLG_STORES s ON s.ID = d.STORE_ID
LEFT JOIN PLG_PLANOGRAMS pl ON pl.ID = d.PLANOGRAM_ID;

-- Сводка дашборда по каждому магазину (одна строка на магазин)
CREATE OR REPLACE VIEW V_PLG_DASHBOARD_STATS AS
SELECT
  s.ID AS STORE_ID, s.CODE AS STORE_CODE,
  s.NAME_RU AS STORE_RU, s.NAME_RO AS STORE_RO, s.NAME_EN AS STORE_EN,
  s.AREA_SQM, s.MAP_WIDTH, s.MAP_HEIGHT, s.CHECKOUT_QTY,
  (SELECT COUNT(*) FROM PLG_ZONES z WHERE z.STORE_ID = s.ID AND z.STATUS = 'active') AS ZONE_COUNT,
  (SELECT COUNT(*) FROM PLG_FIXTURES f WHERE f.STORE_ID = s.ID AND f.STATUS = 'active') AS FIXTURE_COUNT,
  (SELECT COUNT(*) FROM PLG_PLANOGRAMS p WHERE p.STORE_ID = s.ID) AS PLANOGRAM_COUNT,
  (SELECT COUNT(*) FROM PLG_PLANOGRAMS p WHERE p.STORE_ID = s.ID AND p.STATUS = 'active') AS PLANOGRAM_ACTIVE,
  (SELECT COUNT(*) FROM PLG_PLANOGRAMS p WHERE p.STORE_ID = s.ID AND p.STATUS IN ('draft','review')) AS PLANOGRAM_PENDING,
  (SELECT COUNT(DISTINCT i.PRODUCT_ID) FROM PLG_PLANOGRAM_ITEMS i
     JOIN PLG_PLANOGRAMS p ON p.ID = i.PLANOGRAM_ID WHERE p.STORE_ID = s.ID) AS SKU_COUNT,
  (SELECT COUNT(*) FROM PLG_PROMOS pr WHERE pr.STORE_ID = s.ID
     AND pr.STATUS <> 'cancelled' AND TRUNC(SYSDATE) BETWEEN pr.DATE_FROM AND pr.DATE_TO) AS PROMO_ACTIVE,
  (SELECT COUNT(*) FROM PLG_TASKS t WHERE t.STORE_ID = s.ID AND t.STATUS NOT IN ('done','cancelled')) AS TASK_OPEN,
  (SELECT COUNT(*) FROM PLG_TASKS t WHERE t.STORE_ID = s.ID
     AND t.STATUS NOT IN ('done','cancelled') AND t.DUE_DATE < TRUNC(SYSDATE)) AS TASK_OVERDUE,
  (SELECT COUNT(*) FROM PLG_NOTIFICATIONS n WHERE n.STORE_ID = s.ID AND n.IS_READ = 0) AS NOTIFY_UNREAD,
  (SELECT COUNT(*) FROM PLG_DOCUMENTS d WHERE d.STORE_ID = s.ID) AS DOC_COUNT,
  m.METRIC_DATE, m.TRAFFIC, m.BUYERS, m.CONVERSION_PCT, m.AVG_CHECK, m.REVENUE, m.CURRENCY
FROM PLG_STORES s
LEFT JOIN (
  SELECT m2.* FROM PLG_STORE_METRICS m2
  WHERE m2.METRIC_DATE = (
    SELECT MAX(m3.METRIC_DATE) FROM PLG_STORE_METRICS m3 WHERE m3.STORE_ID = m2.STORE_ID
  )
) m ON m.STORE_ID = s.ID;
