-- ============================================================
-- Планограммы: партнёрский и рыночный контур
--
--   1. Поставщики: карточка, контакты, контракты, товарные группы работы
--   2. Конкуренты: сети, мониторинг их цен, их поставщики
--   3. Рынки: страны и схожие торговые сети для бенчмарка
--
-- Всё привязано к набору данных (DATASET_ID) и удаляется вместе с ним.
-- Данные наполняются генератором и правятся вручную в админке.
-- Префикс объектов: PLG_
-- ============================================================

CREATE SEQUENCE PLG_SUPPLIERS_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_SUP_CONTACTS_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_CONTRACTS_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_COMPETITORS_SEQ   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_COMP_PRICES_SEQ   START WITH 1 INCREMENT BY 1 CACHE 1000;
CREATE SEQUENCE PLG_MARKETS_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_MKT_CHAINS_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PLG_CONTRACT_NUM_SEQ  START WITH 2001 INCREMENT BY 1 NOCACHE;

-- ==================== Справочники ====================

CREATE TABLE PLG_REF_SUPPLIER_TYPES (
  CODE       VARCHAR2(20)  NOT NULL,   -- producer / distributor / importer / farm / private_label
  NAME_RU    VARCHAR2(100) NOT NULL,
  NAME_RO    VARCHAR2(100) NOT NULL,
  NAME_EN    VARCHAR2(100) NOT NULL,
  COLOR      VARCHAR2(20),
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_PLG_REF_SUPPLIER_TYPES PRIMARY KEY (CODE)
);

CREATE TABLE PLG_REF_CONTRACT_TYPES (
  CODE       VARCHAR2(20)  NOT NULL,   -- supply / marketing / logistics / private_label / consignment
  NAME_RU    VARCHAR2(100) NOT NULL,
  NAME_RO    VARCHAR2(100) NOT NULL,
  NAME_EN    VARCHAR2(100) NOT NULL,
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_PLG_REF_CONTRACT_TYPES PRIMARY KEY (CODE)
);

CREATE TABLE PLG_REF_CONTACT_ROLES (
  CODE       VARCHAR2(20)  NOT NULL,   -- kam / logistics / finance / quality / director
  NAME_RU    VARCHAR2(100) NOT NULL,
  NAME_RO    VARCHAR2(100) NOT NULL,
  NAME_EN    VARCHAR2(100) NOT NULL,
  ICON       VARCHAR2(10),
  SORT_ORDER NUMBER DEFAULT 0,
  CONSTRAINT PK_PLG_REF_CONTACT_ROLES PRIMARY KEY (CODE)
);

-- ==================== Поставщики ====================

CREATE TABLE PLG_SUPPLIERS (
  ID              NUMBER        NOT NULL,
  DATASET_ID      NUMBER,
  CODE            VARCHAR2(30)  NOT NULL,
  NAME_RU         VARCHAR2(200) NOT NULL,
  NAME_RO         VARCHAR2(200),
  NAME_EN         VARCHAR2(200),
  SUPPLIER_TYPE   VARCHAR2(20)  DEFAULT 'distributor',
  COUNTRY         VARCHAR2(5)   DEFAULT 'MD',
  CITY            VARCHAR2(100),
  ADDRESS         VARCHAR2(400),
  IDNO            VARCHAR2(40),               -- фискальный код
  WEBSITE         VARCHAR2(200),
  PHONE           VARCHAR2(50),
  EMAIL           VARCHAR2(150),
  RATING          NUMBER(3,1),                -- 0..10, оценка надёжности
  OTIF_PCT        NUMBER(5,2),                -- on time in full, %
  ANNUAL_TURNOVER NUMBER(16,2),               -- годовой оборот с сетью
  SKU_COUNT       NUMBER        DEFAULT 0,
  IS_KEY          NUMBER(1)     DEFAULT 0,    -- ключевой поставщик
  DELIVERS_TO     VARCHAR2(20)  DEFAULT 'dc', -- dc / store / both
  STATUS          VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_SUPPLIERS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_SUP_CODE UNIQUE (CODE),
  CONSTRAINT FK_PLG_SUP_DS   FOREIGN KEY (DATASET_ID) REFERENCES PLG_DATASETS(ID),
  CONSTRAINT FK_PLG_SUP_TYPE FOREIGN KEY (SUPPLIER_TYPE) REFERENCES PLG_REF_SUPPLIER_TYPES(CODE),
  CONSTRAINT CHK_PLG_SUP_STATUS   CHECK (STATUS IN ('active','on_hold','terminated','prospect')),
  CONSTRAINT CHK_PLG_SUP_KEY      CHECK (IS_KEY IN (0,1)),
  CONSTRAINT CHK_PLG_SUP_DELIVERS CHECK (DELIVERS_TO IN ('dc','store','both'))
);
/

CREATE OR REPLACE TRIGGER PLG_SUPPLIERS_BI
  BEFORE INSERT ON PLG_SUPPLIERS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_SUPPLIERS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER PLG_SUPPLIERS_BU
  BEFORE UPDATE ON PLG_SUPPLIERS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Рейс теперь может ссылаться на поставщика
ALTER TABLE PLG_SHIPMENTS ADD CONSTRAINT FK_PLG_SHP_SUP
  FOREIGN KEY (SUPPLIER_ID) REFERENCES PLG_SUPPLIERS(ID) ON DELETE CASCADE;

CREATE INDEX IX_PLG_SUP_DS ON PLG_SUPPLIERS (DATASET_ID);

-- Контакты поставщика
CREATE TABLE PLG_SUPPLIER_CONTACTS (
  ID          NUMBER        NOT NULL,
  SUPPLIER_ID NUMBER        NOT NULL,
  FULL_NAME   VARCHAR2(200) NOT NULL,
  ROLE_CODE   VARCHAR2(20),
  POSITION_TX VARCHAR2(150),
  PHONE       VARCHAR2(50),
  MOBILE      VARCHAR2(50),
  EMAIL       VARCHAR2(150),
  MESSENGER   VARCHAR2(100),
  IS_PRIMARY  NUMBER(1)     DEFAULT 0,
  NOTES       VARCHAR2(500),
  CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_SUPPLIER_CONTACTS PRIMARY KEY (ID),
  CONSTRAINT FK_PLG_SC_SUP  FOREIGN KEY (SUPPLIER_ID) REFERENCES PLG_SUPPLIERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_SC_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES PLG_REF_CONTACT_ROLES(CODE),
  CONSTRAINT CHK_PLG_SC_PRIMARY CHECK (IS_PRIMARY IN (0,1))
);
/

CREATE OR REPLACE TRIGGER PLG_SUP_CONTACTS_BI
  BEFORE INSERT ON PLG_SUPPLIER_CONTACTS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_SUP_CONTACTS_SEQ.NEXTVAL;
END;
/

-- Контракты
CREATE TABLE PLG_CONTRACTS (
  ID              NUMBER        NOT NULL,
  SUPPLIER_ID     NUMBER        NOT NULL,
  CODE            VARCHAR2(40)  NOT NULL,   -- CTR-2026-2001
  CONTRACT_TYPE   VARCHAR2(20)  DEFAULT 'supply',
  TITLE_RU        VARCHAR2(300),
  TITLE_RO        VARCHAR2(300),
  TITLE_EN        VARCHAR2(300),
  DATE_FROM       DATE          NOT NULL,
  DATE_TO         DATE,
  CURRENCY        VARCHAR2(5)   DEFAULT 'MDL',
  PAYMENT_DAYS    NUMBER        DEFAULT 30, -- отсрочка платежа
  RETRO_BONUS_PCT NUMBER(5,2)   DEFAULT 0,  -- ретро-бонус
  DISCOUNT_PCT    NUMBER(5,2)   DEFAULT 0,
  MARKETING_FEE   NUMBER(14,2)  DEFAULT 0,
  MIN_ORDER_AMT   NUMBER(14,2),
  INCOTERMS       VARCHAR2(10)  DEFAULT 'DDP',
  LEAD_TIME_DAYS  NUMBER        DEFAULT 2,
  AUTO_RENEW      NUMBER(1)     DEFAULT 0,
  STATUS          VARCHAR2(20)  DEFAULT 'active',
  SIGNED_BY       VARCHAR2(150),
  FILE_URL        VARCHAR2(400),
  NOTES           VARCHAR2(1000),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_CONTRACTS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_CTR_CODE UNIQUE (CODE),
  CONSTRAINT FK_PLG_CTR_SUP  FOREIGN KEY (SUPPLIER_ID) REFERENCES PLG_SUPPLIERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_CTR_TYPE FOREIGN KEY (CONTRACT_TYPE) REFERENCES PLG_REF_CONTRACT_TYPES(CODE),
  CONSTRAINT CHK_PLG_CTR_STATUS CHECK (STATUS IN ('draft','active','expired','terminated')),
  CONSTRAINT CHK_PLG_CTR_RENEW  CHECK (AUTO_RENEW IN (0,1))
);
/

CREATE OR REPLACE TRIGGER PLG_CONTRACTS_BI
  BEFORE INSERT ON PLG_CONTRACTS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := PLG_CONTRACTS_SEQ.NEXTVAL;
  END IF;
  IF :NEW.CODE IS NULL THEN
    :NEW.CODE := 'CTR-' || TO_CHAR(SYSDATE, 'YYYY') || '-' ||
                 TO_CHAR(PLG_CONTRACT_NUM_SEQ.NEXTVAL);
  END IF;
END;
/

CREATE OR REPLACE TRIGGER PLG_CONTRACTS_BU
  BEFORE UPDATE ON PLG_CONTRACTS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Товарные группы, по которым идёт работа с поставщиком
CREATE TABLE PLG_SUPPLIER_CATEGORIES (
  SUPPLIER_ID  NUMBER       NOT NULL,
  CATEGORY_ID  NUMBER       NOT NULL,
  SKU_COUNT    NUMBER       DEFAULT 0,
  TURNOVER     NUMBER(16,2) DEFAULT 0,   -- годовой оборот по группе
  SHARE_PCT    NUMBER(5,2),              -- доля поставщика в закупке группы
  IS_PRIMARY   NUMBER(1)    DEFAULT 0,   -- основная группа для этого поставщика
  MARGIN_PCT   NUMBER(5,2),
  CONSTRAINT PK_PLG_SUPPLIER_CATEGORIES PRIMARY KEY (SUPPLIER_ID, CATEGORY_ID),
  CONSTRAINT FK_PLG_SCAT_SUP FOREIGN KEY (SUPPLIER_ID) REFERENCES PLG_SUPPLIERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_SCAT_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES PLG_CATEGORIES(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_PLG_SCAT_PRIMARY CHECK (IS_PRIMARY IN (0,1))
);

-- Кто из поставщиков даёт конкретный SKU
ALTER TABLE PLG_PRODUCTS ADD (SUPPLIER_ID NUMBER);
ALTER TABLE PLG_PRODUCTS ADD CONSTRAINT FK_PLG_PROD_SUP
  FOREIGN KEY (SUPPLIER_ID) REFERENCES PLG_SUPPLIERS(ID) ON DELETE SET NULL;

-- ==================== Конкуренты ====================

CREATE TABLE PLG_COMPETITORS (
  ID             NUMBER        NOT NULL,
  DATASET_ID     NUMBER,
  CODE           VARCHAR2(30)  NOT NULL,
  NAME_RU        VARCHAR2(200) NOT NULL,
  NAME_RO        VARCHAR2(200),
  NAME_EN        VARCHAR2(200),
  COUNTRY        VARCHAR2(5)   DEFAULT 'MD',
  FORMAT_MIX     VARCHAR2(100),               -- 'hyper,super,convenience'
  STORE_COUNT    NUMBER,
  POSITIONING    VARCHAR2(20)  DEFAULT 'mid', -- discount / mid / premium
  PRICE_INDEX    NUMBER(6,2),                 -- их цена к нашей = 100
  MARKET_SHARE   NUMBER(5,2),
  ANNUAL_REVENUE NUMBER(18,2),
  PRIVATE_LABEL_PCT NUMBER(5,2),
  WEBSITE        VARCHAR2(200),
  COLOR          VARCHAR2(20),
  STATUS         VARCHAR2(20)  DEFAULT 'active',
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_COMPETITORS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_COMP_CODE UNIQUE (CODE),
  CONSTRAINT FK_PLG_COMP_DS FOREIGN KEY (DATASET_ID) REFERENCES PLG_DATASETS(ID),
  CONSTRAINT CHK_PLG_COMP_POS    CHECK (POSITIONING IN ('discount','mid','premium')),
  CONSTRAINT CHK_PLG_COMP_STATUS CHECK (STATUS IN ('active','watch','exited'))
);
/

CREATE OR REPLACE TRIGGER PLG_COMPETITORS_BI
  BEFORE INSERT ON PLG_COMPETITORS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_COMPETITORS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER PLG_COMPETITORS_BU
  BEFORE UPDATE ON PLG_COMPETITORS FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Мониторинг цен конкурента по нашим SKU (append-only факт)
CREATE TABLE PLG_COMPETITOR_PRICES (
  ID            NUMBER        NOT NULL,
  COMPETITOR_ID NUMBER        NOT NULL,
  PRODUCT_ID    NUMBER        NOT NULL,
  CHECK_DATE    DATE          NOT NULL,
  PRICE         NUMBER(14,2)  NOT NULL,
  OUR_PRICE     NUMBER(14,2),               -- наша цена на дату замера
  IS_PROMO      NUMBER(1)     DEFAULT 0,
  IN_STOCK      NUMBER(1)     DEFAULT 1,
  SOURCE        VARCHAR2(20)  DEFAULT 'audit',  -- audit / parsing / receipt / manual
  CITY          VARCHAR2(100),
  CONSTRAINT PK_PLG_COMPETITOR_PRICES PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_CP UNIQUE (COMPETITOR_ID, PRODUCT_ID, CHECK_DATE),
  CONSTRAINT FK_PLG_CP_COMP FOREIGN KEY (COMPETITOR_ID) REFERENCES PLG_COMPETITORS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_CP_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PLG_PRODUCTS(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_PLG_CP_PROMO CHECK (IS_PROMO IN (0,1)),
  CONSTRAINT CHK_PLG_CP_STOCK CHECK (IN_STOCK IN (0,1)),
  CONSTRAINT CHK_PLG_CP_SRC   CHECK (SOURCE IN ('audit','parsing','receipt','manual'))
);
/

CREATE OR REPLACE TRIGGER PLG_COMP_PRICES_BI
  BEFORE INSERT ON PLG_COMPETITOR_PRICES FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_COMP_PRICES_SEQ.NEXTVAL;
END;
/

CREATE INDEX IX_PLG_CP_DATE ON PLG_COMPETITOR_PRICES (CHECK_DATE, COMPETITOR_ID);
CREATE INDEX IX_PLG_CP_PROD ON PLG_COMPETITOR_PRICES (PRODUCT_ID, CHECK_DATE);

-- Поставщики конкурента: пересечение с нашей базой видно через SUPPLIER_ID
CREATE TABLE PLG_COMPETITOR_SUPPLIERS (
  COMPETITOR_ID  NUMBER        NOT NULL,
  SUPPLIER_NAME  VARCHAR2(200) NOT NULL,
  SUPPLIER_ID    NUMBER,                     -- если это наш же поставщик
  CATEGORY_ID    NUMBER,
  IS_EXCLUSIVE   NUMBER(1)     DEFAULT 0,    -- работает только с конкурентом
  EST_SHARE_PCT  NUMBER(5,2),
  SOURCE         VARCHAR2(200),
  CONSTRAINT PK_PLG_COMP_SUPPLIERS PRIMARY KEY (COMPETITOR_ID, SUPPLIER_NAME),
  CONSTRAINT FK_PLG_CS_COMP FOREIGN KEY (COMPETITOR_ID) REFERENCES PLG_COMPETITORS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLG_CS_SUP  FOREIGN KEY (SUPPLIER_ID) REFERENCES PLG_SUPPLIERS(ID) ON DELETE SET NULL,
  CONSTRAINT FK_PLG_CS_CAT  FOREIGN KEY (CATEGORY_ID) REFERENCES PLG_CATEGORIES(ID) ON DELETE SET NULL,
  CONSTRAINT CHK_PLG_CS_EXCL CHECK (IS_EXCLUSIVE IN (0,1))
);

-- ==================== Рынки других стран ====================

CREATE TABLE PLG_MARKETS (
  ID                NUMBER        NOT NULL,
  DATASET_ID        NUMBER,
  COUNTRY_CODE      VARCHAR2(5)   NOT NULL,  -- MD, RO, UA, PL…
  NAME_RU           VARCHAR2(150) NOT NULL,
  NAME_RO           VARCHAR2(150),
  NAME_EN           VARCHAR2(150),
  POPULATION_MLN    NUMBER(8,2),
  GDP_PER_CAPITA    NUMBER(12,2),
  CURRENCY          VARCHAR2(5),
  RETAIL_VOLUME_MLN NUMBER(16,2),            -- объём продуктового ритейла
  MODERN_TRADE_PCT  NUMBER(5,2),             -- доля современной торговли
  TOP5_SHARE_PCT    NUMBER(5,2),             -- концентрация: доля топ-5 сетей
  AVG_CHECK         NUMBER(12,2),
  AVG_CHECK_EUR     NUMBER(12,2),            -- приведение к общей базе
  STORES_PER_100K   NUMBER(8,2),
  PRIVATE_LABEL_PCT NUMBER(5,2),
  NOTES             VARCHAR2(1000),
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_PLG_MARKETS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_MKT UNIQUE (DATASET_ID, COUNTRY_CODE),
  CONSTRAINT FK_PLG_MKT_DS FOREIGN KEY (DATASET_ID) REFERENCES PLG_DATASETS(ID)
);
/

CREATE OR REPLACE TRIGGER PLG_MARKETS_BI
  BEFORE INSERT ON PLG_MARKETS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_MARKETS_SEQ.NEXTVAL;
END;
/

-- Схожие торговые сети на этих рынках — база для бенчмарка
CREATE TABLE PLG_MARKET_CHAINS (
  ID                NUMBER        NOT NULL,
  MARKET_ID         NUMBER        NOT NULL,
  NAME              VARCHAR2(200) NOT NULL,
  OWNER_GROUP       VARCHAR2(200),
  FORMAT_MIX        VARCHAR2(100),
  STORE_COUNT       NUMBER,
  REVENUE_MLN       NUMBER(16,2),
  MARKET_SHARE_PCT  NUMBER(5,2),
  AVG_STORE_SQM     NUMBER(10,2),
  SKU_COUNT         NUMBER,
  PRIVATE_LABEL_PCT NUMBER(5,2),
  AVG_CHECK_EUR     NUMBER(12,2),
  ONLINE_SHARE_PCT  NUMBER(5,2),
  LOYALTY_PROGRAM   NUMBER(1)     DEFAULT 1,
  IS_BENCHMARK      NUMBER(1)     DEFAULT 0, -- эталон для сравнения с нашей сетью
  NOTES             VARCHAR2(1000),
  CONSTRAINT PK_PLG_MARKET_CHAINS PRIMARY KEY (ID),
  CONSTRAINT UQ_PLG_MC UNIQUE (MARKET_ID, NAME),
  CONSTRAINT FK_PLG_MC_MKT FOREIGN KEY (MARKET_ID) REFERENCES PLG_MARKETS(ID) ON DELETE CASCADE,
  CONSTRAINT CHK_PLG_MC_LOYALTY CHECK (LOYALTY_PROGRAM IN (0,1)),
  CONSTRAINT CHK_PLG_MC_BENCH   CHECK (IS_BENCHMARK IN (0,1))
);
/

CREATE OR REPLACE TRIGGER PLG_MKT_CHAINS_BI
  BEFORE INSERT ON PLG_MARKET_CHAINS FOR EACH ROW
  WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID := PLG_MKT_CHAINS_SEQ.NEXTVAL;
END;
/

-- ==================== Наполнение справочников ====================

INSERT INTO PLG_REF_SUPPLIER_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, COLOR, SORT_ORDER) VALUES ('producer',      'Производитель',   'Producător',      'Producer',       '#16a34a', 1);
INSERT INTO PLG_REF_SUPPLIER_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, COLOR, SORT_ORDER) VALUES ('distributor',   'Дистрибьютор',    'Distribuitor',    'Distributor',    '#2563eb', 2);
INSERT INTO PLG_REF_SUPPLIER_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, COLOR, SORT_ORDER) VALUES ('importer',      'Импортёр',        'Importator',      'Importer',       '#7c3aed', 3);
INSERT INTO PLG_REF_SUPPLIER_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, COLOR, SORT_ORDER) VALUES ('farm',          'Фермерское хозяйство','Gospodărie agricolă','Farm',      '#d97706', 4);
INSERT INTO PLG_REF_SUPPLIER_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, COLOR, SORT_ORDER) VALUES ('private_label', 'Контрактное производство (СТМ)','Producție sub marcă proprie','Private label', '#db2777', 5);

INSERT INTO PLG_REF_CONTRACT_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, SORT_ORDER) VALUES ('supply',        'Договор поставки',    'Contract de furnizare', 'Supply agreement',    1);
INSERT INTO PLG_REF_CONTRACT_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, SORT_ORDER) VALUES ('marketing',     'Маркетинговое соглашение','Acord de marketing','Marketing agreement', 2);
INSERT INTO PLG_REF_CONTRACT_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, SORT_ORDER) VALUES ('logistics',     'Логистическое соглашение','Acord logistic',  'Logistics agreement', 3);
INSERT INTO PLG_REF_CONTRACT_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, SORT_ORDER) VALUES ('private_label', 'Договор СТМ',         'Contract marcă proprie','Private label contract', 4);
INSERT INTO PLG_REF_CONTRACT_TYPES (CODE, NAME_RU, NAME_RO, NAME_EN, SORT_ORDER) VALUES ('consignment',   'Договор консигнации', 'Contract de consignație','Consignment contract', 5);

INSERT INTO PLG_REF_CONTACT_ROLES (CODE, NAME_RU, NAME_RO, NAME_EN, ICON, SORT_ORDER) VALUES ('kam',       'Менеджер по работе с сетью','Manager de cont',  'Key account manager', '◉', 1);
INSERT INTO PLG_REF_CONTACT_ROLES (CODE, NAME_RU, NAME_RO, NAME_EN, ICON, SORT_ORDER) VALUES ('logistics', 'Логист',                 'Logistician',       'Logistics manager',   '▬', 2);
INSERT INTO PLG_REF_CONTACT_ROLES (CODE, NAME_RU, NAME_RO, NAME_EN, ICON, SORT_ORDER) VALUES ('finance',   'Бухгалтерия',            'Contabilitate',     'Finance',             '☰', 3);
INSERT INTO PLG_REF_CONTACT_ROLES (CODE, NAME_RU, NAME_RO, NAME_EN, ICON, SORT_ORDER) VALUES ('quality',   'Качество и сертификация','Calitate',          'Quality assurance',   '✓', 4);
INSERT INTO PLG_REF_CONTACT_ROLES (CODE, NAME_RU, NAME_RO, NAME_EN, ICON, SORT_ORDER) VALUES ('director',  'Руководитель',           'Director',          'Director',            '★', 5);

COMMIT;
