-- ============================================================
-- Планограммы: представления логистики и партнёрского контура
--
-- Как и в остальном модуле, названия отдаются сразу в трёх языках,
-- а справочные подписи — под именами *_NAME_RU/RO/EN, чтобы не затирать
-- колонку-код при локализации в контроллере.
-- ============================================================

-- ==================== Логистика ====================

-- Логистические центры со сводкой загрузки
CREATE OR REPLACE VIEW V_PLG_DC AS
SELECT
  d.ID, d.DATASET_ID, d.CODE, d.NAME_RU, d.NAME_RO, d.NAME_EN,
  d.CITY, d.ADDRESS_RU, d.ADDRESS_RO, d.ADDRESS_EN,
  d.AREA_SQM, d.DOCK_COUNT, d.PALLET_SLOTS, d.WORK_FROM, d.WORK_TO,
  d.HAS_FRESH, d.MANAGER_NAME, d.STATUS, d.CREATED_AT,
  (SELECT COUNT(*) FROM PLG_DC_STORES s WHERE s.DC_ID = d.ID)   AS STORE_COUNT,
  (SELECT COUNT(*) FROM PLG_VEHICLES v WHERE v.HOME_DC_ID = d.ID) AS VEHICLE_COUNT,
  (SELECT COUNT(*) FROM PLG_SHIPMENTS sh WHERE sh.DC_ID = d.ID
     AND sh.PLANNED_START >= TRUNC(SYSDATE) - 7)                 AS SHIPMENTS_7D,
  (SELECT NVL(SUM(sh.PALLETS), 0) FROM PLG_SHIPMENTS sh WHERE sh.DC_ID = d.ID
     AND sh.PLANNED_START >= TRUNC(SYSDATE) - 7)                 AS PALLETS_7D
FROM PLG_DC d;

-- Транспорт с типом и фактической загрузкой
CREATE OR REPLACE VIEW V_PLG_VEHICLES AS
SELECT
  v.ID, v.DATASET_ID, v.CODE, v.PLATE_NO, v.VEHICLE_TYPE,
  vt.NAME_RU AS VEHICLE_TYPE_NAME_RU, vt.NAME_RO AS VEHICLE_TYPE_NAME_RO,
  vt.NAME_EN AS VEHICLE_TYPE_NAME_EN,
  vt.COLOR, vt.ICON, vt.IS_REEFER,
  v.CARRIER, v.IS_OWN, v.DRIVER_NAME,
  NVL(v.CAPACITY_KG, vt.CAPACITY_KG)   AS CAPACITY_KG,
  NVL(v.VOLUME_M3, vt.VOLUME_M3)       AS VOLUME_M3,
  NVL(v.PALLET_SLOTS, vt.PALLET_SLOTS) AS PALLET_SLOTS,
  v.HOME_DC_ID, dc.CODE AS DC_CODE,
  dc.NAME_RU AS DC_RU, dc.NAME_RO AS DC_RO, dc.NAME_EN AS DC_EN,
  v.STATUS, v.CREATED_AT,
  (SELECT COUNT(*) FROM PLG_SHIPMENTS sh WHERE sh.VEHICLE_ID = v.ID
     AND sh.PLANNED_START >= TRUNC(SYSDATE) - 7) AS TRIPS_7D,
  (SELECT NVL(ROUND(SUM((CAST(sh.PLANNED_END AS DATE) - CAST(sh.PLANNED_START AS DATE)) * 24), 1), 0)
     FROM PLG_SHIPMENTS sh WHERE sh.VEHICLE_ID = v.ID
     AND sh.PLANNED_START >= TRUNC(SYSDATE) - 7) AS HOURS_7D
FROM PLG_VEHICLES v
JOIN PLG_REF_VEHICLE_TYPES vt ON vt.CODE = v.VEHICLE_TYPE
LEFT JOIN PLG_DC dc ON dc.ID = v.HOME_DC_ID;

-- Рейсы: основа диаграммы Ганта. Отдаёт готовые подписи полос и признак срыва окна.
CREATE OR REPLACE VIEW V_PLG_SHIPMENTS AS
SELECT
  sh.ID, sh.CODE, sh.SHIPMENT_TYPE,
  st.NAME_RU AS SHIPMENT_TYPE_NAME_RU, st.NAME_RO AS SHIPMENT_TYPE_NAME_RO,
  st.NAME_EN AS SHIPMENT_TYPE_NAME_EN, st.COLOR AS TYPE_COLOR,
  sh.SUPPLIER_ID, sup.CODE AS SUPPLIER_CODE,
  sup.NAME_RU AS SUPPLIER_RU, sup.NAME_RO AS SUPPLIER_RO, sup.NAME_EN AS SUPPLIER_EN,
  sh.DC_ID, dc.CODE AS DC_CODE,
  dc.NAME_RU AS DC_RU, dc.NAME_RO AS DC_RO, dc.NAME_EN AS DC_EN,
  sh.STORE_ID, s.CODE AS STORE_CODE,
  s.NAME_RU AS STORE_RU, s.NAME_RO AS STORE_RO, s.NAME_EN AS STORE_EN,
  sh.VEHICLE_ID, v.CODE AS VEHICLE_CODE, v.PLATE_NO, v.VEHICLE_TYPE,
  vt.NAME_RU AS VEHICLE_TYPE_NAME_RU, vt.NAME_RO AS VEHICLE_TYPE_NAME_RO,
  vt.NAME_EN AS VEHICLE_TYPE_NAME_EN, vt.COLOR AS VEHICLE_COLOR,
  NVL(s.DATASET_ID, NVL(dc.DATASET_ID, sup.DATASET_ID)) AS DATASET_ID,
  sh.DOCK_NO, sh.PLANNED_START, sh.PLANNED_END, sh.ACTUAL_START, sh.ACTUAL_END,
  sh.STATUS, sh.TEMP_MODE, sh.PALLETS, sh.WEIGHT_KG, sh.VOLUME_M3, sh.AMOUNT,
  sh.DISTANCE_KM, sh.DELAY_MIN, sh.NOTES,
  ROUND((CAST(sh.PLANNED_END AS DATE) - CAST(sh.PLANNED_START AS DATE)) * 24 * 60) AS PLANNED_MIN,
  ROUND((CAST(sh.ACTUAL_END AS DATE) - CAST(sh.ACTUAL_START AS DATE)) * 24 * 60)   AS ACTUAL_MIN,
  CASE WHEN sh.DELAY_MIN > 30 THEN 1 ELSE 0 END AS IS_LATE,
  (SELECT COUNT(*) FROM PLG_SHIPMENT_LINES l WHERE l.SHIPMENT_ID = sh.ID) AS LINE_COUNT
FROM PLG_SHIPMENTS sh
JOIN PLG_REF_SHIPMENT_TYPES st ON st.CODE = sh.SHIPMENT_TYPE
LEFT JOIN PLG_SUPPLIERS sup ON sup.ID = sh.SUPPLIER_ID
LEFT JOIN PLG_DC dc         ON dc.ID = sh.DC_ID
LEFT JOIN PLG_STORES s      ON s.ID = sh.STORE_ID
LEFT JOIN PLG_VEHICLES v    ON v.ID = sh.VEHICLE_ID
LEFT JOIN PLG_REF_VEHICLE_TYPES vt ON vt.CODE = v.VEHICLE_TYPE;

-- ==================== Поставщики ====================

CREATE OR REPLACE VIEW V_PLG_SUPPLIERS AS
SELECT
  sup.ID, sup.DATASET_ID, sup.CODE, sup.NAME_RU, sup.NAME_RO, sup.NAME_EN,
  sup.SUPPLIER_TYPE,
  t.NAME_RU AS SUPPLIER_TYPE_NAME_RU, t.NAME_RO AS SUPPLIER_TYPE_NAME_RO,
  t.NAME_EN AS SUPPLIER_TYPE_NAME_EN, t.COLOR AS TYPE_COLOR,
  sup.COUNTRY, sup.CITY, sup.ADDRESS, sup.IDNO, sup.WEBSITE, sup.PHONE, sup.EMAIL,
  sup.RATING, sup.OTIF_PCT, sup.ANNUAL_TURNOVER, sup.SKU_COUNT, sup.IS_KEY,
  sup.DELIVERS_TO, sup.STATUS, sup.CREATED_AT, sup.UPDATED_AT,
  (SELECT COUNT(*) FROM PLG_SUPPLIER_CONTACTS c WHERE c.SUPPLIER_ID = sup.ID)   AS CONTACT_COUNT,
  (SELECT COUNT(*) FROM PLG_CONTRACTS ct WHERE ct.SUPPLIER_ID = sup.ID)         AS CONTRACT_COUNT,
  (SELECT COUNT(*) FROM PLG_CONTRACTS ct WHERE ct.SUPPLIER_ID = sup.ID
     AND ct.STATUS = 'active')                                                  AS CONTRACT_ACTIVE,
  (SELECT COUNT(*) FROM PLG_SUPPLIER_CATEGORIES sc WHERE sc.SUPPLIER_ID = sup.ID) AS CATEGORY_COUNT,
  (SELECT COUNT(*) FROM PLG_PRODUCTS p WHERE p.SUPPLIER_ID = sup.ID)            AS PRODUCT_COUNT,
  (SELECT COUNT(*) FROM PLG_SHIPMENTS sh WHERE sh.SUPPLIER_ID = sup.ID
     AND sh.PLANNED_START >= TRUNC(SYSDATE) - 30)                               AS SHIPMENTS_30D,
  (SELECT MIN(ct.DATE_TO) FROM PLG_CONTRACTS ct WHERE ct.SUPPLIER_ID = sup.ID
     AND ct.STATUS = 'active' AND ct.DATE_TO IS NOT NULL)                       AS NEXT_EXPIRY,
  (SELECT c.FULL_NAME FROM PLG_SUPPLIER_CONTACTS c
     WHERE c.SUPPLIER_ID = sup.ID AND c.IS_PRIMARY = 1 AND ROWNUM = 1)          AS PRIMARY_CONTACT,
  (SELECT c.PHONE FROM PLG_SUPPLIER_CONTACTS c
     WHERE c.SUPPLIER_ID = sup.ID AND c.IS_PRIMARY = 1 AND ROWNUM = 1)          AS PRIMARY_PHONE
FROM PLG_SUPPLIERS sup
JOIN PLG_REF_SUPPLIER_TYPES t ON t.CODE = sup.SUPPLIER_TYPE;

CREATE OR REPLACE VIEW V_PLG_SUPPLIER_CONTACTS AS
SELECT
  c.ID, c.SUPPLIER_ID, sup.CODE AS SUPPLIER_CODE,
  sup.NAME_RU AS SUPPLIER_RU, sup.NAME_RO AS SUPPLIER_RO, sup.NAME_EN AS SUPPLIER_EN,
  c.FULL_NAME, c.ROLE_CODE,
  r.NAME_RU AS ROLE_NAME_RU, r.NAME_RO AS ROLE_NAME_RO, r.NAME_EN AS ROLE_NAME_EN, r.ICON,
  c.POSITION_TX, c.PHONE, c.MOBILE, c.EMAIL, c.MESSENGER, c.IS_PRIMARY, c.NOTES, c.CREATED_AT
FROM PLG_SUPPLIER_CONTACTS c
JOIN PLG_SUPPLIERS sup ON sup.ID = c.SUPPLIER_ID
LEFT JOIN PLG_REF_CONTACT_ROLES r ON r.CODE = c.ROLE_CODE;

CREATE OR REPLACE VIEW V_PLG_CONTRACTS AS
SELECT
  ct.ID, ct.SUPPLIER_ID, sup.CODE AS SUPPLIER_CODE, sup.DATASET_ID,
  sup.NAME_RU AS SUPPLIER_RU, sup.NAME_RO AS SUPPLIER_RO, sup.NAME_EN AS SUPPLIER_EN,
  ct.CODE, ct.CONTRACT_TYPE,
  t.NAME_RU AS CONTRACT_TYPE_NAME_RU, t.NAME_RO AS CONTRACT_TYPE_NAME_RO,
  t.NAME_EN AS CONTRACT_TYPE_NAME_EN,
  ct.TITLE_RU, ct.TITLE_RO, ct.TITLE_EN,
  ct.DATE_FROM, ct.DATE_TO, ct.CURRENCY, ct.PAYMENT_DAYS, ct.RETRO_BONUS_PCT,
  ct.DISCOUNT_PCT, ct.MARKETING_FEE, ct.MIN_ORDER_AMT, ct.INCOTERMS,
  ct.LEAD_TIME_DAYS, ct.AUTO_RENEW, ct.STATUS, ct.SIGNED_BY, ct.FILE_URL, ct.NOTES,
  ct.CREATED_AT, ct.UPDATED_AT,
  CASE WHEN ct.DATE_TO IS NULL THEN NULL ELSE ct.DATE_TO - TRUNC(SYSDATE) END AS DAYS_LEFT,
  CASE
    WHEN ct.STATUS <> 'active' THEN ct.STATUS
    WHEN ct.DATE_TO IS NOT NULL AND ct.DATE_TO < TRUNC(SYSDATE) THEN 'expired'
    ELSE 'active'
  END AS EFFECTIVE_STATUS,
  CASE WHEN ct.STATUS = 'active' AND ct.DATE_TO IS NOT NULL
            AND ct.DATE_TO BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE) + 60
       THEN 1 ELSE 0 END AS EXPIRING_SOON
FROM PLG_CONTRACTS ct
JOIN PLG_SUPPLIERS sup ON sup.ID = ct.SUPPLIER_ID
JOIN PLG_REF_CONTRACT_TYPES t ON t.CODE = ct.CONTRACT_TYPE;

-- Связка «поставщик × товарная группа» — ребро графа взаимоотношений
CREATE OR REPLACE VIEW V_PLG_SUPPLIER_CATEGORIES AS
SELECT
  sc.SUPPLIER_ID, sup.CODE AS SUPPLIER_CODE, sup.DATASET_ID,
  sup.NAME_RU AS SUPPLIER_RU, sup.NAME_RO AS SUPPLIER_RO, sup.NAME_EN AS SUPPLIER_EN,
  sup.SUPPLIER_TYPE, sup.IS_KEY, sup.RATING,
  sc.CATEGORY_ID, c.CODE AS CATEGORY_CODE,
  c.NAME_RU AS CATEGORY_RU, c.NAME_RO AS CATEGORY_RO, c.NAME_EN AS CATEGORY_EN,
  c.COLOR AS CATEGORY_COLOR,
  sc.SKU_COUNT, sc.TURNOVER, sc.SHARE_PCT, sc.IS_PRIMARY, sc.MARGIN_PCT
FROM PLG_SUPPLIER_CATEGORIES sc
JOIN PLG_SUPPLIERS sup ON sup.ID = sc.SUPPLIER_ID
JOIN PLG_CATEGORIES c  ON c.ID = sc.CATEGORY_ID;

-- ==================== Конкуренты ====================

CREATE OR REPLACE VIEW V_PLG_COMPETITORS AS
SELECT
  cm.ID, cm.DATASET_ID, cm.CODE, cm.NAME_RU, cm.NAME_RO, cm.NAME_EN,
  cm.COUNTRY, cm.FORMAT_MIX, cm.STORE_COUNT, cm.POSITIONING, cm.PRICE_INDEX,
  cm.MARKET_SHARE, cm.ANNUAL_REVENUE, cm.PRIVATE_LABEL_PCT, cm.WEBSITE,
  NVL(cm.COLOR, '#64748b') AS COLOR, cm.STATUS, cm.CREATED_AT,
  (SELECT COUNT(*) FROM PLG_COMPETITOR_PRICES p WHERE p.COMPETITOR_ID = cm.ID) AS PRICE_CHECKS,
  (SELECT MAX(p.CHECK_DATE) FROM PLG_COMPETITOR_PRICES p WHERE p.COMPETITOR_ID = cm.ID) AS LAST_CHECK,
  (SELECT COUNT(DISTINCT p.PRODUCT_ID) FROM PLG_COMPETITOR_PRICES p WHERE p.COMPETITOR_ID = cm.ID) AS SKU_MONITORED,
  (SELECT COUNT(*) FROM PLG_COMPETITOR_SUPPLIERS cs WHERE cs.COMPETITOR_ID = cm.ID) AS SUPPLIER_COUNT,
  (SELECT COUNT(*) FROM PLG_COMPETITOR_SUPPLIERS cs WHERE cs.COMPETITOR_ID = cm.ID
     AND cs.SUPPLIER_ID IS NOT NULL) AS SHARED_SUPPLIERS,
  (SELECT ROUND(AVG(p.PRICE / NULLIF(p.OUR_PRICE, 0)) * 100, 2)
     FROM PLG_COMPETITOR_PRICES p WHERE p.COMPETITOR_ID = cm.ID
     AND p.CHECK_DATE = (SELECT MAX(p2.CHECK_DATE) FROM PLG_COMPETITOR_PRICES p2
                          WHERE p2.COMPETITOR_ID = cm.ID)) AS PRICE_INDEX_ACTUAL
FROM PLG_COMPETITORS cm;

-- Сравнение цен по SKU на последнюю дату замера
CREATE OR REPLACE VIEW V_PLG_PRICE_COMPARE AS
SELECT
  p.COMPETITOR_ID, cm.CODE AS COMPETITOR_CODE,
  cm.NAME_RU AS COMPETITOR_RU, cm.NAME_RO AS COMPETITOR_RO, cm.NAME_EN AS COMPETITOR_EN,
  NVL(cm.COLOR, '#64748b') AS COMPETITOR_COLOR, cm.DATASET_ID,
  p.PRODUCT_ID, pr.CODE AS PRODUCT_CODE,
  pr.NAME_RU AS PRODUCT_RU, pr.NAME_RO AS PRODUCT_RO, pr.NAME_EN AS PRODUCT_EN,
  pr.ABC_CLASS, pr.CATEGORY_ID,
  c.NAME_RU AS CATEGORY_RU, c.NAME_RO AS CATEGORY_RO, c.NAME_EN AS CATEGORY_EN,
  c.COLOR AS CATEGORY_COLOR,
  p.CHECK_DATE, p.PRICE AS COMPETITOR_PRICE, p.OUR_PRICE, p.IS_PROMO, p.IN_STOCK,
  p.SOURCE, p.CITY,
  ROUND(p.PRICE - p.OUR_PRICE, 2) AS DIFF_ABS,
  ROUND(p.PRICE / NULLIF(p.OUR_PRICE, 0) * 100, 2) AS PRICE_INDEX,
  CASE
    WHEN p.OUR_PRICE IS NULL OR p.OUR_PRICE = 0 THEN 'unknown'
    WHEN p.PRICE < p.OUR_PRICE * 0.97 THEN 'we_expensive'
    WHEN p.PRICE > p.OUR_PRICE * 1.03 THEN 'we_cheap'
    ELSE 'parity'
  END AS POSITION_CODE
FROM PLG_COMPETITOR_PRICES p
JOIN PLG_COMPETITORS cm ON cm.ID = p.COMPETITOR_ID
JOIN PLG_PRODUCTS pr    ON pr.ID = p.PRODUCT_ID
LEFT JOIN PLG_CATEGORIES c ON c.ID = pr.CATEGORY_ID
WHERE p.CHECK_DATE = (SELECT MAX(p2.CHECK_DATE) FROM PLG_COMPETITOR_PRICES p2
                       WHERE p2.COMPETITOR_ID = p.COMPETITOR_ID);

-- Ценовой индекс по категориям: одна строка на «конкурент × товарная группа»
CREATE OR REPLACE VIEW V_PLG_PRICE_INDEX_CAT AS
SELECT
  v.DATASET_ID, v.COMPETITOR_ID, v.COMPETITOR_CODE,
  v.COMPETITOR_RU, v.COMPETITOR_RO, v.COMPETITOR_EN, v.COMPETITOR_COLOR,
  v.CATEGORY_ID, v.CATEGORY_RU, v.CATEGORY_RO, v.CATEGORY_EN, v.CATEGORY_COLOR,
  COUNT(*) AS SKU_COUNT,
  ROUND(AVG(v.PRICE_INDEX), 2) AS PRICE_INDEX,
  ROUND(MIN(v.PRICE_INDEX), 2) AS INDEX_MIN,
  ROUND(MAX(v.PRICE_INDEX), 2) AS INDEX_MAX,
  SUM(CASE WHEN v.POSITION_CODE = 'we_expensive' THEN 1 ELSE 0 END) AS WE_EXPENSIVE,
  SUM(CASE WHEN v.POSITION_CODE = 'we_cheap' THEN 1 ELSE 0 END)     AS WE_CHEAP,
  SUM(CASE WHEN v.POSITION_CODE = 'parity' THEN 1 ELSE 0 END)       AS PARITY,
  SUM(v.IS_PROMO) AS PROMO_COUNT,
  MAX(v.CHECK_DATE) AS CHECK_DATE
FROM V_PLG_PRICE_COMPARE v
WHERE v.CATEGORY_ID IS NOT NULL
GROUP BY v.DATASET_ID, v.COMPETITOR_ID, v.COMPETITOR_CODE,
         v.COMPETITOR_RU, v.COMPETITOR_RO, v.COMPETITOR_EN, v.COMPETITOR_COLOR,
         v.CATEGORY_ID, v.CATEGORY_RU, v.CATEGORY_RO, v.CATEGORY_EN, v.CATEGORY_COLOR;

-- Поставщики конкурентов с пометкой пересечения с нашей базой
CREATE OR REPLACE VIEW V_PLG_COMPETITOR_SUPPLIERS AS
SELECT
  cs.COMPETITOR_ID, cm.CODE AS COMPETITOR_CODE, cm.DATASET_ID,
  cm.NAME_RU AS COMPETITOR_RU, cm.NAME_RO AS COMPETITOR_RO, cm.NAME_EN AS COMPETITOR_EN,
  NVL(cm.COLOR, '#64748b') AS COMPETITOR_COLOR,
  cs.SUPPLIER_NAME, cs.SUPPLIER_ID,
  sup.CODE AS OUR_SUPPLIER_CODE,
  sup.NAME_RU AS OUR_SUPPLIER_RU, sup.NAME_RO AS OUR_SUPPLIER_RO, sup.NAME_EN AS OUR_SUPPLIER_EN,
  cs.CATEGORY_ID,
  c.NAME_RU AS CATEGORY_RU, c.NAME_RO AS CATEGORY_RO, c.NAME_EN AS CATEGORY_EN,
  cs.IS_EXCLUSIVE, cs.EST_SHARE_PCT, cs.SOURCE,
  CASE WHEN cs.SUPPLIER_ID IS NOT NULL THEN 1 ELSE 0 END AS IS_SHARED
FROM PLG_COMPETITOR_SUPPLIERS cs
JOIN PLG_COMPETITORS cm ON cm.ID = cs.COMPETITOR_ID
LEFT JOIN PLG_SUPPLIERS sup ON sup.ID = cs.SUPPLIER_ID
LEFT JOIN PLG_CATEGORIES c  ON c.ID = cs.CATEGORY_ID;

-- ==================== Рынки ====================

CREATE OR REPLACE VIEW V_PLG_MARKETS AS
SELECT
  m.ID, m.DATASET_ID, m.COUNTRY_CODE, m.NAME_RU, m.NAME_RO, m.NAME_EN,
  m.POPULATION_MLN, m.GDP_PER_CAPITA, m.CURRENCY, m.RETAIL_VOLUME_MLN,
  m.MODERN_TRADE_PCT, m.TOP5_SHARE_PCT, m.AVG_CHECK, m.AVG_CHECK_EUR,
  m.STORES_PER_100K, m.PRIVATE_LABEL_PCT, m.NOTES, m.CREATED_AT,
  (SELECT COUNT(*) FROM PLG_MARKET_CHAINS ch WHERE ch.MARKET_ID = m.ID) AS CHAIN_COUNT,
  (SELECT NVL(SUM(ch.STORE_COUNT), 0) FROM PLG_MARKET_CHAINS ch WHERE ch.MARKET_ID = m.ID) AS STORES_TOTAL,
  (SELECT ROUND(AVG(ch.PRIVATE_LABEL_PCT), 2) FROM PLG_MARKET_CHAINS ch WHERE ch.MARKET_ID = m.ID) AS AVG_PL_PCT,
  (SELECT MAX(ch.NAME) FROM PLG_MARKET_CHAINS ch WHERE ch.MARKET_ID = m.ID
     AND ch.MARKET_SHARE_PCT = (SELECT MAX(ch2.MARKET_SHARE_PCT) FROM PLG_MARKET_CHAINS ch2
                                 WHERE ch2.MARKET_ID = m.ID)) AS LEADER_CHAIN
FROM PLG_MARKETS m;

CREATE OR REPLACE VIEW V_PLG_MARKET_CHAINS AS
SELECT
  ch.ID, ch.MARKET_ID, m.DATASET_ID, m.COUNTRY_CODE,
  m.NAME_RU AS MARKET_RU, m.NAME_RO AS MARKET_RO, m.NAME_EN AS MARKET_EN,
  ch.NAME, ch.OWNER_GROUP, ch.FORMAT_MIX, ch.STORE_COUNT, ch.REVENUE_MLN,
  ch.MARKET_SHARE_PCT, ch.AVG_STORE_SQM, ch.SKU_COUNT, ch.PRIVATE_LABEL_PCT,
  ch.AVG_CHECK_EUR, ch.ONLINE_SHARE_PCT, ch.LOYALTY_PROGRAM, ch.IS_BENCHMARK, ch.NOTES,
  CASE WHEN NVL(ch.STORE_COUNT, 0) > 0
       THEN ROUND(ch.REVENUE_MLN / ch.STORE_COUNT, 3) END AS REVENUE_PER_STORE_MLN,
  CASE WHEN NVL(ch.AVG_STORE_SQM, 0) > 0 AND NVL(ch.STORE_COUNT, 0) > 0
       THEN ROUND(ch.REVENUE_MLN * 1000000 / (ch.STORE_COUNT * ch.AVG_STORE_SQM), 0) END AS REVENUE_PER_SQM
FROM PLG_MARKET_CHAINS ch
JOIN PLG_MARKETS m ON m.ID = ch.MARKET_ID;
