from __future__ import annotations

import json
import threading
from typing import Any

import oracledb

from .database import DatabaseConnection


_SCHEMA_LOCK = threading.RLock()
_SCHEMA_READY = False
_CRED_LOG_TABLE = "CRED_EVENT_LOG"
_CRED_LOG_TS_INDEX = "IX_CRED_EVENT_LOG_TS"


def _db_error_code(exc: Exception) -> int | None:
    err = getattr(exc, "args", [None])[0]
    return getattr(err, "code", None)


def ensure_runtime_schema() -> None:
    global _SCHEMA_READY
    if _SCHEMA_READY:
        return

    with _SCHEMA_LOCK:
        if _SCHEMA_READY:
            return

        connection = DatabaseConnection.get_connection()
        try:
            with connection.cursor() as cursor:
                for statement in (
                    """
                    CREATE TABLE CRED_EVENT_LOG (
                        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        TS_ISO VARCHAR2(40) NOT NULL,
                        LEVEL_NAME VARCHAR2(16) NOT NULL,
                        SOURCE_NAME VARCHAR2(200) NOT NULL,
                        MESSAGE_TEXT CLOB,
                        PAYLOAD_JSON CLOB
                    )
                    """,
                    "CREATE INDEX IX_CRED_EVENT_LOG_TS ON CRED_EVENT_LOG (TS_ISO)",
                ):
                    try:
                        cursor.execute(statement)
                    except oracledb.DatabaseError as exc:
                        if _db_error_code(exc) != 955:
                            raise
            connection.commit()
            _SCHEMA_READY = True
        finally:
            connection.close()


def _read_lob(value: Any) -> str:
    if value is None:
        return ""
    if hasattr(value, "read"):
        value = value.read()
    if isinstance(value, bytes):
        return value.decode("utf-8")
    return str(value)


def load_json_state(*args: Any, **kwargs: Any) -> dict[str, Any]:
    raise RuntimeError("JSON runtime state storage was removed. Use normalized DECOR Oracle tables instead.")


def save_json_state(*args: Any, **kwargs: Any) -> None:
    raise RuntimeError("JSON runtime state storage was removed. Use normalized DECOR Oracle tables instead.")


def append_event_log(source: str, message: str, level: str, payload: dict[str, Any] | None = None, ts_iso: str | None = None) -> None:
    ensure_runtime_schema()
    connection = DatabaseConnection.get_connection()
    try:
        with connection.cursor() as cursor:
            cursor.setinputsizes(message_text=oracledb.DB_TYPE_CLOB, payload_json=oracledb.DB_TYPE_CLOB)
            cursor.execute(
                """
                INSERT INTO CRED_EVENT_LOG (TS_ISO, LEVEL_NAME, SOURCE_NAME, MESSAGE_TEXT, PAYLOAD_JSON)
                VALUES (:ts_iso, :level_name, :source_name, :message_text, :payload_json)
                """,
                {
                    "ts_iso": ts_iso or _now_iso(),
                    "level_name": (level or "INFO").upper(),
                    "source_name": source,
                    "message_text": message,
                    "payload_json": json.dumps(payload or {}, ensure_ascii=False),
                },
            )
        connection.commit()
    finally:
        connection.close()


def bulk_insert_event_logs(entries: list[dict[str, Any]]) -> None:
    if not entries:
        return

    ensure_runtime_schema()
    rows = [
        (
            entry.get("ts") or _now_iso(),
            str(entry.get("level") or "INFO").upper(),
            str(entry.get("source") or "runtime"),
            str(entry.get("message") or ""),
            json.dumps(entry.get("payload") or {}, ensure_ascii=False),
        )
        for entry in entries
    ]

    connection = DatabaseConnection.get_connection()
    try:
        with connection.cursor() as cursor:
            cursor.setinputsizes(None, None, None, oracledb.DB_TYPE_CLOB, oracledb.DB_TYPE_CLOB)
            cursor.executemany(
                """
                INSERT INTO CRED_EVENT_LOG (TS_ISO, LEVEL_NAME, SOURCE_NAME, MESSAGE_TEXT, PAYLOAD_JSON)
                VALUES (:1, :2, :3, :4, :5)
                """,
                rows,
            )
        connection.commit()
    finally:
        connection.close()


def count_event_logs() -> int:
    ensure_runtime_schema()
    connection = DatabaseConnection.get_connection()
    try:
        with connection.cursor() as cursor:
            cursor.execute(f"SELECT COUNT(*) FROM {_CRED_LOG_TABLE}")
            row = cursor.fetchone()
            return int((row or [0])[0] or 0)
    finally:
        connection.close()


def get_event_logs(limit: int = 500, since_ts: str | None = None) -> list[dict[str, Any]]:
    ensure_runtime_schema()
    limit = max(1, min(int(limit or 500), 2000))

    sql = """
        SELECT ID, TS_ISO, LEVEL_NAME, SOURCE_NAME, MESSAGE_TEXT, PAYLOAD_JSON
        FROM (
            SELECT ID, TS_ISO, LEVEL_NAME, SOURCE_NAME, MESSAGE_TEXT, PAYLOAD_JSON
            FROM CRED_EVENT_LOG
            WHERE (:since_ts IS NULL OR TS_ISO >= :since_ts)
            ORDER BY ID DESC
        )
        WHERE ROWNUM <= :limit
    """

    connection = DatabaseConnection.get_connection()
    entries: list[dict[str, Any]] = []
    try:
        with connection.cursor() as cursor:
            cursor.execute(sql, {"since_ts": since_ts, "limit": limit})
            rows = cursor.fetchall() or []
            for row in reversed(rows):
                payload = {}
                try:
                    raw_payload = _read_lob(row[5])
                    if raw_payload:
                        parsed = json.loads(raw_payload)
                        if isinstance(parsed, dict):
                            payload = parsed
                except Exception:
                    payload = {}
                entries.append(
                    {
                        "id": int(row[0] or 0),
                        "ts": row[1] or "",
                        "level": row[2] or "INFO",
                        "source": row[3] or "runtime",
                        "message": _read_lob(row[4]),
                        "payload": payload,
                    }
                )
    finally:
        connection.close()
    return entries


def clear_event_logs() -> None:
    ensure_runtime_schema()
    connection = DatabaseConnection.get_connection()
    try:
        with connection.cursor() as cursor:
            cursor.execute(f"TRUNCATE TABLE {_CRED_LOG_TABLE}")
        connection.commit()
    finally:
        connection.close()


def _now_iso() -> str:
    from datetime import datetime, timezone

    return datetime.now(tz=timezone.utc).isoformat()